Repository gear-tech/gear, pull requests merged in 2022-06, with the labels that each got.

#996 Show the descriptive message in wasm-proc
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen, D5-tooling

#1004 Remove environment variables in wasm-builder
  utils/wasm-builder/src/cargo_command.rs
Labels: A0-pleasereview, C0-bug, D5-tooling

#1001 feat(wasm-builder): check crate-type while parsing manifest
  .gitignore
  utils/wasm-builder/src/builder_error.rs
  utils/wasm-builder/src/crate_info.rs
Labels: A2-mergeoncegreen

#1007 update substrate deps in order to fix problems with wasmer unsupported CPUs
  Cargo.lock
Labels: A0-pleasereview, P1-asap

#971 Clean redundant gas value when exit
  Cargo.lock
  core-processor/src/common.rs
  core-processor/src/processor.rs
  examples/binaries/init-wait-reply-exit/Cargo.toml
  examples/binaries/init-wait-reply-exit/build.rs
  examples/binaries/init-wait-reply-exit/src/code.rs
  examples/binaries/init-wait-reply-exit/src/lib.rs
  gear-test/src/manager.rs
  gtest/src/manager.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
  utils/wasm-proc/metadata-js/index.js
Labels: A2-mergeoncegreen

#997 add checks for wasm memory buffer begin addr
  Cargo.lock
  common/src/lazy_pages.rs
  core-backend/sandbox/src/memory.rs
  core-backend/wasmtime/src/memory.rs
  core-processor/src/executor.rs
  core-processor/src/processor.rs
  core/Cargo.toml
  core/src/memory.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/unix.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/deprecated.rs
  runtime-interface/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, C2-refactoring

#1025 Clean up economic-checks unit tests
  utils/economic-checks/Cargo.toml
  utils/economic-checks/src/targets.rs
Labels: A0-pleasereview, D2-node

#1021 Use transactions of Externalities to discard changes
  Cargo.lock
  pallets/gear/Cargo.toml
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, D4-test

#959 Add list of forbidden syscalls to WASM executor
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmtime/src/env.rs
  core-backend/wasmtime/src/funcs.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/env.rs
  examples/binaries/mul-by-const/src/lib.rs
  gear-test/src/proc.rs
  gtest/src/manager.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D1-core, D2-node

#1032 Fix `runtime-interface` cannot be built on Windows
  runtime-interface/src/deprecated.rs
  runtime-interface/src/lib.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen

#1024 Speed up clippy
  Cargo.lock
  Makefile
  runtime/Cargo.toml
  runtime/src/lib.rs
  scripts/src/build.sh
  scripts/src/check.sh
  scripts/src/clippy.sh
  scripts/src/test.sh
  scripts/test-utils/gear_runtime.compact.compressed.wasm
Labels: A2-mergeoncegreen, C2-refactoring, D5-tooling

#848 Messaging tests for `gear_core` and docs
  core/src/message/common.rs
  core/src/message/context.rs
  core/src/message/handle.rs
  core/src/message/init.rs
  core/src/message/reply.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D1-core

#1031 Fix pages update for mode without lazy-pages feature
  .github/workflows/CI.yaml
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmtime/src/env.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core/src/memory.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/tests.rs
  pallets/payment/Cargo.toml
  pallets/usage/Cargo.toml
  runtime/src/lib.rs
  scripts/src/test.sh
Labels: A2-mergeoncegreen, D1-core, D2-node, C2-refactoring

#1046 Make `gcore` and `gstd` docs lighten
  gcore/src/msg.rs
  gstd/src/msg/async.rs
  gstd/src/msg/basic.rs
Labels: A0-pleasereview, D3-gstd

#1037 feat(gstd-codegen): introduce proc-macro `wait_for_reply` to generate async methods
  Cargo.lock
  examples/Cargo.lock
  examples/async-init/src/lib.rs
  examples/async-multisig/src/lib.rs
  examples/async-recursion/src/lib.rs
  examples/async-sign/src/lib.rs
  examples/async/src/lib.rs
  examples/binaries/async-tester/Cargo.toml
  examples/binaries/async-tester/build.rs
  examples/binaries/async-tester/src/code.rs
  examples/binaries/async-tester/src/lib.rs
  examples/binaries/compose/src/lib.rs
  examples/binaries/contract-template/src/lib.rs
  examples/binaries/distributor/src/lib.rs
  examples/binaries/init-wait-reply-exit/src/code.rs
  examples/binaries/ncompose/src/lib.rs
  examples/binaries/waiting-proxy/src/lib.rs
  examples/futures-unordered/src/lib.rs
  examples/incomplete_async_payloads/src/lib.rs
  examples/mutex/src/lib.rs
  examples/rwlock/src/lib.rs
  examples/rwlock_write/src/lib.rs
  examples/sync_duplicate/src/lib.rs
  examples/token-vendor/src/lib.rs
  gstd/codegen/Cargo.toml
  gstd/codegen/src/lib.rs
  gstd/codegen/src/utils.rs
  gstd/src/msg/async.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
  utils/wasm-proc/metadata-js/index.js
Labels: A2-mergeoncegreen

#1054 fix gear test build
  scripts/gear.sh
Labels: A2-mergeoncegreen

#1061 rustfmt: don't specify removed option
  scripts/src/format.sh
Labels: A0-pleasereview, D5-tooling

#973 Unique salt generation
  examples/Cargo.lock
  examples/Cargo.toml
  examples/program_generator/Cargo.toml
  examples/program_generator/child_contract.wasm
  examples/program_generator/src/lib.rs
  gear-test/spec/test_program_generator.yaml
  gstd/src/prog/generator.rs
  gstd/src/prog/mod.rs
Labels: A2-mergeoncegreen, D3-gstd, C1-feature

#1047 Refactor lazy pages
  Cargo.lock
  Cargo.toml
  common/src/lazy_pages.rs
  lazy-pages/Cargo.toml
  lazy-pages/src/lib.rs
  lazy-pages/src/sys.rs
  lazy-pages/src/sys/unix.rs
  lazy-pages/src/sys/windows.rs
  lazy-pages/src/unix.rs
  lazy-pages/src/unsupported.rs
  pallets/gear/src/tests.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/deprecated.rs
  runtime-interface/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#1055 Make `pallet_gas` procedures iterarive instead of recursive
  common/src/lib.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/tests.rs
  pallets/gear-program/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring

#1075 Fix clippy on latest compiler
  .github/workflows/CI.yaml
  pallets/usage/src/offchain.rs
Labels: A2-mergeoncegreen, C0-bug, A4-insubstantial

#1051 Refactor get_gas_spent
  Cargo.lock
  pallets/gear/Cargo.toml
  pallets/gear/rpc/Cargo.toml
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/usage/src/offchain.rs
  runtime/src/lib.rs
  scripts/calc-gas-spent.sh
Labels: A2-mergeoncegreen, D2-node, B1-releasenotes

#1071 Fix fuzzer
  utils/economic-checks/src/targets.rs
Labels: A0-pleasereview, C0-bug, D4-test

#1076 Switch to `wasmi 0.11.0`
  Cargo.lock
  Cargo.toml
Labels: A2-mergeoncegreen, D2-node

#944 Add meta state testing tools
  Cargo.lock
  core-backend/wasmtime/src/env.rs
  core-backend/wasmtime/src/funcs_tree.rs
  core-backend/wasmtime/src/lib.rs
  gtest/Cargo.toml
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/wasm_executor.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-feature, D4-test, D5-tooling

#1082 Remove `id` field from `pallet_gas::ValueNode`
  pallets/gas/src/lib.rs
  pallets/gas/src/property_tests.rs
  runtime/src/lib.rs
  utils/economic-checks/src/util.rs
Labels: A0-pleasereview, D2-node

#1091 Repeat calculate_gas_info logic on gear/rpc side
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#1068 Add gas burned counter to `gtest`
  Cargo.lock
  examples/binaries/gas-burned/Cargo.toml
  examples/binaries/gas-burned/build.rs
  examples/binaries/gas-burned/src/lib.rs
  gtest/Cargo.toml
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/manager.rs
  gtest/src/program.rs
Labels: A0-pleasereview, B1-releasenotes, D5-tooling

#1085 Store module exports in `gear_core::code::Code`
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmtime/src/env.rs
  core-processor/src/executor.rs
  core/src/code.rs
  examples/exit-code/src/lib.rs
  gtest/src/program.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/migration.rs
  pallets/gear-program/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/usage/src/migration.rs
  pallets/usage/src/mock.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D1-core, D2-node, C1-feature

#1103 gtest: Add possibility to load both `.wasm` and `.opt.wasm`
  gtest/src/program.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, D5-tooling

#1081 A little backend cleanup
  Cargo.lock
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmtime/Cargo.toml
  core-backend/wasmtime/src/env.rs
  core-backend/wasmtime/src/funcs.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/env.rs
  gtest/Cargo.toml
  gtest/src/manager.rs
  gtest/src/wasm_executor.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D1-core, D2-node

#1095 feat(gas): introduce `ValueType::ReservedLocal`
  common/src/lib.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature

#1104 Check for required export functions in `wasm-proc` and `wasm-builder`
  utils/wasm-builder/src/builder_error.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview, C1-feature, D5-tooling

#1013 benchmarking: fix instr, `reply_push`, `create_program`, optimize performance
  common/src/lazy_pages.rs
  common/src/lib.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/costs.rs
  examples/async-multisig/src/lib.rs
  examples/binaries/init-with-value/src/lib.rs
  examples/binaries/program-factory/src/lib.rs
  gear-test/spec/test_async_multisig.yaml
  gear-test/src/sample.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/sys.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime-interface/src/lib.rs
  runtime/src/lib.rs
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  utils/economic-checks/src/targets.rs
Labels: A0-pleasereview, D2-node

#1115 rtest: Don't process queue if not all messages have been sent
  utils/gear-runtime-test-cli/src/command.rs
  utils/gear-runtime-test-cli/src/util.rs
Labels: A0-pleasereview, C2-refactoring, D4-test

#1117 Change program upload logic in `gtest`
  Cargo.lock
  gtest/Cargo.toml
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/wasm_executor.rs
  utils/wasm-builder/src/builder_error.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-proc/Cargo.toml
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview, D5-tooling

#1063 feat(gear): set minimal gas amount for mailbox messages
  Cargo.lock
  core-errors/src/lib.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  examples/binaries/proxy-with-gas/Cargo.toml
  examples/binaries/proxy-with-gas/build.rs
  examples/binaries/proxy-with-gas/src/lib.rs
  examples/ping-gas/src/lib.rs
  gear-test/spec/test_ping.yaml
  gear-test/src/proc.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/wasm_executor.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  pallets/usage/src/mock.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature, A3-gotissues

#1120 Update CI.yaml
  .github/workflows/CI.yaml
Labels: A2-mergeoncegreen

#1112 Run CI on Windows
  .github/workflows/CI.yaml
Labels: A1-inprogress, D5-tooling

#1101 Implement abstract GasTree algorithm
  Cargo.lock
  common/Cargo.toml
  common/src/gas_provider/error.rs
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/negative_imbalance.rs
  common/src/gas_provider/node.rs
  common/src/gas_provider/positive_imbalance.rs
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  common/src/gas_provider/property_tests/strategies.rs
  common/src/gas_provider/property_tests/utils.rs
  common/src/lib.rs
  common/src/storage/primitives/map.rs
  common/src/storage/primitives/value.rs
  pallets/gas/Cargo.toml
  pallets/gas/src/lib.rs
  pallets/gas/src/property_tests.rs
  pallets/gas/src/tests.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/mock.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/Cargo.toml
  pallets/payment/src/mock.rs
  pallets/usage/Cargo.toml
  pallets/usage/src/lib.rs
  pallets/usage/src/mock.rs
  pallets/usage/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  utils/economic-checks/Cargo.toml
  utils/economic-checks/src/targets.rs
  utils/economic-checks/src/util.rs
  utils/gear-runtime-test-cli/Cargo.toml
  utils/gear-runtime-test-cli/src/command.rs
  utils/gear-runtime-test-cli/src/util.rs
  utils/regression-analysis/src/main.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring
