Repository gear-tech/gear, pull requests merged in 2022-09, with the labels that each got.

#1403 Make pallet gear benchmarking able to run without lazy-pages
  pallets/gear/src/benchmarking/mod.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#1405 CD: use doubleqoutes in jinja template
  ansible/tasks/docker/docker-compose-insert-keys.yaml.j2
  core-processor/src/executor.rs
  core/src/message/common.rs
  core/src/message/stored.rs
  gstd/codegen/src/lib.rs
  gtest/src/mailbox.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  utils/economic-checks/src/targets.rs
Labels: A0-pleasereview

#1408 CI: get correct branch name
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#1371 Switch Aura to Babe consensus
  .github/workflows/CD.yml
  Cargo.lock
  ansible/tasks/docker/docker-compose-insert-keys.yaml.j2
  common/lazy-pages/src/lib.rs
  lazy-pages/src/deprecated.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/sys.rs
  node/Cargo.toml
  node/cli/src/benchmarking.rs
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/gear.rs
  node/service/src/chain_spec/vara.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  runtime-interface/src/deprecated.rs
  runtime-interface/src/lib.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/constants.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/constants.rs
  runtime/vara/src/lib.rs
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  utils/economic-checks/Cargo.toml
  utils/economic-checks/src/util.rs
  utils/gear-runtime-test-cli/Cargo.toml
  utils/gear-runtime-test-cli/src/util.rs
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview, D2-node

#1411 [skip ci] Move build cache to host
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#1410 Introduce Gear Staging Testnet v3
  .github/workflows/CD.yml
  ansible/README.md
  node/res/staging.json
  node/service/src/chain_spec/gear.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node

#1420 [skip ci] Fix upload job
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#1418 Implement lazy pages comparison optimization on Windows
  lazy-pages/src/sys/windows.rs
Labels: A0-pleasereview

#1397 Fix script sometimes skips spec check
  scripts/check-spec.sh
Labels: A0-pleasereview, D5-tooling

#1427 Set only sr25519 for sp-core
  examples/Cargo.lock
  examples/async-multisig/Cargo.toml
  examples/async-sign/Cargo.toml
Labels: A0-pleasereview, C2-refactoring, D4-test

#1424 Vara: Update stage 1
  .github/workflows/CD-vara.yml
  .github/workflows/CI.yaml
  Cargo.lock
  ansible/tasks/docker/docker-compose-vara.yaml.j2
  ansible/tasks/docker/vara-reset-network.yaml
  ansible/vara-reset.yaml
  examples/gui-test/src/lib.rs
  node/Cargo.toml
  node/cli/src/benchmarking.rs
  node/cli/src/command.rs
  node/res/vara_staging.json
  node/service/Cargo.toml
  pallets/airdrop/Cargo.toml
  pallets/airdrop/README.md
  pallets/airdrop/src/benchmarking.rs
  pallets/airdrop/src/lib.rs
  pallets/airdrop/src/mock.rs
  pallets/airdrop/src/tests.rs
  pallets/airdrop/src/weights.rs
  pallets/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#1438 Remove sp-core dependency from multisig and async-sign
  examples/Cargo.lock
  examples/async-multisig/Cargo.toml
  examples/async-multisig/src/lib.rs
  examples/async-sign/Cargo.toml
  examples/async-sign/src/lib.rs
  examples/light_sr25519/Cargo.toml
  examples/light_sr25519/src/lib.rs
Labels: A0-pleasereview, C2-refactoring, D4-test

#1383 Separate client upload tests
  .github/workflows/CI.yaml
  Makefile
  scripts/gear.sh
  scripts/src/test.sh
  scripts/test-utils/harmlessUploadDemos.js
  scripts/test-utils/infiniteLoop.js
  scripts/test-utils/package.json
  scripts/test-utils/processingMessageWithRuntimeUpgrade.js
  scripts/test-utils/util.js
Labels: A2-mergeoncegreen, C1-feature, D4-test, D5-tooling

#1439 Update runtime and cli parameters
  node/cli/src/command.rs
  node/res/vara.json
  node/res/vara_staging.json
  node/service/src/chain_spec/vara.rs
  runtime/vara/src/constants.rs
Labels: A0-pleasereview

#1167 Regular performance check
  .github/actions/deploy-benchmark/action.yml
  .github/workflows/test-measurements.yaml
  .maintain/regression-analysis-weight-template.hbs
  Cargo.lock
  README.md
  utils/regression-analysis/Cargo.toml
  utils/regression-analysis/src/junit_tree.rs
  utils/regression-analysis/src/main.rs
  utils/regression-analysis/src/output.rs
  utils/regression-analysis/src/stats.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#1443 Vara: Return correct spec
  node/res/vara.json
  node/service/src/chain_spec/vara.rs
Labels: A0-pleasereview

#1446 Remove notifications with performance results
  .github/workflows/CI.yaml
Labels: A0-pleasereview, C2-refactoring, D5-tooling

#1456 gstd: Add `ActorId::is_zero` utility function
  gstd/src/common/primitives.rs
  gstd/src/msg/basic.rs
Labels: A0-pleasereview, D3-gstd

#1458 Add staking pallet to vara runtime
  Cargo.lock
  node/res/vara.json
  node/service/src/chain_spec/vara.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature

#1341 Introduce Reserved gas node
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/node.rs
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  common/src/gas_provider/property_tests/strategies.rs
  common/src/gas_provider/property_tests/utils.rs
  core/src/ids.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/tests.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D1-core

#1419 Implement lazy pages comparison optimization for macOS
  .github/workflows/CI.yaml
  Cargo.lock
  lazy-pages/src/lib.rs
  lazy-pages/src/sys.rs
  lazy-pages/src/sys/unix.rs
  lazy-pages/src/sys/windows.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/lib.rs
  runtime-interface/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#1465 Fix actual clippy lints
  lazy-pages/src/sys/unix.rs
  utils/economic-checks/src/targets.rs
Labels: A4-insubstantial

#1461 fix problem with wasmer fault when lazy pages set sigaction
  .github/workflows/CI.yaml
  Cargo.lock
  examples/wat-examples/inf_recursion.wat
  lazy-pages/Cargo.toml
  lazy-pages/src/lib.rs
  lazy-pages/src/sys/unix.rs
  scripts/src/build.sh
  scripts/test-utils/util.js
Labels: A0-pleasereview

#1472 Drop custom session management for all runtimes
  Cargo.lock
  pallets/shift-session-manager/Cargo.toml
  pallets/shift-session-manager/README.md
  pallets/shift-session-manager/src/lib.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C2-refactoring, Q1-easy

#1473 merge master to vara
  .github/workflows/CI.yaml
  Cargo.lock
  examples/wat-examples/inf_recursion.wat
  lazy-pages/Cargo.toml
  lazy-pages/src/lib.rs
  lazy-pages/src/sys/unix.rs
  pallets/shift-session-manager/Cargo.toml
  pallets/shift-session-manager/README.md
  pallets/shift-session-manager/src/lib.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  scripts/src/build.sh
  scripts/test-utils/util.js
  utils/gear-runtime-test-cli/Cargo.toml
  utils/regression-analysis/Cargo.toml
Labels: A0-pleasereview

#1475 Use VEH instead of SEH in lazy pages on Windows
  core/src/memory.rs
  lazy-pages/src/sys/windows.rs
  pallets/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node

#1480 Vara: Add ChainSpec extensions (#1424)
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec/mod.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#1493 Use volatile operations in read-write flag test
  lazy-pages/src/lib.rs
Labels: A0-pleasereview

#1494 Vara: set epoch length to 40 mins
  runtime/vara/src/constants.rs
Labels: A0-pleasereview, D2-node

#1503 Add check for static memory pages in Code
  core-processor/src/configs.rs
  core/src/code.rs
  gear-test/src/proc.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D1-core, C2-refactoring

#1488 Vara runtime improvements
  Cargo.lock
  node/res/vara.json
  node/service/Cargo.toml
  node/service/src/chain_spec/vara.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen, D2-node

#1492 make big signal alt stack to be able run lazy pages in debug mode
  Cargo.lock
  lazy-pages/Cargo.toml
  lazy-pages/src/lib.rs
  lazy-pages/src/sys.rs
  lazy-pages/src/sys/unix.rs
  lazy-pages/src/sys/windows.rs
Labels: A0-pleasereview, D2-node

#1510 Remove restrictions on custom section
  core/src/code.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#1513 Set non-zero DbWeight in tests
  pallets/gear-scheduler/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#1486 Run JS tests in Windows CI
  .github/workflows/CI.yaml
  scripts/src/build.sh
  scripts/src/init.sh
Labels: A0-pleasereview, D4-test

#1520 Fix CI
  .github/workflows/CI.yaml
  scripts/src/init.sh
Labels: A0-pleasereview

#1525 Use `$RUNNER_OS` instead of `$OSTYPE`
  scripts/src/init.sh
Labels: A0-pleasereview

#1527 node: update revert cmd for babe and grandpa
  node/cli/src/command.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  runtime/common/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen, D2-node

#1539 Fix Cargo.lock
  Cargo.lock
Labels: A0-pleasereview

#1530 Remove deprecated functions from `gstd` and rename syscall
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs.rs
  core-processor/src/ext.rs
  core/src/costs.rs
  core/src/env.rs
  examples/Cargo.lock
  examples/binaries/waiter/src/code.rs
  examples/binaries/waiter/src/lib.rs
  examples/light_sr25519/Cargo.toml
  gcore/src/exec.rs
  gstd/src/async_runtime/futures.rs
  gstd/src/exec.rs
  gstd/src/msg/async.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
  utils/wasm-proc/metadata-js/index.js
Labels: A0-pleasereview, D1-core

#1541 Vara: Fix spec
  node/res/vara.json
  node/service/src/chain_spec/vara.rs
Labels: A0-pleasereview

#1542 fix panic on big allocations in wasm runtime
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/runtime.rs
  core/src/code.rs
  core/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, P1-asap

#1487 Enable logs for dev nodes
  Makefile
Labels: A4-insubstantial

#1540 Fix tests on Windows
  gtest/src/program.rs
Labels: A0-pleasereview, D4-test

#1509 Run perf check tests in 1 thread
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview

#1544 move fix for sandbox backend to vara
  Cargo.lock
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/runtime.rs
  core/src/code.rs
  core/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, P1-asap

#1551 Install required build dependency (protoc)
  .github/workflows/test-measurements.yaml
  pallets/gear-program/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, C2-refactoring, D5-tooling

#1550 Define new design for loader
  Cargo.lock
  utils/node-loader/Cargo.toml
  utils/node-loader/src/args.rs
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/batch_pool/context.rs
  utils/node-loader/src/batch_pool/generators.rs
  utils/node-loader/src/batch_pool/report.rs
  utils/node-loader/src/batch_pool/task.rs
  utils/node-loader/src/main.rs
  utils/node-loader/src/reporter.rs
  utils/node-loader/src/task.rs
  utils/node-loader/src/task/generators.rs
  utils/node-loader/src/task/upload_code.rs
  utils/node-loader/src/task/upload_program.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview, D5-tooling

#1554 Introduce `node-loader` pre-MVP version
  Cargo.lock
  Cargo.toml
  utils/node-loader/Cargo.toml
  utils/node-loader/src/args.rs
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/batch_pool/context.rs
  utils/node-loader/src/batch_pool/generators.rs
  utils/node-loader/src/batch_pool/report.rs
  utils/node-loader/src/batch_pool/task.rs
  utils/node-loader/src/main.rs
  utils/node-loader/src/utils.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/test.rs
Labels: A0-pleasereview, D5-tooling

#1558 Revert "Run perf check tests in 1 thread (#1509)"
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview

#1563 Fix CI: pin minor jobs to specific nightly
  .github/workflows/docs.yml
  .github/workflows/win.yml
Labels: A0-pleasereview, D5-tooling

#1575 Fix weights deserialization
  utils/regression-analysis/src/main.rs
Labels: A0-pleasereview, D5-tooling

#1574 Add block weight dependency from block time
  runtime/common/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C0-bug

#1561 Introduce delayed messaging and waking
  Cargo.lock
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/scheduler/task.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs.rs
  core-processor/src/common.rs
  core-processor/src/ext.rs
  core-processor/src/handler.rs
  core-processor/src/processor.rs
  core/src/env.rs
  core/src/message/context.rs
  examples/binaries/async-tester/src/code.rs
  examples/binaries/delayed-sender/Cargo.toml
  examples/binaries/delayed-sender/build.rs
  examples/binaries/delayed-sender/src/code.rs
  examples/binaries/delayed-sender/src/lib.rs
  gcore/src/exec.rs
  gcore/src/msg.rs
  gcore/src/prog.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gstd/src/exec.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  gstd/src/prog/generator.rs
  gstd/src/prog/mod.rs
  gtest/src/manager.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/ext.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D3-gstd, B1-releasenotes, C1-feature
