Repository gear-tech/gear, pull requests merged in 2022-04, with the labels that each got.

#809 Bugfix: gas nodes are not properly consumed in some circumstances
  pallets/usage/src/lib.rs
  pallets/usage/src/mock.rs
  pallets/usage/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C0-bug

#813 CI: drop old cache when merged to master
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#815 Update substrate
  Cargo.lock
  common/Cargo.toml
  common/src/lib.rs
  core-processor/Cargo.toml
  core/Cargo.toml
  examples/Cargo.lock
  examples/async-init/Cargo.toml
  examples/async-multisig/Cargo.toml
  examples/async-sign/Cargo.toml
  examples/async/Cargo.toml
  examples/binaries/btree/Cargo.toml
  examples/binaries/distributor/Cargo.toml
  examples/binaries/node/Cargo.toml
  examples/binaries/program-factory/Cargo.toml
  examples/binaries/proxy/Cargo.toml
  examples/binaries/wait_wake/Cargo.toml
  examples/bot/Cargo.toml
  examples/chat/Cargo.toml
  examples/fungible-token/Cargo.toml
  examples/guestbook/Cargo.toml
  examples/gui-test/Cargo.toml
  examples/meta/Cargo.toml
  examples/token-vendor/Cargo.toml
  examples/token-vendor/workshop-example/Cargo.toml
  gear-test/Cargo.toml
  gstd/Cargo.toml
  gtest/Cargo.toml
  lazy-pages/Cargo.toml
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/service.rs
  pallets/gas/Cargo.toml
  pallets/gas/src/lib.rs
  pallets/gas/src/mock.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/mock.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/mock.rs
  pallets/gear/Cargo.toml
  pallets/gear/rpc/Cargo.toml
  pallets/gear/rpc/runtime-api/Cargo.toml
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/usage/Cargo.toml
  pallets/usage/src/lib.rs
  pallets/usage/src/mock.rs
  runtime-interface/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  utils/gear-runtime-test-cli/Cargo.toml
Labels: A2-mergeoncegreen, D1-core, D2-node, D3-gstd, D4-test

#816 CI: Fix cache
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#804 Add mailbox mock to gtest
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/mailbox.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A0-pleasereview, D5-tooling

#818 Remove unused crates
  Cargo.lock
  core-backend/sandbox/Cargo.toml
  core/Cargo.toml
  examples/Cargo.lock
  examples/chat/Cargo.toml
  pallets/gas/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-program/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/gear/rpc/Cargo.toml
  pallets/gear/rpc/runtime-api/Cargo.toml
  pallets/usage/Cargo.toml
  runtime-interface/Cargo.toml
  runtime/Cargo.toml
  utils/gear-runtime-test-cli/Cargo.toml
  utils/wasm-proc/Cargo.toml
Labels: A2-mergeoncegreen

#821 [skip ci] Fix image urls in readme
  README.md
Labels: A2-mergeoncegreen

#820 Fix build on Linux
  examples/binaries/btree/src/lib.rs
  examples/binaries/distributor/src/lib.rs
Labels: A4-insubstantial

#827 Fix `core-processor` misprint and provide compact `From`'s for core
  core-processor/src/executor.rs
  core-processor/src/processor.rs
  core/src/message/common.rs
  core/src/message/handle.rs
  core/src/message/incoming.rs
  core/src/message/reply.rs
  core/src/message/stored.rs
  gear-test/src/check.rs
  gear-test/src/manager.rs
  gtest/src/manager.rs
  pallets/gear-program/src/tests.rs
  pallets/gear/src/manager.rs
  pallets/usage/src/tests.rs
  runtime/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A2-mergeoncegreen, C2-refactoring

#765 Provide active and terminated program checks
  core-processor/src/common.rs
  gear-test/spec/test_create_program.yaml
  gear-test/spec/test_failed_program_msg_handling.yaml
  gear-test/src/check.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gear-test/src/sample.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/manager.rs
  runtime/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A2-mergeoncegreen, C2-refactoring, D5-tooling

#810 Configurable page size
  Cargo.lock
  common/src/benchmarking.rs
  common/src/lazy_pages.rs
  common/src/lib.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/memory.rs
  core-backend/wasmtime/src/env.rs
  core-backend/wasmtime/src/funcs.rs
  core-backend/wasmtime/src/memory.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/code.rs
  core/src/env.rs
  core/src/memory.rs
  core/src/program.rs
  examples/binaries/program-factory/src/lib.rs
  gear-test/src/check.rs
  gear-test/src/proc.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/unix.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear-program/src/benchmarking.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/pause.rs
  pallets/gear-program/src/tests.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/tests.rs
  pallets/usage/src/mock.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/lib.rs
  runtime/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A0-pleasereview, D1-core, D2-node, B1-releasenotes

#808 Make `msg::send*` and `msg::reply*` functions fallible
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/lib.rs
  core-backend/wasmtime/src/env.rs
  core-backend/wasmtime/src/funcs.rs
  examples/async-init/src/lib.rs
  examples/async-multisig/src/lib.rs
  examples/async-sign/src/lib.rs
  examples/async/src/lib.rs
  examples/binaries/btree/src/lib.rs
  examples/binaries/distributor/src/lib.rs
  examples/binaries/exit-handle/src/lib.rs
  examples/binaries/exit-init/src/lib.rs
  examples/binaries/init-wait/src/code.rs
  examples/binaries/node/src/lib.rs
  examples/binaries/program-factory/src/lib.rs
  examples/binaries/wait_wake/src/lib.rs
  examples/block-info/src/lib.rs
  examples/bot/src/lib.rs
  examples/capacitor/src/lib.rs
  examples/chat/bot/src/lib.rs
  examples/chat/room/src/lib.rs
  examples/collector/src/lib.rs
  examples/create-program/src/lib.rs
  examples/decoder/src/lib.rs
  examples/exit-code/src/lib.rs
  examples/fib/src/lib.rs
  examples/fungible-token/src/lib.rs
  examples/futures-unordered/src/lib.rs
  examples/guestbook/src/lib.rs
  examples/gui-test/src/lib.rs
  examples/incomplete_async_payloads/src/lib.rs
  examples/mem/src/lib.rs
  examples/meta/src/lib.rs
  examples/minimal/src/lib.rs
  examples/multiping/src/lib.rs
  examples/mutex/src/lib.rs
  examples/ping/src/lib.rs
  examples/program-id/src/lib.rs
  examples/rwlock/src/lib.rs
  examples/rwlock_write/src/lib.rs
  examples/state_rollback/src/lib.rs
  examples/sum/src/lib.rs
  examples/sync_duplicate/src/lib.rs
  examples/token-vendor/src/lib.rs
  examples/token-vendor/workshop-example/src/lib.rs
  examples/vec/src/lib.rs
  examples/wait/src/lib.rs
  gcore/src/exec.rs
  gcore/src/msg.rs
  gcore/src/prog.rs
  gcore/tests/smoke.rs
  gstd/src/common/errors.rs
  gstd/src/exec.rs
  gstd/src/msg/async.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
  utils/wasm-builder/test-program/src/lib.rs
Labels: A2-mergeoncegreen, D1-core, D3-gstd, B1-releasenotes

#814 Log ids as hex strings
  core/src/ids.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D2-node

#840 Remove redundant testing from `CI` and `pre-commit`
  .github/workflows/CI.yaml
  Makefile
Labels: D5-tooling, A4-insubstantial

#843 CI: use another expression for cache
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#839 Message-processing during runtime upgrade
  .gitattributes
  .github/workflows/CI.yaml
  .gitignore
  Makefile
  pallets/gear/src/lib.rs
  runtime/src/lib.rs
  scripts/gear.sh
  scripts/src/init.sh
  scripts/src/test.sh
  scripts/test-utils/README.md
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  scripts/test-utils/package-lock.json
  scripts/test-utils/package.json
  scripts/test-utils/processingMessageWithRuntimeUpgrade.js
Labels: A0-pleasereview, C1-feature, D4-test

#844 Fix unspecified nodes
  pallets/gas/src/lib.rs
  pallets/gas/src/tests.rs
  pallets/usage/Cargo.toml
  pallets/usage/src/lib.rs
  pallets/usage/src/offchain.rs
  pallets/usage/src/tests.rs
  runtime/src/lib.rs
Labels: D2-node, C0-bug

#837 Add coverage in CI
  .github/workflows/CI.yaml
  scripts/gear.sh
  scripts/src/coverage.sh
  scripts/src/test.sh
  utils/wasm-builder/src/cargo_command.rs
Labels: A0-pleasereview, D5-tooling

#846 Clippy cleanup
  .github/workflows/CI.yaml
  examples/binaries/distributor/src/lib.rs
  examples/binaries/program-factory/src/lib.rs
  gcore/tests/smoke.rs
  gtest/src/mailbox.rs
  lazy-pages/src/unsupported.rs
  pallets/gas/src/tests.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/tests.rs
  pallets/usage/src/mock.rs
  pallets/usage/src/tests.rs
  runtime-interface/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  scripts/gear.sh
  scripts/src/check.sh
Labels: A0-pleasereview, D5-tooling, C3-debt

#836 Eliminate possibility of panic in `LaterExt::unset`
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmtime/src/env.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/env.rs
  core/src/gas.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D1-core

#857 Provide non-trivial fee multiplier
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C0-bug

#856 Review arithmetic operations to be safe and sound
  core-processor/src/ext.rs
  core/src/gas.rs
  core/src/memory.rs
  pallets/gas/src/lib.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  runtime-interface/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D1-core, D2-node

#835 Provide gasful reply syscalls
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmtime/src/env.rs
  core-backend/wasmtime/src/funcs.rs
  examples/ping/src/lib.rs
  gcore/src/msg.rs
  gear-test/spec/test_ping.yaml
  gstd/src/msg/basic.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D1-core, C1-feature

#834 pallet-gear: Host functions weights
  .maintain/gear-weight-template.hbs
  Cargo.lock
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmtime/src/funcs.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/code.rs
  core/src/costs.rs
  core/src/env.rs
  core/src/gas.rs
  core/src/lib.rs
  core/src/message/context.rs
  core/src/message/mod.rs
  examples/Cargo.lock
  examples/async-multisig/Cargo.toml
  gear-test/spec/test_vec.yaml
  gear-test/src/proc.rs
  gtest/src/manager.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear/Cargo.toml
  pallets/gear/proc-macro/Cargo.toml
  pallets/gear/proc-macro/src/lib.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/sandbox.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  pallets/usage/src/mock.rs
  runtime/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A2-mergeoncegreen, D2-node, C1-feature, D5-tooling

#870 Improve programs' panic handling
  core-processor/src/ext.rs
  gstd/src/common/handlers.rs
  gstd/src/lib.rs
  gstd/src/macros/debug.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D1-core, D3-gstd

#851 Store program codes in pallet gear-program
  common/src/code_storage.rs
  common/src/lib.rs
  core-processor/src/executor.rs
  core/src/code.rs
  core/src/program.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-program/src/code.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/usage/src/mock.rs
  pallets/usage/src/tests.rs
  runtime/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring

#873 Introduce StorageVersion
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migration.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/migration.rs
  pallets/usage/src/lib.rs
  pallets/usage/src/migration.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#866 [skip ci] Instructuions how to upgrade node in runtime
  images/sudo-upgrade.png
  node/README.md
Labels: A0-pleasereview, D2-node
