Repository gear-tech/gear, pull requests merged in 2022-05, with the labels that each got.

#872 Idiomatic errors
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/src/lazy_pages.rs
  core-backend/common/Cargo.toml
  core-backend/common/src/funcs.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmtime/Cargo.toml
  core-backend/wasmtime/src/env.rs
  core-backend/wasmtime/src/funcs.rs
  core-errors/Cargo.toml
  core-errors/src/lib.rs
  core-processor/Cargo.toml
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/Cargo.toml
  core/src/code.rs
  core/src/env.rs
  core/src/memory.rs
  core/src/message/context.rs
  core/src/program.rs
  gtest/src/manager.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/tests.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/lib.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D1-core

#882 store contracts pages data in storage in lazy manner
  Cargo.lock
  Makefile
  common/src/benchmarking.rs
  common/src/lazy_pages.rs
  common/src/lib.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmtime/src/env.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/handler.rs
  core-processor/src/processor.rs
  core/src/memory.rs
  core/src/program.rs
  gear-test/src/check.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/unix.rs
  node/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/benchmarking.rs
  pallets/gear-program/src/pause.rs
  pallets/gear-program/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/usage/src/mock.rs
  runtime-interface/src/lib.rs
  runtime/src/lib.rs
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  scripts/test-utils/processingMessageWithRuntimeUpgrade.js
  utils/gear-runtime-test-cli/Cargo.toml
  utils/gear-runtime-test-cli/src/command.rs
Labels: A0-pleasereview, D1-core, D2-node

#863 Introduce gear payment pallet
  Cargo.lock
  common/src/storage/deque.rs
  core-backend/sandbox/src/funcs.rs
  gear-test/src/proc.rs
  pallets/payment/Cargo.toml
  pallets/payment/README.md
  pallets/payment/src/lib.rs
  pallets/payment/src/mock.rs
  pallets/payment/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#891 Optimize wasm
  .github/workflows/CI.yaml
  Cargo.lock
  examples/.cargo/config.toml
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/cargo_command.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview, D5-tooling

#908 Add test case that there is no double charging
  pallets/usage/src/offchain.rs
  pallets/usage/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#935 Fix wasm-builder cannot be built on Windows
  utils/wasm-builder/src/optimize.rs
Labels: A0-pleasereview, D5-tooling

#940 Introduce value checking for `init` messages
  Cargo.lock
  core-errors/src/lib.rs
  core-processor/src/ext.rs
  core/src/costs.rs
  examples/binaries/init-with-value/Cargo.toml
  examples/binaries/init-with-value/build.rs
  examples/binaries/init-with-value/child_contract.wasm
  examples/binaries/init-with-value/src/lib.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D1-core, D2-node

#950 Fix of the bug with sending reply to terminated destination
  Cargo.lock
  examples/binaries/exit-init/Cargo.toml
  examples/binaries/exit-init/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#932 move codecov to build job
  .github/workflows/CI.yaml
  codecov.yml
  scripts/src/test.sh
Labels: A0-pleasereview, D4-test

#953 Merge imports
  common/src/lazy_pages.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmtime/src/funcs.rs
  core-backend/wasmtime/src/memory.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/lib.rs
  core-processor/src/processor.rs
  core/src/message/context.rs
  core/src/message/init.rs
  core/src/program.rs
  examples/chat/src/encode.rs
  examples/decoder/src/lib.rs
  examples/futures-unordered/src/lib.rs
  examples/mutex/src/lib.rs
  examples/rwlock/src/lib.rs
  examples/rwlock_write/src/lib.rs
  gcore/src/exec.rs
  gcore/src/msg.rs
  gcore/src/prog.rs
  gear-test/src/check.rs
  gear-test/src/js/mod.rs
  gear-test/src/proc.rs
  gstd/src/async_runtime/futures.rs
  gstd/src/async_runtime/signals.rs
  gstd/src/common/primitives.rs
  gstd/src/lib.rs
  gstd/src/lock/access.rs
  gstd/src/msg/async.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  gstd/src/prelude.rs
  gtest/src/log.rs
  gtest/src/mailbox.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/mock.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  pallets/usage/src/lib.rs
  pallets/usage/src/mock.rs
  pallets/usage/src/offchain.rs
  runtime/src/lib.rs
  rustfmt.toml
  utils/gear-runtime-test-cli/src/util.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A2-mergeoncegreen, D5-tooling

#955 Address new clippy warnings
  common/src/lib.rs
  core/src/env.rs
  core/src/gas.rs
  examples/binaries/btree/src/lib.rs
  examples/binaries/distributor/src/lib.rs
  examples/binaries/node/src/lib.rs
  examples/binaries/wait_wake/src/lib.rs
  examples/meta/src/lib.rs
  examples/token-vendor/src/lib.rs
  gear-test/src/address.rs
  gear-test/src/js/mod.rs
  gear-test/src/sample.rs
  gstd/src/common/primitives.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-program/src/pause.rs
  pallets/gear/src/lib.rs
  pallets/usage/src/offchain.rs
  runtime/src/lib.rs
Labels: A0-pleasereview

#964 Remove legacy clears
  common/src/lib.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen

#966 Introduce `lazy-pages` feature for `pallet-gear-debug`
  core/src/memory.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A0-pleasereview, C0-bug, D4-test

#976 Fix value sending in async scenarios
  Cargo.lock
  core-processor/src/processor.rs
  examples/binaries/waiting-proxy/Cargo.toml
  examples/binaries/waiting-proxy/build.rs
  examples/binaries/waiting-proxy/src/lib.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D1-core, C0-bug

#984 Fix get gas spent and update cascade test
  core-processor/src/handler.rs
  examples/binaries/mul-by-const/src/lib.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/tests.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, C0-bug, C2-refactoring

#967 Introduce `Waitlist` type for `Messenger`
  Cargo.lock
  Makefile
  common/src/lib.rs
  common/src/storage/complex/mailbox.rs
  common/src/storage/complex/messenger.rs
  common/src/storage/complex/mod.rs
  common/src/storage/complex/waitlist.rs
  common/src/storage/primitives/callback.rs
  common/src/storage/primitives/double_map.rs
  common/src/storage/primitives/iterable.rs
  common/src/storage/primitives/key.rs
  common/src/storage/primitives/mod.rs
  core-processor/src/executor.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/benchmarking.rs
  pallets/gear-program/src/code.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/mock.rs
  pallets/gear-program/src/pause.rs
  pallets/gear-program/src/program.rs
  pallets/gear-program/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  pallets/payment/src/tests.rs
  pallets/usage/src/lib.rs
  pallets/usage/src/mock.rs
  pallets/usage/src/offchain.rs
  pallets/usage/src/tests.rs
  runtime/src/lib.rs
  scripts/gear.sh
  scripts/src/build.sh
  scripts/src/test.sh
  utils/gear-runtime-test-cli/src/command.rs
Labels: A2-mergeoncegreen, D1-core, D2-node
