Repository gear-tech/gear, pull requests merged in 2022-03, with the labels that each got.

#742 Modify node startup scripts to enable essential debug logging
  ansible/tasks/docker/docker-compose.yaml.j2
  pallets/usage/src/mock.rs
  pallets/usage/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#748 Add more Gear crates to docs generating
  .github/workflows/docs.yml
  gcore/src/msg.rs
  gstd/src/msg/async.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  lazy-pages/src/lib.rs
Labels: A4-insubstantial

#752 [skip ci] Fix setting of env vars in docker-compose template
  ansible/tasks/docker/docker-compose.yaml.j2
Labels: A0-pleasereview, D2-node, Q1-easy

#754 gear-wasm-builder: Fix target WASM path when using in workspace
  Cargo.lock
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/README.md
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-builder/test-program/Cargo.lock
Labels: A2-mergeoncegreen, D5-tooling

#764 Handle possible errors in `core-processor`
  Cargo.lock
  core-processor/src/ext.rs
  core-processor/src/lib.rs
  core-processor/src/processor.rs
  runtime/src/lib.rs
  tests/common/Cargo.toml
  tests/common/src/lib.rs
Labels: A0-pleasereview, D1-core, C2-refactoring

#759 Avoid env vars in `gtest::Program::current()`
  Cargo.lock
  gtest/src/program.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-builder/test-program/.gitignore
  utils/wasm-builder/test-program/Cargo.lock
Labels: A0-pleasereview, D5-tooling

#727 Refactor the gas spent calculator
  .gitignore
  Cargo.lock
  Makefile
  common/src/lib.rs
  pallets/gear/Cargo.toml
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
  scripts/calc-gas-spent.sh
  scripts/src/run.sh
  tests/btree/src/lib.rs
  utils/wasm-builder/test-program/Cargo.lock
Labels: A2-mergeoncegreen, D2-node

#773 Remove panics from lazy pages
  Cargo.lock
  common/src/lazy_pages.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmtime/src/env.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/gas.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/unix.rs
  pallets/gear/src/ext.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D1-core, C2-refactoring

#779 Add `.gitattributes` configuration file
  .gitattributes
Labels: D5-tooling

#784 Fix Git thinks images are text
  .gitattributes
Labels: A2-mergeoncegreen, D5-tooling

#782 Get rid of unsafe SyncLaterExt
  core-backend/wasmtime/src/env.rs
  core-backend/wasmtime/src/funcs.rs
  core-backend/wasmtime/src/memory.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D1-core

#786 Small amendment of GasHandler API
  common/src/lib.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/tests.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/usage/src/lib.rs
  pallets/usage/src/mock.rs
  pallets/usage/src/offchain.rs
  pallets/usage/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#795 Use patched ring
  Cargo.lock
  Cargo.toml
Labels: A2-mergeoncegreen

#778 Handle possible errors in `pallet gear`
  Cargo.lock
  common/Cargo.toml
  common/src/lib.rs
  common/src/native.rs
  core/src/checked_code.rs
  core/src/code_hash.rs
  core/src/lib.rs
  core/src/program.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gtest/src/program.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/tests.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/tests.rs
  pallets/usage/src/tests.rs
  runtime/src/lib.rs
  tests/common/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#787 switch to host executor in wasm runtime
  .gitignore
  Cargo.lock
  common/Cargo.toml
  common/src/lazy_pages.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/memory.rs
  core-backend/wasmtime/src/env.rs
  core-backend/wasmtime/src/memory.rs
  core-processor/src/ext.rs
  core/src/memory.rs
  pallets/gear/src/ext.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#755 Introduce program creation from program in `gtest`
  Cargo.lock
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
  tests/program-factory/Cargo.toml
  tests/program-factory/child_contract.wasm
  tests/program-factory/src/lib.rs
Labels: A0-pleasereview, D5-tooling

#800 resolve panics in core backend
  core-backend/common/src/funcs.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/memory.rs
  core-backend/wasmtime/src/env.rs
  core-backend/wasmtime/src/funcs.rs
  core-backend/wasmtime/src/memory.rs
  core-processor/src/ext.rs
  core/src/memory.rs
  pallets/gear/src/ext.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D1-core, C2-refactoring, Q1-easy

#803 Use branch with pregenerated files for patched ring
  Cargo.lock
  Cargo.toml
Labels: A2-mergeoncegreen, D5-tooling

#801 Lighten `gear-test` crate
  Cargo.lock
  gear-test/Cargo.toml
  gear-test/spec/test_async_sign.yaml
  gear-test/spec/test_create_program.yaml
  gear-test/src/address.rs
  gear-test/src/check.rs
  gear-test/src/main.rs
  gear-test/src/proc.rs
Labels: A2-mergeoncegreen, C2-refactoring, D5-tooling

#805 Revert "use patched ring to fix CI (#795)"
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview, D5-tooling

#807 Fix development builds on Windows
  galloc/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview
