Repository gear-tech/gear, pull requests merged in 2022-01, with the labels that each got.

#553 `pallet_gear`: add reset extrinsic
  .github/workflows/CI.yaml
  .github/workflows/Runtime-upgrade.yaml
  common/src/lib.rs
  pallets/gear/src/lib.rs
Labels: A0-pleasereview, D2-node

#565 Add workaround to rpc-tests
  rpc-tests/src/index.ts
Labels: A2-mergeoncegreen, C0-bug, D5-tooling

#574 Add gas handler for pallet
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  utils/gear-test-cli/src/manager.rs
Labels: A2-mergeoncegreen, D2-node

#517 Add support to calling `wait` in `init` on the node side
  Cargo.lock
  common/src/lib.rs
  common/src/native.rs
  examples/Cargo.lock
  examples/Cargo.toml
  examples/init-wait/Cargo.toml
  gtest/src/check.rs
  gtest/src/manager.rs
  gtest/src/proc.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  tests/init-wait/Cargo.toml
  tests/init-wait/build.rs
  tests/init-wait/src/code.rs
  tests/init-wait/src/lib.rs
  utils/gear-test-cli/src/manager.rs
Labels: A2-mergeoncegreen, D2-node

#580 bump spec version
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#582 Runtime-upgrade: checkout repo
  .github/workflows/Runtime-upgrade.yaml
Labels: A0-pleasereview

#583 Upgrade-runtime in two steps via cli
  .github/workflows/Runtime-upgrade.yaml
  utils/runtime-upgrade/index.js
  utils/runtime-upgrade/package-lock.json
  utils/runtime-upgrade/package.json
Labels: A0-pleasereview

#557 Keep all gas in parent's tree when sending message to mailbox
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D1-core, D2-node

#584 Validate `Registry` for each `.meta.wasm`
  utils/wasm-proc/metadata-js/index.js
  utils/wasm-proc/metadata-js/test.js
Labels: C1-feature, D4-test

#592 Minor refactoring
  core-processor/src/executor.rs
  core-processor/src/handler.rs
  core-processor/src/processor.rs
  gtest/src/manager.rs
Labels: A4-insubstantial

#600 Load dynamic memory pages for consequent `init` calls
  core-processor/src/executor.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  tests/init-wait/src/code.rs
  tests/init-wait/src/lib.rs
Labels: A2-mergeoncegreen, D1-core, C0-bug

#597 Add trap reason to runtime log
  core-processor/src/common.rs
  core-processor/src/processor.rs
  pallets/gear/src/manager.rs
  tests/common/src/lib.rs
Labels: A2-mergeoncegreen, D2-node

#604 Fix build with rustc 1.60.0-nightly (5e57faa78 2022-01-19)
  Cargo.lock
  tests/btree/Cargo.toml
  tests/distributor/Cargo.toml
  tests/distributor/src/lib.rs
  tests/init-wait/Cargo.toml
  tests/messages/Cargo.toml
  tests/messages/src/lib.rs
  tests/node/Cargo.toml
  tests/wait_wake/Cargo.toml
Labels: A1-inprogress, C0-bug

#586 Implement `async_init` macro
  common/src/lib.rs
  common/src/storage_queue.rs
  examples/Cargo.lock
  examples/Cargo.toml
  examples/async-init/Cargo.toml
  examples/async-init/src/lib.rs
  gstd/codegen/src/lib.rs
  gstd/src/lib.rs
  gtest/spec/test_async_init.yaml
  gtest/src/check.rs
  gtest/src/manager.rs
  gtest/src/proc.rs
  pallets/gear/src/manager.rs
  utils/gear-test-cli/src/manager.rs
Labels: A2-mergeoncegreen, D3-gstd, B1-releasenotes, D4-test, D5-tooling

#617 Update substrate
  Cargo.lock
  common/Cargo.toml
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/memory.rs
  core/src/util.rs
  examples/Cargo.lock
  examples/async-multisig/Cargo.toml
  examples/async-multisig/src/lib.rs
  examples/async-sign/Cargo.toml
  examples/async-sign/src/lib.rs
  gear-test/Cargo.toml
  gear-test/src/proc.rs
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/lib.rs
  node/src/service.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/mock.rs
  pallets/gear/Cargo.toml
  pallets/gear/rpc/Cargo.toml
  pallets/gear/rpc/runtime-api/Cargo.toml
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/usage/Cargo.toml
  pallets/usage/src/lib.rs
  pallets/usage/src/mock.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  utils/gear-test-cli/Cargo.toml
  utils/gear-test-cli/src/lib.rs
Labels: A0-pleasereview, D2-node
