Repository gear-tech/gear, pull requests merged in 2022-07, with the labels that each got.

#1106 Extend `gtest::Program::meta_state` functionality and make it fallible
  Cargo.lock
  gtest/Cargo.toml
  gtest/src/error.rs
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/mailbox.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
  gtest/src/wasm_executor.rs
  pallets/payment/src/lib.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, B1-releasenotes, D4-test, D5-tooling

#1155 Avoid dynamic dispatching
  common/src/lazy_pages.rs
  core-backend/common/src/funcs.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmtime/src/env.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/handler.rs
  core/src/env.rs
  core/src/memory.rs
  pallets/gear/src/ext.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D1-core

#1125 gtest: Add capability to check actors balances
  examples/Cargo.lock
  examples/Cargo.toml
  examples/piggy-bank/Cargo.toml
  examples/piggy-bank/src/lib.rs
  gtest/src/log.rs
  gtest/src/mailbox.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A0-pleasereview, B1-releasenotes, D5-tooling

#1154 Add ability to pin nightly toolchain
  .github/workflows/CI.yaml
Labels: A2-mergeoncegreen, C1-feature, D5-tooling

#1157 Change spec titles to render its test's logic
  gear-test/spec/test_async_recursion.yaml
  gear-test/spec/test_chat.yaml
  gear-test/spec/test_exit_code.yaml
  gear-test/spec/test_program_generator.yaml
  gear-test/spec/test_vec.yaml
Labels: A0-pleasereview, D4-test, A4-insubstantial

#1134 Introduce common configs for processor
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/lib.rs
  core-processor/src/processor.rs
  core/src/costs.rs
  gear-test/src/check.rs
  gear-test/src/main.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/wasm_executor.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  runtime/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A0-pleasereview, D1-core, D2-node

#1163 Revert previous WASM path in `gear-wasm-builder` + minor cleanup
  common/src/lib.rs
  examples/binaries/calc-hash/over-blocks/src/lib.rs
  runtime/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-builder/test-program/src/lib.rs
Labels: A0-pleasereview, D5-tooling

#1166 add not allocated pages test
  pallets/gear-debug/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, A2-mergeoncegreen, D4-test

#1169 Update script and add boxploting
  scripts/performance-boxplot.py
  scripts/performance-check.sh
Labels: A2-mergeoncegreen, C2-refactoring, D4-test, D5-tooling

#1156 Expand `From` implementations for `gtest::Log`
  gtest/src/log.rs
  gtest/src/program.rs
Labels: A0-pleasereview, D3-gstd

#1176 Value sendings and ED fixes for `gtest`
  gtest/src/mailbox.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A0-pleasereview, D3-gstd, C1-feature

#1186 Correct most obvious mistakes in docs
  .github/workflows/docs.yml
  Makefile
  common/src/gas_provider/mod.rs
  gcore/src/msg.rs
  gstd/codegen/src/lib.rs
  gstd/codegen/src/utils.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  gtest/src/error.rs
Labels: A0-pleasereview

#1191 Authorities and authorship in utils
  Cargo.lock
  utils/economic-checks/Cargo.toml
  utils/economic-checks/src/util.rs
  utils/gear-runtime-test-cli/Cargo.toml
  utils/gear-runtime-test-cli/src/command.rs
  utils/gear-runtime-test-cli/src/lib.rs
  utils/gear-runtime-test-cli/src/util.rs
Labels: A0-pleasereview, C1-feature, D5-tooling

#1194 Update substrate
  Cargo.lock
  node/Cargo.toml
  pallets/gas/src/mock.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-messenger/src/mock.rs
  pallets/gear-program/src/mock.rs
  pallets/gear/rpc/Cargo.toml
  pallets/gear/src/mock.rs
  pallets/payment/src/mock.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#1087 Restructure gas tree
  common/src/gas_provider/error.rs
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/node.rs
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  common/src/gas_provider/property_tests/strategies.rs
  common/src/gas_provider/property_tests/utils.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#1196 gtest: Fix panic message decoding in log
  gtest/src/manager.rs
  gtest/src/program.rs
Labels: A0-pleasereview, D5-tooling

#1202 Fix weights and benchmarks
  .maintain/gear-weight-template.hbs
  gear-test/spec/test_async_multisig.yaml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/weights.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D2-node, C0-bug, C2-refactoring

#1198 Replace reply data tuple with struct
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmtime/src/funcs.rs
  core-processor/src/ext.rs
  core/src/env.rs
  core/src/message/common.rs
  core/src/message/incoming.rs
  core/src/message/mod.rs
  core/src/message/reply.rs
  core/src/message/stored.rs
  gtest/src/log.rs
  gtest/src/mailbox.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D1-core, C2-refactoring

#1197 Internal pallet module
  common/src/storage/complex/mailbox.rs
  common/src/storage/complex/messenger.rs
  common/src/storage/complex/waitlist.rs
  common/src/storage/primitives/mod.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/pause.rs
  pallets/gear-program/src/tests.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D2-node, C1-feature

#1219 gtest: Provide block height and timestamp to `meta_state` function
  examples/block-info/src/lib.rs
  gear-test/spec_no_runtime/test_block_info.yaml
  gtest/src/manager.rs
  gtest/src/system.rs
  gtest/src/wasm_executor.rs
Labels: A0-pleasereview, D5-tooling

#1223 Don't process data for stack pages
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmi/src/env.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  pallets/gear/src/ext.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D1-core, C2-refactoring

#1164 Some gear-wasm-builder improvements
  utils/wasm-builder/src/cargo_command.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, D5-tooling

#1225 Refactor `GasNode` type
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/node.rs
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  pallets/gas/src/tests.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D2-node

#1229 update substrate, wasmi, parity-wasm, wasm-instrument
  Cargo.lock
  common/Cargo.toml
  common/src/gas_provider/property_tests/utils.rs
  core-backend/sandbox/Cargo.toml
  core-backend/wasmi/Cargo.toml
  core-backend/wasmi/src/env.rs
  core/Cargo.toml
  gear-test/Cargo.toml
  gtest/Cargo.toml
  node/src/benchmarking.rs
  node/src/command.rs
  node/src/main.rs
  node/src/service.rs
  pallets/gas/Cargo.toml
  pallets/gear-program/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/internal.rs
  pallets/payment/Cargo.toml
  runtime/src/lib.rs
  utils/economic-checks/Cargo.toml
Labels: A2-mergeoncegreen, D2-node

#1232 CI: save temp cache in PR
  .github/workflows/CI-drop-cache.yml
  .github/workflows/CI.yaml
Labels: A0-pleasereview, D5-tooling

#1234 Add authority into benches
  .github/workflows/CI.yaml
  Cargo.lock
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#1238 Set RUSTUP_HOME
  .github/workflows/CI.yaml
Labels: A2-mergeoncegreen, C0-bug, D5-tooling

#1220 Mailbox rent
  Cargo.lock
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/property_tests/utils.rs
  common/src/scheduler/mod.rs
  common/src/storage/complex/mailbox.rs
  common/src/storage/complex/messenger.rs
  core/src/message/common.rs
  core/src/message/stored.rs
  examples/binaries/value-sender/Cargo.toml
  examples/binaries/value-sender/build.rs
  examples/binaries/value-sender/src/code.rs
  examples/binaries/value-sender/src/lib.rs
  gtest/src/manager.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-messenger/src/mock.rs
  pallets/gear-program/src/mock.rs
  pallets/gear-scheduler/src/lib.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  runtime/src/lib.rs
  utils/economic-checks/src/targets.rs
  utils/economic-checks/src/util.rs
  utils/wasm-builder/src/stack_end.rs
Labels: A2-mergeoncegreen, D2-node, B1-releasenotes, C1-feature

#1233 Optimize gas nodes consumption
  common/src/gas_provider/internal.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D2-node

#1236 production profile w\ fat lto
  Cargo.toml
  core-backend/wasmi/src/funcs.rs
  docker/Dockerfile
  docker/build.sh
Labels: A0-pleasereview, D2-node

#1245 Add feature to generate `handle_reply` in bechmarks generator
  gcore/src/msg.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C0-bug

#1256 Fix clippy warnings upon compiler nightly version upgrade
  core-backend/common/src/utils.rs
  core-backend/sandbox/src/memory.rs
  core-backend/wasmi/src/memory.rs
  core/src/message/context.rs
  pallets/gas/src/tests.rs
  pallets/gear-program/src/tests.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/manager/journal.rs
Labels: A0-pleasereview, D1-core, D2-node, Q1-easy

#1261 Build runtime WASM and node binary using production profile
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#1262 [skip ci] Revert "Deploy node binary with `runtime-benchmaks`"
  docker/Dockerfile
Labels: A0-pleasereview
