Repository gear-tech/gear, pull requests merged in 2022-12, with the labels that each got.

#1928 Add ability to define custom entrypoints in async
  Cargo.lock
  examples/binaries/async-custom-entry/Cargo.toml
  examples/binaries/async-custom-entry/build.rs
  examples/binaries/async-custom-entry/src/lib.rs
  gstd/codegen/Cargo.toml
  gstd/codegen/src/lib.rs
  gstd/codegen/tests/ui/async_init_works.rs
  gstd/codegen/tests/ui/async_main_works.rs
  gstd/codegen/tests/ui/reply_double_definition_not_work.rs
  gstd/codegen/tests/ui/reply_double_definition_not_work.stderr
  gstd/codegen/tests/ui/signal_double_definition_not_work.rs
  gstd/codegen/tests/ui/signal_double_definition_not_work.stderr
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D3-gstd

#1941 Add production profile to demos built with `wasm-builder`
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, D5-tooling

#1943 Appease last clippy warnings
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-errors/src/lib.rs
  gear-test/src/check.rs
  lazy-pages/src/lib.rs
  pallets/gear/src/tests.rs
  utils/wasm-builder/src/optimize.rs
Labels: A2-mergeoncegreen

#1942 Use different directory for test data
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview, D5-tooling

#1950 Implement `gr_signal_from`
  core-backend/common/src/mock.rs
  core-backend/common/src/syscalls.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-errors/src/lib.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/costs.rs
  core/src/env.rs
  core/src/message/signal.rs
  examples/binaries/signal-entry/src/lib.rs
  examples/binaries/sys-calls/src/lib.rs
  gcore/src/msg.rs
  gstd/src/msg/basic.rs
  gsys/src/lib.rs
  gtest/src/program.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A0-pleasereview, D1-core, D3-gstd

#1953 Add new modules for `process_queue` & `calculate_gas_info`
  Cargo.lock
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node, C2-refactoring, A4-insubstantial

#1909 Fix bugs in delayed messaging
  common/src/scheduler/task.rs
  examples/binaries/proxy-with-gas/src/lib.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node, C0-bug

#1854 Charge for reservation holding
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/storage/primitives/mod.rs
  core-errors/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/ext.rs
  core-processor/src/handler.rs
  core-processor/src/processor.rs
  core/src/message/context.rs
  core/src/reservation.rs
  examples/binaries/reserve-gas/src/lib.rs
  examples/binaries/signal-entry/src/lib.rs
  gear-test/src/manager.rs
  gtest/src/manager.rs
  gtest/src/wasm_executor.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
  program/tests/rpc/mod.rs
Labels: A0-pleasereview, D2-node, D4-test

#1848 Forbid some sys-calls in handle_signal
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-processor/src/executor.rs
  core/src/ids.rs
  core/src/message/mod.rs
  core/src/message/signal.rs
  examples/binaries/signal-entry/src/lib.rs
  gtest/src/wasm_executor.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/tests.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, D1-core

#1955 Use SysCallName everywhere
  Cargo.lock
  core-backend/common/Cargo.toml
  core-backend/common/src/lib.rs
  core-backend/common/src/mock.rs
  core-backend/common/src/syscalls.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-processor/Cargo.toml
  core-processor/src/configs.rs
  core-processor/src/ext.rs
  core/src/env.rs
  core/src/message/mod.rs
  gtest/src/wasm_executor.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/runtime_api.rs
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/syscalls.rs
  utils/wasm-instrument/Cargo.toml
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/syscalls.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#1963 Add doc tests to CI
  .github/workflows/CI.yaml
  .github/workflows/docs.yml
  examples/binaries/signal-entry/src/lib.rs
  gcore/src/exec.rs
  scripts/gear.sh
  scripts/src/test.sh
Labels: A2-mergeoncegreen

#1969 Fix GH Actions conditional `needs`
  .github/workflows/CI.yaml
Labels: A0-pleasereview, D5-tooling, E1-forcewindows, E2-forcemacos

#1967 Fix the panic after init message `prepare` failure
  core-processor/src/common.rs
  core-processor/src/processor.rs
  gtest/src/manager.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, P0-dropeverything, C0-bug

#1972 Pin `substrate` to `v0.9.33` tag
  .github/workflows/CI.yaml
  .github/workflows/Runtime-upgrade-reset.yaml
  .github/workflows/Runtime-upgrade.yaml
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/lazy-pages/Cargo.toml
  core-backend/sandbox/Cargo.toml
  gear-test/Cargo.toml
  lazy-pages/Cargo.toml
  node/authorship/Cargo.toml
  node/authorship/src/authorship.rs
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/service/Cargo.toml
  node/service/src/client.rs
  pallets/gas/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-messenger/Cargo.toml
  pallets/gear-program/Cargo.toml
  pallets/gear-scheduler/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/gear/rpc/Cargo.toml
  pallets/gear/rpc/runtime-api/Cargo.toml
  pallets/payment/Cargo.toml
  program/Cargo.toml
  program/src/cmd/create.rs
  program/src/cmd/info.rs
  program/src/cmd/key.rs
  program/src/cmd/login.rs
  program/src/cmd/meta.rs
  program/src/cmd/mod.rs
  program/src/cmd/program.rs
  program/src/cmd/reply.rs
  program/src/cmd/send.rs
  program/src/cmd/update.rs
  program/src/cmd/upload_program.rs
  runtime-interface/Cargo.toml
  runtime/common/Cargo.toml
  runtime/gear/Cargo.toml
  runtime/primitives/Cargo.toml
  runtime/vara/Cargo.toml
  scripts/src/build.sh
  utils/economic-checks/Cargo.toml
  utils/gear-runtime-test-cli/Cargo.toml
  utils/gear-runtime-test-cli/src/lib.rs
  utils/regression-analysis/Cargo.toml
  utils/regression-analysis/src/main.rs
  utils/test-runtime/Cargo.toml
  utils/test-runtime/client/Cargo.toml
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-proc/Cargo.toml
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview, D2-node, D5-tooling

#1751 Refine reading state approach
  Cargo.lock
  Cargo.toml
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmi/src/env.rs
  core-processor/src/executor.rs
  core-processor/src/lib.rs
  core/src/code.rs
  core/src/message/mod.rs
  examples/binaries/new-meta/.metahash
  examples/binaries/new-meta/Cargo.toml
  examples/binaries/new-meta/build.rs
  examples/binaries/new-meta/io/Cargo.toml
  examples/binaries/new-meta/io/src/lib.rs
  examples/binaries/new-meta/meta.txt
  examples/binaries/new-meta/src/lib.rs
  examples/binaries/new-meta/src/wasm.rs
  examples/binaries/new-meta/state-v1/Cargo.toml
  examples/binaries/new-meta/state-v1/build.rs
  examples/binaries/new-meta/state-v1/src/lib.rs
  examples/binaries/new-meta/state-v1/src/wasm.rs
  examples/binaries/new-meta/state-v2/Cargo.toml
  examples/binaries/new-meta/state-v2/build.rs
  examples/binaries/new-meta/state-v2/src/lib.rs
  examples/binaries/new-meta/state-v2/src/wasm.rs
  gmeta/Cargo.toml
  gmeta/codegen/Cargo.toml
  gmeta/codegen/src/lib.rs
  gmeta/src/lib.rs
  gtest/src/wasm_executor.rs
  pallets/gear/Cargo.toml
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  runtime/common/src/apis.rs
  scripts/metawasm.sh
  scripts/read-state.sh
  utils/test-runtime/src/lib.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, D2-node, C1-feature

#1959 Precharge message & gas_allowance for reinstrumentation
  common/src/benchmarking.rs
  common/src/code_storage.rs
  common/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/context.rs
  core-processor/src/executor.rs
  core-processor/src/lib.rs
  core-processor/src/processor.rs
  core/src/code.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear.rs
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  utils/gear-runtime-test-cli/src/command.rs
Labels: A2-mergeoncegreen, D1-core, D2-node, P0-dropeverything, C1-feature

#1990 Use CARGO_MANIFEST_DIR to get root of the repo
  gear-test/src/js/mod.rs
Labels: A0-pleasereview, C0-bug, D4-test, A4-insubstantial

#1981 Fix panic on wait + exit across executions
  core-processor/src/processor.rs
  examples/binaries/async-signal-entry/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node

#1992 gclient: Split mailbox getters and add `account_id` method
  gclient/src/api/calls.rs
  gclient/src/api/mod.rs
  gclient/src/api/storage/mod.rs
Labels: A0-pleasereview, D5-tooling

#1999 Make deterministic generation of seed for code seed generator
  utils/node-loader/src/CHANGELOG.md
  utils/node-loader/src/batch_pool/generators/batch.rs
  utils/node-loader/src/batch_pool/generators/seed.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#2004 gclient: Add `last_block_timestamp` function to API
  gclient/src/api/error.rs
  gclient/src/api/storage/block.rs
Labels: A0-pleasereview, D5-tooling

#1961 pages and lazy-pages refactoring
  Cargo.lock
  Cargo.toml
  common/lazy-pages/src/lib.rs
  common/src/benchmarking.rs
  common/src/lib.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/mock.rs
  core-backend/common/src/utils.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/memory.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/memory.rs
  core-errors/src/lib.rs
  core-processor/Cargo.toml
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/code.rs
  core/src/costs.rs
  core/src/env.rs
  core/src/memory.rs
  examples/binaries/new-meta/.metahash
  examples/binaries/new-meta/meta.txt
  gcore/src/general.rs
  gcore/src/msg.rs
  gear-test/src/check.rs
  gear-test/src/manager.rs
  gtest/src/manager.rs
  gtest/src/wasm_executor.rs
  lazy-pages/Cargo.toml
  lazy-pages/src/lib.rs
  lazy-pages/src/mprotect.rs
  lazy-pages/src/sys.rs
  lazy-pages/src/sys/unix.rs
  lazy-pages/src/sys/windows.rs
  lazy-pages/src/tests.rs
  lazy-pages/src/utils.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear-program/src/benchmarking.rs
  pallets/gear-program/src/tests.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/lib.rs
  runtime-interface/src/tests.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A0-pleasereview, D1-core, D2-node, E1-forcewindows

#2015 Improve loader logging
  Cargo.lock
  utils/node-loader/CHANGELOG.md
  utils/node-loader/Cargo.toml
  utils/node-loader/src/args.rs
  utils/node-loader/src/log.rs
  utils/node-loader/src/main.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#2020 Bump substrate to v0.9.36
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/lazy-pages/Cargo.toml
  core-backend/sandbox/Cargo.toml
  lazy-pages/Cargo.toml
  node/authorship/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/benchmarking.rs
  node/cli/src/command.rs
  node/service/Cargo.toml
  pallets/gas/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/lib.rs
  pallets/gear-messenger/Cargo.toml
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/lib.rs
  pallets/gear-scheduler/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/gear/rpc/Cargo.toml
  pallets/gear/rpc/runtime-api/Cargo.toml
  pallets/gear/src/lib.rs
  pallets/payment/Cargo.toml
  pallets/payment/src/mock.rs
  runtime-interface/Cargo.toml
  runtime/common/Cargo.toml
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/primitives/Cargo.toml
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  scripts/src/test.sh
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  utils/economic-checks/Cargo.toml
  utils/gear-runtime-test-cli/Cargo.toml
  utils/regression-analysis/Cargo.toml
  utils/test-runtime/Cargo.toml
  utils/test-runtime/client/Cargo.toml
  utils/test-runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#2030 Set log target for gear-authorship
  node/authorship/src/authorship.rs
Labels: A0-pleasereview, D2-node

#2035 Change epoch duration to 2 hours
  node/cli/src/command.rs
  node/res/stable.json
  node/res/staging.json
  node/service/src/chain_spec/gear.rs
  runtime/gear/src/constants.rs
  runtime/gear/src/lib.rs
Labels: A0-pleasereview, D2-node

#2036 Change epoch duration to 2 hours
  node/res/staging.json
  node/service/src/chain_spec/gear.rs
  runtime/gear/src/constants.rs
  runtime/gear/src/lib.rs
Labels: A0-pleasereview, D2-node

#2039 Fix `wasmtime-runtime` build on Windows
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview, E1-forcewindows

#2042 Adjust junit-common to the new quick-xml
  utils/junit-common/src/lib.rs
Labels: A0-pleasereview, C2-refactoring, D4-test
