Repository gear-tech/gear, pull requests merged in 2022-11, with the labels that each got.

#1740 gstd: Enable `debug` feature only for debug profile or propagate it from contract features
  gcore/src/lib.rs
  gcore/src/utils.rs
  gstd/src/common/handlers.rs
  gstd/src/lib.rs
  gstd/src/macros/bail.rs
  gstd/src/macros/debug.rs
  utils/wasm-builder/src/crate_info.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, D3-gstd

#1736 add syscalls table in gear-wasm-instruments
  Cargo.lock
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/syscalls.rs
  utils/wasm-instrument/Cargo.toml
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/syscalls.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview

#1738 Update README (add Protocol Buffer Compiler)
  node/README.md
Labels: A2-mergeoncegreen, A4-insubstantial

#1750 Rework block authorship
  Cargo.lock
  common/src/lib.rs
  node/authorship/Cargo.toml
  node/authorship/src/authorship.rs
  node/authorship/src/block_builder.rs
  node/authorship/src/lib.rs
  node/service/src/lib.rs
  pallets/gear/rpc/runtime-api/Cargo.toml
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/src/lib.rs
  runtime/common/src/apis.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  utils/test-runtime/Cargo.toml
  utils/test-runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#1759 Rework block authorship (resubmission)
  Cargo.lock
  common/src/lib.rs
  node/authorship/Cargo.toml
  node/authorship/src/authorship.rs
  node/authorship/src/block_builder.rs
  node/authorship/src/lib.rs
  node/res/staging.json
  node/service/src/lib.rs
  pallets/gear/rpc/runtime-api/Cargo.toml
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/src/lib.rs
  runtime/common/src/apis.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  utils/test-runtime/Cargo.toml
  utils/test-runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature

#1761 Change Gear Staging Testnet version from V3 to V4
  ansible/README.md
  node/res/staging.json
  node/service/src/chain_spec/gear.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#1783 Fix events handling
  gclient/src/api/listener/iterator.rs
  program/src/api/events.rs
  program/src/api/mod.rs
  utils/node-loader/Cargo.toml
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#1801 Fix tx-status waiting
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/batch_pool/api/mod.rs
  utils/node-loader/src/batch_pool/report.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#1787 Add features to fix tests in a dependency
  gclient/tests/upload.rs
  utils/test-runtime/Cargo.toml
  utils/test-runtime/src/lib.rs
Labels: A0-pleasereview, C0-bug, D4-test, Q1-easy

#1762 instructions benches
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/pallet_gear.rs
Labels: A0-pleasereview

#1693 Refactor `gear-core-processor` crate and cover by tests
  Cargo.lock
  core-processor/Cargo.toml
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/processor.rs
  core/src/program.rs
  gtest/src/manager.rs
  gtest/src/wasm_executor.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen, D1-core, D4-test

#1749 Fix `gr_unreserve_gas` and `gr_wake` benches
  pallets/gear/src/benchmarking/syscalls.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen, D2-node

#1824 Send messages from reservation
  Cargo.lock
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/node.rs
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-processor/src/common.rs
  core-processor/src/ext.rs
  core-processor/src/handler.rs
  core-processor/src/processor.rs
  core/src/costs.rs
  core/src/env.rs
  core/src/message/context.rs
  core/src/reservation.rs
  examples/binaries/send-from-reservation/Cargo.toml
  examples/binaries/send-from-reservation/build.rs
  examples/binaries/send-from-reservation/src/lib.rs
  gcore/src/msg.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  gtest/src/manager.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/tests.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/economic-checks/src/util.rs
  utils/regression-analysis/src/main.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A0-pleasereview, D1-core, D2-node, D3-gstd

#1834 Fix funds locking and charging artefacts for reservations
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen, D2-node, C0-bug

#1840 Rename `gear-node` base dir to `gear` instead of changing base path
  node/cli/src/command.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#1845 Don't overwrite the last error
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/funcs/mod.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D1-core, C0-bug

#1856 test(program): test program state with real types
  examples/binaries/meta/src/lib.rs
  program/tests/cmd/program.rs
Labels: A0-pleasereview

#1847 Optimise backend memory reads/writes
  Cargo.lock
  Cargo.toml
  core-backend/common/src/error_processor.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/Cargo.toml
  core-backend/wasmi/src/funcs/internal.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-backend/wasmi/src/memory.rs
  core-processor/src/executor.rs
  core/src/buffer.rs
  core/src/message/init.rs
  core/src/message/mod.rs
  examples/Cargo.lock
  examples/binaries/meta/src/lib.rs
  examples/wat-examples/large_scheduled.opt.wat
  examples/wat-examples/large_scheduled.wat
  gclient/tests/keyhasher.rs
  gcore/Cargo.toml
  gcore/src/error.rs
  gcore/src/exec.rs
  gcore/src/general.rs
  gcore/src/msg.rs
  gcore/src/prog.rs
  gsys/Cargo.toml
  gsys/src/lib.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  program/src/metadata/env.rs
  program/src/metadata/executor.rs
  program/src/metadata/funcs.rs
  program/tests/cmd/program.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  scripts/src/test.sh
  utils/wasm-instrument/src/syscalls.rs
Labels: A2-mergeoncegreen, D1-core, D3-gstd, C2-refactoring

#1874 Fix bootnode peer ids
  node/res/stable.json
Labels: A2-mergeoncegreen, D2-node

#1880 Increase loader ux
  Cargo.lock
  gclient/src/api/listener/iterator.rs
  gclient/src/api/listener/mod.rs
  gclient/src/api/storage/block.rs
  gclient/tests/keyhasher.rs
  gclient/tests/loop.rs
  gclient/tests/upload.rs
  utils/node-loader/Cargo.toml
  utils/node-loader/src/CHANGELOG.md
  utils/node-loader/src/args.rs
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/batch_pool/api/nonce.rs
  utils/node-loader/src/batch_pool/report.rs
  utils/node-loader/src/log.rs
  utils/node-loader/src/main.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#1882 Fix runtime weights ratio and weight cost
  pallets/payment/src/mock.rs
  runtime/common/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node

#1867 Improve `gcore` crate documentation
  Cargo.lock
  Makefile
  examples/ping/src/lib.rs
  gcore/Cargo.toml
  gcore/src/error.rs
  gcore/src/exec.rs
  gcore/src/general.rs
  gcore/src/lib.rs
  gcore/src/msg.rs
  gcore/src/prog.rs
  gcore/src/utils.rs
  gstd/src/msg/basic.rs
  scripts/gear.sh
  scripts/src/test.sh
Labels: A0-pleasereview

#1889 Add new CI runners
  .github/workflows/CI.yaml
Labels: D5-tooling

#1890 Don't break Cargo.lock on Windows
  .github/dependabot.yml
  .github/workflows/CI.yaml
  Cargo.lock
Labels: A0-pleasereview, D5-tooling, E1-forcewindows, E2-forcemacos

#1864 Use SignalDetails in SignalMessage
  .github/workflows/CI.yaml
  core/src/message/signal.rs
  scripts/src/init.sh
Labels: A0-pleasereview, D1-core, C0-bug

#1875 Fix kb benches
  pallets/gear/src/benchmarking/mod.rs
Labels: A0-pleasereview, D2-node, D5-tooling

#1907 fix for new rust clippy version
  node/authorship/src/authorship.rs
Labels: A0-pleasereview, P1-asap

#1861 Extend property tests of gas provider
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  common/src/gas_provider/property_tests/strategies.rs
Labels: A0-pleasereview, D1-core

#1908 Alert on tx wait finalized timeout
  utils/node-loader/src/batch_pool/api/mod.rs
  utils/node-loader/src/batch_pool/report.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#1899 Revert preparations
  node/cli/src/command.rs
  node/res/stable.json
  node/service/src/chain_spec/gear.rs
Labels: A2-mergeoncegreen
