Repository gear-tech/gear, pull requests merged in 2022-08, with the labels that each got.

#1265 Rename network to v2
  ansible/README.md
  node/res/staging.json
  node/src/chain_spec.rs
Labels: A0-pleasereview, D2-node

#1267 Change logic of determining the build profile
  utils/wasm-builder/build.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-builder/tests/smoke.rs
Labels: A2-mergeoncegreen, C0-bug, D5-tooling

#1246 Remove options from `GasTree` interface
  common/src/code_storage.rs
  common/src/gas_provider/error.rs
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/negative_imbalance.rs
  common/src/gas_provider/node.rs
  common/src/gas_provider/positive_imbalance.rs
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  common/src/gas_provider/property_tests/strategies.rs
  common/src/lazy_pages.rs
  pallets/gas/src/tests.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
  utils/economic-checks/src/util.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring

#1211 Add `core_processor::prepare` method
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/lib.rs
  core-processor/src/processor.rs
  gear-test/src/check.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gtest/src/manager.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A2-mergeoncegreen, D1-core, D2-node, C1-feature

#1274 Gas locking ability
  common/src/gas_provider/error.rs
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/node.rs
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature

#1289 CD: Insert node keys workflow
  .github/workflows/CD-insert-keys.yml
  ansible/insert-node-keys.yaml
  ansible/tasks/docker/docker-compose-insert-keys.yaml.j2
  ansible/tasks/docker/docker-insert-keys.yaml
Labels: A0-pleasereview, D5-tooling

#1291 Update weights
  examples/binaries/calc-hash/src/lib.rs
  gear-test/spec/test_async_multisig.yaml
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
Labels: A0-pleasereview, D2-node

#1292 Charge correctly in exit_code context
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs.rs
  core-processor/src/ext.rs
  core/src/env.rs
  pallets/gear/src/ext.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D1-core, D2-node

#1301 Run nightly cargo through rustup in WASM builder
  utils/wasm-builder/src/cargo_command.rs
Labels: A0-pleasereview, D5-tooling

#1275 remove pages compare after execution
  Cargo.lock
  common/src/lazy_pages.rs
  common/src/lib.rs
  core-processor/src/executor.rs
  core/src/memory.rs
  lazy-pages/Cargo.toml
  lazy-pages/src/deprecated.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/sys.rs
  lazy-pages/src/sys/unix.rs
  lazy-pages/src/sys/windows.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/tests.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/ext.rs
  pallets/gear/src/tests.rs
  runtime-interface/src/deprecated.rs
  runtime-interface/src/lib.rs
  runtime-interface/src/tests.rs
Labels: A0-pleasereview, B1-releasenotes

#1306 Rename auxiliary pallets directory
  Cargo.toml
  pallets/shift-session-manager/Cargo.toml
  pallets/shift-session-manager/README.md
  pallets/shift-session-manager/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C0-bug

#1307 add stack pages support for lazy pages in runtime
  common/src/lazy_pages.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/utils.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmi/src/env.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/ids.rs
  gear-test/src/check.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/sys.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/tests.rs
  runtime-interface/src/deprecated.rs
  runtime-interface/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#1313 Restore custom transaction fees
  Cargo.lock
  node/cli/Cargo.toml
  node/cli/src/benchmarking.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C0-bug

#1316 Prohibit calling extrinsics from Balances pallet in Vara PoA network
  node/cli/src/benchmarking.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node

#1329 Bump wasm-mutate version to 0.2.7
  Cargo.lock
  runtime/common/src/apis.rs
  utils/economic-checks/Cargo.toml
Labels: A0-pleasereview, dependencies

#1278 Scheduler safety charging
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#1288 Locking gas in waitlist
  Cargo.lock
  common/src/gas_provider/mod.rs
  examples/binaries/gas-burned/src/lib.rs
  examples/binaries/gasless-wasting/Cargo.toml
  examples/binaries/gasless-wasting/build.rs
  examples/binaries/gasless-wasting/src/lib.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  utils/economic-checks/src/util.rs
Labels: A0-pleasereview, D2-node, C0-bug, C1-feature

#1276 Make `HoldBound` errors reachable
  examples/binaries/gasless-wasting/build.rs
  examples/binaries/gasless-wasting/src/lib.rs
  examples/binaries/proxy-with-gas/build.rs
  examples/binaries/proxy-with-gas/src/lib.rs
  examples/binaries/proxy/build.rs
  examples/binaries/proxy/src/lib.rs
  examples/binaries/waiting-proxy/build.rs
  examples/binaries/waiting-proxy/src/lib.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring

#1334 fix bug gas charge for allocated pages
  core-processor/src/ext.rs
  core/src/env.rs
  examples/wat-examples/read_write_access.wat
  pallets/gear/src/ext.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#1343 Fix `check-spec` on CI
  .github/workflows/CI.yaml
Labels: A0-pleasereview, C0-bug, D5-tooling

#1346 Adjust pallet gear tests
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D2-node, A4-insubstantial

#1345 Fuzzer: adjust minimum balance to stay above existential deposit
  utils/economic-checks/src/util.rs
Labels: A0-pleasereview, D2-node, C0-bug

#1309 Check runtime WASM imports for being allowed
  .github/workflows/CI.yaml
  Cargo.lock
  utils/wasm-proc/Cargo.toml
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#1355 fix `gr_read` panic when arguments are incorrect
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, P1-asap

#1365 Fix test on CI
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, C0-bug, D4-test

#1367 Make formatters smarter
  core/src/ids.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D1-core, C2-refactoring

#1368 Implement airdrop in vara stage 1 for initial tokens deposit
  Cargo.lock
  node/service/Cargo.toml
  pallets/airdrop/Cargo.toml
  pallets/airdrop/README.md
  pallets/airdrop/src/benchmarking.rs
  pallets/airdrop/src/lib.rs
  pallets/airdrop/src/mock.rs
  pallets/airdrop/src/tests.rs
  pallets/airdrop/src/weights.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature

#1347 Exited program balance inheritance
  Cargo.lock
  common/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/processor.rs
  examples/binaries/exit-handle-sender/Cargo.toml
  examples/binaries/exit-handle-sender/build.rs
  examples/binaries/exit-handle-sender/src/lib.rs
  examples/binaries/init-fail-sender/Cargo.toml
  examples/binaries/init-fail-sender/build.rs
  examples/binaries/init-fail-sender/src/lib.rs
  gtest/src/manager.rs
  pallets/gear-program/src/tests.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  utils/economic-checks/src/targets.rs
Labels: A0-pleasereview, D2-node, C1-feature

#1370 Fix broken links
  README.md
  gear-test/README.md
  pallets/gear/src/tests.rs
Labels: A4-insubstantial

#1373 vara: Use vara runtime by default
  .github/workflows/CI.yaml
  examples/gui-test/src/lib.rs
  node/Cargo.toml
  node/cli/src/command.rs
  node/res/vara_staging.json
Labels: A0-pleasereview, D2-node

#1354 Test for weight on loop on client
  .github/workflows/CI.yaml
  Makefile
  examples/Cargo.lock
  examples/Cargo.toml
  examples/loop/Cargo.toml
  examples/loop/src/lib.rs
  scripts/gear.sh
  scripts/src/test.sh
  scripts/test-utils/infiniteLoop.js
  scripts/test-utils/package.json
  scripts/test-utils/processingMessageWithRuntimeUpgrade.js
  scripts/test-utils/util.js
Labels: A0-pleasereview, D2-node, D4-test

#1376 fix signal handler for `wasmer`
  .github/workflows/CI.yaml
  core-processor/src/executor.rs
  examples/wat-examples/wrong_load.wat
  lazy-pages/src/sys/unix.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  scripts/src/test.sh
  scripts/test-utils/processingMessageWithRuntimeUpgrade.js
Labels: A0-pleasereview, P1-asap

#1384 Skip `gr_read` on empty
  gcore/src/msg.rs
  gstd/src/msg/basic.rs
Labels: A0-pleasereview, D3-gstd, C2-refactoring

#1385 Bugfix: `gr_read`, `gr_size` economic and memory
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/funcs.rs
  core-backend/wasmi/src/runtime.rs
  core-errors/src/lib.rs
  core-processor/src/ext.rs
  core/src/env.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D1-core, C0-bug
