Repository gear-tech/gear, pull requests merged in 2022-02, with the labels that each got.

#621 bump spec version
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D2-node

#624 Update `node-fetch` to fix Dependabot alerts
  gear-test/src/js/package-lock.json
  rpc-tests/package-lock.json
  utils/wasm-proc/metadata-js/package-lock.json
Labels: A4-insubstantial

#627 Refactor gear core backend
  Cargo.lock
  core-backend/common/Cargo.toml
  core-backend/common/src/funcs.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/lib.rs
  core-backend/wasmtime/Cargo.toml
  core-backend/wasmtime/src/env.rs
  core-backend/wasmtime/src/memory.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/env.rs
  examples/incomplete_async_payloads/src/lib.rs
  gear-test/spec/test_incomplete_async_payloads.yaml
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gtest/src/manager.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  tests/common/src/lib.rs
Labels: A2-mergeoncegreen, D1-core

#634 Rollback state mechanism
  core-backend/common/src/funcs.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmtime/src/env.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/env.rs
  examples/Cargo.lock
  examples/Cargo.toml
  examples/state_rollback/Cargo.toml
  examples/state_rollback/src/lib.rs
  gcore/src/exec.rs
  gear-test/spec/test_mem.yaml
  gear-test/spec/test_state_rollback.yaml
  gstd/src/exec.rs
  runtime/src/lib.rs
  tests/common/src/lib.rs
Labels: A0-pleasereview, D1-core, D3-gstd, B1-releasenotes

#612 Calculate gas spent for init and reply messages too
  node/src/rpc.rs
  pallets/gear/Cargo.toml
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
  scripts/calc-gas-spent.sh
Labels: A0-pleasereview, D2-node, B1-releasenotes

#653 [skip ci] Fix error in documentation and command example
  ansible/README.md
  ansible/tasks/docker/docker-compose.yaml.j2
Labels: A0-pleasereview, D5-tooling, Q1-easy

#656 Bump spec version to apply new RPC calls
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#631 [skip ci] Fix link to chain spec in README
  node/README.md
Labels: A4-insubstantial

#651 Node runtime tests CLI
  .github/workflows/CI.yaml
  Cargo.lock
  Cargo.toml
  Makefile
  common/src/lib.rs
  examples/Cargo.lock
  examples/multiping/src/lib.rs
  examples/sync_duplicate/Cargo.toml
  examples/sync_duplicate/src/lib.rs
  gear-test/Cargo.toml
  gear-test/spec/test_async_init.yaml
  gear-test/spec/test_async_multisig.yaml
  gear-test/spec/test_async_sign.yaml
  gear-test/spec/test_capacitor.yaml
  gear-test/spec/test_i32.yaml
  gear-test/spec/test_mem.yaml
  gear-test/spec/test_multiping.yaml
  gear-test/spec/test_rwlock.yaml
  gear-test/spec/test_sync_dont_duplicate.yaml
  gear-test/spec/test_vec.yaml
  gear-test/spec/test_wait.yaml
  gear-test/src/address.rs
  gear-test/src/check.rs
  gear-test/src/proc.rs
  gear-test/src/sample.rs
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear/src/lib.rs
  runtime/src/lib.rs
  scripts/gear.sh
  scripts/src/test.sh
  utils/gear-runtime-test-cli/Cargo.toml
  utils/gear-runtime-test-cli/src/command.rs
  utils/gear-runtime-test-cli/src/lib.rs
  utils/gear-runtime-test-cli/src/util.rs
  utils/gear-test-cli/Cargo.toml
Labels: A0-pleasereview, D2-node, D4-test

#662 Fix master to try to revive testnet
  common/src/value_tree.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D1-core

#664 CD self-hosted
  .github/workflows/CD.yml
Labels: A0-pleasereview

#667 Update staging.json
  node/res/staging.json
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, Q1-easy

#671 CD self-hosted
  .github/workflows/CD.yml
Labels: A0-pleasereview

#633 Handle messages to limbo prog
  Cargo.lock
  common/src/lib.rs
  common/src/native.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/handler.rs
  core-processor/src/id.rs
  core-processor/src/lib.rs
  core-processor/src/processor.rs
  core/Cargo.toml
  core/src/message.rs
  core/src/program.rs
  gear-test/spec/test_failed_program_msg_handling.yaml
  gear-test/spec/test_gui.yaml
  gear-test/src/check.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gear-test/src/sample.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/benchmarking.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  pallets/usage/src/lib.rs
  pallets/usage/src/tests.rs
  tests/common/src/lib.rs
  tests/node/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
  utils/gear-runtime-test-cli/src/util.rs
  utils/gear-test-cli/src/manager.rs
Labels: A2-mergeoncegreen, D1-core, D2-node

#676 Remove `runtests` command and `rpc-tests`
  .github/workflows/CI.yaml
  Cargo.lock
  Cargo.toml
  Makefile
  gear-test/spec_no_runtime/test_block_info.yaml
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  rpc-tests/.eslintrc.js
  rpc-tests/README.md
  rpc-tests/package-lock.json
  rpc-tests/package.json
  rpc-tests/src/index.ts
  rpc-tests/src/interfaces.ts
  rpc-tests/src/ws-test.ts
  rpc-tests/tsconfig.json
  scripts/gear.sh
  scripts/src/init.sh
  scripts/src/test.sh
  utils/gear-test-cli/Cargo.toml
  utils/gear-test-cli/src/command.rs
  utils/gear-test-cli/src/lib.rs
  utils/gear-test-cli/src/manager.rs
Labels: A2-mergeoncegreen, D2-node

#677 Fix action name
  .github/workflows/Runtime-upgrade-reset.yaml
Labels: A0-pleasereview

#659 Normalize missing entry case
  Cargo.lock
  core-backend/common/src/lib.rs
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/env.rs
  core-backend/wasmtime/src/env.rs
  examples/block-info/src/lib.rs
  examples/bot/src/lib.rs
  examples/collector/src/lib.rs
  examples/decoder/src/lib.rs
  examples/exit-code/src/lib.rs
  examples/fib/src/lib.rs
  examples/guestbook/src/lib.rs
  examples/mem/src/lib.rs
  examples/minimal/src/lib.rs
  examples/multiping/src/lib.rs
  examples/panicker/src/lib.rs
  examples/ping/src/lib.rs
  examples/program-id/src/lib.rs
  examples/state_rollback/src/lib.rs
  examples/sync_duplicate/src/lib.rs
  examples/vec/src/lib.rs
  examples/wait/src/lib.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D1-core, B1-releasenotes, Wiki update

#681 Fix clippy master
  .github/workflows/CI.yaml
  pallets/usage/src/lib.rs
Labels: A4-insubstantial

#679 Add `gear-wasm-builder` crate
  Cargo.lock
  Cargo.toml
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/README.md
  utils/wasm-builder/src/builder_error.rs
  utils/wasm-builder/src/cargo_command.rs
  utils/wasm-builder/src/crate_info.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-builder/test-program/Cargo.lock
  utils/wasm-builder/test-program/Cargo.toml
  utils/wasm-builder/test-program/build.rs
  utils/wasm-builder/test-program/src/lib.rs
  utils/wasm-builder/tests/smoke.rs
Labels: A0-pleasereview, B1-releasenotes, D5-tooling, Wiki update

#683 Store code permanently
  common/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
Labels: A2-mergeoncegreen, D2-node

#684 Save message context over wake logic
  Makefile
  common/src/lib.rs
  common/src/native.rs
  core-backend/common/src/lib.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/message.rs
  examples/incomplete_async_payloads/src/lib.rs
  gear-test/spec/test_incomplete_async_payloads.yaml
  gear-test/src/proc.rs
  gtest/src/manager.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/lib.rs
  pallets/usage/src/tests.rs
  runtime/src/lib.rs
  scripts/check-spec.sh
  tests/common/src/lib.rs
Labels: A0-pleasereview, D1-core

#687 gear-wasm-builder: Always build WASM in release mode
  Cargo.lock
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/README.md
  utils/wasm-builder/src/cargo_command.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-builder/test-program/Cargo.lock
  utils/wasm-builder/test-program/src/lib.rs
Labels: A2-mergeoncegreen, D5-tooling

#688 New `gear-wasm-builder` integration
  Cargo.lock
  core-backend/common/Cargo.toml
  core-backend/sandbox/Cargo.toml
  core-processor/Cargo.toml
  core-processor/src/executor.rs
  core-processor/src/lazy_pages.rs
  gtest/Cargo.toml
  gtest/src/program.rs
  pallets/gear/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  scripts/check-spec.sh
  tests/btree/Cargo.toml
  tests/btree/build.rs
  tests/btree/src/lib.rs
  tests/distributor/Cargo.toml
  tests/distributor/build.rs
  tests/distributor/src/lib.rs
  tests/exit-handle/Cargo.toml
  tests/exit-handle/build.rs
  tests/exit-handle/src/lib.rs
  tests/exit-init/Cargo.toml
  tests/exit-init/build.rs
  tests/exit-init/src/lib.rs
  tests/init-wait/Cargo.toml
  tests/init-wait/build.rs
  tests/init-wait/src/lib.rs
  tests/messages/Cargo.toml
  tests/messages/build.rs
  tests/messages/src/lib.rs
  tests/node/Cargo.toml
  tests/node/build.rs
  tests/node/src/lib.rs
  tests/wait_wake/Cargo.toml
  tests/wait_wake/build.rs
  tests/wait_wake/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-builder/test-program/Cargo.lock
  utils/wasm-builder/test-program/Cargo.toml
  utils/wasm-builder/test-program/build.rs
  utils/wasm-builder/test-program/src/lib.rs
Labels: A0-pleasereview, D1-core, D3-gstd, C1-feature

#690 Align gas_limit in a message with the value locked in gas handler
  pallets/gear/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#685 Add no-value nodes to gas tree
  common/src/lib.rs
  examples/async-init/src/lib.rs
  examples/futures-unordered/src/lib.rs
  examples/incomplete_async_payloads/src/lib.rs
  examples/sync_duplicate/src/lib.rs
  gstd/codegen/src/lib.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/tests.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/usage/src/lib.rs
  pallets/usage/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#694 Add docs to `gstd` utility functions
  examples/meta/src/lib.rs
  gstd/src/lib.rs
  gstd/src/macros/mod.rs
Labels: D3-gstd, A4-insubstantial

#696 Value management in programs
  core-backend/common/src/funcs.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmtime/src/env.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/env.rs
  core/src/gas.rs
  core/src/message.rs
  examples/async-init/src/lib.rs
  gcore/src/exec.rs
  gear-test/src/check.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gstd/src/exec.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
  tests/common/src/lib.rs
Labels: A2-mergeoncegreen, D1-core, D2-node, D3-gstd, B1-releasenotes, Wiki update

#697 Update substrate
  Cargo.lock
  common/Cargo.toml
  examples/Cargo.lock
  examples/async-multisig/Cargo.toml
  examples/async-sign/Cargo.toml
  gear-test/Cargo.toml
  lazy-pages/Cargo.toml
  node/Cargo.toml
  pallets/gas/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/gear/rpc/Cargo.toml
  pallets/gear/rpc/runtime-api/Cargo.toml
  pallets/usage/Cargo.toml
  runtime-interface/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  utils/gear-runtime-test-cli/Cargo.toml
Labels: A2-mergeoncegreen, D2-node

#689 `gstd`: Don't panic if signal not found
  gstd/src/async_runtime/signals.rs
  gstd/src/common/handlers.rs
  gstd/src/macros/debug.rs
Labels: A0-pleasereview, D3-gstd

#706 remove substrate part from core processor
  Cargo.lock
  common/src/lazy_pages.rs
  common/src/lib.rs
  core-processor/Cargo.toml
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/lazy_pages.rs
  core-processor/src/lib.rs
  core-processor/src/processor.rs
  gear-test/src/proc.rs
  gtest/src/manager.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/usage/Cargo.toml
  runtime/src/lib.rs
  tests/common/src/lib.rs
Labels: A2-mergeoncegreen, D1-core

#709 CI: rm types and store cache only on push
  .github/workflows/CI.yaml
Labels: A2-mergeoncegreen, D5-tooling

#711 switch to new allocator: allocator with static pages space using
  Cargo.lock
  examples/Cargo.lock
  examples/vec/src/lib.rs
  galloc/Cargo.toml
  gear-test/spec/test_vec.yaml
  utils/wasm-builder/test-program/Cargo.lock
Labels: D3-gstd

#708 Waitlist messages handling
  common/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/handler.rs
  core-processor/src/id.rs
  core-processor/src/lib.rs
  core-processor/src/processor.rs
  gear-test/src/manager.rs
  gtest/src/manager.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/usage/Cargo.toml
  pallets/usage/src/lib.rs
  pallets/usage/src/mock.rs
  runtime/src/lib.rs
  tests/common/src/lib.rs
Labels: A2-mergeoncegreen, D2-node

#717 use gear_common::set_program to store empty program
  utils/gear-runtime-test-cli/src/command.rs
Labels: A0-pleasereview, D2-node, D5-tooling

#722 Patch 2 for program from program creation
  Cargo.lock
  common/src/lib.rs
  common/src/native.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/handler.rs
  core-processor/src/lib.rs
  core-processor/src/processor.rs
  core/src/message.rs
  core/src/program.rs
  gear-test/src/manager.rs
  gtest/src/manager.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  runtime/src/lib.rs
  tests/common/src/lib.rs
  tests/program-factory/Cargo.toml
  tests/program-factory/build.rs
  tests/program-factory/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A0-pleasereview, D1-core, D2-node

#720 Getter for initial user of messaging
  core-backend/common/src/funcs.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmtime/src/env.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/env.rs
  gcore/src/exec.rs
  gear-test/src/proc.rs
  gstd/src/exec.rs
  gtest/src/manager.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  runtime/src/lib.rs
  tests/common/src/lib.rs
  utils/wasm-builder/test-program/Cargo.lock
Labels: A0-pleasereview, D1-core, D3-gstd, C1-feature

#723 Add error log for code submit
  pallets/gear/src/lib.rs
Labels: D2-node, A4-insubstantial

#726 Replace log::error! and warn! with debug! to a specific target
  core/src/gas.rs
  lazy-pages/src/unix.rs
  pallets/gear/src/manager.rs
  pallets/usage/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature, Q1-easy

#729 Use cargo nextest utility
  scripts/gear.sh
  scripts/src/init.sh
  scripts/src/test.sh
Labels: A0-pleasereview, D5-tooling
