Repository gear-tech/gear, pull requests merged in 2022-10, with the labels that each got.

#1598 Update metadata after introducing `LimitedVec`
  core/src/message/mod.rs
  gclient/src/api/listener/mod.rs
  program/scripts/generate-api.sh
  program/src/api/generated/metadata.rs
  program/src/api/generated/mod.rs
  program/src/cmd/info.rs
  program/tests/cmd/reply.rs
  program/tests/cmd/send.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#1593 Use reexported `scale_info` and `parity-scale-codec` from `gstd`
  examples/Cargo.lock
  examples/async-init/Cargo.toml
  examples/async-init/src/lib.rs
  examples/async-multisig/Cargo.toml
  examples/async/Cargo.toml
  gstd/src/prelude.rs
Labels: A0-pleasereview, D3-gstd

#1599 Introduce more calls to `gear-node-loader` (loader MVP-version)
  Cargo.lock
  core/src/message/mod.rs
  gclient/src/api/calls.rs
  gclient/src/api/listener/mod.rs
  program/scripts/generate-api.sh
  program/src/api/generated/metadata.rs
  program/src/api/generated/mod.rs
  program/src/cmd/info.rs
  program/tests/cmd/reply.rs
  program/tests/cmd/send.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/batch_pool/batch.rs
  utils/node-loader/src/batch_pool/batch/create_program.rs
  utils/node-loader/src/batch_pool/batch/send_message.rs
  utils/node-loader/src/batch_pool/batch/upload_code.rs
  utils/node-loader/src/batch_pool/batch/upload_program.rs
  utils/node-loader/src/batch_pool/context.rs
  utils/node-loader/src/batch_pool/generators.rs
  utils/node-loader/src/batch_pool/report.rs
  utils/node-loader/src/utils.rs
  utils/regression-analysis/Cargo.toml
  utils/regression-analysis/src/main.rs
  utils/regression-analysis/src/output.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#1591 Add login ability into `gclient`
  gclient/src/api/mod.rs
  gclient/tests/loop.rs
  gclient/tests/upload.rs
  program/src/api/signer/mod.rs
Labels: A2-mergeoncegreen, D3-gstd, C1-feature

#1592 Add batch variants for all gear extrinsics in `gclient`
  gclient/src/api/calls.rs
  gclient/src/api/storage/mod.rs
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/batch_pool/batch.rs
  utils/node-loader/src/batch_pool/batch/create_program.rs
  utils/node-loader/src/batch_pool/batch/send_message.rs
  utils/node-loader/src/batch_pool/batch/upload_code.rs
  utils/node-loader/src/batch_pool/batch/upload_program.rs
  utils/node-loader/src/batch_pool/context.rs
  utils/node-loader/src/batch_pool/generators.rs
  utils/node-loader/src/batch_pool/report.rs
  utils/node-loader/src/utils.rs
Labels: A2-mergeoncegreen, D3-gstd, C1-feature

#1581 Windows fixes
  .github/workflows/CI.yaml
  lazy-pages/src/sys/windows.rs
Labels: A0-pleasereview

#1608 make macros to print sys-calls
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/funcs.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#1590 add syscalls in wasm gen
  Cargo.lock
  core-backend/common/Cargo.toml
  core-backend/common/src/lib.rs
  core-backend/common/src/mock.rs
  core/src/env.rs
  gcore/src/general.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/syscalls.rs
  utils/wasm-gen/src/test.rs
Labels: A0-pleasereview

#1619 Update node, substrate
  Cargo.lock
  examples/binaries/calc-hash/over-blocks/src/lib.rs
  examples/binaries/init-wait/src/lib.rs
  examples/bot/src/lib.rs
  examples/collector/src/lib.rs
  examples/fungible-token/src/lib.rs
  examples/token-vendor/src/lib.rs
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/rpc.rs
  pallets/gas/src/mock.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear-messenger/src/mock.rs
  pallets/gear-program/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  runtime/common/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  utils/economic-checks/src/targets.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A0-pleasereview, D2-node

#1603 make possible to use lldb on macos darvin when lazy pages are enabled
  Cargo.lock
  lazy-pages/Cargo.toml
  lazy-pages/src/lib.rs
Labels: A0-pleasereview

#1630 lazy pages runtime refactoring
  common/lazy-pages/src/lib.rs
  core-backend/sandbox/src/memory.rs
  core-backend/wasmi/src/memory.rs
  core-errors/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/memory.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/tests.rs
  program/src/api/generated/metadata.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D1-core

#1620 Run coverage by condition
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#1532 Process queue as unsigned extrinsic at the end of a block
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  node/authorship/Cargo.toml
  node/authorship/src/authorship.rs
  node/authorship/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/benchmarking.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/gear.rs
  node/service/src/chain_spec/vara.rs
  node/service/src/lib.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/payment/src/lib.rs
  pallets/payment/src/mock.rs
  program/src/api/generated/metadata.rs
  runtime-interface/src/lib.rs
  runtime/common/src/lib.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  utils/economic-checks/src/util.rs
  utils/gear-runtime-test-cli/src/util.rs
  utils/test-runtime/Cargo.toml
  utils/test-runtime/README.md
  utils/test-runtime/build.rs
  utils/test-runtime/client/Cargo.toml
  utils/test-runtime/client/src/block_builder_ext.rs
  utils/test-runtime/client/src/lib.rs
  utils/test-runtime/client/src/trait_tests.rs
  utils/test-runtime/src/genesismap.rs
  utils/test-runtime/src/inner.rs
  utils/test-runtime/src/lib.rs
Labels: A0-pleasereview, D1-core, D2-node, C1-feature

#1636 Add pallets to docs and fix links
  .github/workflows/docs.yml
  Makefile
  README.md
  core/src/message/common.rs
  gstd/src/msg/encoded.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/manager/mod.rs
Labels: A4-insubstantial

#1645 [skip ci] update vara spec
  node/res/vara.json
Labels: A0-pleasereview

#1635 Fix feature-dependent node build
  .github/workflows/CI.yaml
  .github/workflows/test-measurements.yaml
  Cargo.lock
  Makefile
  node/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/cli/src/lib.rs
  node/service/Cargo.toml
  pallets/gear-debug/src/tests.rs
  program/build.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  scripts/src/test.sh
  utils/gear-runtime-test-cli/Cargo.toml
  utils/gear-runtime-test-cli/src/command.rs
  utils/gear-runtime-test-cli/src/lib.rs
  utils/gear-runtime-test-cli/src/util.rs
Labels: A0-pleasereview, D2-node, C0-bug, C2-refactoring

#1638 Rename `gear-node` binary to `gear`
  .github/workflows/CI.yaml
  .github/workflows/test-measurements.yaml
  .github/workflows/win.yml
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  ansible/README.md
  ansible/tasks/docker/docker-compose-insert-keys.yaml.j2
  ansible/tasks/docker/docker-compose-purge.yaml.j2
  ansible/tasks/docker/docker-compose-vara.yaml.j2
  ansible/tasks/docker/docker-compose.yaml.j2
  ansible/tasks/docker/docker-vara.yaml
  ansible/tasks/docker/docker.yaml
  docker/Dockerfile
  docker/Vara-Dockerfile
  docker/docker-compose-cd.yaml
  docker/docker-compose-dev.yml
  docker/docker-compose-local.yml
  node/Cargo.toml
  node/README.md
  node/cli/Cargo.toml
  node/cli/build.rs
  node/cli/src/command.rs
  node/cli/src/main.rs
  pallets/gear-debug/src/weights.rs
  pallets/gear-program/src/weights.rs
  pallets/gear/src/weights.rs
  program/build.rs
  program/src/api/generated/metadata.rs
  program/tests/common/node.rs
  program/tests/gear.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/frame_system.rs
  runtime/gear/src/weights/pallet_balances.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/gear/src/weights/pallet_gear_program.rs
  runtime/gear/src/weights/pallet_timestamp.rs
  runtime/gear/src/weights/pallet_utility.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear_program.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
  scripts/benchmarking/run_all_benchmarks.sh
  scripts/calc-gas-spent.sh
  scripts/gear.sh
  scripts/src/build.sh
  scripts/src/run.sh
  scripts/src/test.sh
  scripts/test-utils/package.json
  scripts/test-utils/processingMessageWithRuntimeUpgrade.js
Labels: A2-mergeoncegreen, D1-core

#1654 Fix docs CI
  .github/workflows/docs.yml
Labels: A0-pleasereview, D5-tooling, A4-insubstantial

#1474 Add precharging gas for Program struct & Code
  common/src/benchmarking.rs
  common/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/lib.rs
  core-processor/src/processor.rs
  core/src/code.rs
  core/src/gas.rs
  examples/binaries/gasless-wasting/src/lib.rs
  examples/binaries/init-with-value/src/lib.rs
  examples/binaries/program-factory/src/lib.rs
  gear-test/src/check.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-program/src/tests.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  utils/gear-runtime-test-cli/src/command.rs
Labels: A2-mergeoncegreen, D1-core, C1-feature

#1664 vara-stage-2: Update substrate
  .github/workflows/CI.yaml
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  examples/Cargo.lock
  examples/fungible-token/Cargo.toml
  examples/token-vendor/Cargo.toml
  gclient/Cargo.toml
  gear-test/Cargo.toml
  gstd/Cargo.toml
  node/cli/Cargo.toml
  pallets/gas/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-messenger/Cargo.toml
  pallets/gear-program/Cargo.toml
  pallets/gear-scheduler/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/payment/Cargo.toml
  pallets/payment/src/lib.rs
  program/Cargo.toml
  scripts/test-utils/package-lock.json
  utils/economic-checks/Cargo.toml
  utils/test-runtime/Cargo.toml
  utils/test-runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#1665 Remove redundant feature
  .github/workflows/CI.yaml
  Makefile
  examples/gui-test/src/lib.rs
  gear-test/spec/test_gui.yaml
  node/cli/Cargo.toml
  program/src/api/generated/metadata.rs
  scripts/test-utils/package-lock.json
Labels: A0-pleasereview, D2-node, C2-refactoring, D4-test, Q1-easy

#1668 vara-stage-2: Merge master
  .github/workflows/CI.yaml
  Cargo.lock
  Makefile
  common/src/benchmarking.rs
  common/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/lib.rs
  core-processor/src/processor.rs
  core/src/code.rs
  core/src/gas.rs
  core/src/program.rs
  examples/binaries/gasless-wasting/src/lib.rs
  examples/binaries/init-with-value/src/lib.rs
  examples/binaries/program-factory/src/lib.rs
  examples/gui-test/src/lib.rs
  gear-test/spec/test_gui.yaml
  gear-test/src/check.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  node/cli/Cargo.toml
  pallets/airdrop/src/mock.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-program/src/tests.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  program/Cargo.toml
  program/src/api/generated/metadata.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  scripts/test-utils/package-lock.json
  utils/gear-runtime-test-cli/src/command.rs
Labels: A0-pleasereview

#1663 [skip ci] Improve runtime upgrade workflows
  .github/workflows/Runtime-upgrade-reset.yaml
  .github/workflows/Runtime-upgrade.yaml
Labels: A0-pleasereview

#1671 Add `create_program` async version
  gstd/codegen/src/lib.rs
  gstd/src/msg/async.rs
  gstd/src/msg/basic.rs
  gstd/src/prog/generator.rs
  gstd/src/prog/mod.rs
Labels: A0-pleasereview, D3-gstd

#1674 Wait till test end once part failed
  Makefile
  scripts/src/test.sh
Labels: A0-pleasereview, D4-test, A4-insubstantial

#1672 Sending message fee
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/message/context.rs
  gear-test/src/proc.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/wasm_executor.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D1-core

#1675 wasm gen new features
  Cargo.lock
  utils/node-loader/src/batch_pool/generators.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/syscalls.rs
  utils/wasm-gen/src/test.rs
Labels: A0-pleasereview, D4-test

#1631 Charge for WASM instantiation
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/state.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/processor.rs
  core/src/memory.rs
  gear-test/src/main.rs
  gear-test/src/proc.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  program/src/api/generated/metadata.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/wasm-gen/src/syscalls.rs
Labels: A2-mergeoncegreen, D1-core

#1497 feat(gear): add schedule `WakeMessage` for messages waited with `wait_for`
  common/src/event.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/handler.rs
  core-processor/src/processor.rs
  core/src/env.rs
  core/src/message/mod.rs
  examples/binaries/waiter/src/code.rs
  examples/binaries/waiter/src/lib.rs
  gear-test/src/manager.rs
  gtest/src/manager.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/tests.rs
  program/src/api/generated/metadata.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen, D1-core, D2-node, C2-refactoring

#1677 Vara stage-2 (with governance, token economics, stakers rewards etc.)
  Cargo.lock
  Cargo.toml
  Makefile
  node/service/Cargo.toml
  node/service/src/chain_spec/vara.rs
  runtime/gear/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/bag_thresholds.rs
  runtime/vara/src/constants.rs
  runtime/vara/src/lib.rs
  utils/bags-thresholds/Cargo.toml
  utils/bags-thresholds/src/main.rs
  utils/economic-checks/Cargo.toml
  utils/economic-checks/src/util.rs
  utils/gear-runtime-test-cli/Cargo.toml
  utils/gear-runtime-test-cli/src/util.rs
Labels: A0-pleasereview, D2-node

#1690 `node/cli`: default `lazy-pages` feature
  node/cli/Cargo.toml
Labels: A0-pleasereview, D2-node

#1692 Reorganise task pool for scheduled messages
  common/src/scheduler/task.rs
  common/src/storage/complex/messenger.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/message/context.rs
  gclient/tests/keyhasher.rs
  gclient/tests/large_scheduled.opt.wasm
  gtest/src/wasm_executor.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/task.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C0-bug

#1673 Custom block number for queue processing
  pallets/gear-debug/src/mock.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-messenger/src/mock.rs
  pallets/gear-program/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, B1-releasenotes

#1689 Introduce gear-wasm-instrument
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/src/benchmarking.rs
  core/Cargo.toml
  core/src/code.rs
  core/src/program.rs
  gear-test/Cargo.toml
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gtest/Cargo.toml
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/tests.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/schedule.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/syscalls.rs
  utils/wasm-instrument/Cargo.toml
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, C1-feature

#1707 Update substrate and dependencies
  Cargo.lock
  common/Cargo.toml
  examples/Cargo.lock
  examples/fungible-token/Cargo.toml
  examples/token-vendor/Cargo.toml
  gear-test/Cargo.toml
  gstd/Cargo.toml
  pallets/gas/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-messenger/Cargo.toml
  pallets/gear-program/Cargo.toml
  pallets/gear-scheduler/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/payment/Cargo.toml
  pallets/payment/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  utils/economic-checks/Cargo.toml
  utils/test-runtime/Cargo.toml
  utils/test-runtime/src/lib.rs
Labels: A0-pleasereview, D2-node

#1704 Fix rust-covfix
  .github/workflows/CI.yaml
Labels: A0-pleasereview, D5-tooling, E0-forcecoverage

#1709 fix alloc overflow when 0 pages allocated
  Cargo.lock
  core-processor/src/ext.rs
  gclient/Cargo.toml
  gclient/tests/upload.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, P1-asap

#1711 Test `core-backend/common` crate
  Cargo.lock
  core-backend/common/Cargo.toml
  core-backend/common/src/utils.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D1-core, D4-test

#1714 Adjust to clippy 1.66
  common/src/lib.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-errors/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/ext.rs
  examples/async-recursion/src/lib.rs
  examples/binaries/gas-burned/src/lib.rs
  examples/block-info/src/lib.rs
  examples/capacitor/src/lib.rs
  examples/collector/src/lib.rs
  examples/fib/src/lib.rs
  examples/sum/src/lib.rs
  examples/vec/src/lib.rs
  gear-test/src/check.rs
  gear-test/src/js/mod.rs
  gear-test/src/proc.rs
  gstd/codegen/src/lib.rs
  gstd/src/common/errors.rs
  gtest/src/error.rs
  gtest/src/program.rs
  gtest/src/wasm_executor.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/sys/unix.rs
  node/cli/src/benchmarking.rs
  node/cli/src/command.rs
  node/service/src/chain_spec/mod.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  program/build.rs
  program/src/cmd/key.rs
  program/src/cmd/meta.rs
  program/src/cmd/new.rs
  program/src/metadata/registry/local_type.rs
  program/src/metadata/tests.rs
  program/src/template.rs
  program/tests/common/port.rs
  runtime-interface/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  utils/economic-checks/src/targets.rs
  utils/economic-checks/src/util.rs
  utils/regression-analysis/src/main.rs
  utils/test-runtime/src/lib.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-gen/src/test.rs
Labels: A2-mergeoncegreen, C2-refactoring, A4-insubstantial

#1701 Implement gas counting without system call
  Cargo.lock
  core-backend/common/src/mock.rs
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/Cargo.toml
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs/internal.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-processor/src/ext.rs
  core/src/code.rs
  core/src/env.rs
  core/src/gas.rs
  gtest/src/error.rs
  gtest/src/manager.rs
  gtest/src/wasm_executor.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  utils/wasm-gen/src/syscalls.rs
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen, D1-core, B1-releasenotes, C1-feature

#1705 Set proper gas to value conversion
  common/src/lib.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  program/tests/cmd/claim.rs
  runtime/common/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
  utils/gear-runtime-test-cli/src/util.rs
Labels: A0-pleasereview, D2-node

#1717 `vara-stage-2` SessionKeys migration
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview, D2-node

#1732 Fix wrong Cargo.lock on Windows
  Cargo.lock
Labels: A0-pleasereview, D5-tooling, E1-forcewindows

#1725 Sycalls benchmarks refactoring and problems resolving
  Cargo.lock
  core-backend/sandbox/src/funcs.rs
  core-processor/src/common.rs
  core-processor/src/ext.rs
  core/src/costs.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
Labels: A0-pleasereview

#1691 Implement `gr_random` syscall
  Cargo.lock
  core-backend/common/src/mock.rs
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/Cargo.toml
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-processor/Cargo.toml
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/costs.rs
  core/src/env.rs
  gcore/src/exec.rs
  gear-test/Cargo.toml
  gear-test/src/proc.rs
  gstd/src/exec.rs
  gtest/Cargo.toml
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/system.rs
  gtest/src/wasm_executor.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/Cargo.toml
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  pallets/payment/Cargo.toml
  pallets/payment/src/mock.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
Labels: A0-pleasereview, D1-core, D2-node, D3-gstd, B1-releasenotes, C1-feature

#1600 `gear-node-loader` clean-up
  Cargo.lock
  gclient/src/api/listener/mod.rs
  gclient/src/api/storage/block.rs
  gclient/tests/keyhasher.rs
  gclient/tests/loop.rs
  gclient/tests/upload.rs
  program/src/api/constants.rs
  program/src/api/utils.rs
  program/src/cmd/create.rs
  program/src/cmd/upload_program.rs
  utils/node-loader/Cargo.toml
  utils/node-loader/src/args.rs
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/batch_pool/api/mod.rs
  utils/node-loader/src/batch_pool/api/nonce.rs
  utils/node-loader/src/batch_pool/batch.rs
  utils/node-loader/src/batch_pool/batch/create_program.rs
  utils/node-loader/src/batch_pool/batch/mod.rs
  utils/node-loader/src/batch_pool/batch/send_message.rs
  utils/node-loader/src/batch_pool/batch/upload_code.rs
  utils/node-loader/src/batch_pool/batch/upload_program.rs
  utils/node-loader/src/batch_pool/context.rs
  utils/node-loader/src/batch_pool/generators.rs
  utils/node-loader/src/batch_pool/generators/batch.rs
  utils/node-loader/src/batch_pool/generators/mod.rs
  utils/node-loader/src/batch_pool/generators/program.rs
  utils/node-loader/src/batch_pool/generators/seed.rs
  utils/node-loader/src/batch_pool/report.rs
  utils/node-loader/src/log.rs
  utils/node-loader/src/main.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview, C2-refactoring, D4-test, D5-tooling
