Repository gear-tech/gear, pull requests merged in 2023-10, with the labels that each got.

#3383 refactor(wasm-gen, runtime-fuzzer): Increase successful messages execution rate in `runtime-fuzzer`.
  scripts/src/test.sh
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/README.md
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/wasm-gen/src/config/module.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3385 feat(wasm-instrument): Provide more info about syscall signatures
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-instrument/src/syscalls.rs
  utils/wasm-instrument/src/tests.rs
Labels: A2-mergeoncegreen

#3160 feat(runtime): Introduce `PerformanceMultiplier` as `Config` constant
  Cargo.lock
  Cargo.toml
  core-backend/src/mock.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processing.rs
  core/Cargo.toml
  core/src/env.rs
  core/src/lib.rs
  core/src/percent.rs
  gsdk/src/metadata/generated.rs
  gtest/src/manager.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/payment/src/mock.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3378 feat(wasm-gen): distinguish between importing and inserting functions
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/amount.rs
  utils/wasm-gen/src/config/syscalls/injection.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview, D5-tooling

#3388 feat(vara): Add nomination_pools and staking runtime-api
  Cargo.lock
  Cargo.toml
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node

#3389 feat(vara): Maintain total supply consistency in offchain election provider
  Cargo.lock
  pallets/staking-rewards/Cargo.toml
  pallets/staking-rewards/src/lib.rs
  pallets/staking-rewards/src/mock.rs
  pallets/staking-rewards/src/tests.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature

#3393 feat(vara): add TransactionPaymentCallApi
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3386 refactor(runtime-fuzzer): Change required size for gear calls data
  docker/runtime-fuzzer/scripts/fuzzer.sh
  scripts/check-fuzzer.sh
  scripts/fuzzer_consts.sh
  scripts/src/test.sh
  utils/runtime-fuzzer/README.md
  utils/runtime-fuzzer/src/gear_calls.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3384 refactor(wasm-gen): Clean-up wasm-gen
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/generator.rs
  utils/wasm-gen/src/config/module.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/injection.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/config/syscalls/precise.rs
  utils/wasm-gen/src/generator.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3392 feat(gsdk): upgrade subxt to v0.32.0
  Cargo.lock
  Cargo.toml
  gclient/src/api/mod.rs
  gclient/src/api/rpc.rs
  gclient/src/api/storage/block.rs
  gsdk/api-gen/src/main.rs
  gsdk/src/api.rs
  gsdk/src/backtrace.rs
  gsdk/src/client.rs
  gsdk/src/config.rs
  gsdk/src/metadata/errors.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/result.rs
  gsdk/src/rpc.rs
  gsdk/src/signer/mod.rs
  gsdk/src/signer/pair_signer.rs
  gsdk/src/signer/utils.rs
  gsdk/src/storage.rs
  gsdk/src/subscription.rs
  gsdk/src/utils.rs
  gsdk/tests/backtrace.rs
  gsdk/tests/rpc.rs
  utils/node-loader/src/batch_pool/api/mod.rs
  utils/node-loader/src/batch_pool/api/nonce.rs
Labels: A0-pleasereview

#3405 feat(runtime): Adding dust and slash handlers
  gsdk/src/metadata/generated.rs
  pallets/staking-rewards/src/lib.rs
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature

#3409 Update rust version (considering PR)
  Cargo.lock
  Cargo.toml
  core/src/memory.rs
  core/src/str.rs
  examples/signal-entry/src/wasm.rs
  gcli/tests/common/args.rs
  gcore/src/errors.rs
  gcore/src/lib.rs
  gcore/src/msg.rs
  gcore/src/utils.rs
  gstd/src/async_runtime/locks.rs
  gstd/src/common/handlers.rs
  gstd/src/lib.rs
  gstd/src/prelude.rs
  gstd/src/sync/mod.rs
  gtest/src/system.rs
  node/testing/src/client.rs
  pallets/gear-bank/src/tests.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
  rust-toolchain.toml
  sandbox/host/src/sandbox/wasmer_backend.rs
  utils/wasm-gen/src/config/syscalls/injection.rs
  utils/wasm-gen/src/generator/memory.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/wasm.rs
Labels: A0-pleasereview

#3411 feat(wasm-instrument): add more information about syscalls signatures
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A0-pleasereview

#3418 feat!(runtime): Add ability to align total supply
  gsdk/src/metadata/generated.rs
  pallets/staking-rewards/src/lib.rs
  pallets/staking-rewards/src/tests.rs
  pallets/staking-rewards/src/weights.rs
Labels: A0-pleasereview

#3423 feat(gsdk): Expose `GearConfig` and `PairSigner`
  gsdk/src/lib.rs
  gsdk/src/signer/mod.rs
Labels: A0-pleasereview

#3424 fix(scripts): rewrite `install.sh` in POSIX way
  scripts/install.sh
Labels: A0-pleasereview, A2-mergeoncegreen

#3425 feat!(runtime): Add field `keep_alive` to gear extrinsics defining existence requirement
  gclient/src/api/calls.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/metadata/impls.rs
  gsdk/src/signer/calls.rs
  node/authorship/src/tests.rs
  pallets/gear-bank/src/lib.rs
  pallets/gear-bank/src/tests.rs
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear-voucher/src/lib.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tasks.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/tests.rs
  runtime/vara/src/integration_tests.rs
  utils/runtime-fuzzer/src/lib.rs
Labels: A0-pleasereview

#3429 feat(gstd): add From & Default implementation for sync primitives
  gstd/src/sync/mutex.rs
  gstd/src/sync/rwlock.rs
Labels: A0-pleasereview

#3430 fix(gear-weights-diff): Fix `format_diff` and compilation
  utils/weight-diff/Cargo.toml
  utils/weight-diff/src/main.rs
Labels: A0-pleasereview, D5-tooling

#3431 feat(wasm-builder): Fetch active toolchain via rustup
  utils/wasm-builder/src/builder_error.rs
  utils/wasm-builder/src/cargo_toolchain.rs
  utils/wasm-builder/src/lib.rs
Labels: A0-pleasereview, D5-tooling

#3404 fix(runtime-fuzzer): update wasm-smith fork & disable all traps in wasm
  Cargo.lock
  Cargo.toml
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/module.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview

#3436 chore(runtime): Bump versions after `v1.0.1` release
  Cargo.lock
  Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3434 refactor(pallet-gear, wasm-gen): Remove stack limiter to decrease unnecessary errors from wasmi
  pallets/gear/src/schedule.rs
  scripts/src/test.sh
Labels: A0-pleasereview, A2-mergeoncegreen, D4-test, D5-tooling

#3342 refactor(core-backend): Remove `host` proc macro
  Cargo.lock
  Cargo.toml
  core-backend/Cargo.toml
  core-backend/codegen/Cargo.toml
  core-backend/codegen/src/host.rs
  core-backend/codegen/src/lib.rs
  core-backend/src/env.rs
  core-backend/src/funcs.rs
  core-backend/src/lib.rs
  core-backend/src/log.rs
  core-backend/src/runtime.rs
  core/src/message/handle.rs
  core/src/message/init.rs
  core/src/message/reply.rs
  pallets/gear/src/lib.rs
Labels: A2-mergeoncegreen, D1-core

#3443 refactor(runtime-fuzzer): Decrease payload length in `runtime-fuzzer`
  docker/runtime-fuzzer/scripts/fuzzer.sh
  scripts/fuzzer_consts.sh
  utils/runtime-fuzzer/README.md
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/runtime-fuzzer/src/utils.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#3422 refactor(wasm-gen): add new approach of processing syscall parameters
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A0-pleasereview, C2-refactoring, D5-tooling

#3441 chore: remove unused deps
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  core-processor/Cargo.toml
  gclient/Cargo.toml
  gsdk/api-gen/src/main.rs
  gtest/Cargo.toml
  lazy-pages/Cargo.toml
  lazy-pages/interface/Cargo.toml
  node/authorship/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  runtime-interface/Cargo.toml
  runtime/common/Cargo.toml
  utils/node-loader/Cargo.toml
  utils/runtime-fuzzer/fuzz/Cargo.toml
  utils/wasm-proc/Cargo.toml
Labels: A0-pleasereview

#3419 docs(gtest): crate level documents
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#3166 feat(core, node): Change storage of program memory pages to triple map
  common/src/benchmarking.rs
  common/src/lib.rs
  common/src/paused_program_storage.rs
  common/src/program_storage.rs
  common/src/storage/primitives/mod.rs
  common/src/storage/primitives/triple_map.rs
  core-processor/src/common.rs
  core-processor/src/context.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/program.rs
  gclient/src/api/calls.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/signer/storage.rs
  gsdk/src/storage.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  lazy-pages/interface/src/lib.rs
  lazy-pages/src/lib.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migrations.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tasks.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  runtime-interface/src/lib.rs
  runtime/vara/src/migrations.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview, D1-core, D2-node, C1-feature

#3366 feat(gcli): introduce metadata executor
  Cargo.lock
  gcli/Cargo.toml
  gcli/src/meta/executor.rs
  gcli/src/meta/mod.rs
  gcli/src/result.rs
  gcli/tests/cmd/program.rs
  gcli/tests/cmd/send.rs
  gcli/tests/common/mod.rs
  gcli/tests/common/node.rs
  gcli/tests/common/result.rs
  gsdk/src/signer/utils.rs
Labels: A0-pleasereview

#3451 chore: downgrade rust version to nightly-2023-09-18
  examples/constructor/src/builder.rs
  rust-toolchain.toml
  scripts/src/clippy.sh
Labels: A0-pleasereview, E0-forcecoverage

#3456 refactor(gsdk): Remove abiguity in `Api::blocks()` functions
  gclient/src/api/mod.rs
  gsdk/src/api.rs
  gsdk/tests/rpc.rs
  utils/node-loader/src/main.rs
  utils/validator-checks/src/listener.rs
Labels: A0-pleasereview

#3458 bug(pallet-gear): Send message to user keep alive requirement
  pallets/gear/src/lib.rs
Labels: A0-pleasereview
