Repository gear-tech/gear, pull requests merged in 2023-09, with the labels that each got.

#3198 feat(runtime): make transaction cost multiplier smoother
  pallets/payment/src/lib.rs
  pallets/payment/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node

#3195 feat(node): Add debug runtime interface for benchmarks
  node/service/src/client.rs
  pallets/gear/Cargo.toml
  runtime-interface/src/lib.rs
Labels: A0-pleasereview

#3211 chore(after-release): Clean up and versioning
  core-processor/src/ext.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/migrations/mod.rs
  pallets/gas/src/migrations/v1.rs
  pallets/gas/src/migrations/v2.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-messenger/src/migrations.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migration.rs
  pallets/gear-scheduler/src/lib.rs
  pallets/gear-scheduler/src/migration.rs
  pallets/gear-voucher/src/lib.rs
  pallets/gear-voucher/src/migration.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/migration.rs
  pallets/staking-rewards/src/lib.rs
  pallets/staking-rewards/src/migration.rs
  runtime/common/src/lib.rs
  runtime/common/src/migrations.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/migrations.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview

#2754 refactor(gtest): Check the types for read_state_using_wasm args
  Cargo.lock
  examples/new-meta/tests/read_state.rs
  gtest/Cargo.toml
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/program.rs
Labels: A0-pleasereview

#3206 feat(wasm-gen): Implement fallible syscalls error processing setup
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview

#3200 docs(runtime-fuzzer): add documentation for `runtime-fuzzer` crate
  utils/runtime-fuzzer/README.md
Labels: A0-pleasereview

#3215 chore: Change runner for measurements CI
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview, C2-refactoring

#3208 feat(pallet-gear-rpc): read states in batch
  pallets/gear/rpc/src/lib.rs
Labels: A0-pleasereview, D2-node

#3212 feat(gtest): Support reply deposit in `gtest`
  Cargo.lock
  Cargo.toml
  examples/autoreply/Cargo.toml
  examples/autoreply/build.rs
  examples/autoreply/src/lib.rs
  examples/autoreply/src/wasm.rs
  gtest/src/manager.rs
Labels: A0-pleasereview

#3219 chore(scripts): Update `fuzzer.sh`
  docker/runtime-fuzzer/scripts/fuzzer.sh
Labels: A0-pleasereview

#3177 feat(wasm-gen): implement sys-call patterns
  Cargo.lock
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
Labels: A2-mergeoncegreen, D5-tooling

#3220 fix(vara): Bump MaxAuthorities to 100_000
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3113 test: Introduce `read_big_state` test on benchmark tests
  .github/workflows/build.yml
  Cargo.toml
  examples/read-big-state/Cargo.toml
  examples/read-big-state/build.rs
  examples/read-big-state/src/lib.rs
  examples/sys-calls/src/lib.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
Labels: A2-mergeoncegreen

#3228 fix(runtime-fuzzer): Fix fuzzer coverage script
  docker/runtime-fuzzer/Dockerfile
  docker/runtime-fuzzer/scripts/fuzzer.sh
  utils/runtime-fuzzer/README.md
Labels: A0-pleasereview, D5-tooling

#3229 feat(runtime-fuzzer): Optionally enable fuzzer logs
  Makefile
  scripts/check-fuzzer.sh
  scripts/gear.sh
  scripts/src/test.sh
Labels: A0-pleasereview, D4-test, D5-tooling

#3209 feat(pallet-gear): enable stack limit instrumentation
  Cargo.lock
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/code.rs
  core/src/program.rs
  examples/fungible-token/tests/benchmarks.rs
  gcli/src/meta/mod.rs
  gsdk/HOW-TO-UPDATE.md
  gsdk/src/metadata/generated.rs
  gtest/src/manager.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  sandbox/host/Cargo.toml
  sandbox/host/src/sandbox/wasmer_backend.rs
  sandbox/host/src/sandbox/wasmi_backend.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview

#3239 feat(runtime)!: Add customisation for gas price
  Cargo.lock
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/node.rs
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  common/src/gas_provider/property_tests/utils.rs
  common/src/lib.rs
  gcli/tests/cmd/claim.rs
  gsdk/src/lib.rs
  gsdk/src/metadata/generated.rs
  pallets/airdrop/src/mock.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/migrations.rs
  pallets/gas/src/tests.rs
  pallets/gear-bank/src/lib.rs
  pallets/gear-bank/src/mock.rs
  pallets/gear-bank/src/tests.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  runtime/common/src/lib.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/migrations.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/src/runtime/mod.rs
Labels: A0-pleasereview

#3227 refactor(core): Change Debug/Display implementation for Payload
  core/src/buffer.rs
Labels: A0-pleasereview, C2-refactoring

#3243 chore(runtime): Update weights
  pallets/gear/src/weights.rs
  runtime/gear/src/tests.rs
  runtime/gear/src/weights/frame_system.rs
  runtime/gear/src/weights/pallet_balances.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/gear/src/weights/pallet_gear_voucher.rs
  runtime/gear/src/weights/pallet_timestamp.rs
  runtime/gear/src/weights/pallet_utility.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_airdrop.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
Labels: A0-pleasereview

#3225 perf(wasm-gen): Improve fuzzer's and loader's memory testing
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/README.md
  utils/runtime-fuzzer/src/arbitrary_call.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/generator.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3237 feat(wasm-gen): make first param of `gr_exit` configurable
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
Labels: A0-pleasereview, D5-tooling

#3267 update base image for dockerfile fuzzer
  docker/runtime-fuzzer/Dockerfile
Labels: A0-pleasereview

#3263 chore(v1.0.0): Versions
  Cargo.lock
  Cargo.toml
  lazy-pages/Cargo.toml
  node/authorship/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  node/testing/Cargo.toml
  pallets/gas/Cargo.toml
  pallets/gear-bank/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-messenger/Cargo.toml
  pallets/gear-program/Cargo.toml
  pallets/gear-scheduler/Cargo.toml
  pallets/gear-voucher/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/gear/proc-macro/Cargo.toml
  pallets/gear/rpc/Cargo.toml
  pallets/gear/rpc/runtime-api/Cargo.toml
  pallets/payment/Cargo.toml
  pallets/staking-rewards/Cargo.toml
  runtime-interface/Cargo.toml
  runtime/common/Cargo.toml
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/primitives/Cargo.toml
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3265 chore(v1.0.0): Clean up and constants fix
  node/service/src/chain_spec/vara.rs
  node/testing/src/genesis.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/migrations.rs
  pallets/staking-rewards/src/mock.rs
  runtime/gear/src/constants.rs
  runtime/gear/src/migrations.rs
  runtime/vara/src/constants.rs
  runtime/vara/src/governance/fellowship.rs
  runtime/vara/src/governance/mod.rs
  runtime/vara/src/governance/tracks.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview

#3276 chore(v1.0.0): Remove `pallet-airdrop`
  Cargo.lock
  Cargo.toml
  gsdk/src/metadata/errors.rs
  gsdk/src/metadata/generated.rs
  pallets/airdrop/Cargo.toml
  pallets/airdrop/README.md
  pallets/airdrop/src/benchmarking.rs
  pallets/airdrop/src/lib.rs
  pallets/airdrop/src/mock.rs
  pallets/airdrop/src/tests.rs
  pallets/airdrop/src/weights.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/mod.rs
  runtime/vara/src/weights/pallet_airdrop.rs
Labels: A0-pleasereview

#3277 chore(v1.0.0): Development features gate
  .github/workflows/release.yml
  gsdk/build.rs
  node/authorship/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/gear.rs
  node/service/src/chain_spec/vara.rs
  node/testing/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/lib.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  scripts/update-gsdk-metadata.sh
Labels: A0-pleasereview

#3280 fix(node): Throw error on `--dev` in case of non-dev build
  Makefile
  node/cli/src/command.rs
Labels: A0-pleasereview

#3279 chore(v1.0.0): Remove `pallet-sudo` from production Vara
  .github/workflows/build.yml
  .github/workflows/test-measurements.yaml
  Cargo.lock
  node/authorship/Cargo.toml
  node/service/src/chain_spec/vara.rs
  node/testing/Cargo.toml
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  scripts/benchmarking/run_all_benchmarks.sh
Labels: A0-pleasereview

#3223 chore(scripts): sync doc test command with the help message
  .github/workflows/check.yml
  Makefile
  scripts/gear.sh
Labels: A2-mergeoncegreen

#2797 refactor(node): Benchmark tasks and reduce GasAllowance accordingly
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  common/src/scheduler/task.rs
  examples/constructor/Cargo.toml
  examples/constructor/build.rs
  examples/constructor/src/arg.rs
  examples/constructor/src/call.rs
  examples/constructor/src/lib.rs
  examples/constructor/src/scheme/demo_proxy_with_gas.rs
  examples/delayed-sender/Cargo.toml
  examples/delayed-sender/build.rs
  examples/delayed-sender/src/code.rs
  examples/delayed-sender/src/lib.rs
  examples/init-wait/Cargo.toml
  examples/init-wait/build.rs
  examples/init-wait/src/code.rs
  examples/init-wait/src/lib.rs
  examples/reserve-gas/Cargo.toml
  examples/reserve-gas/build.rs
  examples/reserve-gas/src/lib.rs
  examples/wait_wake/build.rs
  examples/waiter/Cargo.toml
  examples/waiter/build.rs
  examples/waiter/src/code.rs
  examples/waiter/src/lib.rs
  gclient/Cargo.toml
  gsdk/Cargo.toml
  gsdk/tests/rpc.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tasks.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#3262 feat(wasm-gen): create config for precise sys-calls
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/src/arbitrary_call.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/amount.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview, D5-tooling

#3268 feat(runtime-fuzzer): Aggregational PR for different fuzzer features and adjustments
  docker/runtime-fuzzer/Dockerfile
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/README.md
  utils/runtime-fuzzer/bin/run_corpus.rs
  utils/runtime-fuzzer/src/arbitrary_call.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/generator.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/amount.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#3290 feat(rpc): Add RPC call to query inflation and ROI
  Cargo.lock
  Cargo.toml
  node/service/Cargo.toml
  node/service/src/client.rs
  node/service/src/rpc/mod.rs
  pallets/staking-rewards/rpc/Cargo.toml
  pallets/staking-rewards/rpc/runtime-api/Cargo.toml
  pallets/staking-rewards/rpc/runtime-api/src/lib.rs
  pallets/staking-rewards/rpc/src/lib.rs
  pallets/staking-rewards/src/lib.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature

#3298 fix(builds): Pass `dev` feature
  .github/workflows/build.yml
  Makefile
  scripts/calc-gas-spent.sh
  scripts/ci_build.sh
  scripts/read-state.sh
Labels: A0-pleasereview

#3123 chore!: Stabilize `lazy-pages` feature
  .github/workflows/CI.yaml
  .github/workflows/build-macos.yml
  .github/workflows/build.yml
  .github/workflows/test-measurements.yaml
  Cargo.lock
  Makefile
  core-processor/Cargo.toml
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processing.rs
  core/Cargo.toml
  core/src/memory.rs
  docker/Vara-Dockerfile
  examples/new-meta/tests/read_state.rs
  gcli/Cargo.toml
  gcli/src/meta/mod.rs
  gtest/Cargo.toml
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
  node/cli/Cargo.toml
  node/service/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear-scheduler/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/benchmarking/tests/mod.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  pallets/payment/Cargo.toml
  runtime/common/Cargo.toml
  runtime/gear/Cargo.toml
  runtime/vara/Cargo.toml
  scripts/ci_build.sh
  utils/runtime-fuzzer/Cargo.toml
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview, D1-core, D2-node, D4-test

#3278 refactor(pallet-gear): Allow `calculate_gas_info` on terminated program.
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring

#3254 feat(gtest): Add payload to `Program::read_state*`
  examples/autoreply/src/lib.rs
  examples/new-meta/tests/read_state.rs
  gtest/src/manager.rs
  gtest/src/program.rs
Labels: A0-pleasereview

#3300 chore(tests): Adjust `block_max_gas_works` test of gear-authorship
  Cargo.lock
  node/authorship/Cargo.toml
  node/authorship/src/tests.rs
Labels: A0-pleasereview, C2-refactoring, D4-test

#3130 chore(core): move GasInfo to core
  Cargo.lock
  core/Cargo.toml
  core/src/gas.rs
  gsdk/Cargo.toml
  gsdk/src/lib.rs
  pallets/gear/rpc/Cargo.toml
  pallets/gear/src/lib.rs
Labels: A0-pleasereview

#3301 chore(versioning): Update runtime version
  Cargo.lock
  Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A4-insubstantial

#3305 chore(galloc): Update dlmalloc
  Cargo.lock
  Cargo.toml
  galloc/Cargo.toml
Labels: A0-pleasereview, D3-gstd

#3253 ci: add new functions to benchmark workflow
  .github/workflows/benchmarks.yml
  .github/workflows/comparison-table.yml
  .github/workflows/time-consuming-tests.yml
  scripts/weight-diff.sh
  utils/weight-diff/src/main.rs
Labels: A0-pleasereview

#3303 Add workflow to check changes on validator
  .github/workflows/validation.yml
  docker/Dockerfile
Labels: A2-mergeoncegreen

#3307 feat(wasm-gen): Introduce `unreachable_enabled` in `wasm-gen`
  Cargo.lock
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/src/arbitrary_call.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/module.rs
  utils/wasm-gen/src/tests.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3321 fix(gcli): Use vara runtime ss58 prefix by default
  Cargo.lock
  gcli/Cargo.toml
  gcli/bin/gcli.rs
Labels: A0-pleasereview

#3322 chore(depbot): not skipping ci
  .github/dependabot.yml
Labels: A0-pleasereview

#3335 feat(utils): add util to retrieve default peer ID secret keys
  Cargo.lock
  Cargo.toml
  utils/key-finder/Cargo.toml
  utils/key-finder/src/main.rs
Labels: A0-pleasereview, B1-releasenotes

#3010 refactor(core): Add nonce to program id generation
  core-backend/common/src/funcs.rs
  core-processor/src/ext.rs
  core/src/ids.rs
  core/src/message/init.rs
  examples/program-factory/src/lib.rs
  gcli/tests/common/mod.rs
  gsdk/tests/rpc.rs
  gtest/src/program.rs
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tasks.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  utils/runtime-fuzzer/src/arbitrary_call.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview

#3315 fix(gstd-async): Handle locks for default wait sendings
  gstd/src/async_runtime/signals.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#3344 chore(gsdk&CI): update RPC endpoints
  .github/workflows/build.yml
  gsdk/src/client.rs
Labels: A2-mergeoncegreen

#3302 test(wasm-gen): cover all the precise sys-calls with tests
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/precise.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/tests.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3196 feat(runtime-fuzzer): implement testing the rest gear extrinsics
  utils/call-gen/src/send_reply.rs
  utils/runtime-fuzzer/bin/run_corpus.rs
  utils/runtime-fuzzer/fuzz/fuzz_targets/main.rs
  utils/runtime-fuzzer/src/arbitrary_call.rs
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/runtime-fuzzer/src/lib.rs
  utils/runtime-fuzzer/src/runtime/block.rs
  utils/runtime-fuzzer/src/runtime/mailbox.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
  utils/runtime-fuzzer/src/tests.rs
  utils/runtime-fuzzer/src/utils.rs
Labels: A2-mergeoncegreen

#3242 feat(wasm-gen): insert syscall invocations into wasm wisely
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/wasm.rs
Labels: A2-mergeoncegreen

#3349 ci(skip): skip-ci in commit message
  .github/actions/label/skip.js
  .github/workflows/PR.yml
Labels: A0-pleasereview

#3226 feat(pallet-gear-rpc): Pass gas_allowance multiplier from client
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/lib.rs
  node/service/src/rpc/mod.rs
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  runtime/common/src/apis.rs
Labels: A2-mergeoncegreen, D2-node

#3347 ci(dep): introduce groups feature in dependabot
  .github/dependabot.yml
  .github/workflows/PR.yml
  .github/workflows/combined-dependabot.yml
Labels: A0-pleasereview

#3326 feat(vara): Introduce Vara Testnet spec
  node/res/vara_testnet.json
  node/service/src/chain_spec/vara.rs
Labels: A2-mergeoncegreen

#3341 feat(gstd): Mutex lock monitor
  examples/waiter/src/lib.rs
  examples/waiter/src/wasm.rs
  examples/waiter/tests/mx_lock_access.rs
  gstd/src/async_runtime/locks.rs
  gstd/src/sync/access.rs
  gstd/src/sync/mod.rs
  gstd/src/sync/mutex.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#3258 feat(benchmarks): add proper benchmarks for signal syscalls
  core-backend/common/src/funcs.rs
  core/src/costs.rs
  gsdk/src/metadata/generated.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
Labels: A0-pleasereview, D6-gas

#3319 feat(benchmarking): tune benchmarking for non-return syscalls
  scripts/benchmarking/merge_outputs.sh
  scripts/benchmarking/run_all_benchmarks.sh
Labels: A0-pleasereview, D6-gas

#3360 feat(node): Forbid non-wasm execution for validators
  node/cli/src/command.rs
Labels: A0-pleasereview

#3359 feat(wasm-gen): allow `gr_send_commit*` to receive existing address
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
Labels: A0-pleasereview, D5-tooling

#3358 refactor(runtime-fuzzer): Reduce fuzzer input debug printed data when crash happens
  utils/runtime-fuzzer/bin/run_corpus.rs
  utils/runtime-fuzzer/fuzz/fuzz_targets/main.rs
  utils/runtime-fuzzer/src/lib.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3365 fix(vara): nomination pools - set MaxUnbonding eq to staking
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen

#3363 fix(node): Unify client to be compatible with all chains
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test-measurements.yaml
  Cargo.toml
  Makefile
  examples/sys-calls/src/wasm.rs
  gcli/Cargo.toml
  gcli/tests/common/mod.rs
  gclient/tests/node.rs
  gclient/tests/set_code.rs
  node/authorship/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/res/staging.json
  node/service/Cargo.toml
  node/service/src/chain_spec/gear.rs
  node/service/src/chain_spec/vara.rs
  node/service/src/lib.rs
  node/testing/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/lib.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  runtime/gear/Cargo.toml
  runtime/vara/Cargo.toml
  scripts/benchmarking/run_all_benchmarks.sh
  scripts/calc-gas-spent.sh
  scripts/ci_build.sh
  scripts/read-state.sh
  utils/gear-replay-cli/Cargo.toml
  utils/runtime-fuzzer/Cargo.toml
Labels: A0-pleasereview

#3371 fix(benchmarks): fix benchmarks run on CI runner
  scripts/benchmarking/run_all_benchmarks.sh
Labels: A2-mergeoncegreen, C0-bug, Q1-easy

#3370 [depbot] ci(build): not skipping build for depbot
  .github/workflows/PR.yml
Labels: A2-mergeoncegreen

#3376 refactor(gsys): fix signature of `gr_random`
  gcore/src/exec.rs
  gsys/src/lib.rs
Labels: A0-pleasereview, Q1-easy
