Repository gear-tech/gear, pull requests merged in 2023-12, with the labels that each got.

#3555 refactor(gear): Introduced naming convention for "syscall"
  .github/workflows/build.yml
  Cargo.toml
  core-backend/Cargo.toml
  core-backend/src/env.rs
  core-backend/src/error.rs
  core-backend/src/funcs.rs
  core-backend/src/mock.rs
  core-backend/src/tests.rs
  core-processor/src/configs.rs
  core-processor/src/ext.rs
  core/src/env.rs
  core/src/message/mod.rs
  examples/program-factory/src/lib.rs
  examples/program-factory/src/wasm.rs
  examples/syscalls/Cargo.toml
  examples/syscalls/build.rs
  examples/syscalls/src/lib.rs
  examples/syscalls/src/wasm.rs
  lazy-pages/common/src/lib.rs
  lazy-pages/src/host_func.rs
  lazy-pages/src/signal.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/generator.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/injection.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/config/syscalls/precise.rs
  utils/wasm-gen/src/generator.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-gen/src/utils.rs
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/syscalls.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, C2-refactoring

#3542 refactor(tests): Always use `debug` in tests
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, P1-asap, D4-test

#3487 feat(demo-constructor): Support multiple calls in `if_else`
  examples/constructor/src/builder.rs
  examples/constructor/src/call.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen

#3515 feat(crates-io): publish gstd and gear-wasm-builder
  .github/workflows/crates-io.yml
  Cargo.lock
  Cargo.toml
  galloc/Cargo.toml
  gcli/Cargo.toml
  gcore/Cargo.toml
  gstd/Cargo.toml
  gstd/codegen/Cargo.toml
  stack-buffer/Cargo.toml
  utils/crates-io/Cargo.toml
  utils/crates-io/publish.rs
  utils/crates-io/src/lib.rs
  utils/crates-io/src/main.rs
  utils/crates-io/src/manifest.rs
  utils/crates-io/src/publisher.rs
  utils/crates-io/src/rename.rs
  utils/crates-io/src/version.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/stack_end.rs
Labels: A0-pleasereview, B1-releasenotes

#3535 feat(pallet-gear): Actual weight correction in `Gear::run` extrinsic
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#3573 feat(gcli): support customized CLI derived from gcli
  Cargo.lock
  gcli/Cargo.toml
  gcli/examples/mycli.rs
  gcli/src/app.rs
  gcli/src/bin/gcli.rs
  gcli/src/cmd/key.rs
  gcli/src/cmd/mod.rs
  gcli/src/cmd/program.rs
  gcli/src/cmd/upload.rs
  gcli/src/lib.rs
  gcli/tests/cmd/claim.rs
  gcli/tests/cmd/info.rs
  gcli/tests/cmd/key.rs
  gcli/tests/cmd/program.rs
  gcli/tests/cmd/send.rs
  gcli/tests/cmd/upload.rs
  gcli/tests/common/mod.rs
  gcli/tests/common/node.rs
  gsdk/src/client.rs
  gsdk/src/testing/node.rs
Labels: A0-pleasereview

#3558 feat(node): Two phase block proposing for release v1.0.3
  Cargo.lock
  common/src/lib.rs
  examples/constructor/src/builder.rs
  examples/constructor/src/call.rs
  gsdk/src/metadata/generated.rs
  images/block-proposing-timing.svg
  images/substrate-vs-gear-block.svg
  images/time-weight-synchronization.svg
  node/authorship/Cargo.toml
  node/authorship/README.md
  node/authorship/src/authorship.rs
  node/authorship/src/block_builder.rs
  node/authorship/src/tests.rs
  node/service/src/lib.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear/src/lib.rs
  runtime/common/src/apis.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature, check-validator

#3554 refactor(wasm-instrument, wasm-gen): Make syscalls errors config and syscalls results processing more consistent
  gsys/src/lib.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/syscalls.rs
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/injection.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/config/syscalls/process_errors.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-instrument/src/syscalls.rs
  utils/wasm-instrument/src/tests.rs
Labels: A2-mergeoncegreen, D5-tooling

#3567 refactor(pallets): Introduce `Origin::cast` fn
  common/src/benchmarking.rs
  common/src/lib.rs
  common/src/storage/primitives/key.rs
  lazy-pages/interface/src/lib.rs
  pallets/gas/src/tests.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear-voucher/src/benchmarking.rs
  pallets/gear-voucher/src/tests.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/tests.rs
Labels: A2-mergeoncegreen

#3568 feat(gcli): log program ID after uploading program
  Cargo.lock
  gcli/Cargo.toml
  gcli/src/cmd/info.rs
  gcli/src/cmd/send.rs
  gcli/src/cmd/upload.rs
  gcli/tests/cmd/claim.rs
  gcli/tests/cmd/info.rs
  gcli/tests/cmd/program.rs
  gcli/tests/cmd/transfer.rs
  gcli/tests/cmd/upload.rs
  gcli/tests/common/logs.rs
  gcli/tests/common/mod.rs
  gsdk/Cargo.toml
  gsdk/src/api.rs
  gsdk/src/signer/utils.rs
  gsdk/src/testing/node.rs
Labels: A2-mergeoncegreen

#3578 ci(dispatch): skip label dispatching on PRs of dependabot
  .github/actions/label/build.js
  .github/workflows/PR.yml
  .github/workflows/label.yml
Labels: A4-insubstantial

#3593 chore(runtime): Bump versions after `v1.0.2` release (#3522)
  Cargo.lock
  Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3584 feat: Update substrate to v0.9.43
  Cargo.lock
  Cargo.toml
  gcli/src/keystore/key.rs
  gcli/src/result.rs
  gcli/tests/cmd/info.rs
  gclient/src/api/calls.rs
  gclient/src/api/storage/mod.rs
  gsdk/api-gen/src/main.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/metadata/impls.rs
  gsdk/src/storage.rs
  gsdk/src/testing/node.rs
  node/authorship/src/tests.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/rpc/mod.rs
  pallets/gas/src/mock.rs
  pallets/gear-bank/src/mock.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-messenger/src/mock.rs
  pallets/gear-program/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear-voucher/src/mock.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  pallets/staking-rewards/src/lib.rs
  pallets/staking-rewards/src/mock.rs
  pallets/staking-rewards/src/tests.rs
  runtime/common/src/apis.rs
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
  sandbox/host/src/sandbox/wasmer_backend.rs
  sandbox/host/src/sandbox/wasmi_backend.rs
  utils/gear-replay-cli/Cargo.toml
  utils/gear-replay-cli/src/util.rs
  utils/node-loader/src/batch_pool.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
Labels: A0-pleasereview, D2-node

#3581 refactor(crates-io): use `toml_edit` instead of `cargo_toml`
  .github/workflows/crates-io.yml
  Cargo.lock
  Cargo.toml
  utils/crates-io/Cargo.toml
  utils/crates-io/src/lib.rs
  utils/crates-io/src/main.rs
  utils/crates-io/src/manifest.rs
  utils/crates-io/src/publisher.rs
  utils/crates-io/src/rename.rs
  utils/crates-io/src/version.rs
Labels: A0-pleasereview

#3586 refactor(vouchers): Remove gear-pallet explicit dependency on vouchers
  common/src/lib.rs
  common/src/storage/complex/mailbox.rs
  gsdk/src/metadata/generated.rs
  pallets/gear-voucher/src/benchmarking.rs
  pallets/gear-voucher/src/lib.rs
  pallets/gear-voucher/src/mock.rs
  pallets/gear-voucher/src/tests.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/pallet_tests.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  pallets/payment/src/tests.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3604 chore(runtime): move SS58 prefix to primitives
  Cargo.lock
  gcli/Cargo.toml
  gcli/src/app.rs
  gcli/tests/gear.rs
  runtime/primitives/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A4-insubstantial

#3599 chore(runtime): Bump versions after `v1.0.3` release
  Cargo.lock
  Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, A4-insubstantial

#3610 feat(gstd): add the missing `dbg!` macro
  gstd/src/macros/debug.rs
  gstd/src/prelude.rs
  gstd/tests/debug.rs
Labels: A0-pleasereview, B1-releasenotes

#3613 chore(benchmarks): remove redundant benchmarks
  common/src/benchmarking.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tasks.rs
  pallets/gear/src/weights.rs
  runtime/vara/src/weights/pallet_gear.rs
Labels: A0-pleasereview

#3605 feat(gtest): process time-limited wait messages
  examples/custom/src/lib.rs
  examples/custom/src/simple_waiter.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A0-pleasereview, B1-releasenotes, D5-tooling

#3589 feat(gcli): embed programs in commands
  Cargo.lock
  examples/messager/Cargo.toml
  examples/messager/src/bin/demo_messager.rs
  gcli/Cargo.toml
  gcli/examples/mycli.rs
  gcli/src/app.rs
  gcli/src/bin/gcli.rs
  gcli/src/cmd/claim.rs
  gcli/src/cmd/create.rs
  gcli/src/cmd/info.rs
  gcli/src/cmd/key.rs
  gcli/src/cmd/login.rs
  gcli/src/cmd/mod.rs
  gcli/src/cmd/new.rs
  gcli/src/cmd/program.rs
  gcli/src/cmd/reply.rs
  gcli/src/cmd/send.rs
  gcli/src/cmd/transfer.rs
  gcli/src/cmd/update.rs
  gcli/src/cmd/upload.rs
  gcli/src/embed.rs
  gcli/src/lib.rs
  gcli/tests/common/app.rs
  gcli/tests/common/env.rs
  gcli/tests/common/mod.rs
  gcli/tests/gear.rs
  utils/wasm-builder/src/lib.rs
Labels: A0-pleasereview

#3620 chore(vara): Update ECONOMIC_UNIT to 10 UNITS
  runtime/vara/src/constants.rs
Labels: A0-pleasereview

#3512 feat(core, wasm-instrument): add `gr_system_break` syscall
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  core-backend/src/env.rs
  core-backend/src/error.rs
  core-backend/src/funcs.rs
  core-backend/src/tests.rs
  core-errors/src/simple.rs
  core-processor/src/common.rs
  core/src/code.rs
  examples/signal-entry/Cargo.toml
  examples/signal-entry/build.rs
  examples/signal-entry/src/lib.rs
  examples/signal-entry/src/wasm.rs
  gcli/src/meta/executor.rs
  gsdk/src/metadata/generated.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/mod.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/schedule.rs
  utils/calc-stack-height/Cargo.toml
  utils/calc-stack-height/src/main.rs
  utils/wasm-instrument/Cargo.toml
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/syscalls.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, D1-core, B1-releasenotes

#3609 fix(node): Take 'wait' syscall into account in calculate_gas_info
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node, C0-bug

#3612 fix(wasm-gen): copy data from `HashWithValue` before writing to `err`
  utils/wasm-gen/src/generator/syscalls/imports.rs
Labels: A0-pleasereview

#3628 fix: links to Vara network
  README.md
  gclient/src/api/mod.rs
  gclient/src/ws.rs
  gsdk/src/client.rs
  gsdk/tests/rpc.rs
  utils/gear-replay-cli/README.md
  utils/gear-replay-cli/src/lib.rs
Labels: A0-pleasereview

#3559 feat(core): Validate fns signature on code creation
  core/src/code.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D1-core

#3611 chore: bump gear-dlmalloc for free_range support
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview

#3626 chore(sandbox): inherit manifest from workspace
  Cargo.lock
  Cargo.toml
  lazy-pages/Cargo.toml
  lazy-pages/src/globals.rs
  sandbox/env/Cargo.toml
  sandbox/env/src/lib.rs
  sandbox/sandbox/Cargo.toml
  sandbox/sandbox/src/embedded_executor.rs
  sandbox/sandbox/src/host_executor.rs
  sandbox/sandbox/src/lib.rs
Labels: A4-insubstantial

#3608 feat: update substrate to v1.0.0
  .github/workflows/build.yml
  .github/workflows/test-measurements.yaml
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  gsdk/src/metadata/generated.rs
  node/authorship/Cargo.toml
  node/authorship/src/block_builder.rs
  node/authorship/src/tests.rs
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/vara.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  node/service/src/rpc/mod.rs
  node/testing/src/genesis.rs
  node/testing/src/keyring.rs
  pallets/gas/src/mock.rs
  pallets/gear-bank/src/mock.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-messenger/src/mock.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/mock.rs
  pallets/gear-scheduler/src/lib.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear-voucher/src/mock.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  pallets/payment/src/mock.rs
  pallets/staking-rewards/src/lib.rs
  pallets/staking-rewards/src/mock.rs
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  runtime/primitives/src/lib.rs
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
  sandbox/sandbox/src/embedded_executor.rs
  scripts/benchmarking/run_all_benchmarks.sh
  utils/gear-replay-cli/src/cmd/gear_run.rs
  utils/gear-replay-cli/src/cmd/replay_block.rs
  utils/gear-replay-cli/src/util.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, D2-node, P1-asap, C1-feature

#3630 cherry-pick: "chore(runtime): Bump versions after `v1.0.3` release (#3599)"
  Cargo.lock
  Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3631 chore(toml): Disable debug assertions for `wasmer-vm` crate
  Cargo.toml
Labels: A0-pleasereview, D5-tooling

#3625 feat(wasm-gen): Introduce value fuzzing abilities to `wasm-gen`
  utils/node-loader/src/batch_pool/generators/batch.rs
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-gen/src/utils.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling
