Repository gear-tech/gear, pull requests merged in 2023-03, with the labels that each got.

#2323 Burn rewards minted in excess instead of sending them to Treasury
  pallets/staking-rewards/src/mock.rs
  pallets/staking-rewards/src/tests.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node

#2324 chore(gcli): delay tests to make sure the node has been fully initialized first
  .github/workflows/CI.yaml
  gcli/tests/cmd/info.rs
  gcli/tests/common/logs.rs
  gsdk/src/generated/impls.rs
  gsdk/src/generated/mod.rs
Labels: A2-mergeoncegreen

#2333 Fix `Result` aliases and typos
  gcli/scripts/update-readme.sh
  gcli/src/metadata/result.rs
  gcli/src/result.rs
  gcli/tests/common/result.rs
  gclient/src/node/result.rs
  gclient/tests/node.rs
  gsdk/src/result.rs
  gstd/src/common/errors.rs
  utils/validator-checks/src/result.rs
Labels: A2-mergeoncegreen

#2183 Introduce minimal runtime-fuzzer
  Cargo.lock
  Cargo.toml
  gclient/Cargo.toml
  gclient/src/lib.rs
  gclient/src/utils.rs
  gclient/tests/backend.rs
  gclient/tests/keyhasher.rs
  gclient/tests/loop.rs
  gclient/tests/node.rs
  gclient/tests/state.rs
  gclient/tests/upload.rs
  scripts/gear.sh
  scripts/src/test.sh
  utils/call-gen/src/lib.rs
  utils/call-gen/src/upload_code.rs
  utils/call-gen/src/upload_program.rs
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/batch_pool/generators/batch.rs
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/fuzz/Cargo.toml
  utils/runtime-fuzzer/fuzz/fuzz_targets/main.rs
  utils/runtime-fuzzer/src/bin/reproduce_fuzz.rs
  utils/runtime-fuzzer/src/lib.rs
  utils/runtime-fuzzer/src/runtime/account.rs
  utils/runtime-fuzzer/src/runtime/block.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
  utils/utils/Cargo.toml
  utils/utils/src/lib.rs
  utils/wasm-gen/src/lib.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#2336 Fix `make pre-commit` and reveal broken tests.
  .github/workflows/CI.yaml
  .github/workflows/test-measurements.yaml
  Makefile
  core-processor/src/ext.rs
  gcli/Makefile
  pallets/gear/src/tests.rs
  scripts/gear.sh
  scripts/src/check.sh
  scripts/src/clippy.sh
  scripts/src/test.sh
Labels: A0-pleasereview

#2335 Remove economic-checks
  .gitignore
  Cargo.lock
  Cargo.toml
  scripts/src/build.sh
  scripts/src/check.sh
  utils/economic-checks/Cargo.toml
  utils/economic-checks/README.md
  utils/economic-checks/fuzz/.gitignore
  utils/economic-checks/fuzz/Cargo.toml
  utils/economic-checks/fuzz/fuzz_targets/composer_fuzz_target.rs
  utils/economic-checks/fuzz/fuzz_targets/simple_fuzz_target.rs
  utils/economic-checks/src/lib.rs
  utils/economic-checks/src/targets.rs
  utils/economic-checks/src/util.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#2340 Add docker for running fuzzer
  docker/runtime-fuzzer/Dockerfile
Labels: A2-mergeoncegreen, D5-tooling

#2342 Add "make install" command
  Makefile
Labels: A4-insubstantial

#2338 Remove integral-tests crate
  Cargo.toml
  pallets/staking-rewards/src/mock.rs
  pallets/staking-rewards/src/tests.rs
  utils/integral-tests/Cargo.toml
  utils/integral-tests/README.md
  utils/integral-tests/src/bag_thresholds.rs
  utils/integral-tests/src/lib.rs
  utils/integral-tests/src/runtime.rs
  utils/integral-tests/src/tests.rs
  utils/integral-tests/src/util.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#2331 Add program migration functionality
  Cargo.lock
  gcli/Cargo.toml
  gcli/src/cmd/program.rs
  gcli/tests/cmd/upload.rs
  gcli/tests/common/mod.rs
  gcli/tests/rpc/mod.rs
  gclient/Cargo.toml
  gclient/src/api/calls.rs
  gclient/src/api/error.rs
  gclient/src/api/storage/mod.rs
  gclient/src/lib.rs
  gclient/tests/node.rs
  gsdk/src/result.rs
  gsdk/src/signer/calls.rs
  gsdk/src/storage.rs
Labels: A2-mergeoncegreen

#1982 Improve `gstd` docs
  examples/binaries/async-tester/src/code.rs
  examples/binaries/distributor/src/lib.rs
  examples/binaries/proxy-relay/src/lib.rs
  examples/decoder/src/lib.rs
  examples/incomplete_async_payloads/src/lib.rs
  examples/mutex/src/lib.rs
  examples/rwlock/src/lib.rs
  examples/rwlock_write/src/lib.rs
  gcore/src/errors.rs
  gcore/src/exec.rs
  gcore/src/general.rs
  gcore/src/lib.rs
  gcore/src/msg.rs
  gcore/src/prog.rs
  gcore/src/utils.rs
  gstd/README.md
  gstd/codegen/src/lib.rs
  gstd/codegen/src/utils.rs
  gstd/src/async_runtime/futures.rs
  gstd/src/async_runtime/locks.rs
  gstd/src/async_runtime/mod.rs
  gstd/src/async_runtime/signals.rs
  gstd/src/common/errors.rs
  gstd/src/common/mod.rs
  gstd/src/common/primitives.rs
  gstd/src/config.rs
  gstd/src/exec.rs
  gstd/src/lib.rs
  gstd/src/lock/mod.rs
  gstd/src/lock/mutex.rs
  gstd/src/lock/rwlock.rs
  gstd/src/macros/bail.rs
  gstd/src/macros/debug.rs
  gstd/src/macros/export.rs
  gstd/src/macros/metadata.rs
  gstd/src/macros/mod.rs
  gstd/src/msg/async.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  gstd/src/msg/macros.rs
  gstd/src/msg/mod.rs
  gstd/src/prog/generator.rs
  gstd/src/prog/mod.rs
  gstd/src/util.rs
Labels: A2-mergeoncegreen

#2346 Add test with the batch of messages filling the whole block
  Cargo.lock
  examples/binaries/delayed-sender/src/code.rs
  examples/binaries/meta/src/lib.rs
  examples/binaries/ncompose/src/lib.rs
  examples/binaries/node/src/lib.rs
  examples/fib/src/lib.rs
  examples/sum/src/lib.rs
  gclient/Cargo.toml
  gclient/src/node/mod.rs
  gclient/tests/perf.rs
Labels: A0-pleasereview

#2364 gclient: Add dev Vara node spawning
  gclient/src/node/mod.rs
Labels: A0-pleasereview

#1960 feat(gtest): introduce delayed messages in gtest
  gtest/src/log.rs
  gtest/src/mailbox.rs
  gtest/src/manager.rs
  gtest/src/system.rs
Labels: A3-gotissues

#2365 Remove redundant `Ext` methods
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-processor/src/ext.rs
  core/src/env.rs
  pallets/gear/src/ext.rs
Labels: A0-pleasereview, D1-core

#2374 use sccache instead of cachepot
  .github/workflows/CI.yaml
Labels: A0-pleasereview, D5-tooling

#2355 Disable `call_indirect` in runtime fuzzer
  Cargo.lock
  utils/call-gen/src/lib.rs
  utils/wasm-gen/src/lib.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#2378 Update binaryen, use sccache for test measurements
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview, D5-tooling

#2363 prune locks map in gstd
  gstd/src/async_runtime/futures.rs
  gstd/src/async_runtime/locks.rs
  gstd/src/async_runtime/mod.rs
Labels: A0-pleasereview, D3-gstd

#2305 Cross-compile Windows on CI
  .github/build-win-cross/config.toml
  .github/build-win-cross/update-alternatives-clang.sh
  .github/dependabot.yml
  .github/workflows/CI.yaml
  Cargo.lock
  Cargo.toml
  gclient/tests/backend.rs
  gclient/tests/keyhasher.rs
  gclient/tests/loop.rs
  gclient/tests/perf.rs
  gclient/tests/state.rs
  gclient/tests/upload.rs
  lazy-pages/src/init_flag.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/tests.rs
  pallets/gear/src/tests.rs
  scripts/gear.sh
  scripts/src/build.sh
  scripts/src/test.sh
Labels: A0-pleasereview, D5-tooling

#2216 remove old pages charging
  Cargo.lock
  common/lazy-pages/src/lib.rs
  core-backend/common/src/lazy_pages.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/funcs/internal.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/context.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/lib.rs
  core-processor/src/precharge.rs
  core-processor/src/processing.rs
  core/src/costs.rs
  core/src/env.rs
  core/src/gas.rs
  core/src/memory.rs
  examples/binaries/init-fail-sender/src/lib.rs
  gclient/tests/perf.rs
  gear-test/src/proc.rs
  gtest/src/manager.rs
  lazy-pages/src/common.rs
  lazy-pages/src/globals.rs
  lazy-pages/src/host_func.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/mprotect.rs
  lazy-pages/src/process.rs
  lazy-pages/src/signal.rs
  lazy-pages/src/sys.rs
  lazy-pages/src/sys/mod.rs
  lazy-pages/src/sys/unix.rs
  lazy-pages/src/sys/windows.rs
  lazy-pages/src/tests.rs
  lazy-pages/src/utils.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime-interface/src/lib.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen, D1-core, D2-node, E1-forcewindows, D6-gas

#2396 Add checking that gear stack end pointer does not overlap
  core/src/code.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D1-core, C2-refactoring

#2354 Update Schedule module. Charge for bytes len in `reply_*`.
  .maintain/frame-weight-template.hbs
  Cargo.lock
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
  core/src/costs.rs
  gcli/Cargo.toml
  gcli/src/cmd/key.rs
  gcli/src/keystore/node.rs
  pallets/gear/proc-macro/Cargo.toml
  pallets/gear/proc-macro/src/lib.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/tests.rs
  runtime/gear/src/weights/frame_system.rs
  runtime/gear/src/weights/pallet_balances.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/gear/src/weights/pallet_timestamp.rs
  runtime/gear/src/weights/pallet_utility.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
  scripts/benchmarking/run_all_benchmarks.sh
  utils/regression-analysis/src/main.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, D2-node

#2405 Disable gclient tests in `build-win-cross` job
  .github/workflows/CI.yaml
Labels: A0-pleasereview, D4-test

#2403 Set epoch duration to 2 hours in Vara
  runtime/vara/src/constants.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#2409 Set new version for the loader
  Cargo.lock
  utils/node-loader/CHANGELOG.md
  utils/node-loader/Cargo.toml
Labels: A0-pleasereview, D4-test, D5-tooling

#2416 Stabilize CI
  .github/workflows/CI.yaml
Labels: A1-inprogress, E2-forcemacos

#2423 Increase `runtime-fuzzer` performance
  scripts/src/test.sh
  utils/runtime-fuzzer/src/lib.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#2424 Simplify fuzzer crash reproducing
  Cargo.lock
  utils/runtime-fuzzer/fuzz/Cargo.toml
  utils/runtime-fuzzer/fuzz/fuzz_targets/main.rs
  utils/runtime-fuzzer/src/bin/reproduce_fuzz.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#2411 Generate handle_reply method
  utils/wasm-gen/src/lib.rs
Labels: A2-mergeoncegreen, D4-test

#2435 Change fuzzing seeds dir to constant value
  Cargo.lock
  Makefile
  utils/runtime-fuzzer/fuzz/Cargo.toml
  utils/runtime-fuzzer/fuzz/fuzz_targets/main.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#2398 change gear page size to 16 kb
  Cargo.lock
  common/lazy-pages/Cargo.toml
  common/lazy-pages/src/lib.rs
  core-backend/common/src/lazy_pages.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmi/src/env.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/costs.rs
  core/src/memory.rs
  gclient/src/node/mod.rs
  gsdk/src/storage.rs
  lazy-pages/src/common.rs
  lazy-pages/src/globals.rs
  lazy-pages/src/host_func.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/mprotect.rs
  lazy-pages/src/pages.rs
  lazy-pages/src/process.rs
  lazy-pages/src/signal.rs
  lazy-pages/src/tests.rs
  lazy-pages/src/utils.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/lib.rs
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview, D2-node, E1-forcewindows

#2436 [vara] 3 sec per block
  runtime/vara/src/constants.rs
  runtime/vara/src/lib.rs
Labels: D2-node

#2452 Staging Testnet V7
  node/res/staging.json
  node/service/src/chain_spec/gear.rs
Labels: A0-pleasereview

#2460 Update to 0.1.2 for the next release
  Cargo.lock
  node/cli/Cargo.toml
Labels: A4-insubstantial

#2458 Fix zero value send handling
  gclient/src/api/calls.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#2461 [vara] Add ImOnline event handler to gear authorship
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#2439 [gclient] Get rid of GearApiWithNode
  gclient/src/api/error.rs
  gclient/src/api/mod.rs
  gclient/src/lib.rs
  gclient/src/node/mod.rs
  gclient/tests/backend.rs
  gclient/tests/keyhasher.rs
  gclient/tests/loop.rs
  gclient/tests/node.rs
  gclient/tests/perf.rs
  gclient/tests/state.rs
  gclient/tests/upload.rs
Labels: A0-pleasereview

#2450 Add tokens locking integrity tests to vara runtime
  Cargo.lock
  runtime/vara/Cargo.toml
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, D4-test

#2465 Update versions for next release
  Cargo.lock
  gclient/src/api/mod.rs
  gclient/src/node/mod.rs
  node/cli/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A4-insubstantial

#2462 Fix futures and locks are not cleaned during signal
  gstd/src/async_runtime/mod.rs
Labels: A0-pleasereview, D3-gstd

#2471 [vara] Make the fellowship self-governed collective
  Cargo.lock
  runtime/vara/Cargo.toml
  runtime/vara/src/governance/fellowship.rs
  runtime/vara/src/governance/origins.rs
Labels: D2-node

#2384 Support migration of a program with gas reservations
  Cargo.lock
  examples/binaries/reserve-gas/src/lib.rs
  gclient/Cargo.toml
  gclient/src/api/calls.rs
  gclient/src/api/storage/mod.rs
  gclient/tests/node.rs
  gsdk/src/constants.rs
  gsdk/src/metadata/impls.rs
  gsdk/src/signer/calls.rs
  gsdk/src/storage.rs
  gsdk/src/types.rs
Labels: A2-mergeoncegreen

#2494 wasm-builder: Support sign extension Wasm instructions
  Cargo.lock
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview

#2486 Make `Memory::grow` unreachable
  core-backend/sandbox/src/memory.rs
  core-backend/wasmi/src/memory.rs
  core-processor/src/ext.rs
  core/src/memory.rs
Labels: A0-pleasereview, D1-core

#2406 Add benchmarks for i32 operations
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/tests.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
Labels: A0-pleasereview
