Repository gear-tech/gear, pull requests merged in 2023-01, with the labels that each got.

#2051 Implement Gear stack end in `wasm-gen`
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/test.rs
Labels: A0-pleasereview

#2033 replace btreemap to hashmap to improve performance
  Cargo.lock
  core/Cargo.toml
  core/src/reservation.rs
  examples/Cargo.lock
  gstd/Cargo.toml
  gstd/src/async_runtime/futures.rs
  gstd/src/async_runtime/locks.rs
  gstd/src/async_runtime/mod.rs
  gstd/src/async_runtime/signals.rs
  gstd/src/prelude.rs
  pallets/gear-program/Cargo.toml
Labels: A0-pleasereview

#2026 Validate fallible sys-calls in benches
  core-processor/src/ext.rs
  core/src/buffer.rs
  core/src/costs.rs
  core/src/ids.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
Labels: A0-pleasereview, D2-node

#2065 Fix bug with extra Wasms generated by `gclient`
  pallets/gear/Cargo.toml
Labels: A0-pleasereview, D5-tooling

#2056 gclient: Add functions for state reading
  Cargo.lock
  gclient/Cargo.toml
  gclient/src/api/error.rs
  gclient/src/api/rpc.rs
  gclient/src/api/storage/block.rs
  gclient/tests/state.rs
Labels: A2-mergeoncegreen

#2019 core backend refactoring for lazy pages charging
  .github/workflows/CI.yaml
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/memory.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs/internal.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-backend/wasmi/src/memory.rs
  core-processor/src/ext.rs
  core/src/ids.rs
  core/src/memory.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#1989 Re-check gas charge/refunding on backend/processor levels
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/funcs/internal.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/memory.rs
  core-processor/src/ext.rs
  core/src/gas.rs
  core/src/message/mod.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview, D1-core

#2017 Add ProgramStorage
  Cargo.lock
  common/lazy-pages/src/lib.rs
  common/src/benchmarking.rs
  common/src/code_storage.rs
  common/src/lib.rs
  common/src/program_storage.rs
  common/src/storage/primitives/double_map.rs
  common/src/storage/primitives/map.rs
  common/src/storage/primitives/mod.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/buffer.rs
  core/src/memory.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/sys.rs
  lazy-pages/src/tests.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/README.md
  pallets/gear-program/src/benchmarking.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/mock.rs
  pallets/gear-program/src/pause.rs
  pallets/gear-program/src/program.rs
  pallets/gear-program/src/tests.rs
  pallets/gear-program/src/weights.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  program/src/api/storage.rs
  program/src/api/utils.rs
  program/src/metadata/executor.rs
  program/src/metadata/mod.rs
  runtime-interface/src/lib.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/mod.rs
  runtime/gear/src/weights/pallet_gear_program.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/mod.rs
  runtime/vara/src/weights/pallet_gear_program.rs
  scripts/src/test.sh
  scripts/test-utils/gear_runtime.compact.compressed.wasm
  utils/gear-runtime-test-cli/src/command.rs
  utils/regression-analysis/src/main.rs
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring

#2069 Handle pool errors to avoid frequent finalization timeout errors
  Cargo.lock
  program/src/result.rs
  utils/node-loader/CHANGELOG.md
  utils/node-loader/Cargo.toml
  utils/node-loader/src/batch_pool/api/nonce.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#2084 Install wget, bzip2 for measurements CI
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview, D5-tooling

#2082 Bump subxt to a version with rpc errors being displayed
  Cargo.lock
  gclient/Cargo.toml
  program/Cargo.toml
  program/src/api/client.rs
  program/src/metadata/funcs.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#2043 Add more docs to `gclient` crate
  Cargo.lock
  gclient/Cargo.toml
  gclient/src/api/calls.rs
  gclient/src/api/error.rs
  gclient/src/api/listener/iterator.rs
  gclient/src/api/listener/mod.rs
  gclient/src/api/mod.rs
  gclient/src/api/rpc.rs
  gclient/src/api/storage/block.rs
  gclient/src/api/storage/mod.rs
  gclient/src/lib.rs
  gclient/src/node/ws.rs
  gclient/src/utils.rs
  gclient/tests/keyhasher.rs
  gclient/tests/loop.rs
  gclient/tests/state.rs
  gclient/tests/upload.rs
  gtest/src/mailbox.rs
  gtest/src/system.rs
  gtest/src/wasm_executor.rs
  scripts/src/format.sh
Labels: A2-mergeoncegreen

#2054 Rework block authorship
  gclient/src/api/listener/iterator.rs
  gclient/src/api/storage/block.rs
  gclient/tests/keyhasher.rs
  gclient/tests/loop.rs
  gclient/tests/upload.rs
  node/authorship/src/authorship.rs
  node/service/src/chain_spec/gear.rs
  node/service/src/chain_spec/vara.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  utils/test-runtime/client/src/block_builder_ext.rs
  utils/test-runtime/client/src/trait_tests.rs
  utils/test-runtime/src/inner.rs
  utils/test-runtime/src/lib.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#1988 lazy-pages charging
  .github/workflows/CI.yaml
  Cargo.lock
  common/lazy-pages/Cargo.toml
  common/lazy-pages/src/lib.rs
  core-backend/common/src/lazy_pages.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmi/src/env.rs
  core-processor/src/configs.rs
  core-processor/src/context.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/costs.rs
  core/src/memory.rs
  gear-test/src/proc.rs
  gtest/src/manager.rs
  gtest/src/wasm_executor.rs
  lazy-pages/Cargo.toml
  lazy-pages/src/lib.rs
  lazy-pages/src/sys.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/benchmarking/tests/mod.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/lib.rs
  runtime/gear/src/tests.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/tests.rs
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview, D1-core, D2-node, E1-forcewindows

#2117 rename `PageNumber` -> `GearPage` and `WasmPageNumber` -> `WasmPage`
  common/lazy-pages/src/lib.rs
  common/src/benchmarking.rs
  common/src/lib.rs
  common/src/program_storage.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/mock.rs
  core-backend/common/src/utils.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/memory.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/memory.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/context.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processor.rs
  core/src/code.rs
  core/src/env.rs
  core/src/memory.rs
  core/src/program.rs
  gear-test/src/check.rs
  gear-test/src/manager.rs
  gtest/src/error.rs
  gtest/src/manager.rs
  gtest/src/wasm_executor.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/sys.rs
  lazy-pages/src/tests.rs
  lazy-pages/src/utils.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear-program/src/lib.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  program/src/api/storage.rs
  runtime-interface/src/lib.rs
Labels: A0-pleasereview

#2083 safety refactor for read ext
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-processor/src/ext.rs
  core/src/env.rs
  pallets/gear/src/ext.rs
Labels: A0-pleasereview

#2118 Refactor gas tree imbalances
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/negative_imbalance.rs
  common/src/gas_provider/positive_imbalance.rs
  common/src/gas_provider/property_tests/mod.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/tests.rs
  pallets/gear/src/internal.rs
Labels: A0-pleasereview

#2108 Detect and remove recursive calls
  Cargo.lock
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/test.rs
  utils/wasm-gen/src/utils.rs
Labels: A0-pleasereview, C1-feature, D4-test

#2102 Update batch sender's balance
  Cargo.lock
  gclient/src/api/calls.rs
  gclient/src/api/storage/block.rs
  gclient/tests/keyhasher.rs
  gclient/tests/loop.rs
  gclient/tests/upload.rs
  node/service/src/chain_spec/gear.rs
  node/service/src/chain_spec/vara.rs
  utils/node-loader/CHANGELOG.md
  utils/node-loader/Cargo.toml
  utils/node-loader/src/args.rs
  utils/node-loader/src/batch_pool.rs
Labels: A0-pleasereview, D2-node

#2148 extrinsic send to unitialized program
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#2121 Refactor core-processor errors
  core-backend/common/src/lib.rs
  core-errors/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/lib.rs
  core-processor/src/precharge.rs
  core-processor/src/processing.rs
  gear-test/src/proc.rs
  gtest/src/manager.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D1-core

#2041 implement block_number for ActiveProgram, terminated and exited program
  common/src/benchmarking.rs
  common/src/program_storage.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-program/src/lib.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  program/src/api/storage.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A0-pleasereview

#2141 Add vesting pallet to vara runtime
  Cargo.lock
  node/cli/src/command.rs
  node/service/src/chain_spec/vara.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node

#2153 Add checking access to memory
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/syscalls.rs
  utils/wasm-gen/src/test.rs
  utils/wasm-gen/src/utils.rs
  utils/wasm-gen/src/wasm.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A2-mergeoncegreen, C1-feature, D4-test
