Repository gear-tech/gear, pull requests merged in 2023-05, with the labels that each got.

#2603 chore(cd): fix release workflow
  .github/workflows/release.yml
Labels: A0-pleasereview

#2609 chore(vara): change boot nodes to connect nodes
  node/res/vara.json
Labels: A0-pleasereview, D2-node

#2550 test(core): add `MemoryAccessManager` tests
  core-backend/common/Cargo.toml
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-backend/common/src/mock.rs
  core-backend/common/src/tests.rs
Labels: A0-pleasereview, D4-test

#2608 feat(wasm-builder, wasm-proc): use actual index of __stack_pointer global
  Cargo.lock
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/stack_end.rs
Labels: A0-pleasereview, D5-tooling

#2599 build(wasm-builder)!: Pass program build features to wasm-builder
  Cargo.lock
  examples/binaries/proxy/Cargo.toml
  examples/binaries/proxy/build.rs
  examples/binaries/proxy/src/lib.rs
  examples/binaries/sys-calls/Cargo.toml
  examples/binaries/sys-calls/build.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/README.md
  utils/wasm-builder/src/cargo_command.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, B1-releasenotes

#2525 Extend locking in the Gas Tree
  Cargo.lock
  common/Cargo.toml
  common/src/gas_provider/internal.rs
  common/src/gas_provider/lockable.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/node.rs
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  common/src/gas_provider/reservable.rs
  common/src/lib.rs
  common/src/scheduler/mod.rs
  core-errors/src/lib.rs
  gclient/src/api/calls.rs
  gsdk/src/metadata/impls.rs
  gsdk/src/metadata/mod.rs
  pallets/gas/Cargo.toml
  pallets/gas/src/lib.rs
  pallets/gas/src/migrations.rs
  pallets/gas/src/mock.rs
  pallets/gas/src/tests.rs
  pallets/gear-scheduler/src/lib.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/migrations.rs
  runtime/vara/src/migrations.rs
  scripts/check-fuzzer.sh
Labels: A0-pleasereview, A2-mergeoncegreen, D2-node, C1-feature, C2-refactoring

#2620 Bump version for new release
  Cargo.lock
  gcli/Cargo.toml
  node/cli/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen

#2625 chore(examples): Introduce feature for building examples with debug gstd
  examples/binaries/async-custom-entry/Cargo.toml
  examples/binaries/async-signal-entry/Cargo.toml
  examples/binaries/async-tester/Cargo.toml
  examples/binaries/backend-error/Cargo.toml
  examples/binaries/btree/Cargo.toml
  examples/binaries/calc-hash/in-one-block/Cargo.toml
  examples/binaries/calc-hash/over-blocks/Cargo.toml
  examples/binaries/compose/Cargo.toml
  examples/binaries/contract-template/Cargo.toml
  examples/binaries/delayed-sender/Cargo.toml
  examples/binaries/distributor/Cargo.toml
  examples/binaries/distributor/src/lib.rs
  examples/binaries/exit-handle-sender/Cargo.toml
  examples/binaries/exit-handle/Cargo.toml
  examples/binaries/exit-init/Cargo.toml
  examples/binaries/gasless-wasting/Cargo.toml
  examples/binaries/init-fail-sender/Cargo.toml
  examples/binaries/init-wait-reply-exit/Cargo.toml
  examples/binaries/init-wait/Cargo.toml
  examples/binaries/init-with-value/Cargo.toml
  examples/binaries/init-with-value/src/lib.rs
  examples/binaries/meta/Cargo.toml
  examples/binaries/mul-by-const/Cargo.toml
  examples/binaries/ncompose/Cargo.toml
  examples/binaries/new-meta/Cargo.toml
  examples/binaries/node/Cargo.toml
  examples/binaries/node/src/lib.rs
  examples/binaries/out-of-memory/Cargo.toml
  examples/binaries/program-factory/Cargo.toml
  examples/binaries/proxy-relay/Cargo.toml
  examples/binaries/proxy-reservation-with-gas/Cargo.toml
  examples/binaries/proxy-with-gas/Cargo.toml
  examples/binaries/reserve-gas/Cargo.toml
  examples/binaries/send-from-reservation/Cargo.toml
  examples/binaries/signal-entry/Cargo.toml
  examples/binaries/syscall-error/Cargo.toml
  examples/binaries/unchecked-mul/Cargo.toml
  examples/binaries/wait-timeout/Cargo.toml
  examples/binaries/wait_wake/Cargo.toml
  examples/binaries/waiter/Cargo.toml
  examples/binaries/waiting-proxy/Cargo.toml
  gclient/Cargo.toml
  gclient/tests/perf.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#2613 refactor(wasm-proc): Remove legacy meta Wasm generation
  gear-test/src/js/mod.rs
  gtest/src/program.rs
  scripts/src/build.sh
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-proc/metadata-js/test.js
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen

#2636 docs(gstd): explain message locks removing
  gstd/src/async_runtime/locks.rs
Labels: A0-pleasereview

#2627 refactor(backend-common): Avoid memory accesses on zero size reads
  Cargo.lock
  core-backend/common/Cargo.toml
  core-backend/common/src/memory.rs
  core-backend/common/src/mock.rs
  core-backend/common/src/tests.rs
  lazy-pages/src/host_func.rs
Labels: A0-pleasereview

#2642 Re-enable origins and tracks for decentralized treasury management
  runtime/vara/src/governance/mod.rs
  runtime/vara/src/governance/origins.rs
  runtime/vara/src/governance/tracks.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature

#2641 build(wasm-builder): Propagate toolchain to wasm-builder
  common/Cargo.toml
  utils/wasm-builder/src/builder_error.rs
  utils/wasm-builder/src/cargo_command.rs
  utils/wasm-builder/src/cargo_toolchain.rs
  utils/wasm-builder/src/crate_info.rs
  utils/wasm-builder/src/lib.rs
Labels: A0-pleasereview

#2647 feat(gear,vara): Add proxy and multisig pallets to both vara and gear runtimes
  Cargo.lock
  Cargo.toml
  runtime/gear/Cargo.toml
  runtime/gear/src/constants.rs
  runtime/gear/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/constants.rs
  runtime/vara/src/extensions/mod.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature

#2617 refactor(runtime): change saturating to checked in `MAXIMUM_BLOCK_WEIGHT`
  Cargo.lock
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#2626 refactor(node-loader): remove duplicate code
  utils/call-gen/src/claim_value.rs
  utils/call-gen/src/create_program.rs
  utils/call-gen/src/lib.rs
  utils/call-gen/src/send_message.rs
  utils/call-gen/src/send_reply.rs
  utils/call-gen/src/upload_code.rs
  utils/call-gen/src/upload_program.rs
  utils/node-loader/src/batch_pool/generators/batch.rs
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/src/lib.rs
Labels: A0-pleasereview

#2651 Use new approach for migrations in pallet-gear-program
  Cargo.lock
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migration.rs
  pallets/gear-program/src/mock.rs
  runtime/gear/src/migrations.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview, D2-node

#2652 build(wasm-builder): improve toolchain detection with regex
  Cargo.lock
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/cargo_toolchain.rs
Labels: A2-mergeoncegreen, E1-forcewindows, E2-forcemacos

#2633 Obsolete some spec-tests and examples
  examples/Cargo.lock
  examples/Cargo.toml
  examples/decoder/Cargo.toml
  examples/decoder/src/lib.rs
  examples/fib/Cargo.toml
  examples/fib/src/lib.rs
  examples/mem/Cargo.toml
  examples/mem/src/lib.rs
  examples/multiping/Cargo.toml
  examples/multiping/src/lib.rs
  examples/state_rollback/Cargo.toml
  examples/state_rollback/src/lib.rs
  examples/sum/Cargo.toml
  examples/sum/src/lib.rs
  examples/vec/Cargo.toml
  examples/vec/src/lib.rs
  gclient/tests/perf.rs
  gear-test/spec/test_capacitor.yaml
  gear-test/spec/test_collector.yaml
  gear-test/spec/test_decoder.yaml
  gear-test/spec/test_guestbook.yaml
  gear-test/spec/test_i32.yaml
  gear-test/spec/test_mem.yaml
  gear-test/spec/test_multiping.yaml
  gear-test/spec/test_program_id.yaml
  gear-test/spec/test_state_rollback.yaml
  gear-test/spec/test_vec.yaml
Labels: A0-pleasereview

#2655 ci(node-fuzzer): Script to run node-fuzzer in background and small fixes
  .github/workflows/build-node-fuzzer.yaml
  docker/runtime-fuzzer/Dockerfile
  docker/runtime-fuzzer/scripts/fuzzer.service
  docker/runtime-fuzzer/scripts/fuzzer.sh
Labels: A0-pleasereview

#2404 refactor(node)!: Store only first missing block in scheduler
  common/src/scheduler/mod.rs
  pallets/gear-scheduler/src/lib.rs
  pallets/gear-scheduler/src/migration.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  runtime/gear/src/migrations.rs
  runtime/vara/src/migrations.rs
Labels: A2-mergeoncegreen, D2-node

#2660 fix(ci): Update `grcov` to musl-based binary
  .github/workflows/CI.yaml
Labels: A2-mergeoncegreen

#2661 chore(spec-test): Obsolete some spec-tests and examples [2]
  Cargo.lock
  Cargo.toml
  examples/Cargo.lock
  examples/Cargo.toml
  examples/binaries/meta/Cargo.toml
  examples/binaries/meta/build.rs
  examples/binaries/meta/src/code.rs
  examples/binaries/meta/src/lib.rs
  examples/block-info/Cargo.toml
  examples/block-info/src/lib.rs
  examples/create-program/Cargo.toml
  examples/create-program/README.md
  examples/create-program/child_contract.wasm
  examples/create-program/child_contract.wat
  examples/create-program/src/lib.rs
  examples/gui-test/Cargo.toml
  examples/gui-test/src/lib.rs
  gcli/tests/cmd/program.rs
  gcli/tests/cmd/upload.rs
  gcli/tests/common/traits.rs
  gclient/Cargo.toml
  gear-test/spec/test_create_program.yaml
  gear-test/spec/test_failed_program_msg_handling.yaml
  gear-test/spec/test_gui.yaml
  gear-test/spec/test_meta.yaml
  gear-test/spec_no_runtime/test_block_info.yaml
  scripts/src/test.sh
Labels: A2-mergeoncegreen

#2656 fix(weights): tune page weights and make heuristic tests for them
  Cargo.lock
  core-processor/src/configs.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/schedule.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/tests.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/tests.rs
Labels: A0-pleasereview, D6-gas

#2535 feat(node, core): add `pay_program_rent` extrinsic/syscall
  core-backend/common/src/lib.rs
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-errors/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/handler.rs
  core-processor/src/processing.rs
  core/src/costs.rs
  core/src/env.rs
  examples/binaries/sys-calls/src/lib.rs
  gcore/src/exec.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gstd/src/exec.rs
  gsys/src/lib.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/constants.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/constants.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A2-mergeoncegreen, D1-core, D2-node, B1-releasenotes, C1-feature

#2658 test(ci): Run runtime upgrade check
  .github/workflows/CI.yaml
  pallets/gas/src/migrations.rs
  pallets/gas/src/mock.rs
  pallets/gas/src/tests.rs
  pallets/gear-program/src/migration.rs
  pallets/gear-scheduler/src/migration.rs
  pallets/gear/rpc/src/lib.rs
Labels: A2-mergeoncegreen, D5-tooling

#2669 feat(script): Add install script for *nix
  README.md
  scripts/install.sh
Labels: A0-pleasereview, D5-tooling

#2657 refactor(gcli, gsdk) : Move rpc tests from gcli to gsdk
  .github/workflows/CI.yaml
  Cargo.lock
  Cargo.toml
  Makefile
  examples/binaries/messager/Cargo.toml
  examples/binaries/messager/build.rs
  examples/binaries/messager/src/code.rs
  examples/binaries/messager/src/lib.rs
  gcli/Cargo.toml
  gcli/tests/cmd/reply.rs
  gcli/tests/cmd/send.rs
  gcli/tests/common/mod.rs
  gcli/tests/gear.rs
  gsdk/Cargo.toml
  gsdk/tests/rpc.rs
  scripts/gear.sh
  scripts/src/test.sh
Labels: A0-pleasereview

#2671 refactor(node): Add program rent parameters to metadata
  common/src/lib.rs
  pallets/airdrop/src/mock.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/payment/src/mock.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring

#2630 refactor(lazy-pages): use `LimitedStr` for global names
  core-backend/common/src/lazy_pages.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/utils.rs
  core-backend/wasmi/src/env.rs
  lazy-pages/src/globals.rs
Labels: A0-pleasereview

#2670 refactor(runtime): move heuristics from `gear` & `vara` runtimes to `runtime-common`
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/weights.rs
  runtime/gear/src/tests.rs
  runtime/vara/src/tests.rs
Labels: A0-pleasereview

#2672 feat(script): add weight unpacking tool
  scripts/unpack-weights.sh
Labels: A0-pleasereview, D5-tooling

#2676 ci(build-win-native): use symbolic link for pinning toolchain
  .github/workflows/CI.yaml
Labels: A2-mergeoncegreen

#2677 refactor(core): revert `self` mutability for `Ext` trait
  core-backend/common/src/mock.rs
  core-processor/src/ext.rs
  core/src/env.rs
  pallets/gear/src/ext.rs
Labels: A0-pleasereview

#2547 feat!: Auto replies
  Cargo.lock
  core-processor/src/processing.rs
  core/src/ids.rs
  core/src/message/context.rs
  core/src/message/incoming.rs
  core/src/message/reply.rs
  examples/Cargo.lock
  examples/Cargo.toml
  examples/binaries/program-factory/src/lib.rs
  examples/binaries/wait_wake/src/lib.rs
  examples/chat/Cargo.toml
  examples/chat/bot/Cargo.toml
  examples/chat/bot/src/lib.rs
  examples/chat/room/Cargo.toml
  examples/chat/room/src/lib.rs
  examples/chat/src/encode.rs
  examples/chat/src/lib.rs
  examples/chat/src/shared.rs
  gear-test/Cargo.toml
  gear-test/spec/test_async.yaml
  gear-test/spec/test_async_init.yaml
  gear-test/spec/test_async_multisig.yaml
  gear-test/spec/test_async_recursion.yaml
  gear-test/spec/test_async_sign.yaml
  gear-test/spec/test_chat.yaml
  gear-test/spec/test_futures_unordered.yaml
  gear-test/spec/test_incomplete_async_payloads.yaml
  gear-test/spec/test_ping.yaml
  gear-test/spec/test_rwlock.yaml
  gear-test/spec/test_status_code.yaml
  gear-test/spec/test_sync_dont_duplicate.yaml
  gear-test/spec/test_trap.yaml
  gear-test/spec/test_wait.yaml
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  utils/gear-runtime-test-cli/src/command.rs
  utils/wasm-builder/test-program/src/lib.rs
Labels: A2-mergeoncegreen, B1-releasenotes, C1-feature

#2683 chore(core): Hash the data of pausing program in two steps
  common/src/paused_program_storage.rs
Labels: A2-mergeoncegreen, D1-core, C2-refactoring

#2675 feat!: Deny replying on replies
  core-errors/src/lib.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processing.rs
  core/src/message/common.rs
  core/src/message/context.rs
  core/src/message/incoming.rs
  core/src/message/mod.rs
  core/src/message/stored.rs
  examples/binaries/async-signal-entry/src/lib.rs
  examples/binaries/async-tester/src/code.rs
  examples/binaries/async-tester/src/lib.rs
  examples/binaries/exit-init/src/lib.rs
  examples/binaries/init-fail-sender/src/lib.rs
  examples/binaries/messager/src/code.rs
  examples/binaries/program-factory/src/lib.rs
  examples/binaries/proxy/src/lib.rs
  examples/binaries/reserve-gas/Cargo.toml
  examples/binaries/reserve-gas/src/lib.rs
  examples/binaries/signal-entry/src/lib.rs
  examples/binaries/sys-calls/src/lib.rs
  examples/binaries/wait_wake/Cargo.toml
  examples/binaries/wait_wake/src/lib.rs
  gclient/tests/upload.rs
  gear-test/spec/test_async_init.yaml
  gear-test/spec/test_async_multisig.yaml
  gear-test/spec/test_program_generator.yaml
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D1-core, D2-node, B1-releasenotes, C1-feature

#2685 ci: bump `codecov/codecov-action` to `v3`
  .github/workflows/CI.yaml
Labels: A2-mergeoncegreen

#2687 feat!: Deny replies with delay
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-processor/src/ext.rs
  core/src/env.rs
  core/src/message/context.rs
  examples/binaries/delayed-sender/src/code.rs
  examples/binaries/send-from-reservation/src/lib.rs
  examples/binaries/sys-calls/src/lib.rs
  gcore/src/msg.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  gsys/src/lib.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D1-core, D2-node, B1-releasenotes

#2679 refactor(fuzzer): Migrate mutation tests from `mutagen` to a more stable `fail` crate
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/src/gas_provider/internal.rs
  pallets/gear/Cargo.toml
  scripts/check-fuzzer.sh
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#2662 fix(pallet-gear): Fix infinite loop in calculate_gas rpc
  examples/binaries/reserve-gas/src/lib.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen

#2689 feat(demo): Introduce `demo-constructor`
  Cargo.lock
  Cargo.toml
  examples/binaries/constructor/Cargo.toml
  examples/binaries/constructor/build.rs
  examples/binaries/constructor/src/arg.rs
  examples/binaries/constructor/src/builder.rs
  examples/binaries/constructor/src/call.rs
  examples/binaries/constructor/src/lib.rs
  examples/binaries/constructor/src/scheme/mod.rs
  examples/binaries/constructor/src/wasm.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen
