Repository gear-tech/gear, pull requests merged in 2023-07, with the labels that each got.

#2889 chore(spec-test): Obsolete some spec-tests and examples [3]
  .github/workflows/CI.yaml
  Cargo.lock
  Cargo.toml
  Makefile
  examples/Cargo.lock
  examples/Cargo.toml
  examples/binaries/capacitor/Cargo.toml
  examples/binaries/capacitor/build.rs
  examples/binaries/capacitor/src/lib.rs
  examples/binaries/constructor/src/builder.rs
  examples/binaries/constructor/src/call.rs
  examples/binaries/program-generator/Cargo.toml
  examples/binaries/program-generator/build.rs
  examples/binaries/program-generator/src/lib.rs
  examples/binaries/wait/Cargo.toml
  examples/binaries/wait/build.rs
  examples/binaries/wait/src/lib.rs
  examples/binaries/wat/Cargo.toml
  examples/binaries/wat/spec/inf_recursion.wat
  examples/binaries/wat/spec/large_scheduled.wat
  examples/binaries/wat/spec/read_access.wat
  examples/binaries/wat/spec/read_write_access.wat
  examples/binaries/wat/spec/wrong_load.wat
  examples/binaries/wat/src/lib.rs
  examples/capacitor/Cargo.toml
  examples/capacitor/src/lib.rs
  examples/loop/Cargo.toml
  examples/loop/src/lib.rs
  examples/panicker/src/lib.rs
  examples/program_generator/child_contract.wasm
  examples/program_generator/src/lib.rs
  examples/status-code/src/lib.rs
  examples/wait/Cargo.toml
  examples/wait/src/lib.rs
  gclient/Cargo.toml
  gclient/tests/keyhasher.rs
  gclient/tests/loop.rs
  gclient/tests/memory_dump.rs
  gclient/tests/upload.rs
  gear-test/spec/test_program_generator.yaml
  gear-test/spec/test_status_code.yaml
  gear-test/spec/test_wait.yaml
  gear-test/wat-spec/read_access.yaml
  gear-test/wat-spec/read_write_access.yaml
  gtest/Cargo.toml
  gtest/src/program.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
  scripts/ci_build.sh
  scripts/gear.sh
  scripts/src/build.sh
Labels: A2-mergeoncegreen, D4-test

#2893 commemorate: R.I.P. `gear-test`
  .github/workflows/CI.yaml
  .github/workflows/test-measurements.yaml
  Cargo.lock
  Cargo.toml
  Makefile
  examples/README.md
  gear-test/Cargo.toml
  gear-test/README.md
  gear-test/spec/test_async_multisig.yaml
  gear-test/spec/test_async_sign.yaml
  gear-test/src/address.rs
  gear-test/src/check.rs
  gear-test/src/js/decode.js
  gear-test/src/js/encode.js
  gear-test/src/js/mod.rs
  gear-test/src/js/package-lock.json
  gear-test/src/js/package.json
  gear-test/src/lib.rs
  gear-test/src/main.rs
  gear-test/src/manager.rs
  gear-test/src/proc.rs
  gear-test/src/sample.rs
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/command.rs
  scripts/ci_build.sh
  scripts/gear.sh
  scripts/performance-check.sh
  scripts/src/build.sh
  scripts/src/coverage.sh
  scripts/src/init.sh
  scripts/src/test.sh
  utils/gear-runtime-test-cli/Cargo.toml
  utils/gear-runtime-test-cli/src/command.rs
  utils/gear-runtime-test-cli/src/lib.rs
  utils/gear-runtime-test-cli/src/util.rs
  utils/wasm-proc/metadata-js/index.js
  utils/wasm-proc/metadata-js/package-lock.json
  utils/wasm-proc/metadata-js/package.json
  utils/wasm-proc/metadata-js/test.js
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen

#2872 test(pallet-gear): handling gas allowance exceed works correctly
  pallets/gear-messenger/src/tests.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D4-test

#2900 fix(wasm-builder): remove limit on generated files
  utils/wasm-builder/src/smart_fs.rs
Labels: A0-pleasereview, B1-releasenotes, D5-tooling

#2898 fix(scripts): now `weight-diff.sh` can compare branches with `/`
  scripts/weight-diff.sh
Labels: A2-mergeoncegreen

#2899 chore(test): Disable path remap in measurements CI
  .github/workflows/test-measurements.yaml
Labels: A2-mergeoncegreen, D4-test

#2903 chore(ci): Remove deploy step of runtime tests
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview, D4-test

#2906 fix(gstd): Fix deadlocks in mutex/rw-lock
  examples/binaries/waiter/src/code.rs
  examples/binaries/waiter/src/lib.rs
  gstd/src/lock/access.rs
  gstd/src/lock/mutex.rs
  gstd/src/lock/rwlock.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#2913 chore(gcli): Change gh url
  gcli/src/template.rs
Labels: A2-mergeoncegreen, D4-test

#2918 chore(runtime): Remove executed migrations
  runtime/gear/src/migrations.rs
Labels: A0-pleasereview

#2908 refactor(core-errors): Remove `SyscallUsage` error
  core-errors/src/lib.rs
  examples/binaries/reserve-gas/src/lib.rs
  examples/binaries/signal-entry/src/lib.rs
  examples/binaries/syscall-error/src/lib.rs
  gcore/src/errors.rs
  gcore/src/msg.rs
  gcore/src/prog.rs
  gcore/src/utils.rs
  gstd/src/common/errors.rs
  gstd/src/msg/basic.rs
Labels: A0-pleasereview, D1-core

#2922 feat(wasm-builder): Don't track features in wasm-builder via env var
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, D5-tooling

#2892 refactor(core-backend): Refactor `MemoryError`
  core-backend/common/src/funcs.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-backend/common/src/mock.rs
  core-backend/common/src/runtime.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/memory.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-backend/wasmi/src/memory.rs
  core-backend/wasmi/src/runtime.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processing.rs
  core/src/memory.rs
  pallets/gear/src/ext.rs
Labels: A0-pleasereview, D1-core

#2925 refactor(sandbox): Use new temporary directory for wasmer caches for each new node process
  Cargo.lock
  sandbox/host/Cargo.toml
  sandbox/host/src/sandbox/wasmer_backend.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#2926 fix(rpc-fns): Read state gas limit restrictions
  Cargo.lock
  Cargo.toml
  core-processor/src/executor.rs
  examples/binaries/read-big-state/Cargo.toml
  examples/binaries/read-big-state/build.rs
  examples/binaries/read-big-state/src/lib.rs
  gcli/src/meta/mod.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#2917 ci: Speed up tests by giving correct arguments
  .github/workflows/CI.yaml
  Makefile
  gclient/tests/memory_dump.rs
  scripts/ci_build.sh
  scripts/src/test.sh
Labels: A0-pleasereview

#2761 docs(gmeta): add documentation for `gmeta` crate
  Cargo.lock
  gmeta/Cargo.toml
  gmeta/codegen/src/lib.rs
  gmeta/src/lib.rs
  scripts/src/format.sh
Labels: A0-pleasereview

#2673 refactor(pallet-gear): Rewrite alloc benchmark with more common way
  core-backend/common/src/funcs.rs
  core-backend/sandbox/src/lib.rs
  core-backend/sandbox/src/memory.rs
  core/src/costs.rs
  core/src/gas.rs
  gsdk/src/metadata/generated.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/tests.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring

#2939 ci: Fix check after md-rewrite-alloc-benchmark merge
  core-backend/sandbox/src/memory.rs
Labels: A0-pleasereview

#2915 feat(gstd): add feature `panic-handler`
  gstd/Cargo.toml
  gstd/src/common/handlers.rs
  gstd/src/common/mod.rs
  gstd/src/macros/bail.rs
  gstd/src/macros/debug.rs
Labels: A0-pleasereview

#2744 feat(gsdk): unlock all calls and storage queries
  Cargo.lock
  Cargo.toml
  gsdk/Cargo.toml
  gsdk/api-gen/Cargo.toml
  gsdk/api-gen/src/main.rs
  gsdk/src/lib.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/metadata/mod.rs
  gsdk/src/signer/calls.rs
  gsdk/src/signer/utils.rs
  gsdk/src/storage.rs
  gsdk/src/utils.rs
  node/cli/Cargo.toml
  rustfmt.toml
Labels: A0-pleasereview

#2758 fix(core-backend): continue to adopt `LimitedStr`
  common/lazy-pages/src/lib.rs
  core-backend/common/src/lazy_pages.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/utils.rs
  core-backend/wasmi/src/env.rs
  core-processor/src/common.rs
  lazy-pages/src/common.rs
  lazy-pages/src/globals.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/tests.rs
  pallets/gear/src/tests.rs
  runtime-interface/src/lib.rs
Labels: A2-mergeoncegreen, C2-refactoring

#2916 fix(gstd): Allow mutex/read/write lock guard access by holder only
  Cargo.lock
  examples/binaries/waiter/Cargo.toml
  examples/binaries/waiter/src/code.rs
  examples/binaries/waiter/src/lib.rs
  examples/binaries/waiter/tests/mx_lock_access.rs
  examples/binaries/waiter/tests/rw_lock_access.rs
  examples/binaries/waiter/tests/utils.rs
  gstd/src/lock/mutex.rs
  gstd/src/lock/rwlock.rs
  gtest/src/system.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#2943 fix(rpc-fns): Fix bug with `calculate_gas` returning block gas limit
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  pallets/gas/src/tests.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen

#2930 chore: Clean up for latest merged PRs
  core-processor/src/executor.rs
  examples/binaries/read-big-state/src/lib.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  scripts/src/test.sh
Labels: A0-pleasereview

#2928 chore(gear,vara): Update weights
  examples/binaries/async-custom-entry/src/lib.rs
  examples/binaries/signal-entry/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/weights/frame_system.rs
  runtime/gear/src/weights/pallet_balances.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/gear/src/weights/pallet_gear_voucher.rs
  runtime/gear/src/weights/pallet_timestamp.rs
  runtime/gear/src/weights/pallet_utility.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
Labels: A0-pleasereview, D2-node

#2724 feat(tests, cli): CLI tool for executing blocks against the live chain state
  Cargo.lock
  Cargo.toml
  Makefile
  pallets/gear-voucher/Cargo.toml
  scripts/gear.sh
  scripts/src/build.sh
  utils/gear-replay-cli/Cargo.toml
  utils/gear-replay-cli/README.md
  utils/gear-replay-cli/src/main.rs
  utils/gear-replay-cli/src/parse.rs
  utils/gear-replay-cli/src/util.rs
Labels: A0-pleasereview, C1-feature, D5-tooling

#2947 Add original code storage api to sdk and gclient
  gclient/src/api/calls.rs
  gsdk/src/storage.rs
  gsdk/tests/rpc.rs
Labels: A0-pleasereview

#2902 perf(wasm-builder): invert path remapping logic
  .github/workflows/test-measurements.yaml
  utils/wasm-builder/src/lib.rs
Labels: A0-pleasereview

#2951 refactor(examples): inherit crates from workspace
  examples/async-custom-entry/Cargo.toml
  examples/async-signal-entry/Cargo.toml
  examples/async-signal-entry/src/lib.rs
  examples/async-tester/Cargo.toml
  examples/async-tester/src/lib.rs
  examples/btree/Cargo.toml
  examples/btree/src/lib.rs
  examples/calc-hash/Cargo.toml
  examples/calc-hash/in-one-block/Cargo.toml
  examples/calc-hash/in-one-block/src/lib.rs
  examples/calc-hash/over-blocks/Cargo.toml
  examples/calc-hash/over-blocks/src/lib.rs
  examples/calc-hash/src/lib.rs
  examples/distributor/Cargo.toml
  examples/distributor/src/lib.rs
  examples/messager/Cargo.toml
  examples/node/Cargo.toml
  examples/node/src/lib.rs
  examples/program-factory/Cargo.toml
  examples/program-factory/src/lib.rs
  examples/proxy-relay/Cargo.toml
  examples/proxy-relay/src/lib.rs
  examples/proxy-reservation-with-gas/Cargo.toml
  examples/proxy-reservation-with-gas/src/lib.rs
  examples/proxy/Cargo.toml
  examples/proxy/src/lib.rs
  examples/reservation-manager/Cargo.toml
  examples/send-from-reservation/Cargo.toml
  examples/send-from-reservation/src/lib.rs
  examples/sys-calls/Cargo.toml
  examples/sys-calls/src/lib.rs
  examples/syscall-error/Cargo.toml
  examples/wait-timeout/Cargo.toml
  examples/wait-timeout/src/lib.rs
  examples/waiter/Cargo.toml
  examples/waiter/src/lib.rs
Labels: A0-pleasereview, C2-refactoring

#2950 chore: Exclude weight files from stats
  .gitattributes
Labels: A0-pleasereview, D5-tooling

#2956 ci: Add missing cargo init step
  .github/workflows/CI.yaml
Labels: A2-mergeoncegreen

#2955 chore(gclient): improve `get_state` test
  gclient/tests/state.rs
Labels: A0-pleasereview

#2954 refactor(sandbox-host): Remove unnecessary 'host-sandbox' feature
  core-backend/sandbox/Cargo.toml
  lazy-pages/Cargo.toml
  runtime-interface/Cargo.toml
  runtime-interface/src/gear_sandbox/detail.rs
  sandbox/host/Cargo.toml
  sandbox/host/src/sandbox.rs
  sandbox/sandbox/Cargo.toml
  sandbox/sandbox/src/lib.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#2973 feat(wasm-builder): Set optimisation params
  examples/fungible-token/src/contract.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, D5-tooling, D7-performance

#2966 refactor(common): move LockId to gear-core
  Cargo.lock
  common/src/gas_provider/lockable.rs
  core/Cargo.toml
  core/src/gas.rs
  gclient/Cargo.toml
  gclient/src/api/calls.rs
Labels: A0-pleasereview

#2963 feat(gsdk): allow transaction retracted
  gsdk/src/signer/calls.rs
  gsdk/src/signer/mod.rs
Labels: A0-pleasereview

#2964 chore(ft-benchmarks): fix wrong path and set PRNG seed
  examples/fungible-token/tests/benchmarks.rs
Labels: A2-mergeoncegreen

#2961 chore(deps): bump parity-scale-codec to 3.6.4
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview

#2919 test(core-processor): Add tests for send message limit
  core-processor/src/ext.rs
Labels: A0-pleasereview, D1-core, D4-test

#2976 feat(wasm-builder,wasm-opt): use only mvp features, enable sign-ext
  utils/wasm-builder/src/optimize.rs
Labels: A0-pleasereview, D5-tooling

#2974 Put `*.meta.txt`s in the `target` directory along with WASMs
  gcli/tests/cmd/program.rs
  gcli/tests/common/env.rs
  gcli/tests/gear.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, C2-refactoring, D5-tooling

#2985 ci(win-native): Remove cachepot as rustc_wrapper for build-win-native
  .github/workflows/CI.yaml
Labels: A0-pleasereview, D5-tooling

#2995 feat(weights-diff): Add memory weights
  scripts/weight-diff.sh
  utils/weight-diff/src/main.rs
Labels: A2-mergeoncegreen, C1-feature, D5-tooling

#3001 update CI
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#3003 fix(ci): Disable cachepot in win build
  .github/workflows/CI.yaml
Labels: A0-pleasereview
