Repository gear-tech/gear, pull requests merged in 2023-08, with the labels that each got.

#3009 Test sending message to terminated program from program
  examples/constructor/src/builder.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node, D4-test

#2897 feat(gtest): add support of reply code to `Log`
  gtest/src/log.rs
  gtest/src/mailbox.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A0-pleasereview, B1-releasenotes, D5-tooling

#2982 refactoring(wasm-gen): Introduce general generator and memory generator.
  utils/wasm-gen/src/generator.rs
  utils/wasm-gen/src/generator/memory.rs
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/memory.rs
  utils/wasm-gen/src/wasm.rs
Labels: A0-pleasereview, D5-tooling

#3013 fix std feature in gear-wasm-instrument
  utils/wasm-instrument/Cargo.toml
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview

#3004 feat(ci): run time consuming tests using github action
  .github/workflows/time-consuming-tests.yml
  scripts/gear.sh
  scripts/src/test.sh
Labels: A0-pleasereview

#3016 test(wasm-gen): Comment `test_gen_reproduction` until upcoming fix
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#3020 test(pallet-gear): Test pause program task removed for terminated program
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D2-node, D4-test

#3032 feat(node): don't set logger hook if custom log is present
  node/cli/src/command.rs
Labels: A0-pleasereview

#2948 perf(gas)!: Merge two globals into one
  Cargo.lock
  common/lazy-pages/src/lib.rs
  core-backend/common/src/funcs.rs
  core-backend/common/src/lazy_pages.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-backend/common/src/mock.rs
  core-backend/common/src/runtime.rs
  core-backend/common/src/tests.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-backend/wasmi/src/runtime.rs
  core-backend/wasmi/src/state.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/gas.rs
  lazy-pages/src/common.rs
  lazy-pages/src/globals.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/signal.rs
  lazy-pages/src/tests.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime-interface/src/lib.rs
  runtime/gear/src/tests.rs
  runtime/gear/src/weights/frame_system.rs
  runtime/gear/src/weights/pallet_balances.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/gear/src/weights/pallet_gear_voucher.rs
  runtime/gear/src/weights/pallet_timestamp.rs
  runtime/gear/src/weights/pallet_utility.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
  utils/wasm-instrument/Cargo.toml
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/syscalls.rs
  utils/wasm-instrument/src/tests.rs
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen, B1-releasenotes, D6-gas, D7-performance

#3024 fix(gtest): catch panic reply in RunResult
  gtest/src/log.rs
Labels: A0-pleasereview, B1-releasenotes

#3022 refactor(wasm-gen): Introduce generators for gear entry points and sys-calls
  utils/call-gen/src/lib.rs
  utils/call-gen/src/upload_code.rs
  utils/call-gen/src/upload_program.rs
  utils/node-loader/src/batch_pool/generators/batch.rs
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/src/lib.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/generator.rs
  utils/wasm-gen/src/generator/entry_points.rs
  utils/wasm-gen/src/generator/memory.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/memory.rs
  utils/wasm-gen/src/syscalls.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-gen/src/utils.rs
  utils/wasm-gen/src/wasm.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A2-mergeoncegreen, C2-refactoring, D5-tooling

#3036 refactor(wasm-gen): Avoid inserting sys-calls into custom `send_from_reservation` function
  utils/wasm-gen/src/generator.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
Labels: A0-pleasereview, D5-tooling

#2959 ci(PR): introduce new workflow PR
  .github/workflows/CI.yaml
  .github/workflows/PR.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
Labels: A0-pleasereview, A2-mergeoncegreen, E2-forcemacos

#3039 feat(wasm-gen): Introduce config for always valid gear wasm generation
  Cargo.lock
  utils/call-gen/src/claim_value.rs
  utils/call-gen/src/create_program.rs
  utils/call-gen/src/lib.rs
  utils/call-gen/src/send_message.rs
  utils/call-gen/src/send_reply.rs
  utils/call-gen/src/upload_code.rs
  utils/call-gen/src/upload_program.rs
  utils/node-loader/src/batch_pool/generators/batch.rs
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/src/lib.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/generator.rs
  utils/wasm-gen/src/config/module.rs
  utils/wasm-gen/src/generator/memory.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-gen/src/wasm.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#3045 fix(gstd): log the panic message for the debugging convenience
  gstd/src/common/handlers.rs
Labels: A0-pleasereview, D3-gstd, C0-bug

#3043 fix calc gas: enable process queue before calculation
  pallets/gear/src/lib.rs
  pallets/gear/src/runtime_api.rs
Labels: A0-pleasereview

#3046 ci(build): remove sccache status in win-cross
  .github/workflows/build.yml
Labels: A0-pleasereview

#2979 feat(gsdk): introduce events API
  Cargo.lock
  common/src/paused_program_storage.rs
  core/src/code.rs
  examples/constructor/src/call.rs
  gclient/src/api/calls.rs
  gclient/src/api/listener/iterator.rs
  gclient/src/api/listener/subscription.rs
  gclient/src/api/rpc.rs
  gmeta/codegen/src/lib.rs
  gsdk/src/api.rs
  gsdk/src/lib.rs
  gsdk/src/result.rs
  gsdk/src/rpc.rs
  gsdk/src/signer/calls.rs
  gsdk/src/signer/rpc.rs
  gsdk/src/signer/utils.rs
  gsdk/src/storage.rs
  gsdk/src/subscription.rs
  gsdk/src/types.rs
  node/service/src/rpc/runtime_info.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/runtime_api.rs
  utils/validator-checks/Cargo.toml
  utils/validator-checks/src/listener.rs
  utils/wasm-builder/src/stack_end.rs
Labels: A0-pleasereview

#3054 chore(wasm-instrument): replace wasm-instrument with gwasm-instrument
  Cargo.lock
  Cargo.toml
  utils/wasm-instrument/Cargo.toml
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/rules.rs
Labels: A0-pleasereview

#3049 ci(build): make workflow build dispatchable
  .github/workflows/build.yml
Labels: A0-pleasereview

#3066 chore(ci): remove missing label in `combined-dependabot.yml`
  .github/workflows/combined-dependabot.yml
Labels: A0-pleasereview

#3044 test(wasm-gen): Make deterministic wasm generation
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#2975 feat: use `alloca` for stack allocations
  Cargo.lock
  Cargo.toml
  gcore/Cargo.toml
  gcore/src/lib.rs
  gcore/src/msg.rs
  gcore/src/stack_buffer.rs
  gstd/src/msg/encoded.rs
  stack-buffer/Cargo.toml
  stack-buffer/alloca/README.md
  stack-buffer/alloca/alloca.c
  stack-buffer/alloca/libcalloca.a
  stack-buffer/build.rs
  stack-buffer/src/lib.rs
Labels: A0-pleasereview, D3-gstd

#3041 feat(manifest): complete the manifest of all published libraries
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/codegen/Cargo.toml
  core-backend/codegen/Cargo.toml
  core-backend/common/Cargo.toml
  core-backend/wasmi/Cargo.toml
  core-errors/Cargo.toml
  core-processor/Cargo.toml
  core/Cargo.toml
  gcli/Cargo.toml
  gclient/Cargo.toml
  gmeta/Cargo.toml
  gmeta/codegen/Cargo.toml
  gsdk/Cargo.toml
  gsdk/codegen/Cargo.toml
  gsys/Cargo.toml
  utils/wasm-instrument/Cargo.toml
Labels: A0-pleasereview

#2969 refactor(sandbox-host): Process wasm-globals on wasmer side
  Cargo.lock
  core-backend/codegen/src/host.rs
  core-backend/common/src/funcs.rs
  core-backend/common/src/runtime.rs
  core-backend/sandbox/Cargo.toml
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-backend/wasmi/src/runtime.rs
  pallets/gear/src/weights.rs
  runtime-interface/src/gear_sandbox/detail.rs
  runtime-interface/src/gear_sandbox/mod.rs
  runtime/gear/src/weights/frame_system.rs
  runtime/gear/src/weights/pallet_balances.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/gear/src/weights/pallet_gear_voucher.rs
  runtime/gear/src/weights/pallet_timestamp.rs
  runtime/gear/src/weights/pallet_utility.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_airdrop.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
  sandbox/env/Cargo.toml
  sandbox/env/src/lib.rs
  sandbox/host/src/sandbox.rs
  sandbox/host/src/sandbox/wasmer_backend.rs
  sandbox/sandbox/src/embedded_executor.rs
  sandbox/sandbox/src/host_executor.rs
  sandbox/sandbox/src/lib.rs
  utils/wasm-instrument/src/lib.rs
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen, D2-node, B1-releasenotes, D7-performance

#3055 feat(manifest): trim manifest with wildcard
  Cargo.toml
Labels: A0-pleasereview

#3068 refactor(sandbox): Extract dispatch_common function in wasmer backend
  sandbox/host/src/sandbox/wasmer_backend.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#3077 fix(runtime-fuzzer): fix overflowing gas limit
  utils/runtime-fuzzer/src/lib.rs
Labels: A0-pleasereview

#3082 Implement `Arbitrary` for the set of `GearCall`s
  Cargo.lock
  utils/call-gen/Cargo.toml
  utils/call-gen/src/arbitrary_call.rs
  utils/call-gen/src/lib.rs
  utils/node-loader/src/batch_pool/generators/batch.rs
  utils/node-loader/src/utils.rs
  utils/runtime-fuzzer/fuzz/Cargo.toml
  utils/runtime-fuzzer/src/lib.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/generator.rs
  utils/wasm-gen/src/config/module.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/generator.rs
  utils/wasm-gen/src/generator/entry_points.rs
  utils/wasm-gen/src/generator/memory.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-gen/src/wasm.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3007 feat(gstd): propagate stack allocations
  examples/btree/src/lib.rs
  examples/fungible-token/io/src/lib.rs
  examples/fungible-token/src/contract.rs
  examples/stack-allocations/src/lib.rs
  gcore/src/lib.rs
  gstd/src/lib.rs
  gstd/src/msg/encoded.rs
  gstd/src/prelude.rs
  gstd/src/prog/encoded.rs
  gstd/src/prog/generator.rs
  gstd/src/util.rs
Labels: A0-pleasereview, D3-gstd

#3090 chore(gcli): change the timeout ms from 10 to 1 in tests
  gcli/tests/gear.rs
Labels: A0-pleasereview

#3080 fix UB in queue multiplier
  pallets/payment/src/lib.rs
Labels: A0-pleasereview, C0-bug

#3098 chore: fix links in README
  README.md
Labels: A0-pleasereview

#3059 feat!: append payload in `read_state` rpc call
  Cargo.lock
  Cargo.toml
  examples/backend-error/Cargo.toml
  examples/backend-error/build.rs
  examples/btree/Cargo.toml
  examples/capacitor/build.rs
  examples/capacitor/src/lib.rs
  examples/custom/Cargo.toml
  examples/custom/build.rs
  examples/custom/src/backend_error.rs
  examples/custom/src/btree.rs
  examples/custom/src/capacitor.rs
  examples/custom/src/lib.rs
  examples/fungible-token/io/src/lib.rs
  examples/fungible-token/src/contract.rs
  examples/gas-burned/src/lib.rs
  examples/new-meta/io/src/lib.rs
  gcli/src/cmd/program.rs
  gcli/src/meta/mod.rs
  gcli/src/meta/tests.rs
  gcli/tests/cmd/program.rs
  gclient/Cargo.toml
  gclient/src/api/rpc.rs
  gclient/tests/backend.rs
  gclient/tests/memory_dump.rs
  gclient/tests/state.rs
  gmeta/src/lib.rs
  gsdk/src/rpc.rs
  gtest/Cargo.toml
  gtest/src/program.rs
  pallets/gear/Cargo.toml
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  runtime/common/src/apis.rs
Labels: A2-mergeoncegreen

#3110 feat(cli): Add node CLI arg to set max block gas value
  Cargo.lock
  gsdk/src/metadata/generated.rs
  node/authorship/Cargo.toml
  node/authorship/src/authorship.rs
  node/authorship/src/block_builder.rs
  node/authorship/src/tests.rs
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/lib.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/src/benchmarking/tests/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/mock.rs
  runtime/common/src/apis.rs
  runtime/vara/src/integration_tests.rs
Labels: A0-pleasereview, D2-node, C1-feature

#3083 refactor(node): Get rid of redundant `_with_voucher` extrinsics
  examples/fungible-token/tests/benchmarks.rs
  gcli/src/cmd/reply.rs
  gcli/src/cmd/send.rs
  gclient/src/api/calls.rs
  gclient/tests/memory_dump.rs
  gclient/tests/node.rs
  gclient/tests/state.rs
  gclient/tests/upload.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/metadata/impls.rs
  gsdk/src/signer/calls.rs
  gsdk/tests/rpc.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  pallets/payment/src/lib.rs
  pallets/payment/src/mock.rs
  pallets/payment/src/tests.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/call-gen/src/arbitrary_call.rs
  utils/call-gen/src/send_message.rs
  utils/call-gen/src/send_reply.rs
  utils/runtime-fuzzer/src/lib.rs
Labels: A0-pleasereview, D2-node, C2-refactoring, B2-breaking-apis

#3102 feat(runtime-fuzzer): Introduce "precise" `runtime-fuzzer`
  Cargo.lock
  Cargo.toml
  scripts/check-fuzzer.sh
  scripts/src/test.sh
  utils/call-gen/Cargo.toml
  utils/call-gen/src/lib.rs
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/fuzz/fuzz_targets/main.rs
  utils/runtime-fuzzer/src/arbitrary_call.rs
  utils/runtime-fuzzer/src/bin/reproduce_fuzz.rs
  utils/runtime-fuzzer/src/lib.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/lib.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#3035 refactoring(gsdk): structure gsdk API
  gcli/src/cmd/claim.rs
  gcli/src/cmd/create.rs
  gcli/src/cmd/reply.rs
  gcli/src/cmd/send.rs
  gcli/src/cmd/transfer.rs
  gcli/src/cmd/upload.rs
  gclient/src/api/calls.rs
  gclient/src/api/rpc.rs
  gsdk/src/signer/calls.rs
  gsdk/src/signer/mod.rs
  gsdk/src/signer/rpc.rs
  gsdk/src/signer/utils.rs
  gsdk/tests/rpc.rs
Labels: A0-pleasereview

#3070 ci(label): trigger workflows on labelling
  .github/actions/label/build.js
  .github/workflows/build-macos.yml
  .github/workflows/build.yml
  .github/workflows/label.yml
Labels: A0-pleasereview

#3118 fix(authorship): Forward-fix a test that will require the gear-bank account to exist
  Cargo.lock
  node/authorship/Cargo.toml
  node/authorship/src/tests.rs
Labels: A0-pleasereview, D2-node, C0-bug, D4-test

#3085 refactor(node): Terminate the program in RemoveFromWaitlist task for init-message
  examples/constructor/src/scheme/demo_wait_init_exit_reply.rs
  examples/constructor/src/scheme/mod.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring

#3117 test(runtime-fuzzer): Test that `GearCalls` generation is deterministic
  .github/workflows/check.yml
  Cargo.lock
  scripts/gear.sh
  scripts/src/test.sh
  utils/call-gen/src/claim_value.rs
  utils/call-gen/src/create_program.rs
  utils/call-gen/src/lib.rs
  utils/call-gen/src/send_message.rs
  utils/call-gen/src/send_reply.rs
  utils/call-gen/src/upload_code.rs
  utils/call-gen/src/upload_program.rs
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/src/arbitrary_call.rs
  utils/runtime-fuzzer/src/lib.rs
  utils/runtime-fuzzer/src/tests.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3086 refactor: Introduce ActorSystemError
  Cargo.lock
  Cargo.toml
  core-backend/common/Cargo.toml
  core-backend/common/src/lib.rs
  core-processor/Cargo.toml
  core-processor/src/common.rs
  core-processor/src/executor.rs
  utils/actor-system-error/Cargo.toml
  utils/actor-system-error/src/lib.rs
Labels: A0-pleasereview, D1-core, D2-node

#3124 fix(backend): Remove strings from environment variant
  core-processor/src/common.rs
  core-processor/src/executor.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#3125 ci(sccache): Remove `RUSTC_WRAPPER`
  .github/workflows/build.yml
  .github/workflows/check.yml
  docker/build.sh
Labels: A0-pleasereview

#3136 feat(wasm-proc): Make sensible error-reporting on runtime imports check
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview

#1881 Vara stage 2: Rolling changes
  Cargo.lock
  Cargo.toml
  _typos.toml
  gsdk/build.rs
  gsdk/src/metadata/generated.rs
  node/service/src/chain_spec/vara.rs
  node/testing/src/genesis.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/bag_thresholds.rs
  runtime/vara/src/governance/fellowship.rs
  runtime/vara/src/governance/mod.rs
  runtime/vara/src/lib.rs
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen

#3139 feat: check runtime imports in `make pre-commit`
  Makefile
  scripts/gear.sh
  scripts/src/check.sh
Labels: A0-pleasereview

#3143 refactor(gstd-codegen): use fully qualified paths
  gstd/codegen/src/lib.rs
  gstd/codegen/src/utils.rs
  gstd/src/msg/async.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  gstd/src/prog/basic.rs
  gstd/src/prog/encoded.rs
  gstd/src/prog/generator.rs
Labels: A2-mergeoncegreen, C2-refactoring

#3144 feat(docs): generate link to definition
  Makefile
Labels: A0-pleasereview

#3147 chore(node): Update staging spec
  node/res/staging.json
Labels: A0-pleasereview, D2-node

#3145 chore: Version 0.3.0 / 300 in master
  Cargo.lock
  Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#3047 refactor(gstd): align gstd reexports & prelude items with `std`
  examples/async/src/lib.rs
  examples/calc-hash/over-blocks/src/code.rs
  examples/constructor/src/wasm.rs
  examples/custom/src/btree.rs
  examples/custom/src/capacitor.rs
  examples/distributor/src/lib.rs
  examples/fungible-token/io/src/lib.rs
  examples/init-wait/src/code.rs
  examples/program-generator/src/lib.rs
  examples/rwlock/src/lib.rs
  examples/wait_wake/src/lib.rs
  examples/waiter/src/code.rs
  gmeta/codegen/src/lib.rs
  gstd/codegen/src/lib.rs
  gstd/src/async_runtime/locks.rs
  gstd/src/lib.rs
  gstd/src/macros/debug.rs
  gstd/src/prelude.rs
  gstd/src/sync/access.rs
  gstd/src/sync/mod.rs
  gstd/src/sync/mutex.rs
  gstd/src/sync/rwlock.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D3-gstd, C2-refactoring

#2994 refactor(runtime-interface): Serialize `MemoryInterval`, remove `GasLeft`
  Cargo.lock
  Cargo.toml
  common/lazy-pages/Cargo.toml
  common/lazy-pages/src/lib.rs
  core-backend/common/Cargo.toml
  core-backend/common/src/lazy_pages.rs
  core-backend/common/src/memory.rs
  core/Cargo.toml
  core/src/memory.rs
  lazy-pages/src/common.rs
  lazy-pages/src/globals.rs
  lazy-pages/src/host_func.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/process.rs
  lazy-pages/src/signal.rs
  lazy-pages/src/tests.rs
  pallets/gear/src/weights.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/lib.rs
  runtime/gear/src/tests.rs
  runtime/gear/src/weights/frame_system.rs
  runtime/gear/src/weights/pallet_balances.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/gear/src/weights/pallet_gear_voucher.rs
  runtime/gear/src/weights/pallet_timestamp.rs
  runtime/gear/src/weights/pallet_utility.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_airdrop.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview, D1-core, D2-node, D6-gas, D7-performance

#3161 fix(gsdk): update test after the node upgrade
  gsdk/tests/rpc.rs
Labels: A0-pleasereview

#3159 refactor(wasm-gen): Remove prints from `gear-wasm-gen`
  utils/runtime-fuzzer/fuzz/fuzz_targets/main.rs
  utils/runtime-fuzzer/src/arbitrary_call.rs
  utils/runtime-fuzzer/src/lib.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/lib.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3052 feat!(runtime): Introduce `pallet-gear-bank`
  .github/workflows/check.yml
  Cargo.lock
  Cargo.toml
  common/src/gas_provider/node.rs
  common/src/lib.rs
  gclient/src/api/calls.rs
  gclient/src/api/storage/mod.rs
  gclient/src/utils.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/signer/calls.rs
  gsdk/src/storage.rs
  node/service/src/chain_spec/gear.rs
  node/service/src/chain_spec/vara.rs
  pallets/airdrop/Cargo.toml
  pallets/airdrop/src/benchmarking.rs
  pallets/airdrop/src/lib.rs
  pallets/airdrop/src/mock.rs
  pallets/airdrop/src/tests.rs
  pallets/gas/Cargo.toml
  pallets/gear-bank/Cargo.toml
  pallets/gear-bank/src/lib.rs
  pallets/gear-bank/src/mock.rs
  pallets/gear-bank/src/tests.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/mock.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-scheduler/Cargo.toml
  pallets/gear-scheduler/src/mock.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear-voucher/src/benchmarking.rs
  pallets/gear-voucher/src/lib.rs
  pallets/gear-voucher/src/tests.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/Cargo.toml
  pallets/payment/src/mock.rs
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/common/src/lib.rs
  runtime/common/src/migrations.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/gear/src/migrations.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/lib.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
Labels: A2-mergeoncegreen, A5-dontmerge

#3164 fix(vara): Update MAXIMUM_BLOCK_WEIGHT to 1 sec
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3135 feat(node): Make sure `pallet_gear::run()` pseudo-inherent only runs once per block
  gclient/src/api/listener/iterator.rs
  gsdk/src/metadata/generated.rs
  node/authorship/Cargo.toml
  node/authorship/src/tests.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  utils/node-loader/src/batch_pool.rs
Labels: A0-pleasereview, D2-node, C1-feature

#3162 fix(node-loader): Fix anoying error with too large RPC data
  gsdk/src/client.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3165 chore(gstd): remove `MaybeMaxEncodedLen` trait
  .github/workflows/check.yml
  gstd/src/lib.rs
  gstd/src/util.rs
Labels: A2-mergeoncegreen

#3116 refactor(wasm-gen): add methods to generate precise sys-calls
  utils/wasm-gen/src/generator/syscalls/imports.rs
Labels: A0-pleasereview, C2-refactoring, D5-tooling

#3169 Update Build-gear-loader-network.yml
  .github/workflows/Build-gear-loader-network.yml
  .github/workflows/Update-testnet.yml
Labels: A0-pleasereview

#3173 feat(rpc)!: Introduce payload parameter for read_state_using_wasm rpc call
  gcli/src/cmd/program.rs
  gclient/src/api/rpc.rs
  gclient/tests/state.rs
  gsdk/src/rpc.rs
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  runtime/common/src/apis.rs
Labels: A0-pleasereview

#3151 chore(core-backend)!: Remove `gear-backend-wasmi`
  Cargo.lock
  Cargo.toml
  core-backend/wasmi/Cargo.toml
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-backend/wasmi/src/lib.rs
  core-backend/wasmi/src/memory.rs
  core-backend/wasmi/src/runtime.rs
  gcli/Cargo.toml
  gcli/src/meta/mod.rs
  gtest/Cargo.toml
  gtest/src/error.rs
  gtest/src/manager.rs
  pallets/gear/Cargo.toml
  utils/wasm-instrument/Cargo.toml
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, D1-core, D2-node, D4-test, D5-tooling

#3155 ci(label): skip duplicated build on PR creation
  .github/actions/label/build.js
  .github/workflows/PR.yml
  .github/workflows/build.yml
  .github/workflows/label.yml
Labels: A2-mergeoncegreen, A5-dontmerge

#3188 feat: fuzzer scripts update
  docker/runtime-fuzzer/Dockerfile
  docker/runtime-fuzzer/scripts/fuzzer.sh
  scripts/gear.sh
  scripts/src/test.sh
Labels: A2-mergeoncegreen

#3194 chore(wasm-builder): ignore smoke tests
  scripts/src/test.sh
  utils/wasm-builder/tests/smoke.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#2986 test(core): signals tests
  Cargo.lock
  core-errors/signal-code-testing.md
  core-errors/src/simple.rs
  examples/signal-entry/Cargo.toml
  examples/signal-entry/src/lib.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D4-test

#3176 chore(runtime): Adjust target inflation value
  pallets/staking-rewards/src/inflation.rs
  pallets/staking-rewards/src/lib.rs
  pallets/staking-rewards/src/migration.rs
  pallets/staking-rewards/src/mock.rs
  pallets/staking-rewards/src/tests.rs
  runtime/vara/src/migrations.rs
Labels: A2-mergeoncegreen, D2-node

#3140 chore: Disable program rent logic
  Cargo.lock
  gsdk/src/metadata/generated.rs
  pallets/airdrop/src/mock.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/mock.rs
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear-debug/src/tests/utils.rs
  pallets/gear-program/src/migration.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/mock.rs
  pallets/payment/src/mock.rs
  runtime/common/src/constants.rs
  runtime/gear/src/constants.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/constants.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node

#3114 feat(wasm-gen): generate instructions handling fallible sys-calls results
  Cargo.lock
  core-processor/Cargo.toml
  core-processor/src/ext.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/module.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview

#3197 fix(migrations): Adjust versions of migration run
  runtime/common/src/migrations.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview
