Repository gear-tech/gear, pull requests merged in 2023-11, with the labels that each got.

#3463 chore: Macros to ease Config implementations in pallet tests
  Cargo.lock
  common/Cargo.toml
  common/src/lib.rs
  common/src/pallet_tests.rs
  pallets/gas/src/lib.rs
  pallets/gas/src/mock.rs
  pallets/gear-bank/Cargo.toml
  pallets/gear-bank/src/lib.rs
  pallets/gear-bank/src/mock.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/mock.rs
  pallets/gear-messenger/Cargo.toml
  pallets/gear-messenger/src/lib.rs
  pallets/gear-messenger/src/mock.rs
  pallets/gear-messenger/src/pallet_tests.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/mock.rs
  pallets/gear-program/src/pallet_tests.rs
  pallets/gear-scheduler/Cargo.toml
  pallets/gear-scheduler/src/lib.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear-voucher/Cargo.toml
  pallets/gear-voucher/src/mock.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/pallet_tests.rs
  pallets/payment/Cargo.toml
  pallets/payment/src/mock.rs
  pallets/staking-rewards/Cargo.toml
  pallets/staking-rewards/src/mock.rs
Labels: A0-pleasereview, C2-refactoring, D4-test

#3481 fix(gtest): Run delayed dispatches in `externalities` context
  gtest/src/manager.rs
Labels: A0-pleasereview

#3484 fix(wasm-gen): Include value into argument of invocable syscalls with destination param
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3474 fix(readme): Update binary usage examples
  README.md
Labels: A4-insubstantial

#3478 docs(workspace): add favicon url for documented packages
  common/src/lib.rs
  core-errors/src/lib.rs
  core-processor/src/lib.rs
  core/src/lib.rs
  galloc/src/lib.rs
  gclient/src/lib.rs
  gcore/src/lib.rs
  gmeta/src/lib.rs
  gsdk/src/lib.rs
  gstd/src/lib.rs
  gtest/src/lib.rs
  lazy-pages/src/lib.rs
  pallets/gas/src/lib.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-scheduler/src/lib.rs
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/payment/src/lib.rs
  utils/wasm-builder/src/lib.rs
Labels: A0-pleasereview

#3480 fix(readme): Update readme content
  README.md
  images/internal_flow.jpg
  images/title-grey.png
Labels: A2-mergeoncegreen, A4-insubstantial

#3492 chore(actions): rename wasm runtimes to be more clear. fix changelog
  .github/workflows/release.yml
Labels: A0-pleasereview

#3460 chore(wasm-instrument): move syscall table test to core-backend
  Cargo.lock
  core-backend/src/tests.rs
  utils/wasm-instrument/Cargo.toml
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#3495 fix(ci): Change `uri` of try-runtime
  .github/workflows/build.yml
Labels: A0-pleasereview

#3462 fix(windows): Precise stack height limit
  .github/workflows/CI.yaml
  .github/workflows/build-macos.yml
  .github/workflows/build.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  core/src/code.rs
  node/cli/src/command.rs
  pallets/gear/src/benchmarking/tests/mod.rs
  pallets/gear/src/schedule.rs
  sandbox/host/Cargo.toml
  sandbox/host/src/sandbox.rs
  sandbox/host/src/sandbox/wasmer_backend.rs
  scripts/cargo-xwin.sh
  utils/calc-stack-height/Cargo.toml
  utils/calc-stack-height/src/main.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A2-mergeoncegreen, D1-core, D2-node, D5-tooling

#3490 test(pallet-gear): add test for gas limit exceeded when out of memory bounds case
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#3379 feat(lazy-pages): Implement generic storage
  Cargo.lock
  Cargo.toml
  gstd/src/async_runtime/signals.rs
  gstd/src/msg/async.rs
  gtest/Cargo.toml
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
  lazy-pages/Cargo.toml
  lazy-pages/common/src/lib.rs
  lazy-pages/interface/Cargo.toml
  lazy-pages/interface/src/lib.rs
  lazy-pages/src/common.rs
  lazy-pages/src/host_func.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/process.rs
  lazy-pages/src/signal.rs
  lazy-pages/src/tests.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/lib.rs
  sandbox/host/src/sandbox/wasmer_backend.rs
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview, A2-mergeoncegreen, D2-node

#3103 feat(crates-io): introduce crates-io manager
  .github/workflows/crates-io.yml
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  gcli/Cargo.toml
  gcli/src/cmd/program.rs
  gcli/src/meta/executor.rs
  gmeta/Cargo.toml
  gsdk/codegen/Cargo.toml
  sandbox/env/Cargo.toml
  sandbox/host/Cargo.toml
  utils/actor-system-error/Cargo.toml
  utils/crates-io/Cargo.toml
  utils/crates-io/publish.rs
  utils/utils/Cargo.toml
  utils/wasm-builder/Cargo.toml
Labels: A0-pleasereview

#3391 feat(wasm-gen): add limits for recursions and heavy loops
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/generator.rs
  utils/wasm-gen/src/generator.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-gen/src/utils.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#3498 refactor: use `std::sync::OnceLock` instead of `once_cell`
  Cargo.lock
  lazy-pages/Cargo.toml
  lazy-pages/src/init_flag.rs
  lazy-pages/src/sys/unix.rs
  sandbox/host/Cargo.toml
  sandbox/host/src/sandbox/wasmer_backend.rs
  utils/node-loader/Cargo.toml
  utils/node-loader/src/batch_pool/api/nonce.rs
  utils/wasm-builder/src/cargo_toolchain.rs
Labels: A0-pleasereview, C2-refactoring

#3496 bugfix(runtime): Correct charging on delayed sendings from reservations
  Cargo.lock
  Cargo.toml
  core-processor/src/ext.rs
  core/src/reservation.rs
  examples/delayed-reservation-sender/Cargo.toml
  examples/delayed-reservation-sender/build.rs
  examples/delayed-reservation-sender/src/lib.rs
  examples/delayed-reservation-sender/src/wasm.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/tests.rs
Labels: P0-dropeverything, C0-bug, A5-dontmerge

#3505 bugfix(runtime): Correctly distribute resources for gasless delayed sending
  core-processor/src/ext.rs
  examples/delayed-sender/src/lib.rs
  examples/delayed-sender/src/wasm.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, P0-dropeverything, C0-bug

#3510 refactor(gtest): Update some of `gtest`s runtime constants
  gtest/src/lib.rs
  gtest/src/mailbox.rs
  gtest/src/program.rs
Labels: A0-pleasereview

#3479 ci(label): provide precise logs of check runs on skipping build
  .github/actions/label/build.js
Labels: A4-insubstantial

#3516 fix(gtest): make block duration 3 secs
  gtest/src/lib.rs
  gtest/src/system.rs
Labels: A0-pleasereview, B1-releasenotes, D5-tooling

#3517 chore(workspace): fix warnings from dapp template, add gstd as dep
  Cargo.lock
  core/src/ids.rs
  core/src/memory.rs
  examples/calc-hash/Cargo.toml
  examples/new-meta/io/Cargo.toml
  gcore/src/errors.rs
  gcore/src/lib.rs
  gstd/codegen/src/lib.rs
  gstd/src/common/errors.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview

#3522 chore(runtime): Bump versions after `v1.0.2` release
  Cargo.lock
  Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3470 fix(backport)!: Move nightly features behind feature gates
  Cargo.lock
  Cargo.toml
  gstd/Cargo.toml
  gstd/src/common/handlers.rs
  gstd/src/common/mod.rs
  gstd/src/lib.rs
Labels: A0-pleasereview, A2-mergeoncegreen, D3-gstd, B1-releasenotes, C2-refactoring

#3421 feat(pallet-gear): Added example and test to test signal weak case
  Cargo.lock
  Cargo.toml
  examples/signal-wait/Cargo.toml
  examples/signal-wait/build.rs
  examples/signal-wait/src/lib.rs
  examples/signal-wait/src/wasm.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, C1-feature

#3526 feat(runtime-fuzzer): Introduce ability to test helpful corpora
  .github/workflows/check.yml
  scripts/check-fuzzer.sh
  scripts/gear.sh
  scripts/src/test.sh
  utils/runtime-fuzzer/README.md
  utils/runtime-fuzzer/fuzz_corpus/c6e2a597aebabecc9bbb11eefdaa4dd8a6770188
  utils/runtime-fuzzer/src/tests.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3537 CI: + mount fuzzer logs, - check sccache stats
  .github/workflows/build.yml
  .github/workflows/check.yml
Labels: A0-pleasereview

#3536 chore: downgrade rust version to nightly-2023-09-05
  rust-toolchain.toml
Labels: A0-pleasereview

#3538 feat(gear-wasm-builder): Add pre-processor
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview

#3471 feat(core): Add crate for Numerated
  Cargo.lock
  Cargo.toml
  common/numerated/Cargo.toml
  common/numerated/src/interval.rs
  common/numerated/src/lib.rs
  common/numerated/src/mock.rs
  common/numerated/src/numerated.rs
  common/numerated/src/tests.rs
  common/numerated/src/tree.rs
Labels: A0-pleasereview
