Repository gear-tech/gear, pull requests merged in 2023-06, with the labels that each got.

#2709 fix(gsdk): improve error messages and ignore incorrect docs
  gsdk/api-gen/src/main.rs
  gsdk/build.rs
  gsdk/src/metadata/generated.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#2715 chore(ci): bump sccache v0.5.1
  .github/workflows/CI.yaml
  .github/workflows/release.yml
Labels: A0-pleasereview

#2712 fix(weights): Fix `SessionValidatorSetMigration` weight
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/migration.rs
  runtime/gear/src/migrations.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview, D2-node, D6-gas

#2701 fix(core-backend): backend vague errors
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
Labels: A0-pleasereview, D1-core

#2723 fix(runtime): Auto-replies on messages deposited as event
  core/src/ids.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, C0-bug

#2563 feat(pallet-gear): add weights for sign-ext instructions
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/common/src/weights.rs
  runtime/gear/src/tests.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
Labels: A0-pleasereview

#2678 refactor(runtime-fuzzer): Make gas limit variable in runtime-fuzzer
  utils/runtime-fuzzer/src/lib.rs
Labels: A0-pleasereview

#2706 fix(backend-codegen): appending WGas to gasful host calls
  core-backend/codegen/src/host.rs
Labels: A0-pleasereview

#2719 fix(wasm-builder): detect incorrect code at early stage
  Cargo.lock
  core/src/code.rs
  pallets/gear/src/schedule.rs
  scripts/src/build.sh
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/builder_error.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/rules.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, D5-tooling

#2645 docs(galloc): introduce `dlmalloc` & `galloc` optimizations paper
  Cargo.lock
  Cargo.toml
  examples/Cargo.lock
  examples/Cargo.toml
  examples/binaries/fungible-token/Cargo.toml
  examples/binaries/fungible-token/build.rs
  examples/binaries/fungible-token/io/Cargo.toml
  examples/binaries/fungible-token/io/src/lib.rs
  examples/binaries/fungible-token/src/contract.rs
  examples/binaries/fungible-token/src/lib.rs
  examples/binaries/fungible-token/state/Cargo.toml
  examples/binaries/fungible-token/state/build.rs
  examples/binaries/fungible-token/state/src/lib.rs
  examples/binaries/fungible-token/tests/benchmarks.rs
  examples/fungible-token/Cargo.toml
  examples/fungible-token/src/lib.rs
  galloc/README.md
  galloc/docs/optimization.md
  gstd/Cargo.toml
Labels: A2-mergeoncegreen

#2728 runtime(gear,vara): Remove unused migrations
  runtime/common/src/lib.rs
  runtime/common/src/migration.rs
  runtime/gear/src/migrations.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview

#2730 chore: use Rust toolchain override
  .github/workflows/CI.yaml
  .github/workflows/benchmarks.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  Makefile
  examples/binaries/fungible-token/demo_fungible_token.meta.txt
  rust-toolchain.toml
  scripts/src/build.sh
  scripts/src/check.sh
  scripts/src/clippy.sh
  scripts/src/format.sh
  scripts/src/test.sh
Labels: A0-pleasereview

#2736 ignore ft benchmark
  examples/binaries/fungible-token/tests/benchmarks.rs
Labels: A0-pleasereview, P1-asap

#2735 build(examples): fix examples native windows build
  examples/binaries/fungible-token/Cargo.toml
  examples/binaries/fungible-token/build.rs
  examples/binaries/fungible-token/state/Cargo.toml
  examples/binaries/fungible-token/state/build.rs
  examples/binaries/fungible-token/state/src/lib.rs
  rust-toolchain.toml
Labels: A0-pleasereview

#2738 ci: code cleanup
  .github/workflows/Build-gear-loader-network.yml
  .github/workflows/CI.yaml
  .github/workflows/Update-Vara-Prod.yml
  .github/workflows/Update-testnet.yml
  .github/workflows/benchmarks.yml
  .github/workflows/build-node-fuzzer.yaml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .github/workflows/rollback-testnet.yml
  .github/workflows/test-measurements.yaml
  docker/gear-loader/Dockerfile
  rust-toolchain.toml
Labels: A2-mergeoncegreen

#2743 fix(ci): Resolve sccache connection error
  .github/workflows/Build-gear-loader-network.yml
  .github/workflows/CI.yaml
  .github/workflows/release.yml
  .github/workflows/test-measurements.yaml
Labels: A2-mergeoncegreen

#2745 fix: Correctly deal with mailbox interactions and reply deposits
  examples/binaries/constructor/src/scheme/demo_reply_deposit.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node, C0-bug

#2690 feat: add assembler-script support in wasm-proc
  Cargo.lock
  gtest/src/program.rs
  scripts/src/clippy.sh
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/stack_end.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview

#2688 feat(weight-diff): add tool to generate diffs between branches
  Cargo.lock
  Cargo.toml
  scripts/weight-diff.sh
  utils/weight-diff/Cargo.toml
  utils/weight-diff/src/main.rs
Labels: A2-mergeoncegreen, D5-tooling

#2746 feat!(gstd): Add reply deposit for each async *_for_reply fn
  examples/async-multisig/src/lib.rs
  examples/async-sign/src/lib.rs
  examples/binaries/async-init/src/lib.rs
  examples/binaries/async-recursion/src/lib.rs
  examples/binaries/async-signal-entry/src/lib.rs
  examples/binaries/async-tester/src/code.rs
  examples/binaries/async/src/lib.rs
  examples/binaries/compose/src/lib.rs
  examples/binaries/distributor/src/lib.rs
  examples/binaries/futures-unordered/src/lib.rs
  examples/binaries/incomplete-async-payloads/src/lib.rs
  examples/binaries/init-fail-sender/src/lib.rs
  examples/binaries/init-wait-reply-exit/src/code.rs
  examples/binaries/ncompose/src/lib.rs
  examples/binaries/rwlock/src/lib.rs
  examples/binaries/sync-duplicate/src/lib.rs
  examples/binaries/wait-timeout/src/code.rs
  examples/binaries/waiter/src/code.rs
  examples/binaries/waiting-proxy/src/lib.rs
  gstd/codegen/src/lib.rs
  gstd/codegen/src/utils.rs
  gstd/src/lib.rs
  gstd/src/lock/mutex.rs
  gstd/src/lock/rwlock.rs
  gstd/src/msg/async.rs
  pallets/gear/src/tests.rs
  utils/wasm-proc/metadata-js/index.js
Labels: A2-mergeoncegreen, D3-gstd, B1-releasenotes, C1-feature, B2-breaking-apis

#2755 refactor(gclient): avoid async calls inside into_iter() loop
  gclient/src/api/calls.rs
Labels: A0-pleasereview, C2-refactoring, D5-tooling

#2747 feat: restrict mutable globals to be export in gear
  core/src/code.rs
  pallets/gear-program/src/mock.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, B1-releasenotes, C1-feature

#2762 chore: bump version to v0.2.0
  Cargo.lock
  gcli/Cargo.toml
  node/cli/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen

#2748 refactor(node-loader): Spawn tokio threads and broadcast events
  Cargo.lock
  gsdk/src/types.rs
  utils/node-loader/CHANGELOG.md
  utils/node-loader/Cargo.toml
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/main.rs
Labels: A2-mergeoncegreen, C2-refactoring, D5-tooling

#2644 feat(gstd): Implement ReservationManager in gstd
  Cargo.lock
  Cargo.toml
  examples/Cargo.lock
  examples/binaries/reservation-manager/Cargo.toml
  examples/binaries/reservation-manager/build.rs
  examples/binaries/reservation-manager/src/lib.rs
  gstd/Cargo.toml
  gstd/src/lib.rs
  gstd/src/reservations.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D3-gstd, C1-feature

#2757 refactor(gsdk): Make sign_and_submit_then_watch `Send`
  Cargo.lock
  gsdk/Cargo.toml
  gsdk/src/signer/calls.rs
Labels: A0-pleasereview, A2-mergeoncegreen, C2-refactoring

#2764 test: Add repr test for #2763
  examples/binaries/constructor/src/builder.rs
  examples/binaries/constructor/src/call.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D4-test

#2765 chore(ci): Remove sccache
  .github/workflows/CI.yaml
  .github/workflows/release.yml
Labels: A1-inprogress, A2-mergeoncegreen

#2772 fix(core): Fix reserve-use-unreserve panic
  core/src/reservation.rs
  examples/binaries/reserve-gas/src/lib.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, A2-mergeoncegreen, D1-core, D2-node

#2776 refactor(core): remove unused `CountersOwner::refund_gas`
  core-backend/common/src/lib.rs
  core-backend/common/src/mock.rs
  core-processor/src/ext.rs
  core/src/gas.rs
  pallets/gear/src/ext.rs
Labels: A0-pleasereview, A2-mergeoncegreen, D1-core, C2-refactoring

#2622 feat!(node): Add `resume_session_init`, `resume_session_push` and `resume_session_commit` extrinsics
  common/src/paused_program_storage.rs
  common/src/program_storage.rs
  common/src/scheduler/task.rs
  gsdk/src/metadata/generated.rs
  pallets/airdrop/src/mock.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  pallets/payment/src/mock.rs
  runtime/common/src/constants.rs
  runtime/gear/src/constants.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/constants.rs
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/pallet_gear.rs
Labels: A0-pleasereview, D2-node, B1-releasenotes

#2780 ci: cleanup after fe4e9e7
  .github/workflows/Build-gear-loader-network.yml
  .github/workflows/CI-drop-cache.yml
  .github/workflows/Update-testnet.yml
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview

#2778 refactor(docs)!: review doctests in `gstd` and `gcore`
  gcore/src/exec.rs
  gcore/src/lib.rs
  gcore/src/msg.rs
  gcore/src/prog.rs
  gstd/codegen/src/lib.rs
  gstd/src/common/primitives.rs
  gstd/src/exec.rs
  gstd/src/lib.rs
  gstd/src/lock/mutex.rs
  gstd/src/lock/rwlock.rs
  gstd/src/macros/metadata.rs
  gstd/src/msg/async.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
Labels: A0-pleasereview

#2787 chore(tests): Correct cache path in test measurements CI
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview, D5-tooling

#2784 feat (gstd): add 'read_at' in gcore
  gcore/src/msg.rs
Labels: A0-pleasereview, D3-gstd

#2783 refactor(core-backend): rename generics `core-backend` & `core-processor` so they emphasize their essence
  core-backend/common/src/funcs.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-backend/common/src/mock.rs
  core-backend/common/src/runtime.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-backend/wasmi/src/memory.rs
  core-backend/wasmi/src/runtime.rs
  core-backend/wasmi/src/state.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/lib.rs
  core-processor/src/processing.rs
  core/src/code.rs
  core/src/env.rs
  core/src/message/mod.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/ext.rs
Labels: A0-pleasereview, D1-core, C2-refactoring

#2803 feat(gcli): introduce gh token env for gh requests
  .github/workflows/CI.yaml
  gcli/src/template.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#2801 fix(gear-wasm-instrument): correctly calculate cost of `gas_charge` itself
  utils/wasm-instrument/src/lib.rs
Labels: A0-pleasereview, D6-gas

#2767 refactor(wasm-builder): wasm builder refactoring and some logic improvements
  examples/binaries/btree/src/lib.rs
  examples/binaries/out-of-memory/src/lib.rs
  gtest/src/program.rs
  scripts/src/build.sh
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, C2-refactoring

#2794 refactor!: Remove `gr_origin` everywhere
  core-backend/common/src/funcs.rs
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-processor/src/common.rs
  core-processor/src/context.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processing.rs
  core/src/costs.rs
  core/src/env.rs
  examples/binaries/fungible-token/src/contract.rs
  examples/binaries/sys-calls/src/lib.rs
  gcore/src/exec.rs
  gcore/src/general.rs
  gear-test/src/proc.rs
  gsdk/src/metadata/generated.rs
  gstd/src/exec.rs
  gsys/src/lib.rs
  gtest/src/manager.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A0-pleasereview, B1-releasenotes

#2806 test: ft transfer bench
  Cargo.lock
  examples/binaries/fungible-token/Cargo.toml
  examples/binaries/fungible-token/io/src/lib.rs
  examples/binaries/fungible-token/src/contract.rs
  examples/binaries/fungible-token/tests/benchmarks.rs
  gclient/src/api/storage/mod.rs
  gsdk/src/storage.rs
Labels: A0-pleasereview

#2790 feat(node-loader): Spawn batch pool in new thread
  Cargo.lock
  utils/call-gen/src/rand_utils.rs
  utils/node-loader/CHANGELOG.md
  utils/node-loader/Cargo.toml
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/main.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview, D5-tooling

#2833 fix(node-loader): Fix Duration::from_millis
  utils/node-loader/src/batch_pool.rs
Labels: A0-pleasereview

#2827 feat(gtest): add some gtest logging
  Cargo.toml
  gtest/Cargo.toml
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/program.rs
Labels: A0-pleasereview

#2804 refactor(node): Introduce `QueueStep`
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node

#2789 refactoring(core): remove gas counter from `read`
  core-backend/common/src/funcs.rs
  core-backend/common/src/mock.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/buffer.rs
  core/src/env.rs
  core/src/memory.rs
  core/src/message/common.rs
  core/src/message/context.rs
  core/src/message/handle.rs
  core/src/message/incoming.rs
  core/src/message/init.rs
  core/src/message/mod.rs
  core/src/message/reply.rs
  core/src/message/stored.rs
  gclient/tests/memory_dump.rs
  gclient/tests/upload.rs
  gear-test/src/check.rs
  gtest/src/log.rs
  gtest/src/mailbox.rs
  gtest/src/manager.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/tests.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A2-mergeoncegreen, D1-core, C2-refactoring

#2741 feat!(syscalls): Change reply syscalls signatures
  core-backend/common/src/funcs.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmi/src/funcs_tree.rs
  examples/Cargo.lock
  gcore/src/msg.rs
  gsys/src/lib.rs
  pallets/gear/src/benchmarking/syscalls.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A2-mergeoncegreen, D3-gstd, B1-releasenotes, B2-breaking-apis

#2828 fix (gcore): fix read length in gcore
  gcore/src/msg.rs
Labels: A0-pleasereview

#2756 feat(gsdk): update subxt to 0.29.0
  .github/workflows/CI.yaml
  Cargo.lock
  Cargo.toml
  gclient/src/api/calls.rs
  gclient/src/api/error.rs
  gclient/src/api/mod.rs
  gclient/tests/set_code.rs
  gsdk/Cargo.toml
  gsdk/api-gen/Cargo.toml
  gsdk/api-gen/src/main.rs
  gsdk/build.rs
  gsdk/src/events.rs
  gsdk/src/lib.rs
  gsdk/src/metadata/errors.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/metadata/impls.rs
  gsdk/src/metadata/mod.rs
  gsdk/src/signer/calls.rs
  gsdk/src/storage.rs
  gsdk/src/utils.rs
Labels: A0-pleasereview

#2760 feat(node): Implement RPC method returning WASM runtime version
  Cargo.lock
  Cargo.toml
  gsdk/src/rpc.rs
  gsdk/tests/rpc.rs
  node/service/Cargo.toml
  node/service/src/rpc/mod.rs
  node/service/src/rpc/runtime_info.rs
  runtime/gear/Cargo.toml
  runtime/gear/build.rs
  runtime/gear/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/build.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#2847 feat(ci): Run build job only for A0 or A2 labels
  .github/workflows/CI.yaml
Labels: A2-mergeoncegreen

#2839 refactor(core-errors)!: New sys-call error representation
  core-backend/codegen/src/host.rs
  core-backend/codegen/src/lib.rs
  core-backend/common/src/funcs.rs
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-errors/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/ext.rs
  core/src/costs.rs
  core/src/env.rs
  core/src/message/context.rs
  examples/binaries/backend-error/src/lib.rs
  examples/binaries/reserve-gas/src/lib.rs
  examples/binaries/syscall-error/src/lib.rs
  gcore/src/errors.rs
  gcore/src/exec.rs
  gcore/src/msg.rs
  gcore/src/prog.rs
  gsdk/src/metadata/generated.rs
  gsys/src/lib.rs
  gtest/src/program.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
  utils/wasm-gen/src/lib.rs
  utils/wasm-instrument/src/syscalls.rs
  utils/wasm-proc/metadata-js/index.js
Labels: A0-pleasereview, D1-core, D3-gstd, B1-releasenotes

#2851 ci: run build job on push event
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#2854 refactor(test): Don't build runtimes in doc-tests
  scripts/src/test.sh
Labels: A2-mergeoncegreen, C2-refactoring, D5-tooling

#2857 chore: inherit version from workspace and bump to v0.2.1
  Cargo.lock
  Cargo.toml
  examples/Cargo.lock
  galloc/Cargo.toml
  gcli/Cargo.toml
  gcore/Cargo.toml
  gmeta/Cargo.toml
  gstd/Cargo.toml
  gsys/Cargo.toml
  node/cli/Cargo.toml
Labels: A0-pleasereview, A2-mergeoncegreen

#2829 refactor(gmeta)!: change `Reply` type to input only and add new fields
  examples/binaries/new-meta/io/src/lib.rs
  gcli/src/meta/mod.rs
  gcli/src/meta/tests.rs
  gcli/src/result.rs
  gcli/tests/cmd/program.rs
  gmeta/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes

#2866 chore(core-backend): Clean up fallible error handling
  core-backend/common/src/lib.rs
  core-backend/common/src/runtime.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/memory.rs
  core-backend/wasmi/src/runtime.rs
  core-backend/wasmi/src/state.rs
Labels: A0-pleasereview, D1-core

#2856 feat(gstd)!: expand `gstd::debug!` behaviour
  examples/binaries/btree/src/lib.rs
  examples/binaries/compose/src/lib.rs
  examples/binaries/constructor/src/call.rs
  examples/binaries/distributor/src/lib.rs
  examples/binaries/fungible-token/src/contract.rs
  examples/binaries/mul-by-const/src/lib.rs
  examples/binaries/ncompose/src/lib.rs
  examples/binaries/node/src/lib.rs
  examples/binaries/piggy-bank/src/lib.rs
  examples/binaries/vec/src/lib.rs
  examples/capacitor/src/lib.rs
  examples/wait/src/lib.rs
  gstd/src/macros/debug.rs
Labels: A0-pleasereview, D3-gstd

#2852 fix(gtest): remove dependency on gear-common
  Cargo.lock
  common/src/lib.rs
  common/src/memory_dump.rs
  core/Cargo.toml
  gclient/Cargo.toml
  gclient/src/api/calls.rs
  gtest/Cargo.toml
  gtest/src/program.rs
  utils/utils/Cargo.toml
  utils/utils/src/lib.rs
Labels: A2-mergeoncegreen

#2699 feat(gstd): Introduce async exec::sleep_for method
  Cargo.lock
  examples/binaries/waiter/Cargo.toml
  examples/binaries/waiter/src/code.rs
  examples/binaries/waiter/src/lib.rs
  gstd/src/async_runtime/locks.rs
  gstd/src/exec/async.rs
  gstd/src/exec/basic.rs
  gstd/src/exec/mod.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen

#2879 fix(gclient): Resolve feature gate issue
  gclient/Cargo.toml
Labels: A0-pleasereview

#2877 fix(node-loader): Appropriately handle events
  .gitignore
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/utils.rs
Labels: A0-pleasereview

#2876 refactor(core-errors): Initial split ExtError into fallible and infallible versions
  core-backend/common/src/funcs.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/mock.rs
  core-backend/common/src/runtime.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-backend/wasmi/src/runtime.rs
  core-errors/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/lib.rs
  core-processor/src/processing.rs
  core/src/env.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D1-core, A3-gotissues

#2890 feat(wasm-builder): Introduce switch for disabling path remapping
  utils/wasm-builder/src/lib.rs
Labels: A0-pleasereview, D5-tooling

#2805 refactor(gear-wasm-instrument): optimize `gas_charge` function
  pallets/gear/src/schedule.rs
  utils/wasm-instrument/src/lib.rs
Labels: A0-pleasereview, A2-mergeoncegreen, C2-refactoring

#2885 fix(new-meta): add root workspace
  examples/binaries/new-meta/Cargo.toml
  examples/binaries/new-meta/io/Cargo.toml
  examples/binaries/new-meta/io/src/lib.rs
  examples/binaries/new-meta/state-v1/Cargo.toml
  examples/binaries/new-meta/state-v2/Cargo.toml
  examples/binaries/new-meta/state-v3/Cargo.toml
Labels: A0-pleasereview
