Repository gear-tech/gear, pull requests merged in 2023-02, with the labels that each got.

#2138 Refactor core-backend errors
  Cargo.lock
  core-backend/common/src/error_processor.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-backend/common/src/mock.rs
  core-backend/common/src/utils.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs/internal.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-backend/wasmi/src/memory.rs
  core-backend/wasmi/src/state.rs
  core-errors/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processing.rs
  core/src/env.rs
  examples/binaries/syscall-error/Cargo.toml
  examples/binaries/syscall-error/src/lib.rs
  gear-test/src/check.rs
  gear-test/src/proc.rs
  gsys/src/lib.rs
  gtest/src/manager.rs
  gtest/src/wasm_executor.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, D1-core

#2178 Make `OutOfMemoryAccessError` reachable
  core-backend/common/src/memory.rs
Labels: A0-pleasereview, D1-core

#2176 Fix backend errors handling for fallible syscalls
  Cargo.lock
  Cargo.toml
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/funcs/internal.rs
  core-backend/wasmi/src/funcs/mod.rs
  examples/binaries/backend-error/Cargo.toml
  examples/binaries/backend-error/build.rs
  examples/binaries/backend-error/src/lib.rs
  gclient/Cargo.toml
  gclient/tests/backend.rs
  gsys/src/lib.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D1-core, C0-bug

#2179 Take `SKIP_WASM_BUILD` env var into account
  utils/wasm-builder/src/cargo_command.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-builder/test-program/.gitignore
  utils/wasm-builder/test-program/build.rs
  utils/wasm-builder/tests/smoke.rs
Labels: A0-pleasereview, D5-tooling

#2198 Revert check for `--locked` in CI
  .github/workflows/CI.yaml
  Cargo.lock
  examples/Cargo.lock
  scripts/src/build.sh
Labels: A0-pleasereview

#2201 Fix build in `production` profile
  program/build.rs
Labels: A0-pleasereview

#2172 Use msg::source for send-calls in some cases
  utils/wasm-gen/src/lib.rs
Labels: A0-pleasereview, C1-feature, D4-test

#2208 Update peer id in spec
  node/res/staging.json
Labels: A0-pleasereview

#2211 Resolve of runtime panic in msgs sendings.
  core-processor/src/ext.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node, C0-bug

#2194 backend errors refactoring
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/memory.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs/internal.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/memory.rs
  core-backend/wasmi/src/state.rs
  core-errors/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/env.rs
  core/src/memory.rs
  core/src/message/context.rs
  gtest/src/program.rs
  pallets/gear/src/tests.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview

#2197 Validate actor backend errors
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/env.rs
  core-backend/wasmi/src/env.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D1-core, C0-bug

#2205 Introduce `call-gen`
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/lazy-pages/Cargo.toml
  common/src/gas_provider/property_tests/mod.rs
  common/src/gas_provider/property_tests/utils.rs
  pallets/gear-messenger/Cargo.toml
  pallets/gear-program/Cargo.toml
  pallets/gear-scheduler/Cargo.toml
  pallets/gear/Cargo.toml
  utils/call-gen/Cargo.toml
  utils/call-gen/src/create_program.rs
  utils/call-gen/src/lib.rs
  utils/call-gen/src/rand_utils.rs
  utils/call-gen/src/send_message.rs
  utils/call-gen/src/upload_code.rs
  utils/call-gen/src/upload_program.rs
  utils/node-loader/Cargo.toml
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/batch_pool/api/mod.rs
  utils/node-loader/src/batch_pool/batch/create_program.rs
  utils/node-loader/src/batch_pool/batch/mod.rs
  utils/node-loader/src/batch_pool/batch/send_message.rs
  utils/node-loader/src/batch_pool/batch/upload_code.rs
  utils/node-loader/src/batch_pool/batch/upload_program.rs
  utils/node-loader/src/batch_pool/generators/batch.rs
  utils/node-loader/src/batch_pool/generators/mod.rs
  utils/node-loader/src/batch_pool/generators/program.rs
  utils/node-loader/src/batch_pool/generators/seed.rs
  utils/node-loader/src/utils.rs
  utils/utils/Cargo.toml
  utils/utils/src/lib.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#2217 Vara runtime tweaks
  runtime/vara/src/constants.rs
Labels: A0-pleasereview

#2231 Enforce min nominator bond in Vara genesis at stage 1
  node/service/src/chain_spec/vara.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node

#2120 Alternative `#[metawasm]` macro
  Cargo.lock
  examples/binaries/new-meta/state-v1/src/wasm.rs
  examples/binaries/new-meta/state-v2/src/wasm.rs
  examples/binaries/new-meta/state-v3/src/wasm.rs
  gmeta/codegen/Cargo.toml
  gmeta/codegen/src/lib.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D5-tooling

#2235 Remove direct dependency on wasm-gen, use call-gen
  Cargo.lock
  utils/call-gen/src/lib.rs
  utils/node-loader/Cargo.toml
  utils/node-loader/src/batch_pool/generators/batch.rs
  utils/node-loader/src/batch_pool/generators/mod.rs
  utils/node-loader/src/batch_pool/generators/program.rs
  utils/node-loader/src/utils.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#2238 Enable call-gen logs in node-loader
  utils/node-loader/src/log.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#2200 Introduce `gr_panic` sys-call
  core-backend/common/src/lib.rs
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-processor/src/ext.rs
  core/src/env.rs
  gcore/src/lib.rs
  gcore/src/utils.rs
  gear-test/src/js/decode.js
  gear-test/src/js/encode.js
  gear-test/src/js/package-lock.json
  gear-test/src/js/package.json
  gstd/src/common/handlers.rs
  gstd/src/lib.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/ext.rs
  program/src/metadata/env.rs
  program/src/metadata/funcs.rs
  utils/wasm-instrument/src/syscalls.rs
  utils/wasm-proc/metadata-js/index.js
Labels: A0-pleasereview, D1-core, D3-gstd, B1-releasenotes

#2241 Add CI workflow for release
  .github/workflows/CI.yaml
  .github/workflows/release.yml
Labels: A2-mergeoncegreen

#2244 Fix fuzzing tests being non-reproducible
  Cargo.lock
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-gen/src/utils.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#2163 Edit events/errors names and descriptions after proofreading
  common/src/event.rs
  gclient/src/api/calls.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  utils/economic-checks/src/targets.rs
Labels: A2-mergeoncegreen

#2246 Interfaces cleanup
  Makefile
  common/lazy-pages/src/lib.rs
  common/src/lib.rs
  core-backend/common/src/lazy_pages.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/precharge.rs
  core/src/costs.rs
  core/src/gas.rs
  core/src/memory.rs
  gclient/src/api/calls.rs
  lazy-pages/src/sys.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  program/src/api/signer/calls.rs
  runtime-interface/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen

#2239 Change alloc sys-calls' signatures
  .config/nextest.toml
  Cargo.lock
  Cargo.toml
  core-backend/common/src/lib.rs
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/memory.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-backend/wasmi/src/memory.rs
  core-errors/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/ext.rs
  core-processor/src/lib.rs
  core/src/env.rs
  core/src/memory.rs
  examples/Cargo.lock
  examples/binaries/out-of-memory/Cargo.toml
  examples/binaries/out-of-memory/build.rs
  examples/binaries/out-of-memory/src/lib.rs
  galloc/Cargo.toml
  gcore/src/utils.rs
  gear-test/src/js/package-lock.json
  gear-test/src/js/package.json
  gstd/src/common/handlers.rs
  gstd/src/lib.rs
  gsys/src/lib.rs
  pallets/gear-debug/src/tests.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/tests.rs
  program/src/metadata/env.rs
  program/src/metadata/funcs.rs
  utils/wasm-instrument/src/syscalls.rs
  utils/wasm-proc/metadata-js/index.js
Labels: A0-pleasereview, D1-core, D3-gstd, B1-releasenotes

#2253 fix syscalls charge
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/funcs/internal.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-processor/src/ext.rs
  core/src/costs.rs
  core/src/env.rs
  core/src/gas.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear.rs
Labels: A2-mergeoncegreen

#2260 Staging testnet v6
  node/res/staging.json
  node/service/src/chain_spec/gear.rs
  runtime/gear/src/lib.rs
Labels: A0-pleasereview

#2214 Support spawning dev node via gclient means
  Cargo.lock
  gclient/Cargo.toml
  gclient/src/api/mod.rs
  gclient/src/lib.rs
  gclient/src/node/mod.rs
  gclient/src/node/port.rs
  gclient/src/node/result.rs
  gclient/src/node/ws.rs
  gclient/tests/node.rs
  program/tests/common/node.rs
Labels: A2-mergeoncegreen

#2272 Add cachepot to build deps
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview, D5-tooling

#2053 Add gas lock in send_delayed_dispatch
  Cargo.lock
  Cargo.toml
  common/src/gas_provider/internal.rs
  common/src/gas_provider/node.rs
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  common/src/scheduler/mod.rs
  common/src/scheduler/task.rs
  common/src/storage/complex/messenger.rs
  core-errors/src/lib.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processing.rs
  examples/binaries/proxy-reservation-with-gas/Cargo.toml
  examples/binaries/proxy-reservation-with-gas/build.rs
  examples/binaries/proxy-reservation-with-gas/src/lib.rs
  gear-test/src/proc.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  pallets/airdrop/src/mock.rs
  pallets/gas/src/tests.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-scheduler/src/lib.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#2266 return old small syscall weights
  Cargo.lock
  common/lazy-pages/src/lib.rs
  core-backend/common/src/lib.rs
  core-backend/common/src/memory.rs
  core-backend/common/src/mock.rs
  core-backend/sandbox/src/env.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/sandbox/src/runtime.rs
  core-backend/wasmi/src/env.rs
  core-backend/wasmi/src/funcs/internal.rs
  core-backend/wasmi/src/funcs/mod.rs
  core-backend/wasmi/src/funcs_tree.rs
  core-backend/wasmi/src/memory.rs
  core-backend/wasmi/src/state.rs
  core-processor/src/ext.rs
  core-processor/src/precharge.rs
  core/src/costs.rs
  core/src/env.rs
  core/src/gas.rs
  lazy-pages/src/lib.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/tests.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/stack_end.rs
  utils/wasm-gen/src/lib.rs
  utils/wasm-instrument/src/lib.rs
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview, D1-core, D2-node

#2278 Test runtime imports before release
  .github/workflows/release.yml
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen

#2275 Add some alloc tests
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D4-test

#2277 Remove Clone derive for GasCounter
  core-backend/common/src/mock.rs
  core-processor/src/common.rs
  core-processor/src/context.rs
  core-processor/src/ext.rs
  core-processor/src/lib.rs
  core-processor/src/precharge.rs
  core/src/gas.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/ext.rs
  pallets/gear/src/runtime_api.rs
Labels: A0-pleasereview, D1-core, D2-node

#2286 Update client
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: A0-pleasereview, D2-node

#2268 Fix `demo-meta` is being rebuilt each time
  utils/wasm-builder/src/cargo_command.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/smart_fs.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-builder/test-program/.gitignore
  utils/wasm-builder/test-program/build.rs
  utils/wasm-builder/test-program/src/lib.rs
  utils/wasm-builder/tests/smoke.rs
Labels: A0-pleasereview, D5-tooling

#2291 Unpin wasmtime
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview, D2-node

#2288 Fix build on Windows
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview, dependencies, E1-forcewindows

#2299 update to substrate with new cli param: default_heap_pages
  Cargo.lock
  node/cli/Cargo.toml
Labels: A0-pleasereview

#2316 Fix sudo call encoding
  gsdk/src/metadata/impls.rs
  gsdk/src/signer/calls.rs
  utils/node-loader/Cargo.toml
  utils/node-loader/src/batch_pool.rs
Labels: A0-pleasereview, A2-mergeoncegreen, C2-refactoring, D4-test, D5-tooling
