Repository gear-tech/gear, pull requests merged in 2023-04, with the labels that each got.

#2490 change fallible sys-calls checkers in `runtime-benchmarks`
  .github/workflows/CI.yaml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/sandbox.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/tests.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/pallet_gear.rs
Labels: A0-pleasereview, D4-test, D5-tooling, D6-gas

#2515 gmeta: Fix deprecation warning when using `metawasm` attribute
  gmeta/codegen/src/lib.rs
Labels: A0-pleasereview

#2518 Enable call_indirect instruction in call-gen
  utils/call-gen/src/lib.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling, A4-insubstantial

#2513 gtest: Do not validate dispatch for delayed messages
  gtest/src/mailbox.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A0-pleasereview

#2503 Performance improvements
  .maintain/frame-weight-template.hbs
  Cargo.lock
  Cargo.toml
  core/src/ids.rs
  core/src/reservation.rs
  lazy-pages/src/host_func.rs
  lazy-pages/src/process.rs
  lazy-pages/src/signal.rs
  node/cli/Cargo.toml
  node/cli/src/lib.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/tests.rs
  runtime/gear/src/weights/frame_system.rs
  runtime/gear/src/weights/pallet_balances.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/gear/src/weights/pallet_timestamp.rs
  runtime/gear/src/weights/pallet_utility.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
Labels: A0-pleasereview, D1-core, D2-node, C2-refactoring

#2529 Increase fuzzer performance
  utils/runtime-fuzzer/src/lib.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#2532 Use std feature by default in node crates and dev-deps
  lazy-pages/Cargo.toml
  node/authorship/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  node/testing/Cargo.toml
  pallets/airdrop/Cargo.toml
  pallets/gas/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-messenger/Cargo.toml
  pallets/gear-scheduler/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/payment/Cargo.toml
  pallets/staking-rewards/Cargo.toml
  runtime-interface/Cargo.toml
  utils/gear-runtime-test-cli/Cargo.toml
Labels: A0-pleasereview, D2-node, C2-refactoring

#2536 ci: Add check for runtime imports to CI
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#2530 Update substrate v0.9.41
  .maintain/frame-weight-template.hbs
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  gsdk/src/metadata/mod.rs
  node/authorship/Cargo.toml
  node/authorship/src/authorship.rs
  node/authorship/src/block_builder.rs
  node/authorship/src/tests.rs
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/gear.rs
  node/service/src/chain_spec/vara.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  node/service/src/rpc.rs
  pallets/airdrop/src/lib.rs
  pallets/airdrop/src/weights.rs
  pallets/gas/src/lib.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  pallets/payment/src/lib.rs
  pallets/staking-rewards/src/lib.rs
  pallets/staking-rewards/src/weights.rs
  runtime/gear/Cargo.toml
  runtime/gear/build.rs
  runtime/gear/src/lib.rs
  runtime/gear/src/weights/mod.rs
  runtime/vara/Cargo.toml
  runtime/vara/build.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/mod.rs
  utils/gear-runtime-test-cli/Cargo.toml
  utils/gear-runtime-test-cli/src/util.rs
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/src/runtime/account.rs
Labels: A0-pleasereview, D2-node

#2511 Move gas charging inside alloc
  core-backend/sandbox/src/memory.rs
  core-backend/wasmi/src/memory.rs
  core-processor/src/ext.rs
  core/src/gas.rs
  core/src/memory.rs
Labels: A0-pleasereview

#2517 gear-common: Return error in case of imbalance application leads to overflow
  common/src/gas_provider/error.rs
  common/src/gas_provider/internal.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/negative_imbalance.rs
  common/src/gas_provider/positive_imbalance.rs
  common/src/gas_provider/property_tests/mod.rs
  gclient/src/api/calls.rs
  gsdk/src/signer/calls.rs
  gsdk/src/storage.rs
  pallets/gas/src/lib.rs
Labels: A0-pleasereview

#2543 Disable `lto` in dev profile for `wasm-builder`
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, C0-bug, E2-forcemacos

#2546 Check `Sudid` event in gclient
  gclient/src/api/calls.rs
  gclient/tests/set_code.rs
  gsdk/src/metadata/impls.rs
  gsdk/src/signer/calls.rs
Labels: A0-pleasereview, D5-tooling

#2553 Stop using obsolete dependencies in GitHub Actions (closes #2552)
  .github/workflows/Build-gear-loader-network.yml
  .github/workflows/CI.yaml
  .github/workflows/deps.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .github/workflows/test-measurements.yaml
  .github/workflows/win.yml
Labels: A0-pleasereview, C2-refactoring

#2549 feat(utils): switch to `clap` arg parser instead of `structopt`
  Cargo.lock
  utils/node-loader/Cargo.toml
  utils/node-loader/src/args.rs
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/src/bin/reproduce_fuzz.rs
  utils/wasm-info/Cargo.toml
  utils/wasm-info/src/main.rs
Labels: D5-tooling

#2569 Use `validator_set` pallet to manage authorities.
  Cargo.lock
  Cargo.toml
  node/service/src/chain_spec/gear.rs
  node/service/src/chain_spec/vara.rs
  node/testing/src/genesis.rs
  runtime/gear/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/gear/src/migrations.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview, D2-node

#2574 Embed runtime version section into WASM
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node

#2572 chore: prepare for 0.1.4 release
  Cargo.lock
  node/cli/Cargo.toml
  runtime/gear/src/lib.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#2576 refactor(call-gen): add `impl_convert_traits!` macro to reduce boilerplate code
  utils/call-gen/src/claim_value.rs
  utils/call-gen/src/create_program.rs
  utils/call-gen/src/lib.rs
  utils/call-gen/src/send_message.rs
  utils/call-gen/src/send_reply.rs
  utils/call-gen/src/upload_code.rs
  utils/call-gen/src/upload_program.rs
Labels: A0-pleasereview, D5-tooling

#2577 chore(gclient): use tokio directly instead of async-std
  Cargo.lock
  Cargo.toml
  gclient/Cargo.toml
  gclient/tests/upload.rs
Labels: A0-pleasereview

#2582 fix(rust): Support new alloc panic handling
  Cargo.lock
  Cargo.toml
  examples/binaries/async-tester/src/lib.rs
  examples/binaries/exit-handle-sender/src/lib.rs
  examples/binaries/exit-handle/src/lib.rs
  examples/binaries/exit-init/src/lib.rs
  examples/binaries/gas-burned/src/lib.rs
  examples/binaries/init-fail-sender/src/lib.rs
  examples/binaries/init-wait-reply-exit/src/lib.rs
  examples/binaries/init-wait/src/lib.rs
  examples/binaries/node/src/lib.rs
  examples/ping/src/lib.rs
  gcli/res/messager/src/lib.rs
  gcore/src/lib.rs
  gcore/src/utils.rs
  gstd/src/common/handlers.rs
  gstd/src/lib.rs
  gstd/src/prelude.rs
Labels: A2-mergeoncegreen, C0-bug

#2534 Introduce mutation test for fuzzer correctness checking
  .github/workflows/CI.yaml
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/src/gas_provider/internal.rs
  pallets/gas/Cargo.toml
  pallets/gear/Cargo.toml
  runtime/gear/Cargo.toml
  scripts/check-fuzzer.sh
  scripts/src/test.sh
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/fuzz/fuzz_targets/main.rs
  utils/runtime-fuzzer/src/lib.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#2568 ci(gcli): add retries for tests
  .github/workflows/CI.yaml
Labels: A0-pleasereview

#2589 chore(chain-spec): add rpc node in boot nodes section
  node/res/staging.json
Labels: A0-pleasereview

#2507 feat(node): Pause programs after specific amount of blocks
  Cargo.lock
  Cargo.toml
  common/src/benchmarking.rs
  common/src/event.rs
  common/src/lib.rs
  common/src/paused_program_storage.rs
  common/src/program_storage.rs
  examples/binaries/reserve-gas/src/lib.rs
  gclient/src/api/calls.rs
  gclient/tests/node.rs
  gsdk/src/lib.rs
  gsdk/src/metadata/mod.rs
  gsdk/src/signer/calls.rs
  gsdk/src/storage.rs
  gsdk/src/types.rs
  pallets/airdrop/src/mock.rs
  pallets/gas/src/mock.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-messenger/src/mock.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migration.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  pallets/staking-rewards/src/mock.rs
  runtime/gear/src/constants.rs
  runtime/gear/src/lib.rs
  runtime/vara/src/constants.rs
  runtime/vara/src/lib.rs
  utils/gear-runtime-test-cli/src/command.rs
Labels: A2-mergeoncegreen, D2-node, B1-releasenotes, C1-feature

#2558 Add separate bench for each syscall
  Cargo.lock
  Cargo.toml
  core-backend/common/src/lib.rs
  core-backend/sandbox/src/funcs.rs
  core-backend/wasmi/src/funcs/mod.rs
  core/Cargo.toml
  core/src/costs.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/gear/src/tests.rs
  runtime/gear/src/weights/pallet_gear.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A0-pleasereview, D6-gas

#2583 ci(node): fix node build under stable rust
  runtime/gear/Cargo.toml
  runtime/gear/build.rs
  runtime/gear/src/lib.rs
  scripts/src/build.sh
  scripts/src/check.sh
  scripts/src/clippy.sh
  scripts/src/test.sh
  utils/runtime-fuzzer/Cargo.toml
Labels: A2-mergeoncegreen

#2579 fix(node): slow down grandpa finality.
  examples/binaries/reserve-gas/src/lib.rs
  gclient/tests/upload.rs
  node/service/src/lib.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node

#2597 ci: stabilize test-measurements workflow
  .github/workflows/CI.yaml
  scripts/gear.sh
  scripts/src/build.sh
Labels: A0-pleasereview, D5-tooling

#2600 chore(cd): add git-cliff changelog to release body
  .github/workflows/release.yml
  cliff.toml
Labels: A0-pleasereview

#2594 add script for rust nightly version local pin
  scripts/pin-rust-nightly.sh
Labels: A0-pleasereview
