Repository gear-tech/gear, pull requests merged in 2024-07, with the labels that each got.

#4039 feat(gtest): Add send_with_gas
  gsdk/tests/rpc.rs
  gtest/src/program.rs
Labels: A2-mergeoncegreen, A5-dontmerge

#4041 fix(crates-io): resolve publishing issues
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/codegen/Cargo.toml
  common/numerated/Cargo.toml
  core-backend/Cargo.toml
  core-errors/Cargo.toml
  core-processor/Cargo.toml
  core/Cargo.toml
  galloc/Cargo.toml
  gcli/Cargo.toml
  gcli/tests/common/mod.rs
  gclient/Cargo.toml
  gclient/src/api/mod.rs
  gcore/Cargo.toml
  gmeta/Cargo.toml
  gmeta/codegen/Cargo.toml
  gprimitives/Cargo.toml
  gsdk/Cargo.toml
  gsdk/codegen/Cargo.toml
  gsdk/tests/utils/mod.rs
  gstd/Cargo.toml
  gstd/codegen/Cargo.toml
  gsys/Cargo.toml
  gtest/Cargo.toml
  lazy-pages/Cargo.toml
  lazy-pages/common/Cargo.toml
  lazy-pages/interface/Cargo.toml
  lazy-pages/native-interface/Cargo.toml
  runtime-interface/Cargo.toml
  runtime/primitives/Cargo.toml
  sandbox/env/Cargo.toml
  sandbox/host/Cargo.toml
  sandbox/sandbox/Cargo.toml
  stack-buffer/Cargo.toml
  utils/actor-system-error/Cargo.toml
  utils/cargo-gbuild/Cargo.toml
  utils/crates-io/src/lib.rs
  utils/crates-io/src/publisher.rs
  utils/gring/Cargo.toml
  utils/node-wrapper/Cargo.toml
  utils/node-wrapper/src/instance.rs
  utils/node-wrapper/src/lib.rs
  utils/node-wrapper/src/log.rs
  utils/node-wrapper/src/node.rs
  utils/node-wrapper/src/utils.rs
  utils/node-wrapper/tests/main.rs
  utils/ss58/Cargo.toml
  utils/utils/Cargo.toml
  utils/wasm-builder/Cargo.toml
  utils/wasm-instrument/Cargo.toml
Labels: A0-pleasereview

#4044 fix(gstd): make sure `dbg!` macro always expand to valid expression
  gstd/src/macros/debug.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#4034 refactor(runtime-interface): split sandbox interface out of runtime-interface
  Cargo.lock
  Cargo.toml
  runtime-interface/Cargo.toml
  runtime-interface/sandbox/Cargo.toml
  runtime-interface/sandbox/src/detail.rs
  runtime-interface/sandbox/src/lib.rs
  runtime-interface/src/lib.rs
  sandbox/sandbox/Cargo.toml
  sandbox/sandbox/src/host_executor.rs
  utils/crates-io/src/handler.rs
  utils/crates-io/src/lib.rs
Labels: A0-pleasereview

#4045 refactor(gsdk): use `Into<Option<T>>` instead of `AsOption`
  gcli/tests/cmd/claim.rs
  gcli/tests/cmd/reply.rs
  gcli/tests/cmd/send.rs
  gcli/tests/cmd/transfer.rs
  gcli/tests/cmd/upload.rs
  gclient/src/api/mod.rs
  gsdk/src/api.rs
  gsdk/src/client.rs
  gsdk/src/lib.rs
  gsdk/src/utils.rs
  gsdk/tests/backtrace.rs
  gsdk/tests/rpc.rs
  utils/node-loader/src/main.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#3937 feat(pallets,core): separately charge for wasm module sections instantiation
  Cargo.lock
  core-processor/src/configs.rs
  core-processor/src/context.rs
  core-processor/src/lib.rs
  core-processor/src/precharge.rs
  core/src/code/errors.rs
  core/src/code/instrumented.rs
  core/src/code/mod.rs
  core/src/code/utils.rs
  gsdk/src/metadata/generated.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migrations/add_section_sizes.rs
  pallets/gear-program/src/migrations/allocations.rs
  pallets/gear-program/src/migrations/mod.rs
  pallets/gear-program/src/migrations/paused_storage.rs
  pallets/gear-program/src/migrations/v8.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/migrations/mod.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/common/src/weights.rs
  runtime/vara/src/migrations.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/calc-stack-height/src/main.rs
  utils/wasm-builder/src/code_validator.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A2-mergeoncegreen

#4005 feat(utils, ci): add lazy pages fuzzer
  .github/workflows/check.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  lazy-pages/src/common.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/signal.rs
  sandbox/host/Cargo.toml
  sandbox/host/src/error.rs
  sandbox/host/src/sandbox.rs
  sandbox/host/src/sandbox/wasmi_backend.rs
  scripts/check-fuzzer.sh
  scripts/check-lazy-pages-fuzzer.sh
  scripts/gear.sh
  scripts/src/test.sh
  utils/crates-io/src/handler.rs
  utils/lazy-pages-fuzzer/Cargo.toml
  utils/lazy-pages-fuzzer/fuzz/Cargo.toml
  utils/lazy-pages-fuzzer/fuzz/fuzz_targets/main.rs
  utils/lazy-pages-fuzzer/src/config.rs
  utils/lazy-pages-fuzzer/src/generate.rs
  utils/lazy-pages-fuzzer/src/generate/globals.rs
  utils/lazy-pages-fuzzer/src/generate/mem_accesses.rs
  utils/lazy-pages-fuzzer/src/globals.rs
  utils/lazy-pages-fuzzer/src/lazy_pages.rs
  utils/lazy-pages-fuzzer/src/lib.rs
  utils/lazy-pages-fuzzer/src/wasmer_backend.rs
  utils/lazy-pages-fuzzer/src/wasmi_backend.rs
  utils/lazy-pages-fuzzer/src/wasmi_backend/error.rs
Labels: A0-pleasereview

#3934 feat: Update substrate v1.4.0
  Cargo.lock
  Cargo.toml
  gsdk/src/metadata/generated.rs
  node/authorship/src/authorship.rs
  node/authorship/src/block_builder.rs
  node/authorship/src/tests.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/vara.rs
  node/service/src/lib.rs
  node/testing/src/client.rs
  node/testing/src/genesis.rs
  pallets/staking-rewards/src/mock.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/src/lib.rs
  utils/runtime-fuzzer/src/runtime/account.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
Labels: A2-mergeoncegreen, C1-feature, C2-refactoring

#4010 refactoring(gtest): Introduce `gear_common`s mailbox to `gtest`
  common/src/auxiliary/mailbox.rs
  common/src/auxiliary/mod.rs
  common/src/gas_provider/property_tests/mod.rs
  examples/piggy-bank/src/wasm.rs
  gtest/src/blocks.rs
  gtest/src/gas_tree.rs
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/mailbox.rs
  gtest/src/mailbox/actor.rs
  gtest/src/mailbox/manager.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#4059 feat(ci): apply changes from ethexe repository
  .github/workflows/check.yml
  ethexe/observer/Cargo.toml
  ethexe/observer/src/observer.rs
Labels: A0-pleasereview

#3949 feat(pallet-gear): Introduce extrinsic to transfer value from terminated/exited program
  gsdk/src/metadata/generated.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/vara/src/weights/pallet_gear.rs
Labels: A2-mergeoncegreen, D2-node

#4064 tests(ethexe): append initial `ethexe-cli` integration testing
  Cargo.lock
  ethexe/cli/Cargo.toml
  ethexe/cli/src/main.rs
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/common/src/db.rs
  ethexe/ethereum/src/lib.rs
  ethexe/observer/src/observer.rs
  ethexe/runtime/src/wasm/api/run.rs
  ethexe/signer/src/lib.rs
Labels: A0-pleasereview

#4062 fix(ethexe): run tests on free threads
  .config/nextest.toml
  .github/workflows/build.yml
  Cargo.lock
  ethexe/cli/Cargo.toml
  ethexe/cli/src/tests.rs
  ethexe/observer/Cargo.toml
  ethexe/observer/src/observer.rs
Labels: A0-pleasereview

#4066 feat(ethexe): append `--block-time` arg; make prometheus args optional
  ethexe/cli/src/args.rs
  ethexe/cli/src/config.rs
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/observer/src/blobs.rs
  ethexe/observer/src/observer.rs
Labels: A0-pleasereview

#4065 fix(node): Fix migration that pours and locks the ED on programs accounts
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/migrations/ed_locks.rs
  pallets/gear-program/src/migrations/mod.rs
  runtime/vara/src/migrations.rs
Labels: A2-mergeoncegreen, D2-node, C0-bug

#4070 tests(ethexe): run anvil node in block mining mode
  ethexe/cli/src/tests.rs
  ethexe/observer/src/observer.rs
Labels: A0-pleasereview

#4061 refactor(ethexe-network): Rewrite
  Cargo.lock
  ethexe/cli/src/args.rs
  ethexe/cli/src/chain_spec.rs
  ethexe/cli/src/config.rs
  ethexe/cli/src/main.rs
  ethexe/cli/src/metrics.rs
  ethexe/cli/src/params/network_params.rs
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/network/.gitignore
  ethexe/network/Cargo.toml
  ethexe/network/src/behaviour.rs
  ethexe/network/src/config.rs
  ethexe/network/src/custom_connection_limits.rs
  ethexe/network/src/error.rs
  ethexe/network/src/lib.rs
  ethexe/network/src/peer_info.rs
  ethexe/network/src/service.rs
  ethexe/network/src/transport.rs
  ethexe/network/src/utils.rs
  ethexe/signer/src/lib.rs
  ethexe/validator/src/lib.rs
Labels: A0-pleasereview

#4071 fix(ethexe): fixing of ethexe tests hang on
  ethexe/cli/src/tests.rs
  ethexe/observer/src/observer.rs
Labels: A0-pleasereview

#4080 feat(ethexe): Option to print only 1 key format after generation
  ethexe/cli/src/args.rs
  ethexe/cli/src/main.rs
Labels: A0-pleasereview

#4069 chore(ethexe): Add bootnodes, update chain-spec
  ethexe/cli/src/chain_spec.rs
  ethexe/cli/src/config.rs
  ethexe/docker/docker-compose.yml
  ethexe/docker/ethexe_builder.Dockerfile
Labels: A0-pleasereview

#4019 Initial work on Fuzzer randomization
  utils/runtime-fuzzer/src/generator.rs
  utils/runtime-fuzzer/src/generator/upload_program.rs
  utils/runtime-fuzzer/src/runtime/account.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/syscalls/injection.rs
  utils/wasm-gen/src/tests.rs
Labels: A2-mergeoncegreen

#4081 feat(ethexe): Option to generate random role keys in tmp mode
  ethexe/cli/src/args.rs
  ethexe/cli/src/config.rs
  ethexe/cli/src/service.rs
  ethexe/signer/src/lib.rs
Labels: A0-pleasereview

#4086 feat(ethexe): make network and rpc services optional
  ethexe/cli/src/args.rs
  ethexe/cli/src/config.rs
  ethexe/cli/src/main.rs
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/network/src/lib.rs
  ethexe/observer/src/query.rs
  ethexe/validator/src/lib.rs
Labels: A0-pleasereview

#4082 fix(ethexe): Actually use `dev-dependencies` in CLI
  ethexe/cli/Cargo.toml
  ethexe/cli/src/lib.rs
  ethexe/cli/src/main.rs
Labels: A0-pleasereview

#4084 chore(pallet-gear): Add `log::error!` calls before each `unreachable!` call
  core/src/reservation.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/queue.rs
  scripts/check-fuzzer.sh
Labels: A0-pleasereview, D2-node, C2-refactoring

#4076 feat(runtime-fuzzer): use previously waited message id as wake syscall param
  Cargo.lock
  utils/runtime-fuzzer/src/generator/upload_program.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-gen/src/wasm.rs
Labels: A2-mergeoncegreen

#4090 test(ethexe): append ping_reorg test
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/ethereum/src/lib.rs
  ethexe/observer/src/observer.rs
  ethexe/observer/src/query.rs
  ethexe/signer/src/lib.rs
Labels: A0-pleasereview

#4060 feat(pallet_gear): Introduce invariant: all user non-reply messages go to mailbox
  core-processor/src/ext.rs
  core/src/message/handle.rs
  core/src/message/init.rs
  core/src/message/mod.rs
  core/src/message/reply.rs
  examples/constructor/src/builder.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D2-node, B1-releasenotes, C2-refactoring

#4073 feat(gtest): support wasm rebuilding with gbuild
  gtest/src/program.rs
  utils/cargo-gbuild/src/artifact.rs
  utils/cargo-gbuild/src/cli.rs
  utils/cargo-gbuild/test-program/Cargo.toml
  utils/cargo-gbuild/test-program/bar/Cargo.toml
  utils/cargo-gbuild/test-program/foo/Cargo.toml
  utils/cargo-gbuild/test-program/meta/Cargo.toml
  utils/cargo-gbuild/test-program/src/lib.rs
Labels: A0-pleasereview

#4102 refactor(pallet_gear, core-processor): Send all user messages from reservation to mailbox
  core-processor/src/ext.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D1-core, D2-node, C2-refactoring

#4083 chore(runtime): remove applied migrations
  pallets/gear-program/src/migrations/allocations.rs
  pallets/gear-program/src/migrations/ed_locks.rs
  pallets/gear-program/src/migrations/mod.rs
  pallets/gear-program/src/migrations/paused_storage.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview

#3954 feat(pallet-gear): move `allocations` to separate storage, remove `pages_with_data`, expand max memory size to 2 GB
  .github/workflows/build.yml
  Cargo.lock
  common/src/benchmarking.rs
  common/src/program_storage.rs
  common/src/scheduler/task.rs
  common/src/storage/primitives/triple_map.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/context.rs
  core-processor/src/lib.rs
  core-processor/src/precharge.rs
  core-processor/src/processing.rs
  core/src/code/utils.rs
  core/src/memory.rs
  core/src/program.rs
  ethexe/runtime/common/src/lib.rs
  gclient/src/api/calls.rs
  gclient/tests/memory_dump.rs
  gclient/tests/upload.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/storage.rs
  gsdk/tests/rpc.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migrations/add_section_sizes.rs
  pallets/gear-program/src/migrations/allocations.rs
  pallets/gear-program/src/migrations/mod.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/vara/src/migrations.rs
  runtime/vara/src/weights/pallet_gear.rs
Labels: A2-mergeoncegreen
