Repository gear-tech/gear, pull requests merged in 2024-05, with the labels that each got.

#3935 chore(ci): Disable spec_version check in try-runtime
  .github/workflows/build.yml
Labels: A0-pleasereview

#3910 fix(pallet-gear): don't charge gas in benchmarks
  pallets/gear/src/lib.rs
Labels: A0-pleasereview

#3939 chore(ci): set `--repeat=0` for all testing benchmarks run
  .github/workflows/build.yml
Labels: A0-pleasereview

#3940 chore(builtin): remove builtin dummy actors
  pallets/gear-builtin/src/benchmarking.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3936 feat(gtest): search program path from gbuild artifact
  Cargo.lock
  gtest/Cargo.toml
  gtest/src/error.rs
  gtest/src/lib.rs
  gtest/src/program.rs
  utils/cargo-gbuild/test-program/Cargo.toml
  utils/cargo-gbuild/test-program/src/lib.rs
  utils/cargo-gbuild/tests/smoke.rs
Labels: A0-pleasereview

#3922 refactor(core): Context-dependent memory
  core-backend/src/env.rs
  core-backend/src/funcs.rs
  core-backend/src/lib.rs
  core-backend/src/memory.rs
  core-backend/src/mock.rs
  core-backend/src/runtime.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/env.rs
  core/src/memory.rs
  lazy-pages/interface/src/lib.rs
  pallets/gear/src/benchmarking/mod.rs
  sandbox/sandbox/src/embedded_executor.rs
  sandbox/sandbox/src/host_executor.rs
  sandbox/sandbox/src/lib.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview, D1-core

#3938 feat(core,pallets): add data segments amount limit checks
  core/src/code/errors.rs
  core/src/code/mod.rs
  core/src/code/utils.rs
  core/src/program.rs
  gsdk/src/metadata/generated.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  utils/calc-stack-height/src/main.rs
  utils/wasm-builder/src/code_validator.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A0-pleasereview

#3840 feat(gear-bank): impl on-finalize transfers; optimise block-production gas payouts
  gsdk/src/metadata/generated.rs
  pallets/gear-bank/src/lib.rs
  pallets/gear-bank/src/tests.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  runtime/vara/src/integration_tests.rs
  utils/runtime-fuzzer/src/runtime/block.rs
Labels: A2-mergeoncegreen

#3946 chores(workspace): Bump crates and runtime spec versions
  Cargo.lock
  Cargo.toml
  runtime/vara/src/lib.rs
Labels: A4-insubstantial

#3944 refactor(runtime): Dump constants (existential deposit; min voucher duration)
  runtime/vara/src/constants.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3951 chores(workspace): Bump versions after 1.3.1 release
  Cargo.lock
  Cargo.toml
  runtime/vara/src/lib.rs
Labels: A4-insubstantial

#3953 ci(skip): adapt checks with debug profiles
  .github/actions/message/main.js
Labels: A4-insubstantial

#3950 chore(core-processor): remove `pages_with_data` from `ExecutableActorData`
  core-processor/src/common.rs
  gtest/src/manager.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/queue.rs
Labels: A0-pleasereview

#3955 chores(workspace): Bump versions after release `v1.4.0`
  Cargo.lock
  Cargo.toml
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen, A4-insubstantial

#3921 feat: Update substrate to v1.3.0
  Cargo.lock
  Cargo.toml
  common/src/pallet_tests.rs
  gsdk/build.rs
  gsdk/src/metadata/generated.rs
  pallets/gas/src/mock.rs
  pallets/gear-bank/src/mock.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-messenger/src/mock.rs
  pallets/gear-program/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear-voucher/src/mock.rs
  pallets/gear/src/mock.rs
  pallets/payment/src/mock.rs
  pallets/staking-rewards/src/mock.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
Labels: A2-mergeoncegreen, C1-feature

#3957 test(scripts): run benches on isolated core if configured
  scripts/benchmarking/run_all_benchmarks.sh
Labels: A0-pleasereview, A2-mergeoncegreen

#3965 fix(pallet-gear): unable to run migration `MigrateWaitingInitList` with try-runtime
  pallets/gear/src/migrations.rs
Labels: A0-pleasereview

#3963 chore(pallet): move migrations to separate directories
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migration.rs
  pallets/gear-program/src/migrations/mod.rs
  pallets/gear/src/migrations/mod.rs
  pallets/gear/src/migrations/wait_init.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview

#3968 fix(scripts): Use non-compact debug wasm runtime for imports checking
  scripts/src/check.sh
Labels: A0-pleasereview, A4-insubstantial

#3929 test(pallets): add `instantiate_module_*` benches per section
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/vara/src/weights/pallet_gear.rs
Labels: A2-mergeoncegreen

#3956 refactor(docs): Update READMEs
  README.md
  images/internal_flow.jpg
  node/README.md
Labels: A2-mergeoncegreen

#3791 feat(core): change `BTreeSet` to `IntervalsTree` in allocations
  common/src/lib.rs
  common/src/paused_program_storage.rs
  common/src/program_storage.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/precharge.rs
  core/src/costs.rs
  core/src/memory.rs
  core/src/program.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/storage.rs
  gsdk/tests/rpc.rs
  gtest/src/manager.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migrations/allocations.rs
  pallets/gear-program/src/migrations/mod.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/migrations/wait_init.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/common/src/weights.rs
  runtime/vara/src/migrations.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A0-pleasereview

#3971 fix(readme): remove "gasless" feature description
  README.md
Labels: A2-mergeoncegreen

#3972 fix(gtest): Update `ED` constant
  gtest/src/lib.rs
  gtest/src/program.rs
Labels: A0-pleasereview, A4-insubstantial

#3967 fix(runtime): Fix inability to use vouchers with no balance
  gsdk/src/metadata/generated.rs
  node/cli/src/benchmarking.rs
  node/testing/src/keyring.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, C0-bug

#3981 refactor(pallet): remove loaded pages from pallet manager
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
Labels: A0-pleasereview, Q1-easy

#3969 chores(runtime): Bump versions after release `v1.4.1`
  Cargo.lock
  Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, A4-insubstantial

#3980 chore(cargo-gbuild): soft link rust-toolchain from the root workspace
  utils/cargo-gbuild/test-program/rust-toolchain.toml
Labels: A2-mergeoncegreen, A4-insubstantial

#3982 refactor(core): remove core program
  core-processor/src/common.rs
  core-processor/src/context.rs
  core-processor/src/executor.rs
  core-processor/src/processing.rs
  core/src/program.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear/src/benchmarking/syscalls.rs
Labels: A2-mergeoncegreen, Q2-moderate

#3764 ci(label): use fork-action instead of action script
  .github/actions/label/build.js
  .github/actions/message/main.js
  .github/workflows/build-macos.yml
  .github/workflows/build-win-native.yml
  .github/workflows/build.yml
  .github/workflows/label.yml
Labels: A2-mergeoncegreen, E2-forcemacos, E1-forcenatwin, E3-forcerelease, E4-forceproduction

#3987 Replace cost-* helper macros with functions.
  pallets/gear/src/schedule.rs
Labels: A0-pleasereview

#3983 refactor(common, core): move program from `gear-common` to `gear-core`
  Cargo.lock
  common/src/benchmarking.rs
  common/src/lib.rs
  common/src/paused_program_storage.rs
  core/Cargo.toml
  core/src/program.rs
  gclient/src/api/calls.rs
  gsdk/src/lib.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/signer/storage.rs
  gsdk/src/storage.rs
  gsdk/tests/rpc.rs
  node/authorship/src/tests.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migrations/allocations.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#3989 feat(gsdk): Print SCALE metadata
  Cargo.lock
  gsdk/api-gen/Cargo.toml
  gsdk/api-gen/src/main.rs
Labels: A0-pleasereview, C1-feature

#3986 feat(runtime-fuzzer): use existing code ids for syscall params
  .gitignore
  utils/runtime-fuzzer/src/generator.rs
  utils/runtime-fuzzer/src/generator/upload_program.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview
