Repository gear-tech/gear, pull requests merged in 2024-06, with the labels that each got.

#3991 refactor: add generic lazy-pages, native and substrate-ri interfaces
  Cargo.lock
  Cargo.toml
  core-processor/Cargo.toml
  core-processor/src/ext.rs
  gtest/Cargo.toml
  gtest/src/manager.rs
  lazy-pages/common/src/lib.rs
  lazy-pages/interface/src/lib.rs
  lazy-pages/native-interface/Cargo.toml
  lazy-pages/native-interface/src/lib.rs
  lazy-pages/src/common.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/benchmarking/tests/mod.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/lib.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/tests.rs
Labels: A2-mergeoncegreen, check-validator

#4000 fix(benchmarks): update reinstrument bench
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/weights.rs
  runtime/vara/src/weights/pallet_gear.rs
Labels: A0-pleasereview

#3999 feat(gear-common,gtest): Introduce proper mailbox for `gtest` (part 1)
  common/src/auxiliary/gas_provider.rs
  common/src/auxiliary/mailbox.rs
  common/src/auxiliary/mod.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/property_tests/mod.rs
  common/src/lib.rs
  gtest/src/blocks.rs
  gtest/src/gas_tree.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A2-mergeoncegreen, A5-dontmerge

#4002 feat: Publish runtime metadata in release
  .github/workflows/release.yml
Labels: A2-mergeoncegreen, C1-feature

#3994 feat(runtime, ci): finish migration to bare-metal benchmark runner and update weights
  .github/workflows/benchmarks.yml
  gtest/src/program.rs
  pallets/gear-builtin/src/weights.rs
  pallets/gear/src/weights.rs
  runtime/common/src/weights.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear_builtin.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
  scripts/benchmarking/apply_baremetal_weight_patch.rs
  scripts/benchmarking/run_all_benchmarks.sh
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A2-mergeoncegreen

#4007 fix(cargo-gbuild): optional metadata field
  utils/cargo-gbuild/src/metadata.rs
Labels: A2-mergeoncegreen

#4003 feat(gnode): introduce node wrapper
  Cargo.lock
  Cargo.toml
  gcli/Cargo.toml
  gcli/tests/common/app.rs
  gcli/tests/common/mod.rs
  gcli/tests/common/node.rs
  gcli/tests/common/result.rs
  gclient/Cargo.toml
  gclient/src/api/error.rs
  gclient/src/api/mod.rs
  gsdk/Cargo.toml
  gsdk/src/lib.rs
  gsdk/src/testing/node.rs
  gsdk/src/testing/port.rs
  gsdk/tests/backtrace.rs
  gsdk/tests/rpc.rs
  gsdk/tests/utils/mod.rs
  utils/gnode/Cargo.toml
  utils/gnode/src/instance.rs
  utils/gnode/src/lib.rs
  utils/gnode/src/log.rs
  utils/gnode/src/node.rs
  utils/gnode/src/utils.rs
  utils/gnode/tests/main.rs
Labels: A2-mergeoncegreen

#3962 feat(gtest): Porting gas tree implemenatation into `gtest`
  Cargo.lock
  common/src/auxiliary/gas_provider.rs
  common/src/auxiliary/mailbox.rs
  common/src/auxiliary/mod.rs
  common/src/gas_provider/property_tests/assertions.rs
  common/src/gas_provider/property_tests/mod.rs
  common/src/gas_provider/property_tests/utils.rs
  common/src/lib.rs
  gtest/Cargo.toml
  gtest/src/blocks.rs
  gtest/src/gas_tree.rs
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#4011 chore(gbuild): specify stable toolchain installation
  .github/workflows/check.yml
  utils/cargo-gbuild/tests/smoke.rs
Labels: A4-insubstantial

#3948 feat(node): Extend bls381 builtin actor
  Cargo.lock
  Cargo.toml
  examples/calc-hash/Cargo.toml
  gbuiltins/bls381/src/lib.rs
  node/service/src/client.rs
  node/testing/src/client.rs
  pallets/gear-builtin/Cargo.toml
  pallets/gear-builtin/src/benchmarking.rs
  pallets/gear-builtin/src/bls12_381.rs
  pallets/gear-builtin/src/tests/bls381.rs
  pallets/gear-builtin/src/weights.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/lib.rs
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen, D2-node, C1-feature

#3998 feat(gsdk,gclient): Implement gsdk api for calling gear_calculateReplyForHandle
  Cargo.lock
  examples/vec/src/wasm.rs
  gclient/src/api/rpc.rs
  gsdk/Cargo.toml
  gsdk/src/rpc.rs
  gsdk/src/signer/rpc.rs
  gsdk/tests/rpc.rs
Labels: A2-mergeoncegreen

#3901 fix(core): Fix send_commit updating data on operation failure, potential fix for #3881
  common/src/auxiliary/mod.rs
  core-processor/src/ext.rs
  core/src/gas.rs
  core/src/reservation.rs
Labels: A2-mergeoncegreen

#4021 fix(core-processor): reduce for mailbox threshold if gasful sent after gasless
  core-processor/src/ext.rs
  gsdk/tests/rpc.rs
Labels: A0-pleasereview

#4024 chore(runtime): remove old migrations
  pallets/gear/src/migrations/mod.rs
  pallets/gear/src/migrations/wait_init.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview

#4027 feat(gsdk,gclient): Add transfer_all, transfer_allow_death
  gclient/src/api/calls.rs
  gsdk/src/signer/calls.rs
  gsdk/src/signer/utils.rs
Labels: A0-pleasereview, C1-feature

#4022 chore(gsdk): introduce trait AsOption to simplify interface
  gcli/src/app.rs
  gcli/tests/cmd/claim.rs
  gcli/tests/cmd/reply.rs
  gcli/tests/cmd/send.rs
  gcli/tests/cmd/transfer.rs
  gcli/tests/cmd/upload.rs
  gclient/src/api/mod.rs
  gsdk/src/api.rs
  gsdk/src/client.rs
  gsdk/src/lib.rs
  gsdk/src/utils.rs
  gsdk/tests/backtrace.rs
  gsdk/tests/main.rs
  gsdk/tests/rpc.rs
  utils/crates-io/src/lib.rs
  utils/node-loader/src/main.rs
Labels: A0-pleasereview

#4029 fix: syscalls integrity tests gas_available
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
Labels: A0-pleasereview

#4012 feat(gprimitives): add `NonZeroU256` type & lossy conversion for `H160`
  gprimitives/Cargo.toml
  gprimitives/src/lib.rs
  gprimitives/src/macros.rs
  gprimitives/src/nonzero_u256.rs
Labels: A0-pleasereview, A2-mergeoncegreen
