Repository gear-tech/gear, pull requests merged in 2024-11, with the labels that each got.

#4303 refactor(gear-builtin) Concrete error type for builtin actors
  pallets/gear-builtin/src/bls12_381.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/proxy.rs
  pallets/gear-builtin/src/staking.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-eth-bridge/src/builtin.rs
Labels: A0-pleasereview

#4282 feat(sandbox-host): update sandbox host wasmi version
  Cargo.lock
  Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/command.rs
  runtime-interface/sandbox/src/detail.rs
  runtime-interface/sandbox/src/lib.rs
  runtime-interface/src/lib.rs
  sandbox/host/Cargo.toml
  sandbox/host/src/error.rs
  sandbox/host/src/lib.rs
  sandbox/host/src/sandbox.rs
  sandbox/host/src/sandbox/wasmer_backend.rs
  sandbox/host/src/sandbox/wasmi_backend.rs
  sandbox/host/src/store_refcell.rs
  sandbox/sandbox/src/embedded_executor.rs
  utils/gear-replay-cli/src/cmd/mod.rs
  utils/lazy-pages-fuzzer/Cargo.toml
  utils/lazy-pages-fuzzer/src/generate/globals.rs
  utils/lazy-pages-fuzzer/src/generate/mem_accesses.rs
  utils/lazy-pages-fuzzer/src/wasmer_backend.rs
  utils/lazy-pages-fuzzer/src/wasmi_backend.rs
  utils/lazy-pages-fuzzer/src/wasmi_backend/error.rs
Labels: A2-mergeoncegreen, C1-feature

#4314 feat(crates-io): check owners before publishing
  .github/workflows/crates-io.yml
  Cargo.lock
  docker/runtime-fuzzer/scripts/fuzzer.sh
  gbuiltins/proxy/Cargo.toml
  gbuiltins/proxy/src/lib.rs
  scripts/pin-rust-nightly.sh
  utils/crates-io/Cargo.toml
  utils/crates-io/src/handler.rs
  utils/crates-io/src/lib.rs
  utils/crates-io/src/main.rs
  utils/crates-io/src/manifest.rs
  utils/crates-io/src/publisher.rs
  utils/crates-io/src/version.rs
  utils/runtime-fuzzer/README.md
  utils/wasm-builder/test-program/src/lib.rs
  utils/wasm-builder/tests/smoke.rs
Labels: A0-pleasereview

#4299 feat(ethexe/rpc): implement rpc methods
  Cargo.lock
  core/Cargo.toml
  core/src/buffer.rs
  core/src/message/common.rs
  core/src/message/context.rs
  core/src/message/mod.rs
  core/src/pages.rs
  core/src/program.rs
  core/src/reservation.rs
  ethexe/common/src/lib.rs
  ethexe/common/src/mirror.rs
  ethexe/common/src/router.rs
  ethexe/common/src/wvara.rs
  ethexe/rpc/Cargo.toml
  ethexe/rpc/src/apis/block.rs
  ethexe/rpc/src/apis/mod.rs
  ethexe/rpc/src/apis/program.rs
  ethexe/rpc/src/common.rs
  ethexe/rpc/src/errors.rs
  ethexe/rpc/src/lib.rs
  ethexe/runtime/common/Cargo.toml
  ethexe/runtime/common/src/state.rs
  ethexe/signer/src/lib.rs
  gprimitives/src/lib.rs
Labels: A2-mergeoncegreen

#4313 feat(ethexe): Held small payloads directly in dispatches
  Cargo.lock
  core/src/buffer.rs
  ethexe/processor/src/handling/events.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
Labels: A2-mergeoncegreen

#4324 fix(ethexe/contracts): rename RouterScript to DeploymentScript
  ethexe/contracts/script/Deployment.s.sol
Labels: A2-mergeoncegreen

#4319 refactor(gclient): removed filtering static pages while creating memory dump
  gclient/src/api/calls.rs
Labels: A2-mergeoncegreen

#4310 refactor(ethexe): refine storage accesses; redesign maybehash
  Cargo.lock
  core/src/buffer.rs
  ethexe/cli/src/tests.rs
  ethexe/common/src/router.rs
  ethexe/db/src/database.rs
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/handling/mod.rs
  ethexe/processor/src/handling/run.rs
  ethexe/processor/src/host/threads.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/rpc/src/apis/program.rs
  ethexe/runtime/common/Cargo.toml
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/common/src/transitions.rs
  ethexe/runtime/src/wasm/storage.rs
  pallets/gear-messenger/src/tests.rs
  pallets/gear/src/manager/journal.rs
  utils/node-loader/src/batch_pool.rs
Labels: A2-mergeoncegreen

#4330 bench: + lock cpu frequency
  .github/workflows/benchmarks.yml
  terraform/bench-runner/main.tf
Labels: A0-pleasereview

#4331 fix(ethexe): Disable jemalloc in RocksDB for MSVC
  Cargo.lock
  ethexe/db/Cargo.toml
  ethexe/db/src/database.rs
Labels: A0-pleasereview

#4332 fix(ci): WASM benchmark never run
  .github/workflows/build.yml
Labels: A0-pleasereview, E3-forcerelease

#4328 feat(ethexe): extend ethexe cli
  ethexe/cli/src/args.rs
  ethexe/cli/src/config.rs
  ethexe/cli/src/params/mod.rs
  ethexe/cli/src/params/network.rs
  ethexe/cli/src/params/prometheus.rs
  ethexe/cli/src/params/rpc.rs
  ethexe/cli/src/service.rs
  ethexe/processor/src/handling/mod.rs
  ethexe/processor/src/handling/run.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/rpc/src/lib.rs
Labels: A0-pleasereview

#4289 feat: Update substrate to gear-polkadot-stable2409
  .github/workflows/build-win-native.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  common/src/pallet_tests.rs
  gsdk/Cargo.toml
  gsdk/src/client.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/result.rs
  gsdk/tests/rpc.rs
  node/authorship/Cargo.toml
  node/authorship/src/block_builder.rs
  node/authorship/src/tests.rs
  node/cli/Cargo.toml
  node/cli/src/benchmarking.rs
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/mod.rs
  node/service/src/chain_spec/vara.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  node/service/src/rpc/mod.rs
  node/service/src/rpc/runtime_info.rs
  node/testing/Cargo.toml
  node/testing/src/client.rs
  node/testing/src/genesis.rs
  node/testing/src/keyring.rs
  pallets/gear-builtin/Cargo.toml
  pallets/gear-builtin/rpc/src/lib.rs
  pallets/gear-builtin/src/tests/staking.rs
  pallets/gear-eth-bridge/Cargo.toml
  pallets/gear-eth-bridge/rpc/src/lib.rs
  pallets/gear-eth-bridge/src/mock.rs
  pallets/gear-program/src/migrations/add_section_sizes.rs
  pallets/gear-program/src/migrations/allocations.rs
  pallets/gear-program/src/mock.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  pallets/staking-rewards/rpc/src/lib.rs
  pallets/staking-rewards/src/mock.rs
  runtime-interface/sandbox/Cargo.toml
  runtime/common/src/apis.rs
  runtime/common/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/build.rs
  runtime/vara/src/governance/fellowship.rs
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_balances.rs
  rust-toolchain.toml
  utils/crates-io/src/handler.rs
  utils/gear-replay-cli/src/cmd/replay_block.rs
  utils/gring/src/keystore.rs
  utils/gring/src/pair.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
  utils/runtime-fuzzer/src/tests.rs
Labels: A2-mergeoncegreen, C1-feature, E2-forcemacos, E1-forcenatwin, E3-forcerelease

#4304 refactor(core): commit family of syscalls does not keep state between executions
  core/src/message/context.rs
  gsdk/src/metadata/generated.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-messenger/src/migrations/context_store.rs
  pallets/gear-messenger/src/migrations/mod.rs
  pallets/gear/src/tests.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview, A3-gotissues

#4334 chore(ci): clear npm cache, install `@openzeppelin/upgrades-core`
  .github/workflows/check.yml
Labels: A4-insubstantial

#4336 fix: Adjust benchmark pallet cli argument
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview, D4-test

#4339 fix(benchmarks): Create files with weights beforehand
  .github/workflows/test-measurements.yaml
  scripts/benchmarking/run_all_benchmarks.sh
Labels: A0-pleasereview, D5-tooling

#4342 refactor(runtime): adjust proxy filters
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#4325 fix(sandbox): Concurrent file operations in embedded executor cache
  Cargo.lock
  Cargo.toml
  sandbox/host/src/sandbox/wasmer_backend.rs
  sandbox/sandbox/src/embedded_executor.rs
  scripts/src/test.sh
  utils/gear-wasmer-cache/Cargo.toml
  utils/gear-wasmer-cache/src/lib.rs
Labels: A0-pleasereview

#4344 feat(ethexe): add timestamp to commitment
  Cargo.lock
  ethexe/cli/src/service.rs
  ethexe/common/src/lib.rs
  ethexe/common/src/router.rs
  ethexe/contracts/src/IRouter.sol
  ethexe/contracts/src/Router.sol
  ethexe/contracts/test/Router.t.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/abi.rs
  ethexe/sequencer/Cargo.toml
  ethexe/sequencer/src/lib.rs
  ethexe/signer/src/digest.rs
  ethexe/validator/Cargo.toml
  ethexe/validator/src/lib.rs
Labels: A0-pleasereview

#4348 fix(lazy-pages-fuzzer): Increase Wasmi's max stack size
  lazy-pages/src/globals.rs
  lazy-pages/src/host_func.rs
  lazy-pages/src/signal.rs
  sandbox/host/src/store_refcell.rs
  utils/lazy-pages-fuzzer/src/lazy_pages.rs
  utils/lazy-pages-fuzzer/src/lib.rs
  utils/lazy-pages-fuzzer/src/wasmi_backend.rs
Labels: A0-pleasereview

#4350 chore(wasm-instrument): remove gas_metering module
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A0-pleasereview

#4353 chore(wasm-builder): Reduce WASM proposals instead of MVP usage
  utils/wasm-optimizer/src/cargo_command.rs
Labels: A0-pleasereview, D5-tooling

#4361 fix(runtime): reservation reply per byte weight
  core/src/gas_metering/schedule.rs
  pallets/gear/src/schedule.rs
  runtime/vara/src/tests.rs
Labels: A2-mergeoncegreen

#4360 chore(ci): Install dependencies via package managers in Windows
  .github/workflows/build-win-native.yml
Labels: A0-pleasereview, E1-forcenatwin

#4354 feat(ethexe): bump programs memory limit to 2GB
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/common/src/transitions.rs
Labels: A0-pleasereview
