Repository gear-tech/gear, pull requests merged in 2024-02, with the labels that each got.

#3692 refactor(core): Remove useless string conversion (`with_string_payload()`)
  core/src/message/common.rs
  core/src/message/stored.rs
  core/src/message/user.rs
  gtest/src/manager.rs
  pallets/gear/src/internal.rs
Labels: A0-pleasereview

#3698 test(gtest): show bug with reservations in `gtest`
  examples/custom/src/lib.rs
  examples/custom/src/reserver.rs
  gtest/src/program.rs
Labels: A2-mergeoncegreen, A4-insubstantial

#3684 refactor(runtime-fuzzer): Clean-up fuzzer for value fuzzing
  Cargo.lock
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/bin/run_corpus.rs
  utils/runtime-fuzzer/fuzz/fuzz_targets/main.rs
  utils/runtime-fuzzer/src/data.rs
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/runtime-fuzzer/src/generator.rs
  utils/runtime-fuzzer/src/generator/claim_value.rs
  utils/runtime-fuzzer/src/generator/send_message.rs
  utils/runtime-fuzzer/src/generator/send_reply.rs
  utils/runtime-fuzzer/src/generator/upload_program.rs
  utils/runtime-fuzzer/src/lib.rs
  utils/runtime-fuzzer/src/runtime/account.rs
  utils/runtime-fuzzer/src/runtime/mailbox.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
  utils/runtime-fuzzer/src/tests.rs
  utils/runtime-fuzzer/src/utils.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3671 feat(wasm-gen): increase fuzzer stack height limit
  pallets/gear/src/schedule.rs
  sandbox/sandbox/src/embedded_executor.rs
  utils/wasm-gen/src/generator.rs
  utils/wasm-gen/src/utils.rs
Labels: A0-pleasereview, D5-tooling

#3571 chore: bump rust version to latest nightly
  common/numerated/src/interval.rs
  common/src/gas_provider/property_tests/mod.rs
  examples/constructor/src/builder.rs
  examples/constructor/src/wasm.rs
  examples/fungible-token/src/wasm.rs
  examples/fungible-token/tests/benchmarks.rs
  examples/new-meta/src/wasm.rs
  examples/node/src/wasm.rs
  gcli/tests/common/mod.rs
  gclient/src/api/listener/mod.rs
  gclient/src/api/storage/mod.rs
  gclient/src/lib.rs
  gsdk/src/storage.rs
  gsdk/src/testing/node.rs
  gstd/src/async_runtime/signals.rs
  gstd/src/macros/debug.rs
  gstd/src/msg/async.rs
  gstd/tests/debug.rs
  pallets/gear-voucher/src/benchmarking.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tasks.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  runtime/vara/src/lib.rs
  rust-toolchain.toml
  sandbox/host/src/sandbox.rs
  sandbox/host/src/sandbox/wasmer_backend.rs
  scripts/src/clippy.sh
  utils/gear-replay-cli/src/lib.rs
  utils/gring/src/keystore.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
  utils/validator-checks/src/blocks_production.rs
  utils/validator-checks/src/result.rs
  utils/wasm-builder/src/cargo_toolchain.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#3670 feat(gtest): Add option to check for if a message panicked on RunResult
  examples/waiter/tests/mx_lock_access.rs
  examples/waiter/tests/rw_lock_access.rs
  examples/waiter/tests/utils.rs
  gtest/src/log.rs
  gtest/src/program.rs
Labels: A2-mergeoncegreen

#3689 feat(runtime-fuzzer): Introduce value fuzzing in the `runtime-fuzzer`
  utils/runtime-fuzzer/src/generator.rs
  utils/runtime-fuzzer/src/generator/send_message.rs
  utils/runtime-fuzzer/src/generator/send_reply.rs
  utils/runtime-fuzzer/src/generator/upload_program.rs
  utils/runtime-fuzzer/src/lib.rs
  utils/runtime-fuzzer/src/runtime/account.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#3719 feat(runtime-fuzzer): Increase processed tasks rate in `runtime-fuzzer`
  utils/runtime-fuzzer/src/runtime/block.rs
Labels: D4-test, D5-tooling, A5-dontmerge

#3615 feat(wasm-gen): avoid infinite wait-wake for loose syscalls
  Cargo.lock
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/module.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/generator.rs
  utils/wasm-gen/src/generator/entry_points.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/lib.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-gen/src/utils.rs
  utils/wasm-gen/src/wasm.rs
Labels: A2-mergeoncegreen, D5-tooling

#3691 remove initialized field from ExecutableActorData
  core-processor/src/common.rs
  core-processor/src/context.rs
  core/src/program.rs
  gtest/src/manager.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/queue.rs
Labels: A1-inprogress

#3712 fix(typos): rename demo-messager to demo-messenger
  Cargo.lock
  Cargo.toml
  examples/messenger/Cargo.toml
  examples/messenger/build.rs
  examples/messenger/src/bin/demo_messenger.rs
  examples/messenger/src/lib.rs
  examples/messenger/src/wasm.rs
  gcli/Cargo.toml
  gcli/tests/cmd/reply.rs
  gcli/tests/cmd/send.rs
  gcli/tests/common/app.rs
  gcli/tests/common/mod.rs
  gsdk/Cargo.toml
  gsdk/tests/rpc.rs
Labels: A4-insubstantial

#3720 fix(pallet-gear): Remove incorrect `log::error`
  pallets/gear/src/manager/journal.rs
Labels: A2-mergeoncegreen, A4-insubstantial

#3725 feat(runtime): Add ability to decline given voucher
  gsdk/src/metadata/generated.rs
  pallets/gear-voucher/src/benchmarking.rs
  pallets/gear-voucher/src/internal.rs
  pallets/gear-voucher/src/lib.rs
  pallets/gear-voucher/src/mock.rs
  pallets/gear-voucher/src/tests.rs
  pallets/gear-voucher/src/weights.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/payment/src/mock.rs
  pallets/payment/src/tests.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#3723 feat(runtime-fuzzer): Exhaust message queue and task pool after executing all gear calls
  utils/runtime-fuzzer/src/lib.rs
  utils/runtime-fuzzer/src/runtime/account.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#3695 refactor(core): extract `CodeError` into smaller types
  .github/workflows/build.yml
  core/src/code.rs
  core/src/code/errors.rs
  core/src/code/instrumented.rs
  core/src/code/mod.rs
  core/src/code/utils.rs
  examples/wat/spec/large_scheduled.wat
  gsdk/src/metadata/generated.rs
  gsdk/src/signer/storage.rs
  gsdk/src/storage.rs
  pallets/gear/src/tests.rs
  utils/wasm-builder/src/builder_error.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A0-pleasereview, D1-core, C2-refactoring

#3734 chore(ci): Remove coverage
  .github/workflows/build.yml
Labels: A0-pleasereview

#3730 feat(runtime-fuzzer): Add `TransactionPayment::on_finalize` hook call
  utils/runtime-fuzzer/src/runtime/block.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#3687 refactor(gcli): switch resolved API to gclient
  Cargo.lock
  examples/messenger/src/bin/demo_messenger.rs
  gcli/Cargo.toml
  gcli/src/app.rs
  gcli/src/cmd/claim.rs
  gcli/src/cmd/create.rs
  gcli/src/cmd/info.rs
  gcli/src/cmd/key.rs
  gcli/src/cmd/mod.rs
  gcli/src/cmd/program.rs
  gcli/src/cmd/reply.rs
  gcli/src/cmd/send.rs
  gcli/src/cmd/transfer.rs
  gcli/src/cmd/upload.rs
  gcli/src/result.rs
  gcli/tests/cmd/info.rs
  gclient/src/api/mod.rs
  gclient/src/lib.rs
Labels: A0-pleasereview, C2-refactoring, D5-tooling

#3733 feat!(gear-core): check data section for uploading codes
  common/src/paused_program_storage.rs
  core-processor/src/executor.rs
  core-processor/src/precharge.rs
  core/Cargo.toml
  core/src/code/errors.rs
  core/src/code/mod.rs
  core/src/code/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  utils/wasm-builder/src/builder_error.rs
  utils/wasm-instrument/Cargo.toml
Labels: A0-pleasereview

#3732 fix(workspace): correct spelling
  Cargo.toml
  gclient/src/api/calls.rs
  node/authorship/src/tests.rs
  pallets/gear/src/tests.rs
  pallets/staking-rewards/src/lib.rs
  pallets/staking-rewards/src/tests.rs
Labels: A0-pleasereview, A2-mergeoncegreen, A4-insubstantial

#3724 refactor(gcli): replace keystore with gring
  Cargo.lock
  Cargo.toml
  gcli/Cargo.toml
  gcli/src/app.rs
  gcli/src/cmd/key.rs
  gcli/src/cmd/login.rs
  gcli/src/cmd/mod.rs
  gcli/src/cmd/wallet.rs
  gcli/src/lib.rs
  gcli/tests/cmd/key.rs
  gcli/tests/cmd/mod.rs
  gcli/tests/common/mod.rs
  gclient/src/api/mod.rs
  gsdk/src/signer/pair_signer.rs
  utils/gring/src/cmd.rs
  utils/gring/src/keyring.rs
  utils/gring/src/lib.rs
Labels: A0-pleasereview

#3747 chore(test, gsdk): Add a test case showing how to query a storage
  gsdk/tests/rpc.rs
Labels: A0-pleasereview, D4-test, D5-tooling, A4-insubstantial

#3750 fix(gring): remove ss58 version configuration
  utils/gring/src/cmd.rs
  utils/gring/src/keyring.rs
Labels: A0-pleasereview

#3475 fix(core): Allow waking the same message between waits
  Cargo.lock
  common/src/storage/complex/messenger.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processing.rs
  core/src/message/common.rs
  core/src/message/context.rs
  core/src/message/mod.rs
  core/src/message/stored.rs
  gsdk/src/metadata/generated.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-messenger/Cargo.toml
  pallets/gear-messenger/src/lib.rs
  pallets/gear-messenger/src/migrations.rs
  pallets/gear-messenger/src/mock.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview, C0-bug

#3676 refactor(gtest): Remove ambiguous API and incorrectly named functions
  examples/program-factory/src/lib.rs
  gtest/src/manager.rs
  gtest/src/system.rs
Labels: A0-pleasereview, C2-refactoring

#3758 fix(pallet-gear-builtin): Fix the issue of bi-replying
  pallets/gear-builtin/src/lib.rs
Labels: A2-mergeoncegreen, C0-bug

#3757 fix(wasm-builder): improve diagnostics of some errors
  core/src/code/utils.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A2-mergeoncegreen, D5-tooling

#3761 fix(gcore, gstd): improve docs & re-export `EnvVars` from gsys
  core-errors/src/simple.rs
  gcore/src/exec.rs
  gcore/src/lib.rs
  gstd/src/exec/async.rs
  gstd/src/lib.rs
Labels: A0-pleasereview

#3686 feat(node): Modify rent reward distributions
  common/src/pallet_tests.rs
  gcli/tests/cmd/claim.rs
  gcli/tests/common/mod.rs
  pallets/gear-bank/src/lib.rs
  pallets/gear-bank/src/tests.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/pallet_tests.rs
  pallets/gear/src/tests.rs
  pallets/staking-rewards/Cargo.toml
  pallets/staking-rewards/src/lib.rs
  pallets/staking-rewards/src/migrations.rs
  pallets/staking-rewards/src/mock.rs
  pallets/staking-rewards/src/tests.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
Labels: A2-mergeoncegreen, D2-node, C1-feature

#3753 feat(gcli): make gas limit optional argument
  gcli/src/cmd/create.rs
  gcli/src/cmd/reply.rs
  gcli/src/cmd/send.rs
  gcli/src/cmd/upload.rs
Labels: A2-mergeoncegreen, A4-insubstantial

#3597 refactor(numerated): make refactoring for crate numerated
  common/numerated/src/interval.rs
  common/numerated/src/iterators.rs
  common/numerated/src/lib.rs
  common/numerated/src/mock.rs
  common/numerated/src/numerated.rs
  common/numerated/src/tests.rs
  common/numerated/src/tree.rs
Labels: A2-mergeoncegreen

#3760 chore: Fetch previous release, bump versions, fix master clippy
  Cargo.lock
  Cargo.toml
  pallets/gear-messenger/src/migrations.rs
  pallets/gear/src/schedule.rs
  runtime/vara/src/lib.rs
Labels: A4-insubstantial

#3759 fix(rpc-calls): Trigger reinstrumentation if needed for state reading
  core/src/code/mod.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, C0-bug

#3762 fix(tools): split pre-processing, optimization and code validation
  utils/wasm-builder/src/builder_error.rs
  utils/wasm-builder/src/code_validator.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-proc/src/main.rs
Labels: A2-mergeoncegreen, D5-tooling

#3766 fix(workspace): fix some cases for clippy
  node/cli/src/cli.rs
  pallets/staking-rewards/src/migrations.rs
Labels: A0-pleasereview, A4-insubstantial

#3772 chore(runtime): remove old migrations
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migrations.rs
  runtime/vara/src/migrations.rs
Labels: A2-mergeoncegreen
