Repository gear-tech/gear, pull requests merged in 2024-10, with the labels that each got.

#4269 feat(ethexe): add storage key for upcoming scheduler and manage it
  Cargo.lock
  ethexe/common/Cargo.toml
  ethexe/common/src/db.rs
  ethexe/db/src/database.rs
  ethexe/observer/src/query.rs
  ethexe/processor/Cargo.toml
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/handling/mod.rs
  ethexe/processor/src/handling/tasks.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
Labels: A0-pleasereview

#4272 feat(ethexe): impl InBlockTransition (temp changes within the block)
  Cargo.lock
  _typos.toml
  common/src/auxiliary/task_pool.rs
  common/src/scheduler.rs
  common/src/scheduler/mod.rs
  core/src/lib.rs
  core/src/tasks.rs
  ethexe/common/Cargo.toml
  ethexe/common/src/db.rs
  ethexe/common/src/router.rs
  ethexe/processor/Cargo.toml
  ethexe/processor/src/common.rs
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/handling/run.rs
  ethexe/processor/src/handling/tasks.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/runtime/common/Cargo.toml
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/transitions.rs
  gsdk/src/metadata/generated.rs
  gtest/src/manager.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/reservations.rs
  gtest/src/manager/task.rs
  gtest/src/state/task_pool.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-scheduler/src/lib.rs
  pallets/gear-scheduler/src/tests.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#4273 feat(ethexe): impl scheduled program wakes; restore `many-waits` test
  ethexe/common/src/db.rs
  ethexe/db/src/database.rs
  ethexe/processor/src/handling/mod.rs
  ethexe/processor/src/handling/run.rs
  ethexe/processor/src/handling/tasks.rs
  ethexe/processor/src/host/mod.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/common/src/transitions.rs
  ethexe/runtime/src/wasm/api/mod.rs
  ethexe/runtime/src/wasm/api/run.rs
Labels: A0-pleasereview

#4271 refactor(gstd): use waker-fn instead of unsafe code
  Cargo.lock
  gstd/Cargo.toml
  gstd/src/async_runtime/futures.rs
  gstd/src/async_runtime/mod.rs
  gstd/src/async_runtime/waker.rs
Labels: A0-pleasereview

#4278 chore(docs): disable `ethexe` feature on docs.rs, improve docs.gear.rs
  Makefile
  gstd/Cargo.toml
Labels: A0-pleasereview

#4281 chore(workspace): Bump versions to 1.6.2
  Cargo.lock
  Cargo.toml
  core/src/gas_metering/schedule.rs
  pallets/gear/src/schedule.rs
  runtime/vara/src/lib.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A2-mergeoncegreen, A4-insubstantial

#4283 feat(ethexe): use real block header in handling; impl Mailbox timeouts; remove scheduled tasks on actions
  core-processor/src/ext.rs
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/common/src/db.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/network/src/lib.rs
  ethexe/observer/src/event.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/observer.rs
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/handling/mod.rs
  ethexe/processor/src/handling/run.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/rpc/src/lib.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/common/src/transitions.rs
  ethexe/sequencer/src/lib.rs
  gcli/src/cmd/program.rs
  gprimitives/src/nonzero_u256.rs
  lazy-pages/src/common.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/pages.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  sandbox/host/src/sandbox/wasmer_backend/store_refcell.rs
  utils/calc-stack-height/src/main.rs
  utils/gring/src/keyring.rs
  utils/gring/tests/command.rs
  utils/lazy-pages-fuzzer/src/config.rs
  utils/node-loader/src/args.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/module.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/generator.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-optimizer/src/optimize.rs
Labels: A0-pleasereview

#4285 fix(ethexe): Fix critical bug of prefix iterating RocksDB
  ethexe/db/src/lib.rs
  ethexe/db/src/rocks.rs
Labels: A0-pleasereview, C0-bug

#4286 testnet: rotate bootnodes keys
  node/res/vara_testnet.json
Labels: A2-mergeoncegreen

#4291 feat(ethexe): handle incoming transfers: from messaging and from direct WVara erc20.transfer(..)
  ethexe/cli/src/tests.rs
  ethexe/processor/src/handling/events.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/signer/src/lib.rs
Labels: A0-pleasereview

#4290 feat(ethexe): delayed messaging
  common/src/auxiliary/task_pool.rs
  core/src/tasks.rs
  ethexe/common/src/db.rs
  ethexe/db/src/database.rs
  ethexe/processor/src/lib.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/src/wasm/storage.rs
  gsdk/src/metadata/generated.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/task.rs
  gtest/src/state/task_pool.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-scheduler/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/mock.rs
Labels: A0-pleasereview

#4293 fix(ci): install rust-src component for stable rust
  .github/workflows/check.yml
Labels: A0-pleasereview

#4294 feat(ethexe-ethereum): Update alloy to 0.4.2
  Cargo.lock
  Cargo.toml
  ethexe/ethereum/src/lib.rs
  ethexe/signer/Cargo.toml
  ethexe/signer/src/signature.rs
Labels: A2-mergeoncegreen

#4297 feat(gear-reply-cli): Check that the snapshot is for the previous block
  utils/gear-replay-cli/src/cmd/replay_block.rs
  utils/gear-replay-cli/src/lib.rs
Labels: A0-pleasereview, C1-feature, D5-tooling

#4302 feat(ethexe): handle freed pages of programs memory
  Makefile
  ethexe/cli/src/config.rs
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/handling/mod.rs
  ethexe/processor/src/lib.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/signer/src/lib.rs
  utils/calc-stack-height/src/main.rs
  utils/wasm-builder/src/crate_info.rs
  utils/wasm-optimizer/src/cargo_toolchain.rs
Labels: A0-pleasereview

#4292 feat(ethexe): support programs exiting
  ethexe/common/src/router.rs
  ethexe/contracts/src/IMirror.sol
  ethexe/contracts/src/IRouter.sol
  ethexe/contracts/src/Mirror.sol
  ethexe/contracts/src/Router.sol
  ethexe/contracts/test/Router.t.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/abi.rs
  ethexe/processor/src/handling/events.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/transitions.rs
  ethexe/signer/src/digest.rs
  ethexe/validator/src/lib.rs
Labels: A0-pleasereview

#4306 feat(crates-io): publish gbuiltins
  Cargo.lock
  gbuiltins/staking/Cargo.toml
  gbuiltins/staking/src/lib.rs
  utils/crates-io/src/lib.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#4305 refactor(gstd,utils,runtime-interface): get rid of uncecessary clippy lints
  gstd/src/prelude.rs
  runtime-interface/sandbox/src/detail.rs
  utils/gring/src/keyring.rs
  utils/gring/src/keystore.rs
Labels: A0-pleasereview

#4243 feat(ethexe): Initial on-chain `db-sync` request validation
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/network/src/db_sync/mod.rs
  ethexe/network/src/db_sync/ongoing.rs
  ethexe/network/src/lib.rs
  ethexe/network/src/peer_score.rs
Labels: A0-pleasereview

#4316 chore(deps): remove ethers in favor of alloy
  Cargo.lock
  Cargo.toml
  ethexe/cli/src/tests.rs
  ethexe/signer/Cargo.toml
  ethexe/signer/src/lib.rs
Labels: A0-pleasereview
