Repository gear-tech/gear, pull requests merged in 2024-01, with the labels that each got.

#3635 chore(runtime): Bump versions after `v1.0.4` release
  Cargo.lock
  Cargo.toml
  runtime/vara/src/lib.rs
Labels: A4-insubstantial

#3633 fix(vara): Add staking admin origin to pallet-staking
  runtime/vara/src/governance/origins.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3629 chore(manifest): complete package alias for code generator libararies
  Cargo.toml
  gsdk/Cargo.toml
  gstd/Cargo.toml
Labels: A4-insubstantial

#3623 chore(runtime-interface): handle std for sp-io
  Cargo.toml
  runtime-interface/Cargo.toml
Labels: A2-mergeoncegreen

#3596 refactor(workspace): replace static-assertions with const fn expressions
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  core/src/lib.rs
  core/src/memory.rs
  core/src/message/mod.rs
  core/src/pages.rs
  examples/stack-allocations/Cargo.toml
  examples/stack-allocations/src/lib.rs
  gclient/Cargo.toml
  gclient/src/api/calls.rs
  gcore/Cargo.toml
  gcore/src/lib.rs
  gstd/Cargo.toml
  gstd/src/lib.rs
  pallets/gear-program/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/gear/src/schedule.rs
  runtime-interface/Cargo.toml
  runtime-interface/src/lib.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  scripts/src/clippy.sh
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/generator/syscalls/invocator.rs
Labels: A2-mergeoncegreen, A4-insubstantial

#3590 chore: Remove the current rent functionality
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/handler.rs
  core-processor/src/processing.rs
  examples/syscalls/src/wasm.rs
  gcore/src/exec.rs
  gsdk/src/metadata/generated.rs
  gstd/src/exec/basic.rs
  gsys/src/lib.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear-debug/src/tests/utils.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tasks.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
  pallets/gear/src/weights.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/wasm-gen/src/tests.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring, A3-gotissues

#3606 feat(runtime): Revokable vouchers
  Cargo.lock
  common/src/lib.rs
  core/src/ids.rs
  gsdk/src/metadata/generated.rs
  pallets/gear-voucher/Cargo.toml
  pallets/gear-voucher/src/benchmarking.rs
  pallets/gear-voucher/src/internal.rs
  pallets/gear-voucher/src/lib.rs
  pallets/gear-voucher/src/mock.rs
  pallets/gear-voucher/src/tests.rs
  pallets/gear-voucher/src/weights.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/lib.rs
  pallets/payment/src/mock.rs
  pallets/payment/src/tests.rs
  pallets/staking-rewards/src/extension.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
Labels: B1-releasenotes

#3503 feat(gstd): Introduce critical hook
  Cargo.lock
  Cargo.toml
  examples/async-critical/Cargo.toml
  examples/async-critical/build.rs
  examples/async-critical/src/lib.rs
  examples/async-critical/src/wasm.rs
  gstd/src/async_runtime/futures.rs
  gstd/src/async_runtime/mod.rs
  gstd/src/critical.rs
  gstd/src/lib.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D3-gstd, B1-releasenotes

#3594 feat(crates-io): publish gtest on crates.io
  .github/workflows/crates-io.yml
  Cargo.lock
  Cargo.toml
  common/src/pallet_tests.rs
  gcli/src/cmd/key.rs
  gtest/Cargo.toml
  utils/crates-io/src/handler.rs
  utils/crates-io/src/lib.rs
  utils/crates-io/src/main.rs
  utils/crates-io/src/manifest.rs
  utils/crates-io/src/publisher.rs
  utils/crates-io/src/version.rs
  utils/wasm-instrument/Cargo.toml
Labels: A0-pleasereview, A2-mergeoncegreen

#3655 refactor(rpc-call): Never return `<wasm:stripped>` from rpc calls
  gsdk/tests/rpc.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node, C0-bug

#3653 fix(rpc-calls): Calculate gas for empty accounts
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node, C0-bug

#3664 refactor!(backend): Remove `gr_pay_program_rent` syscall
  core-backend/src/env.rs
  core-backend/src/funcs.rs
  core-backend/src/mock.rs
  core-errors/src/lib.rs
  core-processor/src/ext.rs
  core/src/costs.rs
  core/src/env.rs
  examples/syscalls/src/lib.rs
  examples/syscalls/src/wasm.rs
  gcli/src/meta/executor.rs
  gcore/src/exec.rs
  gsdk/src/metadata/generated.rs
  gstd/src/exec/basic.rs
  gsys/src/lib.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/vara/src/weights/pallet_gear.rs
  utils/regression-analysis/src/main.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A0-pleasereview

#3666 chore(migrations): Fix migrations warning
  pallets/gear/src/lib.rs
  runtime/vara/src/migrations.rs
Labels: A4-insubstantial

#3527 feat(gstd): get panic message without `panic_info_message`
  Cargo.lock
  Cargo.toml
  core-backend/src/error.rs
  examples/waiter/tests/utils.rs
  gstd/Cargo.toml
  gstd/src/common/handlers.rs
  gstd/src/common/mod.rs
  gstd/src/lib.rs
  gtest/src/program.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, A2-mergeoncegreen, D3-gstd

#3627 refactor(wasm-gen): Update `wasm-gen` docs
  utils/runtime-fuzzer/src/gear_calls.rs
  utils/wasm-gen/src/config.rs
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/generator.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/additional_data.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/utils.rs
  utils/wasm-gen/src/wasm.rs
Labels: A2-mergeoncegreen, D4-test, D5-tooling

#3459 fix(wasm-builder): allow building with stable toolchain
  .github/workflows/check.yml
  examples/out-of-memory/Cargo.toml
  examples/out-of-memory/build.rs
  utils/wasm-builder/src/builder_error.rs
  utils/wasm-builder/src/cargo_command.rs
  utils/wasm-builder/src/cargo_toolchain.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/tests/smoke.rs
Labels: A2-mergeoncegreen, D5-tooling

#3673 fix(CI): Force CI to run all benchmarks
  .github/workflows/build.yml
  pallets/gear-voucher/src/benchmarking.rs
Labels: A0-pleasereview

#3672 feat(runtime): Add support of `upload_code` for vouchers
  gsdk/src/metadata/generated.rs
  pallets/gear-voucher/src/benchmarking.rs
  pallets/gear-voucher/src/internal.rs
  pallets/gear-voucher/src/lib.rs
  pallets/gear-voucher/src/tests.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/tests.rs
Labels: A2-mergeoncegreen

#3674 fix(rpc-call): Return error on failing init as well as for the traps
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#3678 fix(core-processor): fix double value charge when program terminated
  core-processor/src/processing.rs
  examples/custom/src/lib.rs
  examples/custom/src/wake_after_exit.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#3679 chore(runtime): Bump versions after `v1.0.5` release
  Cargo.lock
  Cargo.toml
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#3677 chore(runtime): Update weights
  pallets/gear/src/schedule.rs
  pallets/gear/src/weights.rs
  runtime/common/src/weights.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/frame_system.rs
  runtime/vara/src/weights/pallet_balances.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
  runtime/vara/src/weights/pallet_timestamp.rs
  runtime/vara/src/weights/pallet_utility.rs
Labels: A0-pleasereview

#3688 chore(docs): replace "contract" by "program"
  core-backend/src/runtime.rs
  core-errors/signal-code-testing.md
  core-errors/src/lib.rs
  core-processor/src/context.rs
  core-processor/src/ext.rs
  core/src/code.rs
  examples/calc-hash/over-blocks/src/wasm.rs
  examples/compose/src/lib.rs
  examples/compose/src/wasm.rs
  examples/mul-by-const/src/lib.rs
  examples/mul-by-const/src/wasm.rs
  examples/ncompose/src/lib.rs
  examples/ncompose/src/wasm.rs
  examples/new-meta/state-v1/src/wasm.rs
  examples/stack-allocations/src/lib.rs
  examples/stack-allocations/src/wasm.rs
  examples/syscalls/src/lib.rs
  examples/waiting-proxy/src/wasm.rs
  galloc/README.md
  galloc/docs/optimization.md
  gcore/README.md
  gcore/src/exec.rs
  gmeta/codegen/src/lib.rs
  gmeta/src/lib.rs
  gstd/Cargo.toml
  gstd/README.md
  gstd/codegen/src/lib.rs
  gstd/src/async_runtime/locks.rs
  gstd/src/async_runtime/waker.rs
  gstd/src/common/errors.rs
  gstd/src/common/handlers.rs
  gstd/src/common/mod.rs
  gtest/src/lib.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/process.rs
  lazy-pages/src/signal.rs
  pallets/gear-voucher/README.md
  pallets/gear-voucher/src/lib.rs
  pallets/gear/src/benchmarking/code.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/tests.rs
  sandbox/host/src/sandbox/wasmer_backend.rs
  sandbox/sandbox/README.md
  sandbox/sandbox/src/lib.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A4-insubstantial

#3657 ci(PR): introduce action message
  .github/actions/label/skip.js
  .github/actions/message/README.md
  .github/actions/message/action.yml
  .github/actions/message/main.js
  .github/actions/message/package.json
  .github/workflows/PR.yml
Labels: A4-insubstantial, E2-forcemacos

#3649 feat(wasm-builder): Check all `gear` requirements for code at compile time
  core/src/code.rs
  utils/wasm-builder/src/optimize.rs
  utils/wasm-instrument/src/syscalls.rs
Labels: A0-pleasereview, B1-releasenotes, C1-feature, D5-tooling

#3694 fix(core): fix export is import case in wasm code
  core/src/code.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview
