Repository gear-tech/gear, pull requests merged in 2024-09, with the labels that each got.

#4214 fix(gstd): parse panic message correctly
  gstd/src/common/handlers.rs
Labels: A0-pleasereview

#4200 refactor(gtest): Actualize message queue processing
  examples/autoreply/src/wasm.rs
  examples/program-factory/src/lib.rs
  examples/signal-entry/src/wasm.rs
  gtest/src/manager.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/expend.rs
  gtest/src/manager/journal.rs
  gtest/src/program.rs
  gtest/src/state/actors.rs
  gtest/src/system.rs
Labels: A2-mergeoncegreen, D5-tooling

#4207 fix(gtest): update `ActorMailbox::claim_value` and `ActorMailbox::reply`
  gtest/src/manager/block_exec.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/wait_wake.rs
  gtest/src/state/blocks.rs
  gtest/src/state/mailbox/actor.rs
Labels: A0-pleasereview

#4209 feat(wasm-builder): Successful build returns paths to the wasm and opt wasm files
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-optimizer/src/optimize.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#4189 fix(pallets-gear, wasm-instrument): take in account Wasmer's optimization when calculating instructions' weights
  core/src/gas_metering/schedule.rs
  pallets/gear/src/schedule.rs
  runtime/vara/src/tests.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A0-pleasereview

#4205 fix(gtest): clean waitlist on exit_dispatch
  gtest/src/manager/journal.rs
  gtest/src/manager/wait_wake.rs
  gtest/src/state/waitlist.rs
Labels: A2-mergeoncegreen

#4217 chore(ethexe): bump alloy to 0.3.1
  Cargo.lock
  Cargo.toml
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/TransparentUpgradeableProxy.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/lib.rs
  ethexe/observer/src/observer.rs
  ethexe/observer/src/query.rs
Labels: A0-pleasereview

#4218 fix(runtime): Fix staking payout call weight; impl test
  common/src/pallet_tests.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/tests.rs
Labels: A2-mergeoncegreen

#4220 fix(gtest): Fix execution model for mock wasms in `gtest`
  core-processor/Cargo.toml
  core-processor/src/context.rs
  core-processor/src/lib.rs
  gtest/Cargo.toml
  gtest/src/manager.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/hold_bound.rs
  gtest/src/program.rs
  gtest/src/state/actors.rs
  gtest/src/system.rs
Labels: A0-pleasereview, D5-tooling

#4216 feat(gtest): proper charging of gas allowance in gtest
  core/src/gas_metering/schedule.rs
  gsdk/src/metadata/generated.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/expend.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/reservations.rs
  gtest/src/manager/send_dispatch.rs
  gtest/src/manager/task.rs
  gtest/src/manager/wait_wake.rs
  gtest/src/state/mailbox/actor.rs
  pallets/gear/src/schedule.rs
  utils/weight-diff/src/main.rs
Labels: A0-pleasereview

#4182 feat(ethexe): introduce test-only field status for Service
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
Labels: A0-pleasereview

#4221 fix(ethexe): problem with too fast request to rpc after transaction confirmation
  Cargo.lock
  ethexe/cli/src/tests.rs
  ethexe/ethereum/Cargo.toml
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/TransparentUpgradeableProxy.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/mirror/mod.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/ethereum/src/wvara/mod.rs
Labels: A0-pleasereview

#4227 fix(ethexe): revert "feat(ethexe): introduce test-only field status for Service (#4182)"
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
Labels: A0-pleasereview

#4225 feat(gsdk): introduce api builder
  gcli/src/app.rs
  gclient/src/api/mod.rs
  gsdk/src/api.rs
  gsdk/src/client.rs
  gsdk/src/lib.rs
  gsdk/tests/main.rs
Labels: A0-pleasereview

#4229 chore(deps): update alloy-sol-type-parser, remove old code
  Cargo.lock
  Cargo.toml
  ethexe/cli/src/tests.rs
  ethexe/observer/src/observer.rs
Labels: A0-pleasereview

#4223 refactor(gtest): update user-facing panic messages
  gtest/src/error.rs
  gtest/src/log.rs
  gtest/src/manager.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/memory.rs
  gtest/src/program.rs
  gtest/src/state/accounts.rs
  gtest/src/state/actors.rs
  gtest/src/state/bank.rs
  gtest/src/state/mailbox/actor.rs
  gtest/src/system.rs
Labels: A0-pleasereview

#4195 feat(ethexe): Initial peer scoring system
  ethexe/network/src/db_sync/mod.rs
  ethexe/network/src/db_sync/ongoing.rs
  ethexe/network/src/lib.rs
  ethexe/network/src/peer_score.rs
Labels: A0-pleasereview

#4098 feat(gstd) use stabilized `panic_info_message` feature from rust 1.81
  Cargo.lock
  Cargo.toml
  gstd/Cargo.toml
  gstd/src/common/handlers.rs
  gstd/src/lib.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-optimizer/src/cargo_command.rs
Labels: A0-pleasereview, D3-gstd

#4190 feat(ethexe): Only handle non-informational events
  core/src/message/context.rs
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/common/src/db.rs
  ethexe/common/src/lib.rs
  ethexe/common/src/mirror.rs
  ethexe/common/src/router.rs
  ethexe/common/src/wvara.rs
  ethexe/db/src/database.rs
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/mirror/events.rs
  ethexe/ethereum/src/mirror/mod.rs
  ethexe/ethereum/src/router/events.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/ethereum/src/wvara/events.rs
  ethexe/observer/src/event.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/observer.rs
  ethexe/observer/src/query.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/sequencer/src/lib.rs
  runtime-interface/src/lib.rs
Labels: A0-pleasereview

#4112 chore(gear): replace dust handling entirely with gear-bank pallet
  pallets/gear/src/internal.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#4234 feat(ethexe): Add TCP fallback transport
  Cargo.lock
  ethexe/cli/src/chain_spec.rs
  ethexe/network/Cargo.toml
  ethexe/network/src/lib.rs
Labels: A0-pleasereview

#4211 test(ethexe): multiple validators test
  Cargo.lock
  core/src/message/mod.rs
  ethexe/cli/Cargo.toml
  ethexe/cli/src/tests.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/network/src/lib.rs
Labels: A0-pleasereview

#4232 chore(gtest): Resolve multiple small issues in `gtest`
  gtest/src/log.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/task.rs
  gtest/src/program.rs
Labels: A0-pleasereview, D5-tooling

#4240 feat(gtest): add self-sent delayed message test
  Cargo.lock
  examples/delayed-sender/src/wasm.rs
  gtest/Cargo.toml
  gtest/src/program.rs
Labels: A0-pleasereview

#4238 feat(ethexe): impl basis for runtime related RPC calls; impl `calculate_reply_for_handle` v1
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  core/src/message/mod.rs
  ethexe/cli/src/service.rs
  ethexe/common/src/db.rs
  ethexe/db/src/database.rs
  ethexe/db/src/lib.rs
  ethexe/db/src/overlay.rs
  ethexe/observer/src/query.rs
  ethexe/processor/src/host/mod.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/run.rs
  ethexe/processor/src/tests.rs
  ethexe/rpc/Cargo.toml
  ethexe/rpc/src/lib.rs
Labels: A2-mergeoncegreen

#4247 feat(wasm-optimizer): build WASMs with `-Ctarget-cpu=mvp`
  Cargo.lock
  utils/wasm-optimizer/Cargo.toml
  utils/wasm-optimizer/src/cargo_command.rs
  utils/wasm-optimizer/src/cargo_toolchain.rs
Labels: A2-mergeoncegreen

#4249 chore(workspace): Bump versions to 1600
  Cargo.lock
  Cargo.toml
  core/src/gas_metering/schedule.rs
  pallets/gear/src/schedule.rs
  runtime/vara/src/lib.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A2-mergeoncegreen, A4-insubstantial

#4254 fix(crates-io): pin to specific version
  utils/crates-io/src/manifest.rs
Labels: A0-pleasereview

#4256 fix(ethexe): multiple validators test fix
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/network/src/lib.rs
  ethexe/sequencer/src/lib.rs
  ethexe/validator/src/lib.rs
Labels: A0-pleasereview

#4257 feat(ethexe): impl Mailbox interactions
  Cargo.lock
  Makefile
  ethexe/cli/Cargo.toml
  ethexe/cli/src/tests.rs
  ethexe/db/src/database.rs
  ethexe/processor/src/lib.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/src/wasm/storage.rs
Labels: A0-pleasereview

#4262 chore(workspace): Bump version to 1.6.1
  Cargo.lock
  Cargo.toml
  core/src/gas_metering/schedule.rs
  pallets/gear/src/schedule.rs
  runtime/vara/src/lib.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A2-mergeoncegreen, A4-insubstantial

#4265 feat(ethexe): Correctly handle storage complex operations
  Cargo.lock
  Cargo.toml
  ethexe/cli/src/tests.rs
  ethexe/processor/src/common.rs
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/handling/mod.rs
  ethexe/processor/src/handling/run.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/runtime/common/Cargo.toml
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/state.rs
  utils/gring/Cargo.toml
  utils/wasm-optimizer/Cargo.toml
Labels: A0-pleasereview

#4261 chore(tooling): Use wasmer instead of wasmi
  Cargo.lock
  Cargo.toml
  gcli/Cargo.toml
  gcli/src/meta/executor.rs
  gcli/src/result.rs
  sandbox/host/Cargo.toml
  sandbox/host/src/sandbox.rs
  sandbox/host/src/sandbox/wasmer_backend.rs
  sandbox/host/src/sandbox/wasmer_backend/cache.rs
  sandbox/host/src/sandbox/wasmer_backend/store_refcell.rs
  utils/calc-stack-height/Cargo.toml
  utils/calc-stack-height/src/main.rs
  utils/crates-io/src/handler.rs
  utils/crates-io/src/manifest.rs
  utils/lazy-pages-fuzzer/Cargo.toml
  utils/lazy-pages-fuzzer/src/wasmer_backend.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-optimizer/Cargo.toml
  utils/wasm-optimizer/src/stack_end.rs
Labels: A0-pleasereview, D5-tooling

#4270 fix(gtest): Fix gas tree ops to avoid `split`/`split_with_value` when both reply is sent and reply deposit exists
  gtest/src/manager/journal.rs
  gtest/src/state/gas_tree.rs
Labels: A2-mergeoncegreen, D5-tooling
