Repository gear-tech/gear, pull requests merged in 2024-03, with the labels that each got.

#3776 chore(wasm-gen): fix `SyscallsParamsConfig::default()`, improve tests
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/tests.rs
Labels: A4-insubstantial

#3774 fix(CI): install wasm-opt for x86 macos
  .github/workflows/build-macos.yml
Labels: A0-pleasereview, E2-forcemacos, E1-forcenatwin

#3778 fix(tools): Generate .binpath only on primary artifact
  utils/wasm-builder/src/wasm_project.rs
Labels: A2-mergeoncegreen

#3755 feat(pallet-gear): test program with large indexes
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, Q3-involved

#3780 fix(rpc-call): Return known value in case of finite waits
  examples/constructor/src/scheme/mod.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, D2-node, C0-bug

#3743 fix!(pallet-gear): append outgoing bytes limit to prevent runtime allocator overflow
  core-errors/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processing.rs
  core/src/message/context.rs
  core/src/message/handle.rs
  core/src/message/init.rs
  core/src/message/mod.rs
  core/src/message/reply.rs
  gtest/src/manager.rs
  node/service/src/lib.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/pallet_tests.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/mock.rs
  runtime/vara/src/lib.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview, A3-gotissues

#3783 fix(gtest): Remove useless brackets
  gtest/src/program.rs
Labels: A4-insubstantial

#3786 refactor(benchmarks): remove garbage from benchmarks
  .github/workflows/comparison-table.yml
  .maintain/frame-weight-template.hbs
  common/src/benchmarking.rs
  pallets/gear/src/weights.rs
  runtime/vara/src/weights/pallet_gear.rs
Labels: A0-pleasereview

#3795 refactor(core): change `PageU32Size` to `PageNumber` in `CostPerPage`
  core/src/costs.rs
Labels: A0-pleasereview

#3796 fix(gtest): Replace opinionated submit_code with non-opinionated
  examples/program-factory/src/lib.rs
  gtest/src/system.rs
Labels: A0-pleasereview

#3785 fix(core): set taken payload back in case of errors in `MessageContext`
  core/src/message/context.rs
  core/src/message/handle.rs
  core/src/message/reply.rs
Labels: A0-pleasereview

#3792 refactor(wasm-instrument): add docs, simplify code
  core-backend/src/env.rs
  core-backend/src/tests.rs
  core/src/code/mod.rs
  core/src/program.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  utils/wasm-gen/src/config/syscalls/injection.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/rules.rs
  utils/wasm-instrument/src/syscalls.rs
  utils/wasm-instrument/src/tests.rs
Labels: A0-pleasereview, C2-refactoring

#3802 fix(pallet-gear): fix CI build
  pallets/gear/src/schedule.rs
Labels: A0-pleasereview

#3781 refactor(node): Hold the instance of BuiltinDispatcher in ExtManager
  gsdk/src/metadata/generated.rs
  pallets/gear-builtin/src/benchmarking.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-builtin/src/weights.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tasks.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/builtin.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/mock.rs
  pallets/gear/src/pallet_tests.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen, D2-node, C2-refactoring

#3806 chore!(workspace): Bump versions and dump gas price
  Cargo.lock
  Cargo.toml
  gcli/tests/cmd/claim.rs
  gtest/src/lib.rs
  pallets/gear-bank/src/mock.rs
  pallets/gear-bank/src/tests.rs
  pallets/gear/src/schedule.rs
  runtime/common/src/lib.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
Labels: A2-mergeoncegreen

#3803 refactor(tests): Revamp gear-authorship tests
  Cargo.lock
  Cargo.toml
  node/authorship/Cargo.toml
  node/authorship/src/tests.rs
  node/testing/Cargo.toml
  node/testing/src/client.rs
Labels: A2-mergeoncegreen, C2-refactoring, D4-test

#3810 chore: Update substrate to use sp-crypto-ec-utils v1.6.0
  Cargo.lock
Labels: A0-pleasereview, C2-refactoring, dependencies

#3794 refactor: Auto-publish releases
  .github/workflows/CI-docker-gear.yml
  .github/workflows/release.yml
  .github/workflows/release_listener.yml
  docker/Dockerfile-release
Labels: A0-pleasereview

#3800 chore(examples): introduce program creation test in async-tester
  examples/async-tester/src/lib.rs
  examples/async-tester/src/wasm.rs
  examples/ping/src/wasm.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#3616 chore(ci): Use `debug` & `release` profiles
  .github/actions/message/action.yml
  .github/actions/message/main.js
  .github/workflows/CI.yaml
  .github/workflows/PR.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-win-native.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/crates-io.yml
  .github/workflows/label.yml
  .github/workflows/typos.yml
  Makefile
  gcli/src/app.rs
  gcli/src/cmd/mod.rs
  gcli/tests/common/app.rs
  gcli/tests/common/env.rs
  gcli/tests/common/mod.rs
  gcli/tests/gear.rs
  gsdk/HOW-TO-UPDATE.md
  pallets/gear-voucher/Cargo.toml
  pallets/gear-voucher/src/benchmarking.rs
  scripts/src/test.sh
  scripts/update-gsdk-metadata.sh
  scripts/weight-diff.sh
  utils/gring/src/cmd.rs
Labels: A0-pleasereview, D5-tooling, E2-forcemacos, E1-forcenatwin, E3-forcerelease

#3808 feat(gtest): use real weights
  .github/workflows/benchmarks.yml
  .gitignore
  Cargo.lock
  core-backend/src/tests.rs
  core/src/code/mod.rs
  core/src/program.rs
  gsdk/Cargo.toml
  gsdk/api-gen/Cargo.toml
  gsdk/api-gen/src/main.rs
  gsdk/build.rs
  gsdk/src/metadata/generated.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  scripts/weight-dump.sh
  utils/utils/src/codegen.rs
  utils/utils/src/lib.rs
  utils/wasm-builder/src/code_validator.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-instrument/src/gas_metering/mod.rs
  utils/wasm-instrument/src/gas_metering/rules.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/rules.rs
  utils/wasm-instrument/src/tests.rs
  utils/weight-diff/Cargo.toml
  utils/weight-diff/src/main.rs
Labels: A0-pleasereview

#3769 ci(PR): gather pull request actions in `PR.yml`
  .github/actions/docs/action.yml
  .github/actions/label/build.js
  .github/actions/message/main.js
  .github/workflows/PR.yml
  .github/workflows/docs.yml
  .github/workflows/typos.yml
Labels: A2-mergeoncegreen, A4-insubstantial

#3801 feat(sandbox): Implement LRU cache for Wasmer modules
  Cargo.lock
  Cargo.toml
  sandbox/host/Cargo.toml
  sandbox/host/src/sandbox/wasmer_backend.rs
Labels: A0-pleasereview, E2-forcemacos, check-validator

#3820 ci(docs): fix the parameters of docs in master
  .github/workflows/docs.yml
Labels: A2-mergeoncegreen, A4-insubstantial

#3767 ci(PR): manage validator checks in `PR.yml`
  .github/actions/message/action.yml
  .github/actions/message/main.js
  .github/workflows/PR.yml
  .github/workflows/validation.yml
Labels: A2-mergeoncegreen, A4-insubstantial, check-validator

#3822 chore(wasm-builder): Test features tracking
  Cargo.lock
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/test-program/Cargo.toml
  utils/wasm-builder/test-program/src/lib.rs
  utils/wasm-builder/tests/smoke.rs
Labels: A2-mergeoncegreen, D4-test

#3811 feat(core): append stack end in `InstrumentedCode`
  core-backend/src/env.rs
  core-backend/src/tests.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/lib.rs
  core/src/code/errors.rs
  core/src/code/instrumented.rs
  core/src/code/mod.rs
  core/src/code/utils.rs
  core/src/program.rs
  gsdk/src/metadata/generated.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migration.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  runtime/vara/src/migrations.rs
  utils/wasm-builder/src/code_validator.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview

#3831 fix(node): Do not take SKIP_WASM_BUILD into account
  utils/wasm-builder/src/lib.rs
Labels: A0-pleasereview, D2-node

#3823 fix(ci): Don't build production binaries in the debug job
  .github/actions/message/action.yml
  .github/actions/message/main.js
  .github/workflows/CI.yaml
  .github/workflows/PR.yml
  .github/workflows/build.yml
Labels: A2-mergeoncegreen, D5-tooling, E3-forcerelease, E4-forceproduction

#3827 ci(build): fix the condition of artifacts
  .github/actions/label/build.js
  .github/actions/message/main.js
  .github/workflows/build.yml
  .github/workflows/label.yml
Labels: D5-tooling, A4-insubstantial

#3829 refactor(core): Costs refactoring
  core-backend/src/funcs.rs
  core-backend/src/mock.rs
  core-backend/src/runtime.rs
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/lib.rs
  core-processor/src/precharge.rs
  core-processor/src/processing.rs
  core/src/costs.rs
  core/src/gas.rs
  gsdk/src/metadata/generated.rs
  gstd/src/critical.rs
  gtest/src/manager.rs
  lazy-pages/common/src/lib.rs
  lazy-pages/interface/src/lib.rs
  lazy-pages/src/common.rs
  lazy-pages/src/host_func.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/signal.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  runtime-interface/src/lib.rs
  runtime/common/src/weights.rs
  runtime/vara/src/tests.rs
  utils/regression-analysis/src/main.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
  utils/weight-diff/src/main.rs
Labels: A0-pleasereview

#3814 feat: Update substrate to v1.1.0
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/src/event.rs
  common/src/gas_provider/mod.rs
  common/src/gas_provider/node.rs
  common/src/lib.rs
  common/src/scheduler/task.rs
  common/src/storage/complicated/dequeue.rs
  common/src/storage/primitives/map.rs
  common/src/storage/primitives/mod.rs
  gsdk/src/metadata/generated.rs
  node/authorship/src/authorship.rs
  node/authorship/src/block_builder.rs
  node/authorship/src/tests.rs
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  node/service/src/rpc/mod.rs
  node/testing/src/client.rs
  pallets/gas/src/lib.rs
  pallets/gear-bank/src/tests.rs
  pallets/gear-messenger/Cargo.toml
  pallets/gear-messenger/src/lib.rs
  pallets/gear-messenger/src/migrations.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migration.rs
  pallets/gear-scheduler/Cargo.toml
  pallets/gear-scheduler/src/lib.rs
  pallets/gear-voucher/src/benchmarking.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/payment/src/tests.rs
  pallets/staking-rewards/Cargo.toml
  pallets/staking-rewards/src/extension.rs
  pallets/staking-rewards/src/mock.rs
  runtime/common/src/apis.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  utils/gear-replay-cli/src/cmd/gear_run.rs
  utils/gear-replay-cli/src/cmd/replay_block.rs
  utils/gear-replay-cli/src/util.rs
  utils/regression-analysis/src/main.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
Labels: A0-pleasereview, D2-node, C1-feature
