Repository gear-tech/gear, pull requests merged in 2024-12, with the labels that each got.

#4340 feat(gear.exe): append slasher logic to middleware
  ethexe/contracts/src/Middleware.sol
  ethexe/contracts/test/Middleware.t.sol
Labels: A0-pleasereview

#4372 feat(ethexe): refactor and optimize mirror; split initialization logic; remove unnecessary token manipulations
  ethexe/cli/src/args.rs
  ethexe/cli/src/tests.rs
  ethexe/contracts/src/IMirror.sol
  ethexe/contracts/src/IRouter.sol
  ethexe/contracts/src/Middleware.sol
  ethexe/contracts/src/Mirror.sol
  ethexe/contracts/src/Router.sol
  ethexe/contracts/test/Router.t.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/TransparentUpgradeableProxy.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/abi/mod.rs
  ethexe/ethereum/src/mirror/mod.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/runtime/src/wasm/storage.rs
Labels: A2-mergeoncegreen

#4374 fix(gcore): add proper conditional compilation for stack_debug macro
  gcore/src/utils.rs
Labels: A0-pleasereview

#4378 feat(ethexe): pass mirror address to decoder's initialise args
  ethexe/contracts/src/IMirrorDecoder.sol
  ethexe/contracts/src/Router.sol
Labels: A2-mergeoncegreen

#4368 chore: Use `cfg(fuzz)` instead of feature
  .github/workflows/check.yml
  Cargo.toml
  common/Cargo.toml
  common/src/gas_provider/internal.rs
  pallets/gas/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/gear/src/schedule.rs
  runtime/vara/Cargo.toml
  runtime/vara/build.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/tests.rs
  scripts/src/build.sh
  scripts/src/check.sh
  scripts/src/clippy.sh
  scripts/src/test.sh
  utils/gear-wasmer-cache/Cargo.toml
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/src/tests.rs
Labels: A0-pleasereview, D5-tooling

#4387 fix(runtime): Vara Network Testnet metadata
  node/service/src/chain_spec/vara.rs
  runtime/common/src/constants.rs
  runtime/vara/build.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen

#4389 fix(features): don't force metadata hash for node build
  .github/workflows/release.yml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: A2-mergeoncegreen

#4388 fix(release): change spec version extraction query
  .github/workflows/release.yml
Labels: A2-mergeoncegreen

#4363 feat(crates-io): add check for package metadata
  .github/workflows/check.yml
  core-backend/Cargo.toml
  galloc/Cargo.toml
  gbuiltins/bls381/Cargo.toml
  gbuiltins/eth-bridge/Cargo.toml
  gbuiltins/proxy/Cargo.toml
  gbuiltins/staking/Cargo.toml
  gcore/Cargo.toml
  gprimitives/Cargo.toml
  runtime-interface/sandbox/Cargo.toml
  stack-buffer/Cargo.toml
  utils/crates-io/src/publisher.rs
  utils/gear-wasmer-cache/Cargo.toml
  utils/ss58/Cargo.toml
  utils/wasm-builder/Cargo.toml
  utils/wasm-optimizer/Cargo.toml
  utils/wasm-proc/Cargo.toml
Labels: A0-pleasereview

#4391 fix(gtest): bump memory limit to 2GB
  core-processor/src/configs.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/manager/block_exec.rs
  gtest/src/program.rs
  gtest/src/state/mailbox/actor.rs
Labels: A2-mergeoncegreen

#4311 refactor(ethexe): Subscribe blocks when `Observer` is created
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/ethereum/src/lib.rs
  ethexe/observer/src/observer.rs
Labels: A0-pleasereview

#4397 fix(ethexe): allocation failure on huge journal returned from runtime
  ethexe/processor/src/host/mod.rs
  ethexe/runtime/src/wasm/api/mod.rs
Labels: A0-pleasereview

#4398 fix(ethexe): faster eth sync
  ethexe/ethereum/src/router/events.rs
  ethexe/observer/src/observer.rs
  ethexe/observer/src/query.rs
Labels: A0-pleasereview

#4373 feat(gear.exe): validators commitment
  ethexe/common/src/events/router.rs
  ethexe/common/src/gear.rs
  ethexe/contracts/script/Deployment.s.sol
  ethexe/contracts/src/IRouter.sol
  ethexe/contracts/src/Middleware.sol
  ethexe/contracts/src/Router.sol
  ethexe/contracts/src/libraries/Gear.sol
  ethexe/contracts/test/Base.t.sol
  ethexe/contracts/test/Middleware.t.sol
  ethexe/contracts/test/POC.t.sol
  ethexe/contracts/test/Router.t.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/TransparentUpgradeableProxy.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/abi/events/router.rs
  ethexe/ethereum/src/abi/gear.rs
  ethexe/ethereum/src/abi/mod.rs
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/router/events.rs
  ethexe/processor/src/handling/events.rs
Labels: A2-mergeoncegreen

#4402 chore(ethexe): bump alloy to 0.8.0
  Cargo.lock
  Cargo.toml
  ethexe/ethereum/src/lib.rs
  ethexe/observer/src/blobs.rs
  ethexe/observer/src/observer.rs
  ethexe/signer/src/lib.rs
Labels: A0-pleasereview

#4252 Heuristics tests are altered to panic with multiple results
  core/src/costs.rs
  core/src/gas_metering/schedule.rs
  pallets/gear/src/schedule.rs
  runtime/common/src/lib.rs
  runtime/common/src/weights.rs
  runtime/vara/src/tests/mod.rs
  runtime/vara/src/tests/utils.rs
  utils/weight-diff/src/main.rs
Labels: A2-mergeoncegreen

#4411 feat(ethexe/contracts): improve interaction with MirrorProxy via etherscan
  ethexe/cli/src/args.rs
  ethexe/contracts/src/MirrorProxy.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/TransparentUpgradeableProxy.json
  ethexe/ethereum/WrappedVara.json
Labels: A0-pleasereview

#4413 chore: change reth node address
  ethexe/cli/src/service.rs
  ethexe/docker/docker-compose.yml
Labels: A0-pleasereview

#4345 feat(runtime): Track block gas allowance in builtins
  core-processor/src/lib.rs
  core-processor/src/processing.rs
  pallets/gear-builtin/src/bls12_381.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/proxy.rs
  pallets/gear-builtin/src/staking.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-builtin/src/tests/bls381.rs
  pallets/gear-builtin/src/tests/proxy.rs
  pallets/gear-builtin/src/tests/staking.rs
  pallets/gear-eth-bridge/src/builtin.rs
  pallets/gear-eth-bridge/src/mock.rs
  pallets/gear/src/builtin.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview, D2-node, C1-feature, C2-refactoring
