Repository gear-tech/gear, pull requests merged in 2024-04, with the labels that each got.

#3848 fix(gtest): allow zero balance for `exec::exit()`
  Cargo.lock
  gtest/Cargo.toml
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A2-mergeoncegreen, D5-tooling

#3858 ci(typos): run typos check weekly
  .github/workflows/CI.yaml
  .github/workflows/PR.yml
  .github/workflows/weekly.yml
  Cargo.lock
  Cargo.toml
  Makefile
  _typos.toml
  common/src/gas_provider/node.rs
  gclient/src/api/listener/mod.rs
  runtime/vara/src/lib.rs
  scripts/gear.sh
  scripts/src/test.sh
  utils/gear-replay-cli/README.md
  utils/wasm-gen/src/config/generator.rs
Labels: A4-insubstantial

#3856 refactor(utils): Update gear-replay-cli tool
  Cargo.lock
  utils/gear-replay-cli/Cargo.toml
  utils/gear-replay-cli/README.md
  utils/gear-replay-cli/src/cmd/create_snapshot.rs
  utils/gear-replay-cli/src/cmd/gear_run.rs
  utils/gear-replay-cli/src/cmd/mod.rs
  utils/gear-replay-cli/src/cmd/replay_block.rs
  utils/gear-replay-cli/src/lib.rs
  utils/gear-replay-cli/src/main.rs
  utils/gear-replay-cli/src/parse.rs
  utils/gear-replay-cli/src/shared_parameters.rs
  utils/gear-replay-cli/src/state.rs
  utils/gear-replay-cli/src/util.rs
Labels: A0-pleasereview, C2-refactoring, D5-tooling

#3867 fix!(core): Handle unreserve of already unreserved slots
  core/src/reservation.rs
  utils/runtime-fuzzer/fuzz_corpus/aa91f1d5873e3fa7045ceeef9e26448e71f82482
  utils/runtime-fuzzer/src/tests.rs
Labels: A0-pleasereview

#3864 fix(wasm-proc): process assembly script correctly
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview

#3860 fix(benchmarks): improve github workflow, fix regex in merge script
  .github/workflows/benchmarks.yml
  scripts/benchmarking/merge_outputs.sh
  scripts/unpack-weights.sh
Labels: A0-pleasereview

#3869 chore(workspace): Bump versions, clean up migrations
  Cargo.lock
  Cargo.toml
  pallets/gear-messenger/src/lib.rs
  pallets/gear-messenger/src/migrations.rs
  pallets/gear-program/src/migration.rs
  pallets/gear/src/schedule.rs
  pallets/staking-rewards/src/lib.rs
  pallets/staking-rewards/src/migrations.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A0-pleasereview, A4-insubstantial

#3874 chore: Show error output on failure in measurements
  .github/workflows/test-measurements.yaml
  scripts/gear.sh
Labels: A0-pleasereview, D4-test

#3859 chore(ci): Smart caching in native Windows and macOS jobs
  .config/nextest.toml
  .github/workflows/CI.yaml
  .github/workflows/PR.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-win-native.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/crates-io.yml
  .github/workflows/release.yml
Labels: A0-pleasereview, E2-forcemacos, A5-dontmerge, E1-forcenatwin, E3-forcerelease

#3878 feat(gtest): Intorduce reading of previously submitted code by its id
  gtest/src/manager.rs
  gtest/src/system.rs
Labels: A0-pleasereview

#3873 fix(benchmarks): auto-trigger CI, produce correct output
  .github/workflows/benchmarks.yml
  pallets/gear/src/lib.rs
  scripts/unpack-weights.sh
Labels: A0-pleasereview

#3884 fix(tests): fix try-runtime execution CI
  .github/workflows/build.yml
Labels: A0-pleasereview, P1-asap

#3882 test: add showcases of some internal bugs
  core-processor/src/ext.rs
Labels: A2-mergeoncegreen

#3833 feat(gstd): Add ability to get payload of error replies in async messaging
  gstd/src/async_runtime/locks.rs
  gstd/src/common/errors.rs
  gstd/src/config.rs
  gstd/src/msg/async.rs
  gstd/src/sync/mutex.rs
Labels: A2-mergeoncegreen

#3812 refactor(pallet-gear): Remove waiting init list
  common/src/event.rs
  common/src/paused_program_storage.rs
  common/src/program_storage.rs
  core-errors/src/simple.rs
  core-processor/src/common.rs
  core-processor/src/handler.rs
  core-processor/src/processing.rs
  examples/init-wait/src/wasm.rs
  gsdk/src/metadata/generated.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  pallets/gear-program/src/lib.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/internal.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/migrations.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/tests.rs
  runtime/vara/src/migrations.rs
Labels: A2-mergeoncegreen, D2-node, B1-releasenotes

#3846 refactor(core-backend): Type-safe memory accesses
  core-backend/src/env.rs
  core-backend/src/funcs.rs
  core-backend/src/lib.rs
  core-backend/src/memory.rs
  core-backend/src/mock.rs
  core-backend/src/runtime.rs
  core-backend/src/tests.rs
  core-processor/src/ext.rs
  core/src/memory.rs
  sandbox/sandbox/src/embedded_executor.rs
  sandbox/sandbox/src/host_executor.rs
  sandbox/sandbox/src/lib.rs
Labels: A2-mergeoncegreen, D1-core

#3892 fix(core-backend): `std` used in mock
  core-backend/src/mock.rs
Labels: A0-pleasereview, D1-core, E3-forcerelease

#3877 feat(ci): M1 runner
  .github/actions/label/build.js
  .github/workflows/build-macos.yml
  .github/workflows/build-win-native.yml
  .github/workflows/build.yml
Labels: A2-mergeoncegreen, D5-tooling, E2-forcemacos, E1-forcenatwin, E3-forcerelease, E4-forceproduction

#3889 chore(gsdk): provide error details in assertions
  gcli/tests/cmd/claim.rs
  gcli/tests/cmd/send.rs
  gclient/tests/set_code.rs
  gclient/tests/upload.rs
  gsdk/tests/backtrace.rs
  gsdk/tests/rpc.rs
Labels: A4-insubstantial

#3834 feat(wasm-gen): reuse resources in programs
  Cargo.lock
  core-processor/src/ext.rs
  utils/runtime-fuzzer/src/generator/upload_program.rs
  utils/wasm-gen/Cargo.toml
  utils/wasm-gen/src/config/syscalls.rs
  utils/wasm-gen/src/config/syscalls/injection.rs
  utils/wasm-gen/src/config/syscalls/param.rs
  utils/wasm-gen/src/config/syscalls/process_errors.rs
  utils/wasm-gen/src/generator/entry_points.rs
  utils/wasm-gen/src/generator/syscalls.rs
  utils/wasm-gen/src/generator/syscalls/imports.rs
  utils/wasm-gen/src/generator/syscalls/invocator.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-gen/src/utils.rs
  utils/wasm-gen/src/wasm.rs
Labels: A2-mergeoncegreen, D5-tooling

#3888 chore(scripts): exclude g-tools in test scripts by default
  .github/workflows/build.yml
  Makefile
  scripts/src/test.sh
Labels: A4-insubstantial

#3880 runtime-fuzzer(tests): Add test cases which could cause previously fixed panics
  utils/runtime-fuzzer/fuzz_corpus/03d70a0b413038867c102a2b52f56b637ca6b277
  utils/runtime-fuzzer/fuzz_corpus/3a8de0dbd12a8a5e6e77bf5a81f2c511816a0ec2
  utils/runtime-fuzzer/fuzz_corpus/888e61e90b2d419b40d362af7036387364eef9bf
  utils/runtime-fuzzer/fuzz_corpus/b09f6282c0e906c06168e7fc22fb5417c3f6fafb-pr-3496-gas5k-delay10k
  utils/runtime-fuzzer/fuzz_corpus/bfcd26c09ccc57e35aaabc0937b0711520bddf75
  utils/runtime-fuzzer/src/tests.rs
Labels: A0-pleasereview, D4-test, D5-tooling

#3902 test(runtime): append `MemoryWeights` and syscalls heuristic tests #3839
  runtime/common/src/weights.rs
  runtime/vara/src/tests.rs
Labels: A0-pleasereview

#3904 refactor(core): add with_bytes functionality for `CostOf<CallsAmount…
  core-processor/src/precharge.rs
  core/src/costs.rs
Labels: A0-pleasereview

#3911 feat(core): restrict global and table imports in program code
  core/src/code/errors.rs
  core/src/code/mod.rs
  core/src/code/utils.rs
  pallets/gear/src/tests.rs
  utils/wasm-builder/src/code_validator.rs
Labels: A0-pleasereview

#3913 feat(gtest): `Program` constructors and `System` additional methods
  Cargo.lock
  examples/program-factory/src/lib.rs
  gtest/Cargo.toml
  gtest/src/lib.rs
  gtest/src/mailbox.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A0-pleasereview, D5-tooling, A4-insubstantial

#3905 fix(ci): use stable toolchain for ecosystem
  .github/workflows/check.yml
  .github/workflows/crates-io.yml
  .github/workflows/time-consuming-tests.yml
  common/numerated/Cargo.toml
  scripts/src/test.sh
  utils/crates-io/src/lib.rs
  utils/crates-io/src/manifest.rs
  utils/wasm-builder/tests/smoke.rs
Labels: A2-mergeoncegreen

#3898 feat: Update substrate to v1.2.0
  Cargo.lock
  Cargo.toml
  gcli/src/cmd/transfer.rs
  gclient/src/api/calls.rs
  gclient/tests/node.rs
  gsdk/README.md
  gsdk/src/metadata/generated.rs
  gsdk/src/signer/calls.rs
  gsdk/src/signer/utils.rs
  gsdk/tests/backtrace.rs
  node/authorship/src/tests.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  pallets/payment/src/tests.rs
  pallets/staking-rewards/src/mock.rs
  pallets/staking-rewards/src/tests.rs
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/lib.rs
  utils/node-loader/src/batch_pool.rs
Labels: A0-pleasereview, D2-node, C1-feature

#3916 feat(gstd): add `actor_id!` macro
  Cargo.lock
  Cargo.toml
  gstd/Cargo.toml
  gstd/codegen/Cargo.toml
  gstd/codegen/src/lib.rs
  gstd/src/common/primitives.rs
  gstd/src/lib.rs
  utils/crates-io/src/lib.rs
  utils/gring/Cargo.toml
  utils/gring/src/lib.rs
  utils/ss58/Cargo.toml
  utils/ss58/src/lib.rs
Labels: A0-pleasereview, D3-gstd

#3918 feat(gring): vara formatter for ss58 addresses
  utils/gring/src/cmd.rs
  utils/ss58/src/lib.rs
Labels: A0-pleasereview

#3923 fix(gear-wasm-builder): Support 1.79.0 nightly
  Cargo.lock
  Cargo.toml
  utils/wasm-builder/Cargo.toml
  utils/wasm-builder/src/crate_info.rs
Labels: A0-pleasereview, C0-bug, D5-tooling

#3897 refactor(core): move `validate_memory_params` to `AllocationsCotntext…
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/memory.rs
Labels: A0-pleasereview

#3887 chore: remove pallet::getter usage
  pallets/gear-bank/src/lib.rs
  pallets/gear-bank/src/tests.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/staking-rewards/src/lib.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#3909 feat(gcli): introduce command config
  Cargo.lock
  gcli/Cargo.toml
  gcli/src/app.rs
  gcli/src/cmd/config.rs
  gcli/src/cmd/info.rs
  gcli/src/cmd/mod.rs
  gcli/src/keystore/json.rs
  gcli/src/keystore/key.rs
  gcli/src/keystore/mod.rs
  gcli/src/result.rs
  gclient/src/api/mod.rs
Labels: A0-pleasereview

#3835 feat(gbuild): introduce cargo-gbuild
  .cargo/config.toml
  Cargo.lock
  Cargo.toml
  Makefile
  utils/cargo-gbuild/Cargo.toml
  utils/cargo-gbuild/src/artifact.rs
  utils/cargo-gbuild/src/bin/cargo-gbuild.rs
  utils/cargo-gbuild/src/cli.rs
  utils/cargo-gbuild/src/lib.rs
  utils/cargo-gbuild/test-program/Cargo.lock
  utils/cargo-gbuild/test-program/Cargo.toml
  utils/cargo-gbuild/test-program/src/lib.rs
  utils/cargo-gbuild/tests/smoke.rs
  utils/wasm-builder/src/cargo_command.rs
  utils/wasm-builder/src/lib.rs
Labels: A0-pleasereview, A3-gotissues, D5-tooling, E3-forcerelease

#3903 fix(pallet-gear-program): Migrations version
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migration.rs
  pallets/gear/src/migrations.rs
Labels: A2-mergeoncegreen, D2-node

#3933 fix toolchain matching and remove redundant cargo lock
  utils/cargo-gbuild/test-program/.gitignore
  utils/cargo-gbuild/test-program/Cargo.lock
  utils/wasm-builder/src/cargo_toolchain.rs
Labels: A0-pleasereview
