Repository gear-tech/gear, pull requests merged in 2024-08, with the labels that each got.

#3966 chore: debug assert reservation states in process_success
  core-processor/src/processing.rs
Labels: A2-mergeoncegreen

#4096 feat(gbuild): new programs from template
  utils/cargo-gbuild/src/cli.rs
  utils/cargo-gbuild/src/command.rs
  utils/cargo-gbuild/src/lib.rs
  utils/cargo-gbuild/src/utils.rs
  utils/cargo-gbuild/tests/smoke.rs
Labels: A2-mergeoncegreen

#4075 feat(gtest): Implement send_signal and system gas reserve/unreserve
  gtest/Cargo.toml
  gtest/src/gas_tree.rs
  gtest/src/manager.rs
  gtest/src/program.rs
Labels: A0-pleasereview, A2-mergeoncegreen, A3-gotissues

#4105 fix(ethexe): Add bootstrap addresses explicitly to KadDHT
  ethexe/network/src/lib.rs
Labels: A0-pleasereview

#4104 fix(ethexe): Shutdown network service on channel disconnect
  ethexe/network/src/lib.rs
Labels: A0-pleasereview

#4046 feat(gstd): Add handle_reply to MessageFuture
  Cargo.lock
  Cargo.toml
  examples/async-reply-hook/Cargo.toml
  examples/async-reply-hook/build.rs
  examples/async-reply-hook/src/lib.rs
  examples/async-reply-hook/src/wasm.rs
  examples/distributor/src/wasm.rs
  gstd/codegen/src/lib.rs
  gstd/src/async_runtime/mod.rs
  gstd/src/async_runtime/reply_hooks.rs
  gstd/src/common/errors.rs
  gstd/src/lib.rs
  gstd/src/msg/async.rs
  gstd/src/msg/macros.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#4114 chore(workspace): bump versions for release
  Cargo.lock
  Cargo.toml
  ethexe/cli/src/tests.rs
  runtime/vara/src/lib.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A2-mergeoncegreen

#4126 fix(benchmarks): remove too many pages accesses in benchmarks
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  runtime/vara/src/tests.rs
Labels: A2-mergeoncegreen

#4124 fix(workspace): specify minimum rust version for published crates
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/codegen/Cargo.toml
  common/numerated/Cargo.toml
  core-errors/Cargo.toml
  core-processor/Cargo.toml
  core/Cargo.toml
  galloc/Cargo.toml
  gcli/Cargo.toml
  gclient/Cargo.toml
  gcore/Cargo.toml
  gmeta/Cargo.toml
  gmeta/codegen/Cargo.toml
  gprimitives/Cargo.toml
  gsdk/Cargo.toml
  gsdk/codegen/Cargo.toml
  gstd/Cargo.toml
  gstd/codegen/Cargo.toml
  gsys/Cargo.toml
  gtest/Cargo.toml
  lazy-pages/Cargo.toml
  lazy-pages/common/Cargo.toml
  lazy-pages/native-interface/Cargo.toml
  runtime-interface/sandbox/Cargo.toml
  runtime/primitives/Cargo.toml
  sandbox/env/Cargo.toml
  sandbox/host/Cargo.toml
  sandbox/sandbox/Cargo.toml
  stack-buffer/Cargo.toml
  utils/actor-system-error/Cargo.toml
  utils/cargo-gbuild/Cargo.toml
  utils/crates-io/src/lib.rs
  utils/gring/Cargo.toml
  utils/node-wrapper/Cargo.toml
  utils/ss58/Cargo.toml
  utils/utils/Cargo.toml
  utils/wasm-builder/Cargo.toml
  utils/wasm-instrument/Cargo.toml
  utils/wasm-proc/Cargo.toml
Labels: A0-pleasereview

#4134 fix(weight-diff): add missing fields
  utils/wasm-instrument/src/gas_metering/schedule.rs
  utils/weight-diff/src/main.rs
Labels: A0-pleasereview

#4135 chore(tests): logging init in allocations migrations test
  pallets/gear-program/src/migrations/allocations.rs
Labels: A0-pleasereview, A4-insubstantial

#4088 chore(gtest): Update gtest weights to match onchain weights
  gtest/src/lib.rs
  gtest/src/manager.rs
Labels: A2-mergeoncegreen

#4067 feat(ethexe): Initial step of reverse gas model implementation
  Cargo.lock
  _typos.toml
  core-processor/src/configs.rs
  core-processor/src/executor.rs
  core/src/reservation.rs
  ethexe/common/src/events.rs
  ethexe/db/src/database.rs
  ethexe/processor/Cargo.toml
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/src/wasm/storage.rs
  examples/async/Cargo.toml
  examples/async/src/wasm.rs
  examples/init-fail-sender/src/lib.rs
  examples/ping/Cargo.toml
  examples/value-sender/src/lib.rs
  examples/waiter/src/lib.rs
  gcore/Cargo.toml
  gcore/src/exec.rs
  gcore/src/lib.rs
  gcore/src/msg.rs
  gcore/src/prog.rs
  gcore/src/utils.rs
  gstd/Cargo.toml
  gstd/codegen/Cargo.toml
  gstd/codegen/src/lib.rs
  gstd/codegen/tests/ui/signal_doesnt_work_with_ethexe.rs
  gstd/codegen/tests/ui/signal_doesnt_work_with_ethexe.stderr
  gstd/src/async_runtime/futures.rs
  gstd/src/async_runtime/mod.rs
  gstd/src/common/mod.rs
  gstd/src/config.rs
  gstd/src/lib.rs
  gstd/src/msg/async.rs
  gstd/src/msg/basic.rs
  gstd/src/msg/encoded.rs
  gstd/src/msg/macros.rs
  gstd/src/msg/mod.rs
  gstd/src/prelude.rs
  gstd/src/prog/basic.rs
  gstd/src/prog/encoded.rs
  gstd/src/prog/generator.rs
  gstd/src/sync/mutex.rs
  gstd/src/sync/rwlock.rs
  gsys/Cargo.toml
  gsys/src/lib.rs
Labels: A0-pleasereview

#4143 fix(crates-io): correct publishing order
  runtime-interface/sandbox/Cargo.toml
  utils/crates-io/src/lib.rs
Labels: A0-pleasereview

#4055 refactor(sandbox-host): remove double wasmer module serialization
  sandbox/host/src/sandbox/wasmer_backend.rs
  sandbox/host/src/sandbox/wasmer_backend/cache.rs
Labels: A0-pleasereview, C2-refactoring

#4145 feat(common): introduce AuxiliaryStorageWrap to remove boilerplate code
  common/src/auxiliary/mailbox.rs
  common/src/auxiliary/mod.rs
Labels: A2-mergeoncegreen

#4051 feat(gear-builtin): Separate actor id declaration
  pallets/gear-builtin/src/bls12_381.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/staking.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-builtin/src/tests/staking.rs
  pallets/gear-eth-bridge/src/builtin.rs
  pallets/gear-eth-bridge/src/mock.rs
  pallets/gear-eth-bridge/src/tests.rs
  runtime/vara/src/lib.rs
Labels: A2-mergeoncegreen

#4117 feat(ethexe-db): Router-independent block storage
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/db/src/database.rs
  ethexe/processor/src/tests.rs
Labels: A0-pleasereview

#4101 chore(core, sandbox, lazy-pages, bank, debug, builtin): add `log::error! `calls before each `unreachable!` call
  Cargo.lock
  common/src/gas_provider/node.rs
  core-backend/src/env.rs
  core-backend/src/funcs.rs
  core-backend/src/memory.rs
  core-backend/src/runtime.rs
  core-backend/src/state.rs
  core-processor/src/ext.rs
  core-processor/src/processing.rs
  core/src/memory.rs
  core/src/pages.rs
  core/src/reservation.rs
  lazy-pages/interface/src/lib.rs
  lazy-pages/native-interface/Cargo.toml
  lazy-pages/native-interface/src/lib.rs
  lazy-pages/src/host_func.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/pages.rs
  lazy-pages/src/process.rs
  lazy-pages/src/sys/windows.rs
  pallets/gear-bank/src/lib.rs
  pallets/gear-builtin/src/bls12_381.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear-debug/src/lib.rs
  sandbox/host/src/sandbox/wasmer_backend.rs
  sandbox/host/src/sandbox/wasmi_backend.rs
  sandbox/sandbox/src/embedded_executor.rs
  sandbox/sandbox/src/host_executor.rs
Labels: A2-mergeoncegreen, C2-refactoring

#4119 refactor(gtest): Change block execution model in `gtest` to be similar to the vara-runtime
  examples/autoreply/src/lib.rs
  examples/custom/src/btree.rs
  examples/distributor/src/lib.rs
  examples/gas-burned/src/lib.rs
  examples/new-meta/tests/read_state.rs
  examples/node/src/lib.rs
  examples/program-factory/src/lib.rs
  examples/reserve-gas/src/lib.rs
  examples/signal-entry/src/lib.rs
  examples/stack-allocations/src/lib.rs
  examples/syscall-error/src/lib.rs
  examples/wait_wake/src/lib.rs
  examples/waiter/tests/mx_lock_access.rs
  examples/waiter/tests/rw_lock_access.rs
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/mailbox/actor.rs
  gtest/src/manager.rs
  gtest/src/program.rs
  gtest/src/system.rs
  utils/cargo-gbuild/test-program/src/lib.rs
  utils/cargo-gbuild/tests/smoke.rs
  utils/wasm-builder/test-program/src/lib.rs
Labels: A2-mergeoncegreen, B1-releasenotes, D4-test, D5-tooling

#4141 feat(common, gtest): add AuxiliaryTaskpool
  common/src/auxiliary/mailbox.rs
  common/src/auxiliary/mod.rs
  common/src/auxiliary/taskpool.rs
  gtest/src/lib.rs
  gtest/src/mailbox/actor.rs
  gtest/src/mailbox/manager.rs
  gtest/src/taskpool.rs
Labels: A0-pleasereview

#4152 feat(ethexe): Extend programs mapping with code id
  ethexe/contracts/src/IRouter.sol
  ethexe/contracts/src/Router.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/WrappedVara.json
Labels: A0-pleasereview

#4154 feat(gtest): Use `AuxiliaryTaskPool` for current scheduled ops on `gtest`
  common/src/auxiliary/mailbox.rs
  common/src/auxiliary/mod.rs
  common/src/auxiliary/task_pool.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/task.rs
  gtest/src/system.rs
  gtest/src/task_pool.rs
Labels: A0-pleasereview, D5-tooling

#4150 feat(ethexe-network): Add memory transport for local testing
  Cargo.lock
  ethexe/cli/src/params/network_params.rs
  ethexe/network/Cargo.toml
  ethexe/network/src/lib.rs
Labels: A0-pleasereview

#4106 feat(ethexe): Add script to boot local ethereum node
  Cargo.toml
  ethexe/contracts/.gitignore
  ethexe/scripts/local-ethereum-node.sh
Labels: A0-pleasereview

#4078 feat(ethexe-contracts): add scripts for upgrades
  Makefile
  ethexe/contracts/.env.example
  ethexe/contracts/README.md
  ethexe/contracts/foundry.toml
  ethexe/contracts/script/Deployment.s.sol
  ethexe/contracts/script/upgrades/Mirror.s.sol
  ethexe/contracts/script/upgrades/Router.s.sol
  ethexe/contracts/script/upgrades/WrappedVara.s.sol
  ethexe/contracts/src/Mirror.sol
  ethexe/contracts/src/Router.sol
  ethexe/contracts/src/WrappedVara.sol
  ethexe/contracts/test/Router.t.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/TransparentUpgradeableProxy.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/lib.rs
Labels: A0-pleasereview

#4147 feat(crates-io): simulate packages publishing
  .github/workflows/check.yml
  .github/workflows/crates-io.yml
  Cargo.lock
  Cargo.toml
  gcore/Cargo.toml
  utils/crates-io/Cargo.toml
  utils/crates-io/src/handler.rs
  utils/crates-io/src/lib.rs
  utils/crates-io/src/main.rs
  utils/crates-io/src/manifest.rs
  utils/crates-io/src/publisher.rs
  utils/crates-io/src/simulator.rs
  utils/crates-io/src/version.rs
Labels: A0-pleasereview

#4129 feat(gsdk, gclient): Introduce support for vouchers in Gsdk and GClient
  gclient/src/api/calls.rs
  gclient/src/api/mod.rs
  gclient/src/api/voucher.rs
  gclient/tests/voucher.rs
  gsdk/src/metadata/impls.rs
  gsdk/src/signer/calls.rs
  gsdk/tests/voucher.rs
  pallets/gear-voucher/src/internal.rs
Labels: A2-mergeoncegreen

#4111 feat(gtest): Improve value and ED managment
  examples/autoreply/src/lib.rs
  examples/custom/src/btree.rs
  examples/distributor/src/lib.rs
  examples/gas-burned/src/lib.rs
  examples/new-meta/tests/read_state.rs
  examples/node/src/lib.rs
  examples/program-factory/src/lib.rs
  examples/reserve-gas/src/lib.rs
  examples/signal-entry/src/lib.rs
  examples/stack-allocations/src/lib.rs
  examples/syscall-error/src/lib.rs
  examples/wait_wake/src/lib.rs
  examples/waiter/tests/mx_lock_access.rs
  examples/waiter/tests/rw_lock_access.rs
  gtest/src/accounts.rs
  gtest/src/actors.rs
  gtest/src/bank.rs
  gtest/src/gas_tree.rs
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/mailbox/actor.rs
  gtest/src/manager.rs
  gtest/src/manager/journal.rs
  gtest/src/program.rs
  gtest/src/system.rs
  utils/cargo-gbuild/test-program/src/lib.rs
  utils/cargo-gbuild/tests/smoke.rs
Labels: A2-mergeoncegreen, B1-releasenotes

#4166 fix(runtime): Correct normal dispatches length
  Cargo.lock
  common/src/pallet_tests.rs
  ethexe/network/src/lib.rs
  images/time-weight-synchronization.svg
  node/authorship/README.md
  node/authorship/src/authorship.rs
  runtime/common/src/lib.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/tests.rs
Labels: A2-mergeoncegreen

#4151 chore(gsdk): upgrade to subxt-0.37.0
  Cargo.lock
  Cargo.toml
  gclient/src/api/calls.rs
  gclient/src/api/error.rs
  gclient/src/api/listener/iterator.rs
  gsdk/api-gen/Cargo.toml
  gsdk/api-gen/src/main.rs
  gsdk/src/api.rs
  gsdk/src/config.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/result.rs
  gsdk/src/signer/calls.rs
  gsdk/src/signer/storage.rs
  gsdk/src/signer/utils.rs
  gsdk/src/storage.rs
  gsdk/src/subscription.rs
  gsdk/src/utils.rs
  gsdk/tests/rpc.rs
  utils/node-loader/src/batch_pool.rs
  utils/node-loader/src/main.rs
  utils/validator-checks/Cargo.toml
  utils/validator-checks/src/result.rs
Labels: A0-pleasereview

#4153 refactor(ethexe): Move `WVara` eth getter to `Router` instance
  ethexe/cli/src/tests.rs
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/mirror/mod.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/ethereum/src/wvara/mod.rs
Labels: A0-pleasereview

#4173 feat(ethexe): zero program state; handle exec balances topups; handle unrecognised mirrors; refactor
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/contracts/script/Deployment.s.sol
  ethexe/contracts/src/IMirror.sol
  ethexe/db/src/database.rs
  ethexe/observer/src/observer.rs
  ethexe/processor/src/host/threads.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/src/wasm/storage.rs
Labels: A0-pleasereview

#3652 feat(vara,gear-bank): Split gas and fees to author/treasury
  Cargo.lock
  pallets/gear-bank/src/lib.rs
  pallets/gear-bank/src/mock.rs
  pallets/gear-bank/src/tests.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-builtin/src/tests/staking.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-eth-bridge/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/mock.rs
  pallets/payment/src/mock.rs
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/common/src/lib.rs
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/lib.rs
Labels: A0-pleasereview

#4184 fix(ethexe): correct numeric cast function
  Cargo.lock
  ethexe/ethereum/Cargo.toml
  ethexe/ethereum/src/abi.rs
Labels: A2-mergeoncegreen

#4168 chore(pallet_gear_voucher): Remove pallet_gear_voucher::call_deprecated and clean all references
  gsdk/src/metadata/generated.rs
  pallets/gear-voucher/src/internal.rs
  pallets/gear-voucher/src/lib.rs
  pallets/gear-voucher/src/tests.rs
  pallets/payment/src/tests.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#4185 refactor(ethexe-observer): simplify events querying
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/mirror/events.rs
  ethexe/ethereum/src/mirror/mod.rs
  ethexe/ethereum/src/router/events.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/ethereum/src/wvara/events.rs
  ethexe/observer/src/observer.rs
Labels: A0-pleasereview

#4174 chore(ethexe-network): Update libp2p to 0.54.1
  Cargo.lock
  ethexe/network/Cargo.toml
  ethexe/network/src/custom_connection_limits.rs
Labels: A0-pleasereview

#4165 refactor(core-processor, core): Reimburse reduced for the reservation gas, if it was unreserved immediately
  core-processor/src/ext.rs
  core/src/gas.rs
  core/src/reservation.rs
Labels: A2-mergeoncegreen, D1-core, C2-refactoring

#4193 feat(gtest): Introduce auxiliary waitlist impl to `gtest`
  common/src/auxiliary/mod.rs
  common/src/auxiliary/waitlist.rs
  gtest/src/blocks.rs
  gtest/src/gas_tree.rs
  gtest/src/lib.rs
  gtest/src/mailbox/manager.rs
  gtest/src/task_pool.rs
  gtest/src/waitlist.rs
Labels: A2-mergeoncegreen, D5-tooling

#4192 fix(benchmarks,runtime-interface): clear store by counter when runnining benchmarks
  pallets/gear/Cargo.toml
  pallets/gear/src/weights.rs
  runtime-interface/Cargo.toml
  runtime-interface/sandbox/Cargo.toml
  runtime-interface/sandbox/src/detail.rs
  runtime/vara/src/tests.rs
  runtime/vara/src/weights/pallet_gear.rs
  scripts/benchmarking/run_all_benchmarks.sh
  utils/wasm-instrument/src/gas_metering/schedule.rs
Labels: A0-pleasereview

#4132 feat(ethexe): Initial fast sync protocol
  Cargo.lock
  ethexe/cli/Cargo.toml
  ethexe/cli/src/chain_spec.rs
  ethexe/cli/src/params/network_params.rs
  ethexe/cli/src/service.rs
  ethexe/common/src/db.rs
  ethexe/db/src/database.rs
  ethexe/db/src/lib.rs
  ethexe/db/src/mem.rs
  ethexe/db/src/rocks.rs
  ethexe/network/Cargo.toml
  ethexe/network/src/custom_connection_limits.rs
  ethexe/network/src/db_sync/mod.rs
  ethexe/network/src/db_sync/ongoing.rs
  ethexe/network/src/lib.rs
  ethexe/network/src/utils.rs
Labels: A0-pleasereview

#4186 fix(core-processor): Force `*_input` syscalls to return an error on out of bounds `offset` and `len` params.
  core-errors/src/lib.rs
  core-processor/src/ext.rs
  core/src/message/context.rs
  examples/proxy-relay/src/wasm.rs
  examples/syscalls/src/wasm.rs
  gtest/src/lib.rs
  pallets/gear/src/tests.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview, D1-core, B1-releasenotes, C0-bug

#4194 feat(gtest): Introduce full waitlist management to `gtest`
  common/src/auxiliary/waitlist.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/manager/exec.rs
  gtest/src/manager/expend.rs
  gtest/src/manager/hold_bound.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/memory.rs
  gtest/src/manager/reservations.rs
  gtest/src/manager/send_dispatch.rs
  gtest/src/manager/task.rs
  gtest/src/manager/wait_wake.rs
  gtest/src/program.rs
  gtest/src/state/accounts.rs
  gtest/src/state/actors.rs
  gtest/src/state/bank.rs
  gtest/src/state/blocks.rs
  gtest/src/state/gas_tree.rs
  gtest/src/state/mailbox.rs
  gtest/src/state/mailbox/actor.rs
  gtest/src/state/mailbox/manager.rs
  gtest/src/state/mod.rs
  gtest/src/state/task_pool.rs
  gtest/src/state/waitlist.rs
  gtest/src/system.rs
Labels: A0-pleasereview, D5-tooling

#4196 feat(gtest): Proper runtime-like reservations for gtest
  gtest/src/manager/journal.rs
  gtest/src/manager/reservations.rs
  gtest/src/manager/task.rs
  gtest/src/program.rs
  gtest/src/state/gas_tree.rs
Labels: A2-mergeoncegreen

#4191 feat(ethexe): impl decoder support for mirror contract
  ethexe/contracts/src/IMirror.sol
  ethexe/contracts/src/IMirrorDecoder.sol
  ethexe/contracts/src/IRouter.sol
  ethexe/contracts/src/Mirror.sol
  ethexe/contracts/src/Router.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/WrappedVara.json
Labels: A0-pleasereview

#4198 fix(lazy-pages-fuzzer, ci): add error output on lazy pages fuzzer's smoke test fail
  .github/workflows/check.yml
  scripts/check-lazy-pages-fuzzer.sh
Labels: A0-pleasereview

#4109 feat(ethexe): append validation round
  Cargo.lock
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
  ethexe/common/src/db.rs
  ethexe/common/src/lib.rs
  ethexe/db/src/database.rs
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/mirror/mod.rs
  ethexe/ethereum/src/router/events.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/network/src/lib.rs
  ethexe/observer/src/blobs.rs
  ethexe/observer/src/observer.rs
  ethexe/observer/src/query.rs
  ethexe/processor/src/lib.rs
  ethexe/rpc/src/lib.rs
  ethexe/sequencer/Cargo.toml
  ethexe/sequencer/src/agro.rs
  ethexe/sequencer/src/lib.rs
  ethexe/signer/Cargo.toml
  ethexe/signer/src/digest.rs
  ethexe/signer/src/lib.rs
  ethexe/signer/src/signature.rs
  ethexe/validator/Cargo.toml
  ethexe/validator/src/lib.rs
Labels: A0-pleasereview

#4202 fix(lazy-pages-fuzzer): remove host address check
  scripts/check-lazy-pages-fuzzer.sh
  utils/lazy-pages-fuzzer/src/lib.rs
Labels: A0-pleasereview

#4208 feat(ethexe): call initialize fn on decoder after cloning
  ethexe/contracts/src/IMirrorDecoder.sol
  ethexe/contracts/src/Mirror.sol
Labels: A0-pleasereview, A2-mergeoncegreen

#4148 refactor(gtest, core): refactor weight dumping, dump additional constants
  Cargo.lock
  core-backend/src/lib.rs
  core-processor/src/configs.rs
  core-processor/src/ext.rs
  core-processor/src/precharge.rs
  core/Cargo.toml
  core/src/code/mod.rs
  core/src/costs.rs
  core/src/gas_metering/mod.rs
  core/src/gas_metering/rules.rs
  core/src/gas_metering/schedule.rs
  core/src/lib.rs
  ethexe/runtime/src/wasm/api/instrument.rs
  gsdk/src/metadata/generated.rs
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/manager/exec.rs
  gtest/src/manager/expend.rs
  gtest/src/manager/journal.rs
  gtest/src/program.rs
  lazy-pages/common/src/lib.rs
  lazy-pages/interface/src/lib.rs
  lazy-pages/native-interface/src/lib.rs
  pallets/gear/src/benchmarking/tests/lazy_pages.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  runtime/common/src/weights.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/tests.rs
  scripts/weight-dump.sh
  utils/wasm-builder/src/code_validator.rs
  utils/wasm-gen/src/tests.rs
  utils/wasm-instrument/src/gas_metering/schedule.rs
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/tests.rs
  utils/weight-diff/Cargo.toml
  utils/weight-diff/src/main.rs
Labels: A0-pleasereview, A2-mergeoncegreen, D1-core, D5-tooling
