Repository gear-tech/gear, pull requests merged in 2025-02, with the labels that each got.

#4474 revert(sandbox, lazy-pages): Increase corosensei precommited stack size to 1MiB (windows)
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview

#4407 feat(wasm-builder): switch to new `wasm32v1-none` target
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/crates-io.yml
  Cargo.lock
  Cargo.toml
  docker/Dockerfile
  docker/runtime-fuzzer/Dockerfile
  ethexe/docker/ethexe_builder.Dockerfile
  gcli/README.md
  gcli/src/embed.rs
  gcli/src/lib.rs
  gcli/tests/common/env.rs
  gclient/src/lib.rs
  gclient/src/utils.rs
  gtest/src/lib.rs
  node/README.md
  runtime/vara/src/lib.rs
  rust-toolchain.toml
  scripts/pin-rust-nightly.sh
  scripts/src/build.sh
  scripts/src/init.sh
  scripts/src/test.sh
  stack-buffer/alloca/README.md
  stack-buffer/build.rs
  utils/cargo-gbuild/src/cli.rs
  utils/cargo-gbuild/tests/smoke.rs
  utils/wasm-builder/README.md
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-builder/test-program/src/lib.rs
  utils/wasm-builder/tests/smoke.rs
  utils/wasm-optimizer/Cargo.toml
  utils/wasm-optimizer/src/cargo_command.rs
  utils/wasm-optimizer/src/cargo_toolchain.rs
Labels: A0-pleasereview, D5-tooling

#4484 feat(ethexe): add more accurate gas estimation for commitments
  ethexe/contracts/foundry.toml
  ethexe/contracts/src/IRouter.sol
  ethexe/contracts/src/Router.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/router/mod.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview, E1-forcenatwin, E3-forcerelease

#4489 feat(ethexe): Introduce stream returning events from the `ethexe-rpc`
  ethexe/rpc/src/lib.rs
  ethexe/service/src/lib.rs
Labels: A2-mergeoncegreen

#4491 fix(crates-io): fix late partial publishing
  scripts/src/init.sh
  utils/crates-io/src/handler.rs
  utils/crates-io/src/manifest.rs
  utils/crates-io/src/publisher.rs
Labels: A0-pleasereview

#4495 chore(scripts/CI): fuzzer expand
  .github/workflows/check.yml
  .gitignore
  scripts/check-fuzzer.sh
Labels: A0-pleasereview

#4492 chore(ethexe): impl `Clone` for `NetworkEvent`
  ethexe/network/src/db_sync/mod.rs
  ethexe/network/src/db_sync/ongoing.rs
  ethexe/network/src/lib.rs
Labels: A0-pleasereview

#4494 chore: Remove `wabt`
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  core/src/code/mod.rs
  core/src/memory.rs
  ethexe/observer/Cargo.toml
  ethexe/observer/src/tests.rs
  ethexe/processor/Cargo.toml
  ethexe/processor/src/tests.rs
  examples/program-factory/child_contract.wasm
  examples/program-factory/src/lib.rs
  examples/wat/Cargo.toml
  examples/wat/src/lib.rs
  gclient/Cargo.toml
  gclient/src/utils.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear-debug/src/tests/utils.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/migrations/add_section_sizes.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  pallets/payment/Cargo.toml
  runtime/vara/Cargo.toml
  runtime/vara/src/integration_tests.rs
  utils/calc-stack-height/Cargo.toml
  utils/calc-stack-height/src/main.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-optimizer/Cargo.toml
  utils/wasm-optimizer/src/stack_end.rs
Labels: A0-pleasereview, D5-tooling

#4490 feat(ethexe): use `Router.commitBatch()` in sequencer and validator
  ethexe/contracts/src/IRouter.sol
  ethexe/contracts/src/Router.sol
  ethexe/contracts/test/Base.t.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/router/mod.rs
  ethexe/sequencer/Cargo.toml
  ethexe/sequencer/src/agro.rs
  ethexe/sequencer/src/lib.rs
  ethexe/sequencer/src/tests.rs
  ethexe/service/src/lib.rs
  ethexe/validator/src/lib.rs
Labels: A0-pleasereview

#4502 chore(wasm-gen): Enable sign-extension opcodes
  utils/wasm-gen/src/config/module.rs
Labels: A0-pleasereview, D5-tooling

#4419 refactor(ethexe): remove to_vec and mem::transmute from ethexe
  ethexe/processor/src/host/api/lazy_pages.rs
  ethexe/processor/src/host/api/mod.rs
  ethexe/processor/src/host/api/sandbox.rs
  ethexe/processor/src/host/mod.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/src/wasm/api/mod.rs
  ethexe/runtime/src/wasm/interface/database.rs
  ethexe/runtime/src/wasm/interface/mod.rs
  runtime-interface/src/lib.rs
Labels: A0-pleasereview, A5-dontmerge

#4500 fix: compilation of dev runtime with try-runtime feature; update try-runtime-cli version
  .github/workflows/build.yml
  pallets/gear-eth-bridge/Cargo.toml
Labels: A0-pleasereview

#4501 chore: remove legacy migrations
  pallets/gear-messenger/src/lib.rs
  pallets/gear-messenger/src/migrations/context_store.rs
  pallets/gear-messenger/src/migrations/mod.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migrations/add_section_sizes.rs
  pallets/gear-program/src/migrations/allocations.rs
  pallets/gear-program/src/migrations/mod.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview

#4455 refactor(ethexe): simplify program creation and message sending in tests
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4320 refactor(gtest): removed use of read_state_bytes_using_wasm
  examples/new-meta/tests/read_state.rs
  gcli/src/cmd/program.rs
  gclient/src/api/rpc.rs
  gclient/tests/state.rs
  gsdk/src/rpc.rs
  gtest/src/manager.rs
  gtest/src/manager/memory.rs
  gtest/src/program.rs
  utils/cargo-gbuild/tests/smoke.rs
Labels: A0-pleasereview

#4473 feat(core): add storing heap as field in AllocationsContext
  core/src/memory.rs
Labels: A0-pleasereview, D1-core, C2-refactoring

#4475 feat(ethexe): compute service initial impl with non-blocking codes and blocks processing
  Cargo.lock
  Cargo.toml
  ethexe/common/src/lib.rs
  ethexe/compute/Cargo.toml
  ethexe/compute/src/lib.rs
  ethexe/observer/src/lib.rs
  ethexe/processor/src/handling/run.rs
  ethexe/service/Cargo.toml
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4409 refactor(backend): refine approach of funcs forbidding
  core-backend/src/env.rs
  core-backend/src/funcs.rs
  core-backend/src/mock.rs
  core-backend/src/runtime.rs
  core-processor/src/ext.rs
  core/src/env.rs
  core/src/message/context.rs
  core/src/message/mod.rs
Labels: A0-pleasereview

#4510 feat(gprimitives): add SolValue trait impl for ActorId under ethexe feature
  Cargo.lock
  Cargo.toml
  gprimitives/Cargo.toml
  gprimitives/src/lib.rs
  gprimitives/src/sol_types.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#4448 feat(ethexe): add dispatch origin
  .gitignore
  Cargo.lock
  ethexe/common/Cargo.toml
  ethexe/common/src/gear.rs
  ethexe/common/src/lib.rs
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/handling/run.rs
  ethexe/processor/src/host/mod.rs
  ethexe/runtime/Cargo.toml
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/src/wasm/api/mod.rs
  ethexe/runtime/src/wasm/api/run.rs
Labels: A0-pleasereview

#4503 feat(ethexe): Introduce centralized event broadcasting system for services
  ethexe/compute/src/lib.rs
  ethexe/prometheus/src/lib.rs
  ethexe/rpc/src/lib.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4517 fix: centralized service broadcast; feat: rm sleeps from tests
  ethexe/network/src/lib.rs
  ethexe/rpc/src/lib.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
Labels: A2-mergeoncegreen

#4366 feat(ethexe-tx-pool): Introduce basic tx-pool
  Cargo.lock
  Cargo.toml
  core/src/lib.rs
  ethexe/cli/src/commands/tx.rs
  ethexe/common/src/lib.rs
  ethexe/common/src/tx_pool.rs
  ethexe/db/src/database.rs
  ethexe/db/src/lib.rs
  ethexe/db/src/overlay.rs
  ethexe/network/src/lib.rs
  ethexe/rpc/Cargo.toml
  ethexe/rpc/src/apis/mod.rs
  ethexe/rpc/src/apis/tx_pool.rs
  ethexe/rpc/src/errors.rs
  ethexe/rpc/src/lib.rs
  ethexe/rpc/src/test_utils.rs
  ethexe/service/Cargo.toml
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/signer/Cargo.toml
  ethexe/signer/src/address.rs
  ethexe/signer/src/digest.rs
  ethexe/signer/src/lib.rs
  ethexe/signer/src/signature.rs
  ethexe/tx-pool/Cargo.toml
  ethexe/tx-pool/src/lib.rs
  ethexe/tx-pool/src/tests.rs
  ethexe/tx-pool/src/validation.rs
  pallets/gear-builtin/src/lib.rs
Labels: A2-mergeoncegreen

#4428 chore(vara): Update bags thresholds
  runtime/vara/src/bag_thresholds.rs
  runtime/vara/src/migrations.rs
  utils/bags-thresholds/Cargo.toml
  utils/bags-thresholds/src/main.rs
Labels: A2-mergeoncegreen
