Repository gear-tech/gear, pull requests merged in 2025-04, with the labels that each got.

#4527 feat(vara): Implement gear eth bridge governance
  pallets/gear-eth-bridge/src/lib.rs
  pallets/gear-eth-bridge/src/mock.rs
  runtime/vara/src/governance/tracks.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/tests/mod.rs
Labels: A2-mergeoncegreen, C1-feature

#4586 chore(ci): disable weight warnings in try-runtime job
  .github/workflows/build.yml
Labels: A0-pleasereview

#4585 fix(runtime): adjust economical constants, bump gas price
  common/src/gas_provider/node.rs
  common/src/gas_provider/property_tests/mod.rs
  common/src/lib.rs
  core-backend/src/mock.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  ethexe/ethereum/src/lib.rs
  ethexe/runtime/common/src/lib.rs
  gcli/tests/cmd/claim.rs
  gsys/src/lib.rs
  gtest/src/lib.rs
  gtest/src/program.rs
  node/authorship/src/tests.rs
  node/testing/src/genesis.rs
  pallets/gas/src/tests.rs
  pallets/gear-bank/src/mock.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-builtin/src/tests/staking.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-eth-bridge/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/mock.rs
  pallets/payment/src/mock.rs
  runtime/common/src/lib.rs
  runtime/vara/src/constants.rs
Labels: A0-pleasereview

#4580 test(ethexe-db): cover program_ids() & check_within_recent_blocks()
  ethexe/db/src/database.rs
Labels: A0-pleasereview

#4588 refactor(gear-bank): Derive gear bank account id from the pallet id
  Cargo.lock
  gclient/src/api/calls.rs
  gclient/src/api/storage/mod.rs
  gclient/src/utils.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/storage.rs
  node/testing/src/genesis.rs
  pallets/gear-bank/Cargo.toml
  pallets/gear-bank/src/lib.rs
  pallets/gear-bank/src/migrations.rs
  pallets/gear-bank/src/mock.rs
  pallets/gear-bank/src/tests.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-builtin/src/tests/staking.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-eth-bridge/src/mock.rs
  pallets/gear-scheduler/src/mock.rs
  pallets/gear/src/mock.rs
  pallets/payment/src/mock.rs
  runtime/common/src/constants.rs
  runtime/vara/src/genesis_config_presets.rs
  runtime/vara/src/integration_tests.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
  utils/runtime-fuzzer/src/runtime/mod.rs
Labels: A0-pleasereview, D2-node, C2-refactoring

#4590 feat(pallet-gear-eth-bridge): Add message fee
  gsdk/src/metadata/generated.rs
  pallets/gear-eth-bridge/Cargo.toml
  pallets/gear-eth-bridge/src/benchmarking.rs
  pallets/gear-eth-bridge/src/builtin.rs
  pallets/gear-eth-bridge/src/lib.rs
  pallets/gear-eth-bridge/src/mock.rs
  pallets/gear-eth-bridge/src/tests.rs
  pallets/gear-eth-bridge/src/weights.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/tests/mod.rs
  runtime/vara/src/weights/pallet_gear_eth_bridge.rs
Labels: A2-mergeoncegreen

#4592 fix(gtest): limit max applied gas
  gtest/src/manager.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/memory.rs
Labels: A0-pleasereview

#4589 feat(core-errors): More descriptive `UnavailableActor` (former `InactiveError`)
  Cargo.lock
  Cargo.toml
  core-errors/src/simple.rs
  core-processor/src/lib.rs
  core-processor/src/processing.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/service/src/tests.rs
  examples/inheritor-in-error-reply/Cargo.toml
  examples/inheritor-in-error-reply/build.rs
  examples/inheritor-in-error-reply/src/lib.rs
  examples/inheritor-in-error-reply/src/wasm.rs
  gsdk/src/metadata/generated.rs
  gstd/src/common/errors.rs
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/manager.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/memory.rs
  gtest/src/program.rs
  gtest/src/state/actors.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/tests.rs
Labels: A2-mergeoncegreen, D1-core

#4597 chore(workspace): update codec, update substrate to workaround codec bug
  Cargo.lock
  Cargo.toml
  core-backend/Cargo.toml
  core-backend/src/error.rs
  core-backend/src/memory.rs
  core-backend/src/mock.rs
  examples/bls381/Cargo.toml
  examples/bls381/src/lib.rs
  gbuiltins/bls381/Cargo.toml
  gbuiltins/bls381/src/lib.rs
  gtest/Cargo.toml
  gtest/src/error.rs
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/program.rs
  gtest/src/state/mailbox/actor.rs
  gtest/src/system.rs
  lazy-pages/common/Cargo.toml
  lazy-pages/common/src/lib.rs
  node/authorship/Cargo.toml
  node/authorship/src/authorship.rs
  node/authorship/src/block_builder.rs
  node/authorship/src/tests.rs
  node/testing/Cargo.toml
  node/testing/src/keyring.rs
  runtime-interface/Cargo.toml
  runtime-interface/sandbox/Cargo.toml
  runtime-interface/sandbox/src/detail.rs
  runtime-interface/src/lib.rs
  sandbox/env/Cargo.toml
  sandbox/env/src/lib.rs
  sandbox/host/Cargo.toml
  sandbox/host/src/sandbox.rs
  sandbox/host/src/sandbox/wasmer_backend.rs
  sandbox/host/src/sandbox/wasmi_backend.rs
  sandbox/sandbox/Cargo.toml
  sandbox/sandbox/src/host_executor.rs
  utils/gear-replay-cli/Cargo.toml
  utils/gear-replay-cli/src/cmd/gear_run.rs
  utils/gear-replay-cli/src/cmd/replay_block.rs
  utils/runtime-fuzzer/Cargo.toml
  utils/runtime-fuzzer/src/runtime/block.rs
Labels: A2-mergeoncegreen

#4600 fix(release): remove check for dev runtime
  .github/workflows/release.yml
Labels: A2-mergeoncegreen

#4606 chore: update derive_more to version 2.0.1
  Cargo.lock
  Cargo.toml
  common/numerated/src/interval.rs
  core-backend/src/env.rs
  core-backend/src/error.rs
  core-errors/src/lib.rs
  core-errors/src/simple.rs
  core-processor/src/common.rs
  core-processor/src/ext.rs
  core-processor/src/precharge.rs
  core/src/code/errors.rs
  core/src/gas.rs
  core/src/memory.rs
  core/src/pages.rs
  core/src/program.rs
  core/src/str.rs
  ethexe/runtime/common/src/state.rs
  gprimitives/src/lib.rs
  gtest/src/error.rs
  lazy-pages/src/common.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/mprotect.rs
  lazy-pages/src/sys/unix.rs
  node/cli/src/cli.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear/src/tests.rs
  utils/gear-wasmer-cache/src/lib.rs
  utils/lazy-pages-fuzzer/src/generate/mem_accesses.rs
  utils/lazy-pages-fuzzer/src/wasmi_backend/error.rs
  utils/wasm-instrument/src/gas_metering/mod.rs
  utils/wasm-instrument/src/lib.rs
  utils/wasm-instrument/src/module.rs
Labels: A0-pleasereview

#4444 feat(wasm-builder): reduce the amount of data sections in opt-wasm
  .github/workflows/Build-gear-loader-network.yml
  .github/workflows/CI.yaml
  .github/workflows/PR.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/test-measurements.yaml
  Cargo.lock
  Cargo.toml
  examples/big-data-section/Cargo.toml
  examples/big-data-section/build.rs
  examples/big-data-section/src/constants.rs
  examples/big-data-section/src/data_access.rs
  examples/big-data-section/src/lib.rs
  examples/big-data-section/src/wasm.rs
  utils/wasm-builder/Cargo.toml
  utils/wasm-optimizer/Cargo.toml
  utils/wasm-optimizer/src/optimize.rs
  utils/wasm-proc/Cargo.toml
Labels: A0-pleasereview

#4614 chore(gear): disable win-cross
  .github/workflows/build.yml
Labels: A0-pleasereview

#4612 chore(workspace): update holesky wss endpoint
  ethexe/docker/docker-compose.yml
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4582 refactor(ethexe): move block metadata persistence to ComputeService
  ethexe/compute/src/lib.rs
  ethexe/observer/src/blobs.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/sync.rs
  ethexe/observer/src/tests.rs
  ethexe/observer/src/utils.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/rpc/src/apis/dev.rs
  ethexe/rpc/src/lib.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview, C2-refactoring

#4621 fix(gear-wasm-instrument): Keep custom sections
  .github/workflows/release.yml
  utils/wasm-instrument/src/module.rs
  utils/wasm-optimizer/src/optimize.rs
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview, D5-tooling

#4619 fix(ethexe): add missing parts for rust client
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/TransparentUpgradeableProxy.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/abi/gear.rs
  ethexe/ethereum/src/lib.rs
  ethexe/sequencer/src/lib.rs
  ethexe/validator/src/lib.rs
Labels: A0-pleasereview

#4620 fix(gear): send auto reply on exit
  core-processor/src/processing.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#4622 feat(gsdk): impl query for inheritor
  gsdk/src/storage.rs
Labels: A0-pleasereview

#4628 fix(ethexe-processor): Enable wasmtime cache
  ethexe/processor/src/host/mod.rs
Labels: A0-pleasereview

#4629 fix(ethexe-network): Close listeners on drop
  ethexe/network/src/lib.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4539 feat(ethexe): Implement fast sync
  Cargo.lock
  ethexe/cli/src/params/node.rs
  ethexe/common/src/db.rs
  ethexe/compute/Cargo.toml
  ethexe/compute/src/lib.rs
  ethexe/db/src/database.rs
  ethexe/db/src/lib.rs
  ethexe/db/src/mem.rs
  ethexe/db/src/overlay.rs
  ethexe/db/src/rocks.rs
  ethexe/network/Cargo.toml
  ethexe/network/src/custom_connection_limits.rs
  ethexe/network/src/db_sync/mod.rs
  ethexe/network/src/db_sync/ongoing.rs
  ethexe/network/src/lib.rs
  ethexe/network/src/utils.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/utils.rs
  ethexe/processor/src/host/api/database.rs
  ethexe/processor/src/tests.rs
  ethexe/runtime/common/Cargo.toml
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
  ethexe/sequencer/Cargo.toml
  ethexe/service/Cargo.toml
  ethexe/service/src/config.rs
  ethexe/service/src/fast_sync.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/service/utils/src/timer.rs
  ethexe/validator/src/lib.rs
  examples/async/src/wasm.rs
  examples/autoreply/src/wasm.rs
Labels: A0-pleasereview
