Repository gear-tech/gear, pull requests merged in 2025-09, with the labels that each got.

#4836 chore: remove regular docs publishing
  .github/workflows/build-linux.yml
  Makefile
  common/numerated/src/iterators.rs
  common/numerated/src/lib.rs
  common/numerated/src/numerated.rs
  common/numerated/src/tree.rs
  common/src/lib.rs
  core-errors/src/lib.rs
  core-processor/src/lib.rs
  core/src/lib.rs
  ethexe/common/src/crypto/signature.rs
  ethexe/consensus/src/lib.rs
  ethexe/runtime/common/src/state.rs
  galloc/src/lib.rs
  gbuiltins/bls381/src/lib.rs
  gbuiltins/staking/src/lib.rs
  gcli/tests/cmd/claim.rs
  gcli/tests/cmd/info.rs
  gcli/tests/cmd/reply.rs
  gcli/tests/cmd/send.rs
  gcli/tests/common/mod.rs
  gclient/src/api/calls.rs
  gclient/src/api/listener/iterator.rs
  gclient/src/lib.rs
  gcore/src/lib.rs
  gprimitives/src/lib.rs
  gsdk/README.md
  gsdk/src/lib.rs
  gstd/src/lib.rs
  gtest/src/lib.rs
  lazy-pages/src/lib.rs
  node/authorship/src/authorship.rs
  node/authorship/src/lib.rs
  node/cli/src/cli.rs
  pallets/gas/src/lib.rs
  pallets/gear-bank/src/lib.rs
  pallets/gear-eth-bridge/primitives/src/lib.rs
  pallets/gear-eth-bridge/src/lib.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-program/src/lib.rs
  pallets/gear-scheduler/src/lib.rs
  pallets/gear/rpc/runtime-api/src/lib.rs
  pallets/gear/rpc/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/payment/src/lib.rs
  runtime/vara/src/lib.rs
  utils/gring/src/keyring.rs
  utils/node-wrapper/src/instance.rs
  utils/node-wrapper/src/node.rs
  utils/runtime-fuzzer/bin/run_corpus.rs
  utils/runtime-fuzzer/src/data.rs
  utils/wasm-builder/src/lib.rs
  utils/wasm-instrument/src/lib.rs
Labels: A2-mergeoncegreen

#4848 build(nix): rework Nix devenv
  .envrc
  flake.lock
  flake.nix
  npins/default.nix
  npins/sources.json
  scripts/src/test.sh
  shell.nix
  utils/cargo-gbuild/tests/smoke.rs
  utils/wasm-optimizer/src/cargo_command.rs
  utils/wasm-optimizer/src/cargo_toolchain.rs
Labels: A0-pleasereview, D5-tooling

#4855 style: move `format_code_in_doc_comments` to the root `rustfmt.toml`
  common/numerated/src/numerated.rs
  common/numerated/src/tree.rs
  gbuiltins/staking/src/lib.rs
  gcli/src/cmd/program.rs
  gclient/rustfmt.toml
  gcore/rustfmt.toml
  gsdk/src/storage.rs
  gstd/rustfmt.toml
  gtest/rustfmt.toml
  pallets/gear/src/schedule.rs
  pallets/staking-rewards/src/lib.rs
  rustfmt.toml
  sandbox/host/src/store_refcell.rs
  utils/wasm-gen/src/config.rs
Labels: A0-pleasereview, D5-tooling

#4842 refactor(ethexe): Make `TxPoolService` an actual service
  Cargo.lock
  ethexe/service/src/lib.rs
  ethexe/service/src/tests/mod.rs
  ethexe/service/src/tests/utils/events.rs
  ethexe/tx-pool/Cargo.toml
  ethexe/tx-pool/src/lib.rs
  gstd/Cargo.toml
  pallets/gear-builtin/Cargo.toml
Labels: A0-pleasereview, D8-gearexe

#4856 fix(ethexe): fix potential problem in consensus implementation
  ethexe/consensus/src/lib.rs
  ethexe/consensus/src/mock.rs
  ethexe/consensus/src/utils.rs
  ethexe/consensus/src/validator/coordinator.rs
  ethexe/consensus/src/validator/core.rs
  ethexe/consensus/src/validator/initial.rs
  ethexe/consensus/src/validator/mock.rs
  ethexe/consensus/src/validator/mod.rs
  ethexe/consensus/src/validator/participant.rs
  ethexe/consensus/src/validator/producer.rs
  ethexe/consensus/src/validator/submitter.rs
  ethexe/consensus/src/validator/subordinate.rs
  ethexe/ethereum/src/deploy.rs
  ethexe/ethereum/src/lib.rs
Labels: A0-pleasereview, A2-mergeoncegreen, D8-gearexe

#4866 chore(runtime): remove legacy, applied migrations
  Cargo.lock
  pallets/gear-bank/Cargo.toml
  pallets/gear-bank/src/lib.rs
  pallets/gear-bank/src/migrations.rs
  pallets/gear-builtin/Cargo.toml
  pallets/gear-builtin/src/lib.rs
  pallets/gear-builtin/src/migration.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migrations/mod.rs
  pallets/gear-program/src/migrations/v11_code_metadata_delete_migration.rs
  pallets/gear-program/src/migrations/v12_program_code_id_migration.rs
  pallets/gear-program/src/migrations/v13_split_instrumented_code_migration.rs
  runtime/vara/src/migrations.rs
Labels: A2-mergeoncegreen

#4840 feat(bridge): impl unlimited queue capacity
  gbuiltins/eth-bridge/src/lib.rs
  gsdk/src/metadata/generated.rs
  pallets/gear-eth-bridge/src/builtin.rs
  pallets/gear-eth-bridge/src/internal.rs
  pallets/gear-eth-bridge/src/lib.rs
  pallets/gear-eth-bridge/src/migrations/reset.rs
  pallets/gear-eth-bridge/src/mock.rs
  pallets/gear-eth-bridge/src/tests.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
  runtime/vara/src/tests/mod.rs
Labels: A0-pleasereview

#4877 chore(test-measurements): Checkout submodules recursively
  .github/workflows/test-measurements.yaml
Labels: A0-pleasereview, D4-test, D5-tooling

#4878 refactor(ethexe-network): Resolve TODOs
  ethexe/cli/src/params/mod.rs
  ethexe/cli/src/params/network.rs
  ethexe/common/src/db.rs
  ethexe/db/src/database.rs
  ethexe/network/src/db_sync/mod.rs
  ethexe/network/src/db_sync/responses.rs
  ethexe/network/src/lib.rs
  ethexe/processor/src/host/api/database.rs
  ethexe/service/src/config.rs
  ethexe/service/src/fast_sync.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests/mod.rs
  ethexe/service/src/tests/utils/env.rs
Labels: A0-pleasereview, D8-gearexe
