Repository gear-tech/gear, pull requests merged in 2025-05, with the labels that each got.

#4633 fix(builtins): mint and lock ED for builtins as for programs
  pallets/gear-builtin/Cargo.toml
  pallets/gear-builtin/src/lib.rs
  pallets/gear-builtin/src/migration.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-builtin/src/tests/staking.rs
  pallets/gear-eth-bridge/src/mock.rs
  pallets/gear/src/lib.rs
  runtime/vara/src/genesis_config_presets.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/migrations.rs
Labels: A0-pleasereview

#4591 feat!(ethexe): block producer
  Cargo.lock
  Cargo.toml
  ethexe/cli/src/params/node.rs
  ethexe/common/src/gear.rs
  ethexe/common/src/lib.rs
  ethexe/compute/src/lib.rs
  ethexe/consensus/Cargo.toml
  ethexe/consensus/src/connect/mod.rs
  ethexe/consensus/src/lib.rs
  ethexe/consensus/src/mock.rs
  ethexe/consensus/src/utils.rs
  ethexe/consensus/src/validator/coordinator.rs
  ethexe/consensus/src/validator/initial.rs
  ethexe/consensus/src/validator/mock.rs
  ethexe/consensus/src/validator/mod.rs
  ethexe/consensus/src/validator/participant.rs
  ethexe/consensus/src/validator/producer.rs
  ethexe/consensus/src/validator/submitter.rs
  ethexe/consensus/src/validator/subordinate.rs
  ethexe/contracts/src/Router.sol
  ethexe/contracts/test/Base.t.sol
  ethexe/docker/docker-compose.yml
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/TransparentUpgradeableProxy.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/prometheus/src/lib.rs
  ethexe/sequencer/src/agro.rs
  ethexe/sequencer/src/lib.rs
  ethexe/sequencer/src/tests.rs
  ethexe/service/Cargo.toml
  ethexe/service/src/config.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/signer/src/contract.rs
  ethexe/signer/src/digest.rs
  ethexe/signer/src/lib.rs
  ethexe/signer/src/signature.rs
  ethexe/validator/Cargo.toml
  ethexe/validator/src/lib.rs
Labels: A2-mergeoncegreen

#4644 feat(tooling): add nix flake development environment
  .envrc
  .gitignore
  flake.lock
  flake.nix
  utils/cargo-gbuild/tests/smoke.rs
  utils/wasm-optimizer/src/cargo_command.rs
  utils/wasm-optimizer/src/cargo_toolchain.rs
Labels: A0-pleasereview, D5-tooling

#4653 chore: add --profile ci to gclient testing
  scripts/src/test.sh
Labels: A0-pleasereview

#4655 feat(ethexe): support in rust rewards commitment types
  ethexe/common/src/gear.rs
  ethexe/consensus/src/utils.rs
  ethexe/consensus/src/validator/producer.rs
  ethexe/consensus/src/validator/submitter.rs
  ethexe/ethereum/src/abi/gear.rs
  ethexe/signer/src/digest.rs
Labels: A0-pleasereview

#4634 feat!(gear): invariant for value passing only with messages; error replies inherit value as well
  core-processor/src/common.rs
  core-processor/src/handler.rs
  core-processor/src/processing.rs
  core/src/message/reply.rs
  ethexe/runtime/common/src/journal.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/send_dispatch.rs
  gtest/src/manager/task.rs
  gtest/src/state/bank.rs
  pallets/gear-bank/src/lib.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear/src/internal.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#4652 fix(ethexe): switch to blocking RwLock in MockBlobReader
  ethexe/observer/src/blobs.rs
  ethexe/observer/src/tests.rs
  ethexe/rpc/src/apis/dev.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4618 refactor(ethexe-signer): signer refactoring; switch to k256 crate instead of secp256k1
  Cargo.lock
  ethexe/cli/src/commands/key.rs
  ethexe/cli/src/commands/tx.rs
  ethexe/consensus/src/mock.rs
  ethexe/consensus/src/utils.rs
  ethexe/consensus/src/validator/coordinator.rs
  ethexe/consensus/src/validator/participant.rs
  ethexe/consensus/src/validator/producer.rs
  ethexe/consensus/src/validator/submitter.rs
  ethexe/consensus/src/validator/subordinate.rs
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/network/src/lib.rs
  ethexe/observer/src/tests.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/signer/Cargo.toml
  ethexe/signer/src/address.rs
  ethexe/signer/src/contract.rs
  ethexe/signer/src/digest.rs
  ethexe/signer/src/keys.rs
  ethexe/signer/src/lib.rs
  ethexe/signer/src/signature.rs
  ethexe/signer/src/signer.rs
  ethexe/signer/src/storage.rs
  ethexe/tx-pool/src/lib.rs
  ethexe/tx-pool/src/tests.rs
  ethexe/tx-pool/src/validation.rs
Labels: A0-pleasereview

#4626 refactor(ethexe-consensus): Remove `Box<...>` in `ServiceHandler`
  ethexe/consensus/src/connect/mod.rs
  ethexe/consensus/src/validator/coordinator.rs
  ethexe/consensus/src/validator/initial.rs
  ethexe/consensus/src/validator/mock.rs
  ethexe/consensus/src/validator/mod.rs
  ethexe/consensus/src/validator/participant.rs
  ethexe/consensus/src/validator/producer.rs
  ethexe/consensus/src/validator/submitter.rs
  ethexe/consensus/src/validator/subordinate.rs
Labels: A0-pleasereview

#4662 chore(ci): Use faster linkers
  .github/workflows/build-macos.yml
  .github/workflows/build-win-native.yml
  .github/workflows/build.yml
  scripts/cargo-xwin.sh
Labels: A0-pleasereview, A4-insubstantial, E2-forcemacos, E1-forcenatwin, E3-forcerelease

#4660 refactor(core): [p.1] shuffle some modules
  common/src/event.rs
  core-backend/src/env.rs
  core-backend/src/error.rs
  core-backend/src/funcs.rs
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/precharge.rs
  core-processor/src/processing.rs
  core-processor/tests/codes_display_len.rs
  core/src/buffer.rs
  core/src/code/utils.rs
  core/src/env.rs
  core/src/gas.rs
  core/src/lib.rs
  core/src/message/common.rs
  core/src/message/context.rs
  core/src/message/handle.rs
  core/src/message/incoming.rs
  core/src/message/init.rs
  core/src/message/mod.rs
  core/src/message/reply.rs
  core/src/message/stored.rs
  core/src/message/user.rs
  core/src/rpc.rs
  ethexe/db/src/database.rs
  ethexe/processor/src/lib.rs
  ethexe/rpc/src/apis/program.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/src/wasm/storage.rs
  gclient/src/api/rpc.rs
  gsdk/src/lib.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/rpc.rs
  gsdk/src/signer/rpc.rs
  gsdk/tests/rpc.rs
  gtest/src/log.rs
  gtest/src/manager/journal.rs
  node/authorship/src/tests.rs
  pallets/gear-builtin/src/benchmarking.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear-builtin/src/mock.rs
  pallets/gear-builtin/src/tests/bad_builtin_ids.rs
  pallets/gear-eth-bridge/src/builtin.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/builtin.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/task.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/schedule.rs
  pallets/gear/src/tests.rs
  utils/runtime-fuzzer/src/generator.rs
Labels: A0-pleasereview

#4603 implement updradeable logic for middleware
  ethexe/contracts/.env.example
  ethexe/contracts/script/Deployment.s.sol
  ethexe/contracts/src/IMiddleware.sol
  ethexe/contracts/src/Middleware.sol
  ethexe/contracts/src/libraries/Gear.sol
  ethexe/contracts/test/Base.t.sol
  ethexe/contracts/test/Middleware.t.sol
Labels: A0-pleasereview

#4671 chore(gear-cli): Update mimalloc to 0.1.46
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview, D2-node

#4617 feat(ethexe): implement BlobLoaderService
  Cargo.lock
  Cargo.toml
  ethexe/blob-loader/Cargo.toml
  ethexe/blob-loader/src/lib.rs
  ethexe/blob-loader/src/local.rs
  ethexe/common/src/db.rs
  ethexe/compute/src/lib.rs
  ethexe/contracts/src/IMiddleware.sol
  ethexe/db/src/database.rs
  ethexe/observer/Cargo.toml
  ethexe/observer/src/blobs.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/sync.rs
  ethexe/observer/src/tests.rs
  ethexe/observer/src/utils.rs
  ethexe/rpc/Cargo.toml
  ethexe/rpc/src/apis/dev.rs
  ethexe/rpc/src/lib.rs
  ethexe/service/Cargo.toml
  ethexe/service/src/fast_sync.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4676 feat(ci): Clippy multiple target runners
  .github/workflows/build.yml
  .github/workflows/check.yml
  core-backend/src/env.rs
  ethexe/common/src/crypto/keys.rs
  examples/async-critical/src/wasm.rs
  examples/async-reply-hook/src/wasm.rs
  gstd/src/common/handlers.rs
  gstd/src/reservations.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/sys/windows.rs
  node/testing/Cargo.toml
  pallets/gear/proc-macro/src/lib.rs
  runtime-interface/src/lib.rs
  sandbox/sandbox/src/embedded_executor.rs
  sandbox/sandbox/src/host_executor.rs
  sandbox/sandbox/src/lib.rs
  scripts/gear.sh
  scripts/src/check.sh
  scripts/src/clippy.sh
  scripts/src/test.sh
  utils/gear-replay-cli/Cargo.toml
Labels: A0-pleasereview

#4649 feat(ethexe/mirror): partially support whether to call message or just emit event
  ethexe/common/src/events/mirror.rs
  ethexe/common/src/gear.rs
  ethexe/consensus/src/mock.rs
  ethexe/contracts/foundry.toml
  ethexe/contracts/script/Deployment.s.sol
  ethexe/contracts/src/IMirror.sol
  ethexe/contracts/src/Mirror.sol
  ethexe/contracts/src/MirrorProxy.sol
  ethexe/contracts/src/libraries/Clones.sol
  ethexe/contracts/src/libraries/Gear.sol
  ethexe/contracts/test/Base.t.sol
  ethexe/contracts/test/POC.t.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/abi/events/mirror.rs
  ethexe/ethereum/src/abi/gear.rs
  ethexe/ethereum/src/mirror/events.rs
  ethexe/ethereum/src/mirror/mod.rs
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/handling/run.rs
  ethexe/processor/src/host/mod.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/common/src/transitions.rs
  ethexe/runtime/src/wasm/api/mod.rs
  ethexe/runtime/src/wasm/api/run.rs
Labels: A0-pleasereview

#4670 refactor(ethexe-service): Implement `TestableEvent`
  ethexe/blob-loader/src/lib.rs
  ethexe/compute/src/lib.rs
  ethexe/network/src/db_sync/mod.rs
  ethexe/prometheus/src/lib.rs
  ethexe/rpc/src/lib.rs
  ethexe/service/src/fast_sync.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/service/src/tests/mod.rs
  ethexe/service/src/tests/utils/env.rs
  ethexe/service/src/tests/utils/events.rs
  ethexe/service/src/tests/utils/mod.rs
Labels: A0-pleasereview, D4-test
