Repository gear-tech/gear, pull requests merged in 2025-01, with the labels that each got.

#4425 fix(ethexe): bump version of alloy, fix tests
  Cargo.lock
  Cargo.toml
  ethexe/cli/src/service.rs
  ethexe/cli/src/tests.rs
Labels: A0-pleasereview

#4421 refactor(ethexe/cli): lots of changes; improved redesign
  .config/nextest.toml
  Cargo.lock
  Cargo.toml
  Makefile
  ethexe/cli/Cargo.toml
  ethexe/cli/src/args.rs
  ethexe/cli/src/chain_spec.rs
  ethexe/cli/src/commands/key.rs
  ethexe/cli/src/commands/mod.rs
  ethexe/cli/src/commands/run.rs
  ethexe/cli/src/commands/tx.rs
  ethexe/cli/src/config.rs
  ethexe/cli/src/lib.rs
  ethexe/cli/src/main.rs
  ethexe/cli/src/metrics.rs
  ethexe/cli/src/params/ethereum.rs
  ethexe/cli/src/params/mod.rs
  ethexe/cli/src/params/network.rs
  ethexe/cli/src/params/node.rs
  ethexe/cli/src/params/prometheus.rs
  ethexe/cli/src/params/rpc.rs
  ethexe/network/Cargo.toml
  ethexe/service/Cargo.toml
  ethexe/service/src/config.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/signer/src/lib.rs
  ethexe/signer/src/signature.rs
  ethexe/utils/prometheus/Cargo.toml
  ethexe/utils/prometheus/src/lib.rs
Labels: A0-pleasereview

#4430 feat(ethexe): support non active programs
  .github/workflows/check.yml
  Cargo.lock
  ethexe/runtime/common/src/lib.rs
  ethexe/service/Cargo.toml
  ethexe/service/src/tests.rs
  examples/async-init/Cargo.toml
  examples/async-init/src/wasm.rs
Labels: A0-pleasereview

#4429 fix(crates-io): publish of core-processor with new dependency
  runtime-interface/Cargo.toml
  utils/crates-io/src/handler.rs
  utils/crates-io/src/lib.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#4420 fix(sandbox): clear sandbox store inside a block
  node/cli/src/cli.rs
  node/cli/src/command.rs
  runtime-interface/sandbox/src/detail.rs
  sandbox/host/src/sandbox.rs
  utils/gear-replay-cli/src/cmd/mod.rs
Labels: A2-mergeoncegreen

#4434 fix(ci): feature gateway
  README.md
  examples/constructor/src/arg.rs
  examples/constructor/src/builder.rs
  examples/constructor/src/call.rs
  examples/constructor/src/wasm.rs
  pallets/gear/Cargo.toml
  runtime-interface/Cargo.toml
  runtime-interface/sandbox/Cargo.toml
Labels: A0-pleasereview, E3-forcerelease

#4435 fix(ethexe): properly define region idx for memory pages
  ethexe/runtime/common/src/state.rs
Labels: A0-pleasereview

#4412 fix(ethexe): problem with many redundant block commitments
  Cargo.lock
  ethexe/ethereum/src/lib.rs
  ethexe/sequencer/src/lib.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/signer/Cargo.toml
  ethexe/signer/src/lib.rs
Labels: A0-pleasereview

#4436 fix(ethexe): correctly determine if allocations changed
  ethexe/runtime/common/src/state.rs
Labels: A0-pleasereview

#4437 chore: rename WAMV to Wasm VM
  README.md
Labels: A0-pleasereview

#4441 chore(ethexe): add getters for `*.sol` contract interfaces on Rust side
  ethexe/ethereum/src/mirror/mod.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/ethereum/src/wvara/mod.rs
Labels: A0-pleasereview

#4426 feat(ethexe): support late commitments validation
  ethexe/contracts/script/Deployment.s.sol
  ethexe/contracts/src/Router.sol
  ethexe/contracts/src/libraries/Gear.sol
  ethexe/contracts/test/Base.t.sol
  ethexe/contracts/test/Router.t.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/TransparentUpgradeableProxy.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/lib.rs
Labels: A0-pleasereview

#4427 feat(ethexe-tx-pool): introduce proper tx pool integration with rpc and service
  Cargo.lock
  ethexe/db/src/database.rs
  ethexe/rpc/src/apis/tx_pool.rs
  ethexe/rpc/src/lib.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/tx-pool/Cargo.toml
  ethexe/tx-pool/src/lib.rs
  ethexe/tx-pool/src/service.rs
  ethexe/tx-pool/src/tests.rs
  ethexe/tx-pool/src/transaction.rs
  ethexe/tx-pool/src/validation.rs
Labels: A0-pleasereview

#4439 chore(benchmarks): Implement new Substrate-approach to build the genesis
  Cargo.lock
  Cargo.toml
  gsdk/Cargo.toml
  node/service/Cargo.toml
  node/service/src/chain_spec/mod.rs
  node/service/src/chain_spec/vara.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/genesis_config_presets.rs
  runtime/vara/src/lib.rs
  scripts/benchmarking/run_all_benchmarks.sh
  utils/cargo-gbuild/Cargo.toml
  utils/gring/Cargo.toml
  utils/regression-analysis/Cargo.toml
Labels: A0-pleasereview, D2-node, C2-refactoring

#4446 feat(gprimitives): serialize actor id as hex
  ethexe/rpc/Cargo.toml
  ethexe/runtime/common/src/state.rs
  gprimitives/Cargo.toml
  gprimitives/src/lib.rs
  pallets/gear-builtin/src/lib.rs
Labels: A2-mergeoncegreen

#4450 chore(tests): re-run tests for gclient if failed
  .config/nextest.toml
  gclient/tests/upload.rs
Labels: A0-pleasereview, A4-insubstantial

#4452 chore(gcore): rename with_read_on_stack -> with_read_on_stack_or_heap
  examples/piggy-bank/src/wasm.rs
  examples/stack-allocations/src/wasm.rs
  gcore/src/msg.rs
  gstd/src/msg/encoded.rs
  gstd/src/msg/mod.rs
Labels: A0-pleasereview, A4-insubstantial

#4457 fix(sandbox, lazy-pages): Increase corosensei precommited stack size to 1MiB (windows)
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview, E1-forcenatwin

#4458 feat(ethexe): dev mode, set blob via rpc
  Cargo.lock
  ethexe/cli/src/params/ethereum.rs
  ethexe/cli/src/params/mod.rs
  ethexe/cli/src/params/node.rs
  ethexe/cli/src/params/rpc.rs
  ethexe/rpc/Cargo.toml
  ethexe/rpc/src/apis/dev.rs
  ethexe/rpc/src/apis/mod.rs
  ethexe/rpc/src/lib.rs
  ethexe/service/src/config.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
Labels: A2-mergeoncegreen

#4451 chore(tests): enable RUST_LIB_BACKTRACE=1 for CI and other
  .github/workflows/CI.yaml
  .github/workflows/PR.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-win-native.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/crates-io.yml
Labels: A0-pleasereview, A4-insubstantial

#4453 chore(core-processor): remove ActorExecutionError::UnsupportedMessage
  core-processor/src/common.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/src/message/context.rs
  lazy-pages/src/common.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear/src/tests.rs
  utils/wasm-gen/src/tests.rs
Labels: A0-pleasereview, A4-insubstantial

#4468 fix(ci): downgrade `@openzeppelin/upgrades-core` to `=1.41.0` using `sed`
  .github/workflows/check.yml
Labels: A0-pleasereview

#4456 refactor(ethexe): service based architecture
  Cargo.lock
  Cargo.toml
  ethexe/cli/Cargo.toml
  ethexe/cli/src/params/ethereum.rs
  ethexe/cli/src/params/network.rs
  ethexe/cli/src/params/prometheus.rs
  ethexe/common/src/db.rs
  ethexe/common/src/events/mirror.rs
  ethexe/common/src/events/mod.rs
  ethexe/common/src/events/router.rs
  ethexe/common/src/events/wvara.rs
  ethexe/contracts/script/Deployment.s.sol
  ethexe/contracts/src/libraries/Gear.sol
  ethexe/contracts/test/Base.t.sol
  ethexe/contracts/test/POC.t.sol
  ethexe/contracts/test/Router.t.sol
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/TransparentUpgradeableProxy.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/mirror/events.rs
  ethexe/ethereum/src/router/events.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/ethereum/src/wvara/events.rs
  ethexe/network/Cargo.toml
  ethexe/network/src/lib.rs
  ethexe/observer/Cargo.toml
  ethexe/observer/src/blobs.rs
  ethexe/observer/src/event.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/observer.rs
  ethexe/observer/src/query.rs
  ethexe/observer/src/tests.rs
  ethexe/processor/src/lib.rs
  ethexe/prometheus/Cargo.toml
  ethexe/prometheus/src/lib.rs
  ethexe/rpc/src/apis/dev.rs
  ethexe/sequencer/Cargo.toml
  ethexe/sequencer/src/lib.rs
  ethexe/sequencer/src/tests.rs
  ethexe/service/Cargo.toml
  ethexe/service/src/config.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/service/utils/Cargo.toml
  ethexe/service/utils/src/lib.rs
  ethexe/service/utils/src/timer.rs
  ethexe/utils/Cargo.toml
  ethexe/utils/prometheus/Cargo.toml
  ethexe/utils/prometheus/src/lib.rs
  ethexe/utils/prometheus/src/sourced.rs
  ethexe/utils/src/lib.rs
  ethexe/utils/src/metrics.rs
  ethexe/utils/src/mpsc.rs
Labels: A0-pleasereview

#4454 refactor(common): 3879 change return types for insert and remove in numerated intervals tree
  common/numerated/src/tree.rs
  core/src/memory.rs
  lazy-pages/src/common.rs
Labels: A0-pleasereview, Q1-easy

#4472 refactor(sequencer): impl FuturesUnordered managing of commit submissions
  ethexe/sequencer/src/lib.rs
  ethexe/service/src/lib.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#4471 refactor(ethexe): accept only EIP-4844 transactions in `requestCodeValidation`
  ethexe/cli/src/commands/tx.rs
  ethexe/common/src/db.rs
  ethexe/common/src/events/router.rs
  ethexe/contracts/src/IRouter.sol
  ethexe/contracts/src/Router.sol
  ethexe/contracts/test/POC.t.sol
  ethexe/db/src/database.rs
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/MirrorProxy.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/TransparentUpgradeableProxy.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/abi/events/router.rs
  ethexe/ethereum/src/router/events.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/query.rs
  ethexe/observer/src/tests.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4459 chore: add testing encode/decode for ReplyCode and SignalCode
  core-errors/src/simple.rs
Labels: A0-pleasereview, A4-insubstantial

#4470 feat(ethexe): implement more rpc methods
  Cargo.toml
  ethexe/common/Cargo.toml
  ethexe/common/src/db.rs
  ethexe/common/src/events/mirror.rs
  ethexe/common/src/events/mod.rs
  ethexe/common/src/events/router.rs
  ethexe/common/src/events/wvara.rs
  ethexe/common/src/gear.rs
  ethexe/db/src/database.rs
  ethexe/rpc/Cargo.toml
  ethexe/rpc/src/apis/block.rs
  ethexe/rpc/src/apis/code.rs
  ethexe/rpc/src/apis/mod.rs
  ethexe/rpc/src/apis/program.rs
  ethexe/rpc/src/lib.rs
  ethexe/runtime/common/src/state.rs
Labels: A0-pleasereview

#4480 refactor(ethexe): impl proper Streams on services
  ethexe/network/src/lib.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/tests.rs
  ethexe/prometheus/src/lib.rs
  ethexe/sequencer/src/lib.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/service/utils/src/lib.rs
  ethexe/service/utils/src/timer.rs
Labels: A0-pleasereview

#4478 feat(wasm-builder): Include workspace patches
  utils/wasm-builder/src/crate_info.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, D5-tooling

#4481 feat(ethexe): impl headers stream resubscription for observer service
  ethexe/observer/src/lib.rs
Labels: A0-pleasereview

#4482 chore(wasm-info): Removal
  Cargo.lock
  utils/wasm-info/Cargo.toml
  utils/wasm-info/src/main.rs
Labels: A0-pleasereview, D5-tooling

#4477 fix(vara-runtime): Do not use floats
  Cargo.lock
  Cargo.toml
  node/service/src/chain_spec/vara.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/genesis_config_presets.rs
Labels: A0-pleasereview, D2-node

#4485 chore(wasm-builder): add constants module for CodeValidator
  utils/wasm-builder/src/code_validator.rs
Labels: A0-pleasereview
