Repository gear-tech/gear, pull requests merged in 2025-03, with the labels that each got.

#4509 refactor(core): store bool flag instead of full init allocations
  core-processor/src/ext.rs
  core/src/memory.rs
Labels: A0-pleasereview, C2-refactoring

#4512 feat(ethexe): observer on-chain data sync
  ethexe/cli/src/params/node.rs
  ethexe/common/src/db.rs
  ethexe/compute/src/lib.rs
  ethexe/db/src/database.rs
  ethexe/observer/src/blobs.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/observer.rs
  ethexe/observer/src/query.rs
  ethexe/observer/src/sync.rs
  ethexe/observer/src/tests.rs
  ethexe/observer/src/utils.rs
  ethexe/rpc/src/apis/block.rs
  ethexe/rpc/src/apis/dev.rs
  ethexe/service/src/config.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/validator/src/lib.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#4521 ethexe(refactor): db refactoring
  ethexe/common/src/db.rs
  ethexe/compute/src/lib.rs
  ethexe/db/Cargo.toml
  ethexe/db/src/database.rs
  ethexe/db/src/lib.rs
  ethexe/db/src/mem.rs
  ethexe/db/src/overlay.rs
  ethexe/db/src/rocks.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/sync.rs
  ethexe/observer/src/tests.rs
  ethexe/processor/src/handling/mod.rs
  ethexe/processor/src/host/threads.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/rpc/src/common.rs
  ethexe/sequencer/src/lib.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/tx-pool/src/tests.rs
  ethexe/validator/Cargo.toml
  ethexe/validator/src/lib.rs
Labels: A0-pleasereview

#4528 feat(ethexe): update alloy to 0.12
  Cargo.lock
  Cargo.toml
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/mirror/mod.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/ethereum/src/wvara/mod.rs
  ethexe/observer/src/blobs.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/sync.rs
  ethexe/observer/src/utils.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview, dependencies

#4523 feat(workspace): support Rust 2024 edition
  Cargo.lock
  Cargo.toml
  Makefile
  common/src/gas_provider/property_tests/mod.rs
  common/src/storage/complicated/dequeue.rs
  core-processor/src/ext.rs
  core/src/buffer.rs
  ethexe/cli/src/lib.rs
  ethexe/cli/src/params/node.rs
  ethexe/network/src/db_sync/ongoing.rs
  ethexe/network/src/utils.rs
  examples/constructor/src/call.rs
  gprimitives/src/lib.rs
  gprimitives/src/utils.rs
  gsdk/codegen/src/storage.rs
  gsdk/src/client.rs
  gsdk/tests/rpc.rs
  gtest/src/lib.rs
  gtest/src/manager/block_exec.rs
  node/authorship/src/authorship.rs
  node/cli/src/benchmarking.rs
  node/cli/src/command.rs
  node/cli/src/main.rs
  node/service/src/lib.rs
  pallets/gas/src/lib.rs
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear-messenger/src/lib.rs
  pallets/gear-voucher/src/internal.rs
  pallets/gear/src/tests.rs
  pallets/staking-rewards/src/lib.rs
  runtime/vara/src/tests/utils.rs
  rustfmt.toml
  utils/cargo-gbuild/test-program/Cargo.toml
  utils/cargo-gbuild/test-program/bar/Cargo.toml
  utils/cargo-gbuild/test-program/foo/Cargo.toml
  utils/gear-replay-cli/src/cmd/mod.rs
  utils/gear-replay-cli/src/lib.rs
  utils/regression-analysis/src/main.rs
  utils/ss58/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-builder/test-program/Cargo.toml
  utils/wasm-gen/src/generator/syscalls/invocator.rs
Labels: A0-pleasereview

#4460 feat(ethexe): split single mailbox entry into user individuals
  .gitignore
  core/src/buffer.rs
  ethexe/db/src/database.rs
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/tests.rs
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/src/wasm/storage.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4536 feat(ethexe-service): Named services in test logs
  Cargo.lock
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4535 fix(ethexe): Receiver can miss events in tests
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4540 refactor(ethexe-runtime-common): Idiomatic method names for `MaybeHashOf`
  ethexe/processor/src/host/threads.rs
  ethexe/processor/src/tests.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/state.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4537 feat(ethexe): append service identity (block-identity)
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/mirror/mod.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/ethereum/src/wvara/mod.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/sync.rs
  ethexe/observer/src/tests.rs
  ethexe/observer/src/utils.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4541 refactor(ethexe): create separate DB folders for routers, do not use router address as key prefix
  ethexe/compute/src/lib.rs
  ethexe/db/src/database.rs
  ethexe/network/src/db_sync/mod.rs
  ethexe/network/src/lib.rs
  ethexe/observer/src/tests.rs
  ethexe/processor/src/tests.rs
  ethexe/service/src/config.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
  ethexe/tx-pool/src/tests.rs
  ethexe/tx-pool/src/validation.rs
  ethexe/validator/src/lib.rs
Labels: A0-pleasereview

#4567 feat(observer): add resubscribing for headers stream after its termin…
  ethexe/observer/src/lib.rs
Labels: A0-pleasereview, C2-refactoring

#4570 Add todo for issue 4568
  ethexe/observer/src/lib.rs
Labels: A0-pleasereview

#4573 chore(ethexe): remove block_time in MockBlobReader
  ethexe/observer/src/blobs.rs
  ethexe/observer/src/tests.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests.rs
Labels: A0-pleasereview

#4575 chore: Skip runtime build on Intellij project sync
  ethexe/runtime/build.rs
  runtime/vara/build.rs
Labels: A0-pleasereview

#4578 chore: Remove and check unused dependencies
  .github/workflows/check.yml
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/numerated/Cargo.toml
  common/numerated/src/tree.rs
  core-processor/Cargo.toml
  ethexe/common/Cargo.toml
  ethexe/compute/Cargo.toml
  ethexe/ethereum/Cargo.toml
  ethexe/network/Cargo.toml
  ethexe/observer/Cargo.toml
  ethexe/prometheus/Cargo.toml
  ethexe/rpc/Cargo.toml
  ethexe/runtime/Cargo.toml
  ethexe/sequencer/Cargo.toml
  ethexe/service/Cargo.toml
  ethexe/service/utils/Cargo.toml
  ethexe/tx-pool/Cargo.toml
  ethexe/validator/Cargo.toml
  examples/async-critical/Cargo.toml
  examples/async-custom-entry/Cargo.toml
  examples/async-reply-hook/Cargo.toml
  examples/autoreply/Cargo.toml
  examples/calc-hash/Cargo.toml
  examples/constructor/Cargo.toml
  examples/proxy-broker/Cargo.toml
  examples/staking-broker/Cargo.toml
  examples/syscall-error/Cargo.toml
  examples/wait/Cargo.toml
  gbuiltins/bls381/Cargo.toml
  gbuiltins/proxy/Cargo.toml
  gbuiltins/staking/Cargo.toml
  gcli/Cargo.toml
  gprimitives/Cargo.toml
  gsdk/Cargo.toml
  gsdk/api-gen/Cargo.toml
  gtest/Cargo.toml
  lazy-pages/native-interface/Cargo.toml
  node/authorship/Cargo.toml
  node/service/Cargo.toml
  node/testing/Cargo.toml
  pallets/gas/Cargo.toml
  pallets/gear-messenger/Cargo.toml
  pallets/gear-program/Cargo.toml
  pallets/gear-scheduler/Cargo.toml
  pallets/gear-voucher/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/gear/rpc/Cargo.toml
  pallets/payment/Cargo.toml
  pallets/staking-rewards/Cargo.toml
  runtime-interface/Cargo.toml
  runtime/common/Cargo.toml
  runtime/vara/Cargo.toml
  utils/cargo-gbuild/Cargo.toml
  utils/gear-replay-cli/Cargo.toml
  utils/lazy-pages-fuzzer/fuzz/Cargo.toml
  utils/node-loader/Cargo.toml
  utils/runtime-fuzzer/Cargo.toml
  utils/wasm-instrument/Cargo.toml
Labels: A0-pleasereview
