Repository gear-tech/gear, pull requests merged in 2025-06, with the labels that each got.

#4488 feat(ethexe): chunked parallel executor/runtime runner
  Cargo.lock
  ethexe/cli/src/commands/mod.rs
  ethexe/cli/src/commands/run.rs
  ethexe/cli/src/commands/tx.rs
  ethexe/cli/src/lib.rs
  ethexe/cli/src/main.rs
  ethexe/cli/src/params/node.rs
  ethexe/common/src/db.rs
  ethexe/common/src/primitives.rs
  ethexe/compute/src/lib.rs
  ethexe/db/src/database.rs
  ethexe/processor/Cargo.toml
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/handling/run.rs
  ethexe/processor/src/host/api/database.rs
  ethexe/processor/src/host/mod.rs
  ethexe/processor/src/host/threads.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/rpc/src/apis/program.rs
  ethexe/runtime/Cargo.toml
  ethexe/runtime/common/src/journal.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/state.rs
  ethexe/runtime/common/src/transitions.rs
  ethexe/runtime/src/wasm/api/mod.rs
  ethexe/runtime/src/wasm/api/run.rs
  ethexe/runtime/src/wasm/interface/database.rs
  ethexe/runtime/src/wasm/storage.rs
  ethexe/service/src/config.rs
  ethexe/service/src/fast_sync.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests/mod.rs
Labels: A2-mergeoncegreen

#4701 fix(gbuiltin-proxy): Fix proxy builtin actor id
  examples/proxy-broker/src/wasm.rs
  pallets/gear-builtin/src/mock.rs
Labels: A0-pleasereview

#4697 chore(ci): Use Ubuntu ARM for clippy
  .github/actions/docs/action.yml
  .github/actions/setup-linker/action.yml
  .github/build-win-cross/config.toml
  .github/workflows/build-macos.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
  scripts/cargo-xwin.sh
  scripts/gear.sh
Labels: A0-pleasereview

#4702 feat(lazy-pages): Support linux Aarch64 target
  lazy-pages/src/sys/unix.rs
Labels: A0-pleasereview

#4596 chore(ethexe): bump alloy to 1.0
  Cargo.lock
  Cargo.toml
  ethexe/ethereum/src/lib.rs
  ethexe/ethereum/src/mirror/mod.rs
  ethexe/ethereum/src/router/mod.rs
  ethexe/ethereum/src/wvara/mod.rs
  ethexe/service/src/tests/utils/env.rs
  ethexe/signer/src/signer.rs
  gprimitives/src/sol_types.rs
Labels: A0-pleasereview

#4703 fix(ethexe): move back code blob info storing to observer
  ethexe/common/src/db.rs
  ethexe/common/src/primitives.rs
  ethexe/compute/src/lib.rs
  ethexe/consensus/src/mock.rs
  ethexe/consensus/src/validator/producer.rs
  ethexe/db/src/database.rs
  ethexe/ethereum/Router.json
  ethexe/observer/src/lib.rs
  ethexe/observer/src/sync.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#4705 refactor(ethexe): split db interfaces to read and write
  ethexe/blob-loader/src/lib.rs
  ethexe/blob-loader/src/local.rs
  ethexe/common/src/db.rs
  ethexe/common/src/primitives.rs
  ethexe/compute/src/lib.rs
  ethexe/consensus/src/mock.rs
  ethexe/consensus/src/validator/participant.rs
  ethexe/consensus/src/validator/producer.rs
  ethexe/db/src/database.rs
  ethexe/observer/src/lib.rs
  ethexe/observer/src/sync.rs
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/handling/mod.rs
  ethexe/processor/src/handling/run.rs
  ethexe/processor/src/host/threads.rs
  ethexe/processor/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/rpc/src/apis/block.rs
  ethexe/rpc/src/apis/code.rs
  ethexe/rpc/src/apis/program.rs
  ethexe/rpc/src/common.rs
  ethexe/runtime/common/src/schedule.rs
  ethexe/runtime/common/src/transitions.rs
  ethexe/service/src/fast_sync.rs
  ethexe/service/src/tests/mod.rs
  ethexe/service/src/tests/utils/events.rs
  ethexe/tx-pool/src/tests.rs
Labels: A0-pleasereview, A2-mergeoncegreen

#4714 chore(ethexe-network): Update libp2p
  Cargo.lock
  ethexe/network/Cargo.toml
  ethexe/network/src/custom_connection_limits.rs
  ethexe/network/src/db_sync/mod.rs
  ethexe/network/src/lib.rs
  ethexe/network/src/peer_score.rs
Labels: A0-pleasereview

#4711 chore(ethexe): remove useless as_ref() as_bytes() as_slice()
  ethexe/cli/src/commands/key.rs
  ethexe/common/src/crypto/digest.rs
  ethexe/common/src/crypto/signature.rs
  ethexe/common/src/gear.rs
  ethexe/common/src/primitives.rs
  ethexe/compute/src/lib.rs
  ethexe/consensus/src/utils.rs
  ethexe/consensus/src/validator/coordinator.rs
  ethexe/consensus/src/validator/participant.rs
  ethexe/db/src/database.rs
  ethexe/ethereum/src/lib.rs
  ethexe/processor/src/tests.rs
  ethexe/signer/src/signer.rs
Labels: A0-pleasereview

#4719 refactoring(gtest): Remove redundant `Gas` type from `gtest`
  examples/gas-burned/src/lib.rs
  gtest/src/lib.rs
  gtest/src/log.rs
  gtest/src/manager.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/expend.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/task.rs
  gtest/src/program.rs
  gtest/src/system.rs
Labels: A0-pleasereview, D5-tooling

#4718 fix(ethexe): skipping middleware deployment
  ethexe/contracts/README.md
  ethexe/contracts/script/Deployment.s.sol
Labels: A2-mergeoncegreen

#4706 feat(`ethexe`): switch from anyhow to thiserror (blob-loader, compute, processor)
  Cargo.lock
  Cargo.toml
  ethexe/blob-loader/Cargo.toml
  ethexe/blob-loader/src/lib.rs
  ethexe/blob-loader/src/local.rs
  ethexe/compute/Cargo.toml
  ethexe/compute/src/lib.rs
  ethexe/processor/Cargo.toml
  ethexe/processor/src/handling/events.rs
  ethexe/processor/src/handling/mod.rs
  ethexe/processor/src/host/api/allocator.rs
  ethexe/processor/src/host/api/database.rs
  ethexe/processor/src/host/api/lazy_pages.rs
  ethexe/processor/src/host/api/logging.rs
  ethexe/processor/src/host/api/sandbox.rs
  ethexe/processor/src/host/mod.rs
  ethexe/processor/src/lib.rs
  ethexe/rpc/src/errors.rs
Labels: A0-pleasereview

#4381 feat(code-backend) implemented extractors in backend to avoid accidental memory registry creation
  core-backend/src/accessors.rs
  core-backend/src/funcs.rs
  core-backend/src/lib.rs
  core-backend/src/memory.rs
  core-backend/src/runtime.rs
  core/src/env.rs
  core/src/memory.rs
  lazy-pages/common/src/lib.rs
Labels: A0-pleasereview

#4735 fix(ethexe/blob-loader): add missing features to build crate
  ethexe/blob-loader/Cargo.toml
Labels: A0-pleasereview

#4737 fix: Clippy warnings because of Substrate update
  Cargo.lock
  common/numerated/src/mock.rs
  common/src/gas_provider/internal.rs
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core-processor/src/processing.rs
  core/src/memory.rs
  ethexe/processor/src/host/api/lazy_pages.rs
  ethexe/rpc/src/lib.rs
  ethexe/service/src/tests/utils/env.rs
  gclient/src/api/error.rs
  gsdk/Cargo.toml
  gsdk/src/result.rs
  gsdk/src/utils.rs
  gsdk/tests/rpc.rs
  gtest/src/manager/journal.rs
  lazy-pages/src/lib.rs
  lazy-pages/src/signal.rs
  lazy-pages/src/sys/unix.rs
  node/authorship/src/authorship.rs
  node/service/src/lib.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/staking-rewards/src/lib.rs
  runtime-interface/src/lib.rs
  sandbox/sandbox/src/embedded_executor.rs
  utils/calc-stack-height/src/main.rs
  utils/gear-replay-cli/src/cmd/replay_block.rs
  utils/gear-replay-cli/src/lib.rs
  utils/gear-replay-cli/src/state.rs
  utils/lazy-pages-fuzzer/src/lazy_pages.rs
  utils/runtime-fuzzer/src/generator/upload_program.rs
  utils/runtime-fuzzer/src/lib.rs
  utils/runtime-fuzzer/src/runtime/block.rs
  utils/wasm-builder/src/wasm_project.rs
  utils/wasm-gen/src/generator/memory.rs
  utils/wasm-optimizer/src/optimize.rs
  utils/wasm-optimizer/src/stack_end.rs
  utils/wasm-proc/src/main.rs
Labels: A0-pleasereview

#4736 fix(gtest): swap gas subtraction to addition on repeated message execution
  gtest/src/manager/expend.rs
Labels: A2-mergeoncegreen

#4738 chore: Use `cargo-shear` to detect unused deps
  .github/workflows/check.yml
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/numerated/Cargo.toml
  core-processor/Cargo.toml
  ethexe/consensus/Cargo.toml
  ethexe/db/Cargo.toml
  ethexe/network/Cargo.toml
  ethexe/service/Cargo.toml
  examples/async-custom-entry/Cargo.toml
  examples/async-signal-entry/Cargo.toml
  examples/calc-hash/Cargo.toml
  examples/reservation-manager/Cargo.toml
  examples/send-from-reservation/Cargo.toml
  gcli/Cargo.toml
  gclient/Cargo.toml
  gcore/Cargo.toml
  node/authorship/Cargo.toml
  node/service/Cargo.toml
  pallets/gear-builtin/Cargo.toml
  pallets/gear-debug/Cargo.toml
  pallets/gear-eth-bridge/Cargo.toml
  pallets/gear-messenger/Cargo.toml
  pallets/gear-program/Cargo.toml
  pallets/gear-scheduler/Cargo.toml
  pallets/gear-voucher/Cargo.toml
  pallets/gear/Cargo.toml
  pallets/staking-rewards/Cargo.toml
  runtime-interface/Cargo.toml
  runtime/vara/Cargo.toml
  utils/gear-wasmer-cache/Cargo.toml
  utils/runtime-fuzzer/Cargo.toml
  utils/wasm-gen/Cargo.toml
Labels: A0-pleasereview

#4749 chore(ethexe): Fix clippy warnings
  ethexe/compute/src/lib.rs
  ethexe/network/src/lib.rs
  ethexe/observer/src/lib.rs
Labels: A2-mergeoncegreen

#4751 feat(gtest)!: remove trait `WasmProgram` from `gtest`
  examples/async-custom-entry/Cargo.toml
  examples/program-factory/src/lib.rs
  examples/reservation-manager/Cargo.toml
  examples/send-from-reservation/Cargo.toml
  gtest/src/lib.rs
  gtest/src/manager.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/memory.rs
  gtest/src/manager/reservations.rs
  gtest/src/program.rs
  gtest/src/state/actors.rs
  gtest/src/system.rs
Labels: A2-mergeoncegreen

#4754 chore(ethexe): add script to update Clones.sol
  .github/workflows/check.yml
  ethexe/scripts/update-clones-sol.rs
Labels: A0-pleasereview
