Repository gear-tech/gear, pull requests merged in 2025-07, with the labels that each got.

#4274 refactor(core-code) Optimisation of read-write structures for code instrumentation
  Cargo.lock
  common/src/benchmarking.rs
  common/src/code_storage.rs
  common/src/lib.rs
  core-processor/src/common.rs
  core-processor/src/context.rs
  core-processor/src/executor.rs
  core-processor/src/lib.rs
  core-processor/src/precharge.rs
  core-processor/src/processing.rs
  core/Cargo.toml
  core/src/code/instrumented.rs
  core/src/code/metadata.rs
  core/src/code/mod.rs
  core/src/program.rs
  ethexe/common/src/db.rs
  ethexe/db/src/database.rs
  ethexe/processor/src/handling/mod.rs
  ethexe/processor/src/handling/run.rs
  ethexe/processor/src/host/mod.rs
  ethexe/processor/src/tests.rs
  ethexe/runtime/common/src/lib.rs
  ethexe/runtime/src/wasm/api/instrument.rs
  ethexe/runtime/src/wasm/api/mod.rs
  ethexe/runtime/src/wasm/api/run.rs
  gcli/tests/cmd/upload.rs
  gclient/src/api/calls.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/signer/storage.rs
  gsdk/src/storage.rs
  gsdk/tests/rpc.rs
  gtest/src/manager.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/memory.rs
  gtest/src/program.rs
  gtest/src/state/actors.rs
  pallets/gear-builtin/src/lib.rs
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear-program/Cargo.toml
  pallets/gear-program/src/lib.rs
  pallets/gear-program/src/migrations/mod.rs
  pallets/gear-program/src/migrations/v11_code_metadata_delete_migration.rs
  pallets/gear-program/src/migrations/v12_program_code_id_migration.rs
  pallets/gear-program/src/migrations/v13_split_instrumented_code_migration.rs
  pallets/gear/src/benchmarking/mod.rs
  pallets/gear/src/benchmarking/syscalls.rs
  pallets/gear/src/benchmarking/utils.rs
  pallets/gear/src/lib.rs
  pallets/gear/src/manager/journal.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/runtime_api.rs
  pallets/gear/src/tests.rs
  runtime/vara/src/migrations.rs
  scripts/check-fuzzer.sh
  utils/calc-stack-height/src/main.rs
  utils/wasm-gen/src/tests.rs
Labels: A2-mergeoncegreen

#4750 refactor: remove useless trait derives
  .config/nextest.toml
  Cargo.lock
  core-backend/src/mock.rs
  core-errors/Cargo.toml
  core-errors/src/lib.rs
  core-errors/src/simple.rs
  core-processor/Cargo.toml
  core-processor/src/executor.rs
  core-processor/src/ext.rs
  core/Cargo.toml
  core/src/message/common.rs
  core/src/message/context.rs
  core/src/message/handle.rs
  core/src/message/incoming.rs
  core/src/message/init.rs
  core/src/message/mod.rs
  core/src/message/reply.rs
  core/src/message/signal.rs
  core/src/message/stored.rs
  core/src/message/user.rs
  ethexe/common/src/events/mirror.rs
  ethexe/common/src/events/mod.rs
  ethexe/common/src/events/wvara.rs
  ethexe/common/src/gear.rs
  ethexe/ethereum/src/abi/gear.rs
  gtest/Cargo.toml
  gtest/src/log.rs
  gtest/src/manager/block_exec.rs
  pallets/gear/src/tests.rs
Labels: A0-pleasereview

#4763 fix(ethexe-processor): Fix parallel runner state overwrite bug
  ethexe/processor/src/handling/run.rs
Labels: A0-pleasereview

#4759 refactor(gtest): Replace `gtest::state::actors::TestActor` with `gear_core::program::Program`
  gtest/src/manager.rs
  gtest/src/manager/block_exec.rs
  gtest/src/manager/journal.rs
  gtest/src/manager/memory.rs
  gtest/src/manager/reservations.rs
  gtest/src/manager/task.rs
  gtest/src/program.rs
  gtest/src/state/mailbox/actor.rs
  gtest/src/state/mod.rs
  gtest/src/state/programs.rs
  gtest/src/system.rs
  pallets/gear/src/manager/mod.rs
  pallets/gear/src/queue.rs
Labels: A2-mergeoncegreen

#4765 revert: Don't build WASMs inside Substrate runtime
  scripts/src/clippy.sh
  utils/wasm-builder/src/lib.rs
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview

#4731 refactor(ethexe-network): Revamp `db-sync` protocol
  Cargo.lock
  Cargo.toml
  ethexe/common/src/db.rs
  ethexe/common/src/gear.rs
  ethexe/db/src/database.rs
  ethexe/ethereum/Cargo.toml
  ethexe/ethereum/src/router/mod.rs
  ethexe/network/Cargo.toml
  ethexe/network/src/db_sync/mod.rs
  ethexe/network/src/db_sync/ongoing.rs
  ethexe/network/src/db_sync/requests.rs
  ethexe/network/src/db_sync/responses.rs
  ethexe/network/src/lib.rs
  ethexe/network/src/peer_score.rs
  ethexe/network/src/utils.rs
  ethexe/service/Cargo.toml
  ethexe/service/src/fast_sync.rs
  ethexe/service/src/lib.rs
  ethexe/service/src/tests/utils/env.rs
  ethexe/service/utils/src/lib.rs
  ethexe/service/utils/src/task_local.rs
  sandbox/sandbox/Cargo.toml
Labels: A0-pleasereview, D8-gearexe

#4709 feat(ci): Refactor
  .cargo/config.toml
  .config/nextest.toml
  .github/actions/docs/action.yml
  .github/actions/install-cargo-xwin/action.yml
  .github/actions/install-rust/action.yml
  .github/actions/message/README.md
  .github/actions/message/action.yml
  .github/actions/message/main.js
  .github/actions/message/package.json
  .github/actions/rust-cache/action.yml
  .github/actions/setup-compilation-env/action.yml
  .github/actions/setup-linker/action.yml
  .github/build-win-cross/update-alternatives-clang.sh
  .github/workflows/Build-gear-loader-network.yml
  .github/workflows/CI.yaml
  .github/workflows/PR.yml
  .github/workflows/benchmarks.yml
  .github/workflows/build-linux.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-win-native.yml
  .github/workflows/build-windows.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/comparison-table.yml
  .github/workflows/docs.yml
  .github/workflows/label.yml
  .github/workflows/release.yml
  .github/workflows/test-measurements.yaml
  .github/workflows/time-consuming-tests.yml
  Cargo.lock
  Cargo.toml
  Makefile
  gclient/tests/set_code.rs
  gsdk/build.rs
  gsdk/tests/utils/mod.rs
  gstd/codegen/Cargo.toml
  node/authorship/src/tests.rs
  rust-toolchain.toml
  sandbox/sandbox/Cargo.toml
  sandbox/sandbox/src/embedded_executor.rs
  scripts/check-fuzzer.sh
  scripts/gear.sh
  scripts/src/build.sh
  scripts/src/clippy.sh
  scripts/src/test.sh
  utils/calc-stack-height/Cargo.toml
  utils/calc-stack-height/src/main.rs
  utils/cargo-gbuild/tests/smoke.rs
  utils/crates-io/src/manifest.rs
  utils/crates-io/src/publisher.rs
  utils/gring/tests/command.rs
  utils/runtime-fuzzer/fuzz/Cargo.toml
  utils/wasm-builder/src/crate_info.rs
  utils/wasm-instrument/tests/diff.rs
Labels: A0-pleasereview, E2-forcemacos, E1-forcenatwin, E3-forcerelease, E4-forceproduction

#4667 refactor(pallet-gear-debug): remove legacy pallet-gear-debug
  Cargo.lock
  Cargo.toml
  gsdk/src/metadata/errors.rs
  gsdk/src/metadata/generated.rs
  node/authorship/Cargo.toml
  node/authorship/src/tests.rs
  pallets/gear-debug/Cargo.toml
  pallets/gear-debug/README.md
  pallets/gear-debug/src/lib.rs
  pallets/gear-debug/src/mock.rs
  pallets/gear-debug/src/tests/mod.rs
  pallets/gear-debug/src/tests/utils.rs
  pallets/gear-debug/src/weights.rs
  pallets/gear/Cargo.toml
  pallets/gear/src/lib.rs
  pallets/gear/src/pallet_tests.rs
  pallets/gear/src/queue.rs
  pallets/gear/src/tests.rs
  runtime/vara/Cargo.toml
  runtime/vara/src/lib.rs
  utils/regression-analysis/src/main.rs
Labels: A0-pleasereview

#4761 chore(ethexe): append compute service metrics for prometeus
  ethexe/compute/src/service.rs
  ethexe/prometheus/src/lib.rs
  ethexe/service/src/lib.rs
Labels: A0-pleasereview

#4770 feat(ci): Cache WASMs
  .github/actions/rust-cache/action.yml
Labels: A0-pleasereview

#4786 fix(ci): Free disk space in docs job
  .github/workflows/build-linux.yml
Labels: A0-pleasereview

#4780 feat(gbuiltins): Add `TypeInfo` impl for builtins
  Cargo.lock
  gbuiltins/bls381/Cargo.toml
  gbuiltins/bls381/src/lib.rs
  gbuiltins/proxy/Cargo.toml
  gbuiltins/proxy/src/lib.rs
  gbuiltins/staking/Cargo.toml
  gbuiltins/staking/src/lib.rs
Labels: A2-mergeoncegreen

#4784 feat(gear-ss58): make crate `#![no_std]`
  utils/gring/Cargo.toml
  utils/ss58/Cargo.toml
  utils/ss58/src/lib.rs
Labels: A0-pleasereview

#4789 refactor(benchmarks/runtime): remove useless weights; use proper ones in runtime
  .github/workflows/benchmarks.yml
  pallets/gear-eth-bridge/src/weights.rs
  pallets/gear-voucher/src/weights.rs
  runtime/vara/src/lib.rs
  runtime/vara/src/weights/mod.rs
  runtime/vara/src/weights/pallet_gear.rs
  runtime/vara/src/weights/pallet_gear_builtin.rs
  runtime/vara/src/weights/pallet_gear_eth_bridge.rs
  runtime/vara/src/weights/pallet_gear_voucher.rs
  scripts/benchmarking/apply_weights.sh
  scripts/benchmarking/run_all_benchmarks.sh
  scripts/weight-dump.sh
Labels: A0-pleasereview

#4788 feat(ethexe): commit only head of blocks
  ethexe/blob-loader/Cargo.toml
  ethexe/cli/Cargo.toml
  ethexe/common/src/db.rs
  ethexe/common/src/events/router.rs
  ethexe/common/src/gear.rs
  ethexe/common/src/primitives.rs
  ethexe/compute/Cargo.toml
  ethexe/compute/src/compute.rs
  ethexe/compute/src/lib.rs
  ethexe/compute/src/prepare.rs
  ethexe/compute/src/service.rs
  ethexe/compute/src/tests.rs
  ethexe/consensus/Cargo.toml
  ethexe/consensus/src/mock.rs
  ethexe/consensus/src/utils.rs
  ethexe/consensus/src/validator/initial.rs
  ethexe/consensus/src/validator/mod.rs
  ethexe/consensus/src/validator/participant.rs
  ethexe/consensus/src/validator/producer.rs
  ethexe/consensus/src/validator/subordinate.rs
  ethexe/contracts/src/IRouter.sol
  ethexe/contracts/src/Router.sol
  ethexe/contracts/src/libraries/Gear.sol
  ethexe/contracts/test/Base.t.sol
  ethexe/db/Cargo.toml
  ethexe/db/src/database.rs
  ethexe/ethereum/Cargo.toml
  ethexe/ethereum/Mirror.json
  ethexe/ethereum/Router.json
  ethexe/ethereum/WrappedVara.json
  ethexe/ethereum/src/abi/events/router.rs
  ethexe/ethereum/src/abi/gear.rs
  ethexe/ethereum/src/router/events.rs
  ethexe/network/Cargo.toml
  ethexe/observer/Cargo.toml
  ethexe/observer/src/lib.rs
  ethexe/processor/Cargo.toml
  ethexe/rpc/src/apis/block.rs
  ethexe/runtime/Cargo.toml
  ethexe/service/Cargo.toml
  ethexe/service/src/fast_sync.rs
  ethexe/service/src/tests/mod.rs
  ethexe/tx-pool/Cargo.toml
  gprimitives/Cargo.toml
  gprimitives/src/lib.rs
  pallets/gear-builtin/Cargo.toml
  pallets/gear-eth-bridge/Cargo.toml
Labels: A0-pleasereview
