Repository gear-tech/gear, pull requests merged in 2025-10, with the labels that each got.

#4883 feat(pallet-gear-eth-bridge): Add verify_justification
  Cargo.lock
  Cargo.toml
  gsdk/src/metadata/generated.rs
  pallets/gear-eth-bridge/Cargo.toml
  pallets/gear-eth-bridge/src/builtin.rs
  pallets/gear-eth-bridge/src/internal.rs
  pallets/gear-eth-bridge/src/lib.rs
Labels: A0-pleasereview

#4884 feat(pallet-gear-eth-bridge): impl `reset_overflowed_queue` based on finality
  gclient/src/api/calls.rs
  gsdk/src/metadata/generated.rs
  gsdk/src/signer/calls.rs
  pallets/gear-eth-bridge/src/builtin.rs
  pallets/gear-eth-bridge/src/internal.rs
  pallets/gear-eth-bridge/src/lib.rs
  pallets/gear-eth-bridge/src/migrations/reset.rs
  pallets/gear-eth-bridge/src/tests.rs
Labels: A2-mergeoncegreen

#4885 refactor(ci): Unify CI for UNIX-like targets
  .github/workflows/CI.yaml
  .github/workflows/PR.yml
  .github/workflows/build-linux.yml
  .github/workflows/build-unix.yml
  .github/workflows/build.yml
Labels: A1-inprogress, D5-tooling, E2-forcemacos, E1-forcenatwin, E3-forcerelease, E4-forceproduction, E5-forcelinuxaarch64

#4854 feat(gcore): Global constructors
  Cargo.lock
  Cargo.toml
  examples/ctor/Cargo.toml
  examples/ctor/build.rs
  examples/ctor/src/lib.rs
  examples/ctor/src/wasm.rs
  gcore/Cargo.toml
  gcore/build.rs
  gcore/libgcore_shim.a
  gcore/src/ctor.rs
  gcore/src/exec.rs
  gcore/src/lib.rs
  gcore/src/shim.c
  gstd/src/lib.rs
  stack-buffer/Cargo.toml
  utils/wasm-builder/src/wasm_project.rs
Labels: A0-pleasereview, D1-core
